package.json
pnpm-lock.yaml
sdk/constants/market-map/index.tsx
sdk/constants/token-map/index.tsx

Hey
Here's a PR to fix 2 issues I've faced
* Missing zod dependency (used by abitype as peer)
* Reordering exports (function is used before being defined after the build because of how the index.ts are built)

Fixing sdk

---

sdk/constants/market-map/1/definitions/1_1_0x1c0b7b379dede9cc83201620725ba733fc52971f.ts

feat(market-map): Update market -- 1_1_0x1c0b7b379dede9cc83201620725ba733fc52971f -- Vault (0x1c0b...971f)
- Chain ID: 1
- Market ID: 0x1c0b7b379dede9cc83201620725ba733fc52971f (Wrapped Vault Address)
- Request Timestamp: Wed, 04 Dec 2024 21:27:31 GMT

feat(market-map): Update market -- 1_1_0x1c0b7b379dede9cc83201620725ba733fc52971f

---

sdk/constants/market-map/1/definitions/1_1_0x957e8d86b31847b55f4589999407aeb15b7ada54.ts

feat(market-map): Update market -- 1_1_0x957e8d86b31847b55f4589999407aeb15b7ada54 -- Vault (0x957e...da54)
- Chain ID: 1
- Market ID: 0x957e8d86b31847b55f4589999407aeb15b7ada54 (Wrapped Vault Address)
- Request Timestamp: Fri, 06 Dec 2024 10:37:30 GMT

feat(market-map): Update market -- 1_1_0x957e8d86b31847b55f4589999407aeb15b7ada54

---

sdk/constants/market-map/1/definitions/1_1_0xaba9d0d3816e6069d14484149fd50780821ddc0f.ts

feat(market-map): Update market -- 1_1_0xaba9d0d3816e6069d14484149fd50780821ddc0f -- Vault (0xaba9...dc0f)
- Chain ID: 1
- Market ID: 0xaba9d0d3816e6069d14484149fd50780821ddc0f (Wrapped Vault Address)
- Request Timestamp: Fri, 06 Dec 2024 22:26:51 GMT

feat(market-map): Update market -- 1_1_0xaba9d0d3816e6069d14484149fd50780821ddc0f

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x9d8c3dbb66cbd7a70755d487aeb86f03f46c87b883f11acd6ba2e48b33da0fd7.ts

feat(market-map): Update market -- 11155111_0_0x9d8c3dbb66cbd7a70755d487aeb86f03f46c87b883f11acd6ba2e48b33da0fd7 -- Recipe (0x9d8c...0fd7)
- Market ID: 0x9d8c3dbb66cbd7a70755d487aeb86f03f46c87b883f11acd6ba2e48b33da0fd7 (Market Hash)
- Request Timestamp: Mon, 09 Dec 2024 20:01:39 GMT

feat(market-map): Update market -- 11155111_0_0x9d8c3dbb66cbd7a70755d487aeb86f03f46c87b883f11acd6ba2e48b33da0fd7

---

sdk/constants/market-map/8453/definitions/8453_1_0xb511c70f6c37b200117e5ab950035ebc64b8062b.ts

feat(market-map): Update market -- 8453_1_0xb511c70f6c37b200117e5ab950035ebc64b8062b -- Vault (0xb511...062b)
- Market ID: 0xb511c70f6c37b200117e5ab950035ebc64b8062b (Wrapped Vault Address)
- Request Timestamp: Mon, 09 Dec 2024 19:07:10 GMT

feat(market-map): Update market -- 8453_1_0xb511c70f6c37b200117e5ab950035ebc64b8062b

---

sdk/constants/market-map/1/definitions/1_1_0xdc4e33582784f8b577f4e84c47af9b31e583e6db.ts

feat(market-map): Update market -- 1_1_0xdc4e33582784f8b577f4e84c47af9b31e583e6db -- Vault (0xdc4e...e6db)
- Chain ID: 1
- Market ID: 0xdc4e33582784f8b577f4e84c47af9b31e583e6db (Wrapped Vault Address)
- Request Timestamp: Mon, 09 Dec 2024 18:49:44 GMT

feat(market-map): Update market -- 1_1_0xdc4e33582784f8b577f4e84c47af9b31e583e6db

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xda51d0e8b23511146ab4c2058859473536fef2f7ae7edb52c99c947b292cbbc1.ts

feat(market-map): Update market -- 11155111_0_0xda51d0e8b23511146ab4c2058859473536fef2f7ae7edb52c99c947b292cbbc1 -- Recipe (0xda51...bbc1)
- Market ID: 0xda51d0e8b23511146ab4c2058859473536fef2f7ae7edb52c99c947b292cbbc1 (Market Hash)
- Request Timestamp: Mon, 09 Dec 2024 21:45:31 GMT

feat(market-map): Update market -- 11155111_0_0xda51d0e8b23511146ab4c2058859473536fef2f7ae7edb52c99c947b292cbbc1

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xb7a4762722bc11627db15058c2067772831a6c869955784f79db9ecd90bec87a.ts

feat(market-map): Update market -- 11155111_0_0xb7a4762722bc11627db15058c2067772831a6c869955784f79db9ecd90bec87a -- Recipe (0xb7a4...c87a)
- Market ID: 0xb7a4762722bc11627db15058c2067772831a6c869955784f79db9ecd90bec87a (Market Hash)
- Request Timestamp: Tue, 10 Dec 2024 12:06:19 GMT

feat(market-map): Update market -- 11155111_0_0xb7a4762722bc11627db15058c2067772831a6c869955784f79db9ecd90bec87a

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xa8f8410870203a2cee840e9fa43bb0ab95efe5096c8d8274f2e0505d88e31ec3.ts

feat(market-map): Update market -- 11155111_0_0xa8f8410870203a2cee840e9fa43bb0ab95efe5096c8d8274f2e0505d88e31ec3 -- Recipe (0xa8f8...1ec3)
- Market ID: 0xa8f8410870203a2cee840e9fa43bb0ab95efe5096c8d8274f2e0505d88e31ec3 (Market Hash)
- Request Timestamp: Tue, 10 Dec 2024 20:36:02 GMT

feat(market-map): Update market -- 11155111_0_0xa8f8410870203a2cee840e9fa43bb0ab95efe5096c8d8274f2e0505d88e31ec3

---

sdk/constants/market-map/11155111/definitions/11155111_1_0xbe2a22476b6e3658fddd04c20928f52929aa4019.ts

feat(market-map): Update market -- 11155111_1_0xbe2a22476b6e3658fddd04c20928f52929aa4019 -- Vault (0xbe2a...4019)
- Market ID: 0xbe2a22476b6e3658fddd04c20928f52929aa4019 (Wrapped Vault Address)
- Request Timestamp: Tue, 10 Dec 2024 22:33:54 GMT

feat(market-map): Update market -- 11155111_1_0xbe2a22476b6e3658fddd04c20928f52929aa4019

---

sdk/constants/market-map/42161/definitions/42161_0_0xf9771d89961fe2537de348458ce82c39894e1c7943c63834cb3d4c2c4ce73de4.ts

feat(market-map): Update market -- 42161_0_0xf9771d89961fe2537de348458ce82c39894e1c7943c63834cb3d4c2c4ce73de4 -- Recipe (0xf977...3de4)
- Market ID: 0xf9771d89961fe2537de348458ce82c39894e1c7943c63834cb3d4c2c4ce73de4 (Market Hash)
- Request Timestamp: Wed, 11 Dec 2024 19:26:47 GMT

feat(market-map): Update market -- 42161_0_0xf9771d89961fe2537de348458ce82c39894e1c7943c63834cb3d4c2c4ce73de4

---

sdk/constants/market-map/1/definitions/1_1_0xdc4e33582784f8b577f4e84c47af9b31e583e6db.ts

Mainnet ethereum Fluid vault USDC verify

---

sdk/constants/market-map/1/definitions/1_0_0xea47034ba4ba711a3c9b3d87c84149e7666040e2a31389e8594778feddb28ce2.ts

feat(market-map): Update market -- 1_0_0xea47034ba4ba711a3c9b3d87c84149e7666040e2a31389e8594778feddb28ce2 -- Recipe (0xea47...8ce2)
- Chain ID: 1
- Market ID: 0xea47034ba4ba711a3c9b3d87c84149e7666040e2a31389e8594778feddb28ce2 (Market Hash)
- Request Timestamp: Thu, 12 Dec 2024 12:46:15 GMT

feat(market-map): Update market -- 1_0_0xea47034ba4ba711a3c9b3d87c84149e7666040e2a31389e8594778feddb28ce2

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x02b3fbf71d027698992f4d25c21579b3d6be19aae510b9568b3f4a07735eb6ae.ts

feat(market-map): Update market -- 11155111_0_0x02b3fbf71d027698992f4d25c21579b3d6be19aae510b9568b3f4a07735eb6ae -- Recipe (0x02b3...b6ae)
- Market ID: 0x02b3fbf71d027698992f4d25c21579b3d6be19aae510b9568b3f4a07735eb6ae (Market Hash)
- Request Timestamp: Tue, 17 Dec 2024 01:36:52 GMT

feat(market-map): Update market -- 11155111_0_0x02b3fbf71d027698992f4d25c21579b3d6be19aae510b9568b3f4a07735eb6ae

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x52c4828959394a4c6cb4cc16552f5f963199c1f8b659fc785a1ce6e8fddd5b7d.ts

feat(market-map): Update market -- 11155111_0_0x52c4828959394a4c6cb4cc16552f5f963199c1f8b659fc785a1ce6e8fddd5b7d -- Recipe (0x52c4...5b7d)
- Market ID: 0x52c4828959394a4c6cb4cc16552f5f963199c1f8b659fc785a1ce6e8fddd5b7d (Market Hash)
- Request Timestamp: Mon, 16 Dec 2024 18:08:17 GMT

feat(market-map): Update market -- 11155111_0_0x52c4828959394a4c6cb4cc16552f5f963199c1f8b659fc785a1ce6e8fddd5b7d

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x7b5bf8336ed469737813a9d3d2cfd77970d9c2a033ae0c64bb94d720860e9161.ts

feat(market-map): Update market -- 11155111_0_0x7b5bf8336ed469737813a9d3d2cfd77970d9c2a033ae0c64bb94d720860e9161 -- Recipe (0x7b5b...9161)
- Market ID: 0x7b5bf8336ed469737813a9d3d2cfd77970d9c2a033ae0c64bb94d720860e9161 (Market Hash)
- Request Timestamp: Tue, 17 Dec 2024 13:44:45 GMT

feat(market-map): Update market -- 11155111_0_0x7b5bf8336ed469737813a9d3d2cfd77970d9c2a033ae0c64bb94d720860e9161

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xc60c2b6d4e0c8565653e173f7bd56ededb4ca74d72b250bf18c65d4264f6323a.ts

feat(market-map): Update market -- 11155111_0_0xc60c2b6d4e0c8565653e173f7bd56ededb4ca74d72b250bf18c65d4264f6323a -- Recipe (0xc60c...323a)
- Market ID: 0xc60c2b6d4e0c8565653e173f7bd56ededb4ca74d72b250bf18c65d4264f6323a (Market Hash)
- Request Timestamp: Tue, 17 Dec 2024 13:19:22 GMT

feat(market-map): Update market -- 11155111_0_0xc60c2b6d4e0c8565653e173f7bd56ededb4ca74d72b250bf18c65d4264f6323a

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x92ea4fc9eec17cc5fdcb71831ce0ac868f7308031b10389e3bf389a6c7d18ded.ts

feat(market-map): Update market -- 11155111_0_0x92ea4fc9eec17cc5fdcb71831ce0ac868f7308031b10389e3bf389a6c7d18ded -- Recipe (0x92ea...8ded)
- Market ID: 0x92ea4fc9eec17cc5fdcb71831ce0ac868f7308031b10389e3bf389a6c7d18ded (Market Hash)
- Request Timestamp: Wed, 18 Dec 2024 03:35:05 GMT

feat(market-map): Update market -- 11155111_0_0x92ea4fc9eec17cc5fdcb71831ce0ac868f7308031b10389e3bf389a6c7d18ded

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xb773f2cfc26d17f56cdc1bf33d3a18c26eeddedea7c6562144e742da241d2ab6.ts

feat(market-map): Update market -- 11155111_0_0xb773f2cfc26d17f56cdc1bf33d3a18c26eeddedea7c6562144e742da241d2ab6 -- Recipe (0xb773...2ab6)
- Market ID: 0xb773f2cfc26d17f56cdc1bf33d3a18c26eeddedea7c6562144e742da241d2ab6 (Market Hash)
- Request Timestamp: Wed, 18 Dec 2024 05:17:45 GMT

feat(market-map): Update market -- 11155111_0_0xb773f2cfc26d17f56cdc1bf33d3a18c26eeddedea7c6562144e742da241d2ab6

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xfe62791d480b81430159f3b1ba676a05d86f6e5476fdb424f637daa32b5cadb2.ts

feat(market-map): Update market -- 11155111_0_0xfe62791d480b81430159f3b1ba676a05d86f6e5476fdb424f637daa32b5cadb2 -- Recipe (0xfe62...adb2)
- Market ID: 0xfe62791d480b81430159f3b1ba676a05d86f6e5476fdb424f637daa32b5cadb2 (Market Hash)
- Request Timestamp: Fri, 20 Dec 2024 01:54:37 GMT

feat(market-map): Update market -- 11155111_0_0xfe62791d480b81430159f3b1ba676a05d86f6e5476fdb424f637daa32b5cadb2

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x8886ad204aa8fd5779a876becbf0a4d14d449e6675788c6a88bd2a8abe1539d1.ts

feat(market-map): Update market -- 11155111_0_0x8886ad204aa8fd5779a876becbf0a4d14d449e6675788c6a88bd2a8abe1539d1 -- Recipe (0x8886...39d1)
- Market ID: 0x8886ad204aa8fd5779a876becbf0a4d14d449e6675788c6a88bd2a8abe1539d1 (Market Hash)
- Request Timestamp: Fri, 20 Dec 2024 09:43:06 GMT

feat(market-map): Update market -- 11155111_0_0x8886ad204aa8fd5779a876becbf0a4d14d449e6675788c6a88bd2a8abe1539d1

---

sdk/constants/market-map/21000000/definitions/21000000_1_0x9c94d6da78a2cc690de21af641f756ff621424db.ts

feat(market-map): Update market -- 21000000_1_0x9c94d6da78a2cc690de21af641f756ff621424db -- Vault (0x9c94...24db)
- Chain ID: 21000000
- Market ID: 0x9c94d6da78a2cc690de21af641f756ff621424db (Wrapped Vault Address)
- Request Timestamp: Fri, 20 Dec 2024 09:28:02 GMT

feat(market-map): Update market -- 21000000_1_0x9c94d6da78a2cc690de21af641f756ff621424db

---

sdk/constants/market-map/1/definitions/1_0_0x0c27382300c4fa216ec1e0a0a5d6a28555843aeb0c13fbfbfe8305f7faf311ef.ts

feat(market-map): Update market -- 1_0_0x0c27382300c4fa216ec1e0a0a5d6a28555843aeb0c13fbfbfe8305f7faf311ef -- Recipe (0x0c27...11ef)
- Chain ID: 1
- Market ID: 0x0c27382300c4fa216ec1e0a0a5d6a28555843aeb0c13fbfbfe8305f7faf311ef (Market Hash)
- Request Timestamp: Fri, 20 Dec 2024 04:23:18 GMT

feat(market-map): Update market -- 1_0_0x0c27382300c4fa216ec1e0a0a5d6a28555843aeb0c13fbfbfe8305f7faf311ef

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xe59a2e7d6a0ecbe38be39244d633340dc0615a7321dec3c76d7b99e2ef198a47.ts

feat(market-map): Update market -- 11155111_0_0xe59a2e7d6a0ecbe38be39244d633340dc0615a7321dec3c76d7b99e2ef198a47 -- Recipe (0xe59a...8a47)
- Market ID: 0xe59a2e7d6a0ecbe38be39244d633340dc0615a7321dec3c76d7b99e2ef198a47 (Market Hash)
- Request Timestamp: Fri, 20 Dec 2024 04:17:08 GMT

feat(market-map): Update market -- 11155111_0_0xe59a2e7d6a0ecbe38be39244d633340dc0615a7321dec3c76d7b99e2ef198a47

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xe8203a05754c8f11d136fcce4d2edfda85d8196843661774f8302eb974712d7f.ts

feat(market-map): Update market -- 11155111_0_0xe8203a05754c8f11d136fcce4d2edfda85d8196843661774f8302eb974712d7f -- Recipe (0xe820...2d7f)
- Market ID: 0xe8203a05754c8f11d136fcce4d2edfda85d8196843661774f8302eb974712d7f (Market Hash)
- Request Timestamp: Fri, 20 Dec 2024 03:22:35 GMT

feat(market-map): Update market -- 11155111_0_0xe8203a05754c8f11d136fcce4d2edfda85d8196843661774f8302eb974712d7f

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xdde2187e9a073c7031059ca15aa1d87f3a0a701cba4c7d12a79f9208feb625b5.ts

feat(market-map): Update market -- 11155111_0_0xdde2187e9a073c7031059ca15aa1d87f3a0a701cba4c7d12a79f9208feb625b5 -- Recipe (0xdde2...25b5)
- Market ID: 0xdde2187e9a073c7031059ca15aa1d87f3a0a701cba4c7d12a79f9208feb625b5 (Market Hash)
- Request Timestamp: Fri, 20 Dec 2024 03:06:06 GMT

feat(market-map): Update market -- 11155111_0_0xdde2187e9a073c7031059ca15aa1d87f3a0a701cba4c7d12a79f9208feb625b5

---

sdk/constants/token-map/11155111/definitions/11155111-0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14.ts

feat(token-map): 11155111-0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14.ts

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x4da53da9630ac045ae22eee6db5c06fe0e5f120ae5b3418f2605e95115c891c5.ts

feat(market-map): Update market -- 11155111_0_0x4da53da9630ac045ae22eee6db5c06fe0e5f120ae5b3418f2605e95115c891c5 -- Recipe (0x4da5...91c5)
- Market ID: 0x4da53da9630ac045ae22eee6db5c06fe0e5f120ae5b3418f2605e95115c891c5 (Market Hash)
- Request Timestamp: Sun, 29 Dec 2024 17:22:38 GMT

feat(market-map): Update market -- 11155111_0_0x4da53da9630ac045ae22eee6db5c06fe0e5f120ae5b3418f2605e95115c891c5

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x14c698108985b999445ea83257066b3b18c689b079a03654ec9439a4bef09caf.ts

feat(market-map): Update market -- 11155111_0_0x14c698108985b999445ea83257066b3b18c689b079a03654ec9439a4bef09caf -- Recipe (0x14c6...9caf)
- Market ID: 0x14c698108985b999445ea83257066b3b18c689b079a03654ec9439a4bef09caf (Market Hash)
- Request Timestamp: Sun, 29 Dec 2024 16:20:44 GMT

feat(market-map): Update market -- 11155111_0_0x14c698108985b999445ea83257066b3b18c689b079a03654ec9439a4bef09caf

---

sdk/constants/market-map/1/definitions/1_1_0xa2bb5cd636a098783f629d1f1431934a45eee7fa.ts

feat(market-map): Update market -- 1_1_0xa2bb5cd636a098783f629d1f1431934a45eee7fa -- Vault (0xa2bb...e7fa)
- Chain ID: 1
- Market ID: 0xa2bb5cd636a098783f629d1f1431934a45eee7fa (Wrapped Vault Address)
- Request Timestamp: Sun, 29 Dec 2024 10:55:33 GMT

feat(market-map): Update market -- 1_1_0xa2bb5cd636a098783f629d1f1431934a45eee7fa

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x67ce48013dc6509385f4717d73f301db9a1295e07c54fe5d15c100c655b74d80.ts

feat(market-map): Update market -- 11155111_0_0x67ce48013dc6509385f4717d73f301db9a1295e07c54fe5d15c100c655b74d80 -- Recipe (0x67ce...4d80)
- Market ID: 0x67ce48013dc6509385f4717d73f301db9a1295e07c54fe5d15c100c655b74d80 (Market Hash)
- Request Timestamp: Sun, 29 Dec 2024 03:29:09 GMT

feat(market-map): Update market -- 11155111_0_0x67ce48013dc6509385f4717d73f301db9a1295e07c54fe5d15c100c655b74d80

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xe9361c6676c14fe04c72c841d1db72280e0db59b563d5f3e236400078cb4e235.ts

feat(market-map): Update market -- 11155111_0_0xe9361c6676c14fe04c72c841d1db72280e0db59b563d5f3e236400078cb4e235 -- Recipe (0xe936...e235)
- Market ID: 0xe9361c6676c14fe04c72c841d1db72280e0db59b563d5f3e236400078cb4e235 (Market Hash)
- Request Timestamp: Sat, 28 Dec 2024 08:48:27 GMT

feat(market-map): Update market -- 11155111_0_0xe9361c6676c14fe04c72c841d1db72280e0db59b563d5f3e236400078cb4e235

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x620841ee55ae930f1471afc3feb1433a8fc68bac0a768eeb10e88837ffad7868.ts

feat(market-map): Update market -- 11155111_0_0x620841ee55ae930f1471afc3feb1433a8fc68bac0a768eeb10e88837ffad7868 -- Recipe (0x6208...7868)
- Market ID: 0x620841ee55ae930f1471afc3feb1433a8fc68bac0a768eeb10e88837ffad7868 (Market Hash)
- Request Timestamp: Sat, 28 Dec 2024 06:49:30 GMT

feat(market-map): Update market -- 11155111_0_0x620841ee55ae930f1471afc3feb1433a8fc68bac0a768eeb10e88837ffad7868

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xc74bcce181b08956cd3984bcb93f6eb86c3bb7322d219131b2585f7ba862be81.ts

feat(market-map): Update market -- 11155111_0_0xc74bcce181b08956cd3984bcb93f6eb86c3bb7322d219131b2585f7ba862be81 -- Recipe (0xc74b...be81)
- Market ID: 0xc74bcce181b08956cd3984bcb93f6eb86c3bb7322d219131b2585f7ba862be81 (Market Hash)
- Request Timestamp: Sat, 28 Dec 2024 04:41:21 GMT

feat(market-map): Update market -- 11155111_0_0xc74bcce181b08956cd3984bcb93f6eb86c3bb7322d219131b2585f7ba862be81

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xe657daa959bcb3214a25291a504e5c70e65df0c0b0e433a5a3dd1f502f0dab15.ts

feat(market-map): Update market -- 11155111_0_0xe657daa959bcb3214a25291a504e5c70e65df0c0b0e433a5a3dd1f502f0dab15 -- Recipe (0xe657...ab15)
- Market ID: 0xe657daa959bcb3214a25291a504e5c70e65df0c0b0e433a5a3dd1f502f0dab15 (Market Hash)
- Request Timestamp: Fri, 27 Dec 2024 17:09:41 GMT

feat(market-map): Update market -- 11155111_0_0xe657daa959bcb3214a25291a504e5c70e65df0c0b0e433a5a3dd1f502f0dab15

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xe025922949f624146d8cbb04efb0d3095ca114ee1d16c1354216a308e075503d.ts

feat(market-map): Update market -- 11155111_0_0xe025922949f624146d8cbb04efb0d3095ca114ee1d16c1354216a308e075503d -- Recipe (0xe025...503d)
- Market ID: 0xe025922949f624146d8cbb04efb0d3095ca114ee1d16c1354216a308e075503d (Market Hash)
- Request Timestamp: Fri, 27 Dec 2024 17:06:43 GMT

feat(market-map): Update market -- 11155111_0_0xe025922949f624146d8cbb04efb0d3095ca114ee1d16c1354216a308e075503d

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xc58a014795eb4957b713511d8984fb56fbb93b631f598f4575379a5b3019501f.ts

feat(market-map): Update market -- 11155111_0_0xc58a014795eb4957b713511d8984fb56fbb93b631f598f4575379a5b3019501f -- Recipe (0xc58a...501f)
- Market ID: 0xc58a014795eb4957b713511d8984fb56fbb93b631f598f4575379a5b3019501f (Market Hash)
- Request Timestamp: Fri, 27 Dec 2024 15:29:56 GMT

feat(market-map): Update market -- 11155111_0_0xc58a014795eb4957b713511d8984fb56fbb93b631f598f4575379a5b3019501f

---

sdk/constants/token-map/11155111/definitions/11155111-0xfff9976782d46cc05630d1f6ebab18b2324d6b14.ts

fixed weth9 decimals

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xe8a1fbb53dc288063b4a367376c7a32c3e250ae8618a35ea9d72ae827093a805.ts

feat(market-map): Update market -- 11155111_0_0xe8a1fbb53dc288063b4a367376c7a32c3e250ae8618a35ea9d72ae827093a805 -- Recipe (0xe8a1...a805)
- Market ID: 0xe8a1fbb53dc288063b4a367376c7a32c3e250ae8618a35ea9d72ae827093a805 (Market Hash)
- Request Timestamp: Tue, 31 Dec 2024 11:57:56 GMT

feat(market-map): Update market -- 11155111_0_0xe8a1fbb53dc288063b4a367376c7a32c3e250ae8618a35ea9d72ae827093a805

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xb98ea071712cadd5e3605c0156c90017044098010d20b17bbad72665de62d326.ts

feat(market-map): Update market -- 11155111_0_0xb98ea071712cadd5e3605c0156c90017044098010d20b17bbad72665de62d326 -- Recipe (0xb98e...d326)
- Market ID: 0xb98ea071712cadd5e3605c0156c90017044098010d20b17bbad72665de62d326 (Market Hash)
- Request Timestamp: Fri, 27 Dec 2024 14:48:42 GMT

feat(market-map): Update market -- 11155111_0_0xb98ea071712cadd5e3605c0156c90017044098010d20b17bbad72665de62d326

---

sdk/constants/market-map/42161/definitions/42161_0_0x30a4824074bbd584b42b30dc31553d5e49aae9f802738a3c0e4c621e6071bbc1.ts

feat(market-map): Update market -- 42161_0_0x30a4824074bbd584b42b30dc31553d5e49aae9f802738a3c0e4c621e6071bbc1 -- Recipe (0x30a4...bbc1)
- Market ID: 0x30a4824074bbd584b42b30dc31553d5e49aae9f802738a3c0e4c621e6071bbc1 (Market Hash)
- Request Timestamp: Fri, 27 Dec 2024 12:46:17 GMT

feat(market-map): Update market -- 42161_0_0x30a4824074bbd584b42b30dc31553d5e49aae9f802738a3c0e4c621e6071bbc1

---

sdk/constants/market-map/1/definitions/1_1_0xdb8711c854e414a863459bca5d73c4cc3c537c35.ts

feat(market-map): Update market -- 1_1_0xdb8711c854e414a863459bca5d73c4cc3c537c35 -- Vault (0xdb87...7c35)
- Chain ID: 1
- Market ID: 0xdb8711c854e414a863459bca5d73c4cc3c537c35 (Wrapped Vault Address)
- Request Timestamp: Fri, 27 Dec 2024 05:52:17 GMT

feat(market-map): Update market -- 1_1_0xdb8711c854e414a863459bca5d73c4cc3c537c35

---

sdk/constants/market-map/11155111/definitions/11155111_1_0x0bb110b88d895e9939a0cd554ad3473ebc5e5704.ts

feat(market-map): Update market -- 11155111_1_0x0bb110b88d895e9939a0cd554ad3473ebc5e5704 -- Vault (0x0bb1...5704)
- Market ID: 0x0bb110b88d895e9939a0cd554ad3473ebc5e5704 (Wrapped Vault Address)
- Request Timestamp: Tue, 24 Dec 2024 13:45:29 GMT

feat(market-map): Update market -- 11155111_1_0x0bb110b88d895e9939a0cd554ad3473ebc5e5704

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xc96c9c374c96e21f73e1a81fba19e6da25010041c5d0afc5205f93fbcb1bffa4.ts

feat(market-map): Update market -- 11155111_0_0xc96c9c374c96e21f73e1a81fba19e6da25010041c5d0afc5205f93fbcb1bffa4 -- Recipe (0xc96c...ffa4)
- Market ID: 0xc96c9c374c96e21f73e1a81fba19e6da25010041c5d0afc5205f93fbcb1bffa4 (Market Hash)
- Request Timestamp: Tue, 24 Dec 2024 06:09:53 GMT

feat(market-map): Update market -- 11155111_0_0xc96c9c374c96e21f73e1a81fba19e6da25010041c5d0afc5205f93fbcb1bffa4

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x303391336fe8a0e4d2fd237917a7c4ffb86e70e820f104b0fc575e0a6dc83f98.ts

feat(market-map): Update market -- 11155111_0_0x303391336fe8a0e4d2fd237917a7c4ffb86e70e820f104b0fc575e0a6dc83f98 -- Recipe (0x3033...3f98)
- Market ID: 0x303391336fe8a0e4d2fd237917a7c4ffb86e70e820f104b0fc575e0a6dc83f98 (Market Hash)
- Request Timestamp: Tue, 24 Dec 2024 06:06:29 GMT

feat(market-map): Update market -- 11155111_0_0x303391336fe8a0e4d2fd237917a7c4ffb86e70e820f104b0fc575e0a6dc83f98

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xf99d7017e65a307f4094686f7b3d244ed7908dc27fd517340d49bc75b2a54974.ts

feat(market-map): Update market -- 11155111_0_0xf99d7017e65a307f4094686f7b3d244ed7908dc27fd517340d49bc75b2a54974 -- Recipe (0xf99d...4974)
- Market ID: 0xf99d7017e65a307f4094686f7b3d244ed7908dc27fd517340d49bc75b2a54974 (Market Hash)
- Request Timestamp: Tue, 24 Dec 2024 06:04:42 GMT

feat(market-map): Update market -- 11155111_0_0xf99d7017e65a307f4094686f7b3d244ed7908dc27fd517340d49bc75b2a54974

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x6e8cf1b892f302f94fbebd4fe37a63acb992d3361bcf6b37b2067dfecc006182.ts

feat(market-map): Update market -- 11155111_0_0x6e8cf1b892f302f94fbebd4fe37a63acb992d3361bcf6b37b2067dfecc006182 -- Recipe (0x6e8c...6182)
- Market ID: 0x6e8cf1b892f302f94fbebd4fe37a63acb992d3361bcf6b37b2067dfecc006182 (Market Hash)
- Request Timestamp: Tue, 24 Dec 2024 06:02:17 GMT

feat(market-map): Update market -- 11155111_0_0x6e8cf1b892f302f94fbebd4fe37a63acb992d3361bcf6b37b2067dfecc006182

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x31766b4d2d428f51b048acab2112377879ee874ffa4db1db0453274acec320c0.ts

feat(market-map): Update market -- 11155111_0_0x31766b4d2d428f51b048acab2112377879ee874ffa4db1db0453274acec320c0 -- Recipe (0x3176...20c0)
- Market ID: 0x31766b4d2d428f51b048acab2112377879ee874ffa4db1db0453274acec320c0 (Market Hash)
- Request Timestamp: Tue, 24 Dec 2024 05:53:18 GMT

feat(market-map): Update market -- 11155111_0_0x31766b4d2d428f51b048acab2112377879ee874ffa4db1db0453274acec320c0

---

sdk/constants/market-map/1/definitions/1_0_0x96b0b1f1b039c85b4825891b25f6acb602b19d156192509b2772491e1a24e650.ts

feat(market-map): Update market -- 1_0_0x96b0b1f1b039c85b4825891b25f6acb602b19d156192509b2772491e1a24e650 -- Recipe (0x96b0...e650)
- Chain ID: 1
- Market ID: 0x96b0b1f1b039c85b4825891b25f6acb602b19d156192509b2772491e1a24e650 (Market Hash)
- Request Timestamp: Tue, 24 Dec 2024 03:11:32 GMT

feat(market-map): Update market -- 1_0_0x96b0b1f1b039c85b4825891b25f6acb602b19d156192509b2772491e1a24e650

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x868096ac22d1d42ced54795ebf1754400ca51b399cd1c84a46ac3be04daf22a1.ts

feat(market-map): Update market -- 11155111_0_0x868096ac22d1d42ced54795ebf1754400ca51b399cd1c84a46ac3be04daf22a1 -- Recipe (0x8680...22a1)
- Market ID: 0x868096ac22d1d42ced54795ebf1754400ca51b399cd1c84a46ac3be04daf22a1 (Market Hash)
- Request Timestamp: Mon, 23 Dec 2024 21:21:58 GMT

feat(market-map): Update market -- 11155111_0_0x868096ac22d1d42ced54795ebf1754400ca51b399cd1c84a46ac3be04daf22a1

---

sdk/constants/market-map/8453/definitions/8453_1_0x9db6dbdcf6b3f158f8b02d762f99f8ce7663e1aa.ts

feat(market-map): Update market -- 8453_1_0x9db6dbdcf6b3f158f8b02d762f99f8ce7663e1aa -- Vault (0x9db6...e1aa)
- Market ID: 0x9db6dbdcf6b3f158f8b02d762f99f8ce7663e1aa (Wrapped Vault Address)
- Request Timestamp: Mon, 23 Dec 2024 18:39:06 GMT

feat(market-map): Update market -- 8453_1_0x9db6dbdcf6b3f158f8b02d762f99f8ce7663e1aa

---

sdk/constants/market-map/8453/definitions/8453_1_0xb98840b22618e77bbd0403c81365eefc7d449559.ts

feat(market-map): Update market -- 8453_1_0xb98840b22618e77bbd0403c81365eefc7d449559 -- Vault (0xb988...9559)
- Market ID: 0xb98840b22618e77bbd0403c81365eefc7d449559 (Wrapped Vault Address)
- Request Timestamp: Mon, 23 Dec 2024 18:24:25 GMT

feat(market-map): Update market -- 8453_1_0xb98840b22618e77bbd0403c81365eefc7d449559

---

sdk/constants/market-map/8453/definitions/8453_0_0xd9cefc89a473c60f4c2328fc6af2cc0dbe59f250299133ab3c53c5afc0fdb11a.ts

feat(market-map): Update market -- 8453_0_0xd9cefc89a473c60f4c2328fc6af2cc0dbe59f250299133ab3c53c5afc0fdb11a -- Recipe (0xd9ce...b11a)
- Market ID: 0xd9cefc89a473c60f4c2328fc6af2cc0dbe59f250299133ab3c53c5afc0fdb11a (Market Hash)
- Request Timestamp: Mon, 23 Dec 2024 17:11:01 GMT

feat(market-map): Update market -- 8453_0_0xd9cefc89a473c60f4c2328fc6af2cc0dbe59f250299133ab3c53c5afc0fdb11a

---

sdk/constants/market-map/8453/definitions/8453_0_0x63cb3b36c1b893932321463867a6dbfac387611b28eee083d8d256e35e00f348.ts

feat(market-map): Update market -- 8453_0_0x63cb3b36c1b893932321463867a6dbfac387611b28eee083d8d256e35e00f348 -- Recipe (0x63cb...f348)
- Market ID: 0x63cb3b36c1b893932321463867a6dbfac387611b28eee083d8d256e35e00f348 (Market Hash)
- Request Timestamp: Sun, 22 Dec 2024 04:41:32 GMT

feat(market-map): Update market -- 8453_0_0x63cb3b36c1b893932321463867a6dbfac387611b28eee083d8d256e35e00f348

---

sdk/constants/market-map/42161/definitions/42161_0_0xda2d6a0d934ca3837ef875f4fc16032b9779fae57df6d3adf24bdc9b43096f4f.ts

feat(market-map): Update market -- 42161_0_0xda2d6a0d934ca3837ef875f4fc16032b9779fae57df6d3adf24bdc9b43096f4f -- Recipe (0xda2d...6f4f)
- Market ID: 0xda2d6a0d934ca3837ef875f4fc16032b9779fae57df6d3adf24bdc9b43096f4f (Market Hash)
- Request Timestamp: Tue, 31 Dec 2024 12:17:00 GMT

feat(market-map): Update market -- 42161_0_0xda2d6a0d934ca3837ef875f4fc16032b9779fae57df6d3adf24bdc9b43096f4f

---

sdk/constants/market-map/42161/definitions/42161_0_0xbd1770a17fb3b1ca93517bd7ffb6f2638f5edc4eaf6b4e553245d4d34e186cfd.ts

feat(market-map): Update market -- 42161_0_0xbd1770a17fb3b1ca93517bd7ffb6f2638f5edc4eaf6b4e553245d4d34e186cfd -- Recipe (0xbd17...6cfd)
- Market ID: 0xbd1770a17fb3b1ca93517bd7ffb6f2638f5edc4eaf6b4e553245d4d34e186cfd (Market Hash)
- Request Timestamp: Wed, 01 Jan 2025 05:19:41 GMT

feat(market-map): Update market -- 42161_0_0xbd1770a17fb3b1ca93517bd7ffb6f2638f5edc4eaf6b4e553245d4d34e186cfd

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x6ef0239f3a265036a6f5aed98deaf0eec82da93e4760421ea31b7999dc912df7.ts

feat(market-map): Update market -- 11155111_0_0x6ef0239f3a265036a6f5aed98deaf0eec82da93e4760421ea31b7999dc912df7 -- Recipe (0x6ef0...2df7)
- Market ID: 0x6ef0239f3a265036a6f5aed98deaf0eec82da93e4760421ea31b7999dc912df7 (Market Hash)
- Request Timestamp: Wed, 01 Jan 2025 17:36:31 GMT

feat(market-map): Update market -- 11155111_0_0x6ef0239f3a265036a6f5aed98deaf0eec82da93e4760421ea31b7999dc912df7

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x463b8b0944240a3aeb108600b08d7a4357e961d0e454219a92375c5b59dbff46.ts

feat(market-map): Update market -- 11155111_0_0x463b8b0944240a3aeb108600b08d7a4357e961d0e454219a92375c5b59dbff46 -- Recipe (0x463b...ff46)
- Market ID: 0x463b8b0944240a3aeb108600b08d7a4357e961d0e454219a92375c5b59dbff46 (Market Hash)
- Request Timestamp: Wed, 01 Jan 2025 17:39:30 GMT

feat(market-map): Update market -- 11155111_0_0x463b8b0944240a3aeb108600b08d7a4357e961d0e454219a92375c5b59dbff46

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xafac66433f00d152c43097707811594b6c2781e4baaccd8d3be6cd3d3af4d600.ts

feat(market-map): Update market -- 11155111_0_0xafac66433f00d152c43097707811594b6c2781e4baaccd8d3be6cd3d3af4d600 -- Recipe (0xafac...d600)
- Market ID: 0xafac66433f00d152c43097707811594b6c2781e4baaccd8d3be6cd3d3af4d600 (Market Hash)
- Request Timestamp: Thu, 02 Jan 2025 05:14:05 GMT

feat(market-map): Update market -- 11155111_0_0xafac66433f00d152c43097707811594b6c2781e4baaccd8d3be6cd3d3af4d600

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x5a1271f538303a5c1139b506712e680fd660d5b56ff5bbe98080ed537bdafdda.ts

feat(market-map): Update market -- 11155111_0_0x5a1271f538303a5c1139b506712e680fd660d5b56ff5bbe98080ed537bdafdda -- Recipe (0x5a12...fdda)
- Market ID: 0x5a1271f538303a5c1139b506712e680fd660d5b56ff5bbe98080ed537bdafdda (Market Hash)
- Request Timestamp: Thu, 02 Jan 2025 05:16:33 GMT

feat(market-map): Update market -- 11155111_0_0x5a1271f538303a5c1139b506712e680fd660d5b56ff5bbe98080ed537bdafdda

---

sdk/constants/market-map/98865/definitions/98865_0_0xf1925365d20600cbcc4a8e1c3039cf68a3ae1ded9c4d95c84346b2928f20f08b.ts

feat(market-map): Update market -- 98865_0_0xf1925365d20600cbcc4a8e1c3039cf68a3ae1ded9c4d95c84346b2928f20f08b -- Recipe (0xf192...f08b)
- Market ID: 0xf1925365d20600cbcc4a8e1c3039cf68a3ae1ded9c4d95c84346b2928f20f08b (Market Hash)
- Request Timestamp: Thu, 02 Jan 2025 06:44:10 GMT

feat(market-map): Update market -- 98865_0_0xf1925365d20600cbcc4a8e1c3039cf68a3ae1ded9c4d95c84346b2928f20f08b

---

sdk/constants/market-map/1/definitions/1_1_0xdbf074ef1689a3349fd3ac2316655069c84450c2.ts

feat(market-map): Update market -- 1_1_0xdbf074ef1689a3349fd3ac2316655069c84450c2 -- Vault (0xdbf0...50c2)
- Chain ID: 1
- Market ID: 0xdbf074ef1689a3349fd3ac2316655069c84450c2 (Wrapped Vault Address)
- Request Timestamp: Thu, 02 Jan 2025 18:13:56 GMT

feat(market-map): Update market -- 1_1_0xdbf074ef1689a3349fd3ac2316655069c84450c2

---

sdk/constants/market-map/1/definitions/1_1_0x76c1c39bc6c0f16abb6925ba5c2fe03848abc667.ts

feat(market-map): Update market -- 1_1_0x76c1c39bc6c0f16abb6925ba5c2fe03848abc667 -- Vault (0x76c1...c667)
- Chain ID: 1
- Market ID: 0x76c1c39bc6c0f16abb6925ba5c2fe03848abc667 (Wrapped Vault Address)
- Request Timestamp: Thu, 02 Jan 2025 18:46:53 GMT

feat(market-map): Update market -- 1_1_0x76c1c39bc6c0f16abb6925ba5c2fe03848abc667

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x4b8724dc73163b586d84c8fecda13266dbb6fec140b02fd70b7aae6245bb0100.ts

feat(market-map): Update market -- 11155111_0_0x4b8724dc73163b586d84c8fecda13266dbb6fec140b02fd70b7aae6245bb0100 -- Recipe (0x4b87...0100)
- Market ID: 0x4b8724dc73163b586d84c8fecda13266dbb6fec140b02fd70b7aae6245bb0100 (Market Hash)
- Request Timestamp: Thu, 02 Jan 2025 20:36:27 GMT

feat(market-map): Update market -- 11155111_0_0x4b8724dc73163b586d84c8fecda13266dbb6fec140b02fd70b7aae6245bb0100

---

sdk/constants/market-map/21000000/definitions/21000000_1_0x91e59126365118a2bfe13560a3a575c6d42bf59f.ts

feat(market-map): Update market -- 21000000_1_0x91e59126365118a2bfe13560a3a575c6d42bf59f -- Vault (0x91e5...f59f)
- Chain ID: 21000000
- Market ID: 0x91e59126365118a2bfe13560a3a575c6d42bf59f (Wrapped Vault Address)
- Request Timestamp: Fri, 03 Jan 2025 12:49:29 GMT

feat(market-map): Update market -- 21000000_1_0x91e59126365118a2bfe13560a3a575c6d42bf59f

---

sdk/constants/market-map/98865/definitions/98865_1_0x8cc74dd458db4289ce03d8e4606433ab3631242d.ts

feat(market-map): Update market -- 98865_1_0x8cc74dd458db4289ce03d8e4606433ab3631242d -- Vault (0x8cc7...242d)
- Market ID: 0x8cc74dd458db4289ce03d8e4606433ab3631242d (Wrapped Vault Address)
- Request Timestamp: Fri, 03 Jan 2025 18:49:54 GMT

feat(market-map): Update market -- 98865_1_0x8cc74dd458db4289ce03d8e4606433ab3631242d

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x2a8b3660ee8d64a6464648dce594afb92d6697e06264c936ea8f96f4c1cc73eb.ts

feat(market-map): Update market -- 11155111_0_0x2a8b3660ee8d64a6464648dce594afb92d6697e06264c936ea8f96f4c1cc73eb -- Recipe (0x2a8b...73eb)
- Market ID: 0x2a8b3660ee8d64a6464648dce594afb92d6697e06264c936ea8f96f4c1cc73eb (Market Hash)
- Request Timestamp: Fri, 03 Jan 2025 19:40:41 GMT

feat(market-map): Update market -- 11155111_0_0x2a8b3660ee8d64a6464648dce594afb92d6697e06264c936ea8f96f4c1cc73eb

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xdea9721b598778d7131edb33d8ae76244a881434b6bbd27bb78e53bb303aade3.ts

feat(market-map): Update market -- 11155111_0_0xdea9721b598778d7131edb33d8ae76244a881434b6bbd27bb78e53bb303aade3 -- Recipe (0xdea9...ade3)
- Market ID: 0xdea9721b598778d7131edb33d8ae76244a881434b6bbd27bb78e53bb303aade3 (Market Hash)
- Request Timestamp: Fri, 03 Jan 2025 20:03:17 GMT

feat(market-map): Update market -- 11155111_0_0xdea9721b598778d7131edb33d8ae76244a881434b6bbd27bb78e53bb303aade3

---

sdk/constants/market-map/21000000/definitions/21000000_1_0x1e01b44d1ed5eab8f009b89489f033e676bc00b8.ts

feat(market-map): Update market -- 21000000_1_0x1e01b44d1ed5eab8f009b89489f033e676bc00b8 -- Vault (0x1e01...00b8)
- Chain ID: 21000000
- Market ID: 0x1e01b44d1ed5eab8f009b89489f033e676bc00b8 (Wrapped Vault Address)
- Request Timestamp: Fri, 03 Jan 2025 20:24:17 GMT

feat(market-map): Update market -- 21000000_1_0x1e01b44d1ed5eab8f009b89489f033e676bc00b8

---

sdk/constants/market-map/98865/definitions/98865_1_0xebedd3ec4b38c0488ccda9bd825ac174546f99a2.ts

feat(market-map): Update market -- 98865_1_0xebedd3ec4b38c0488ccda9bd825ac174546f99a2 -- Vault (0xebed...99a2)
- Market ID: 0xebedd3ec4b38c0488ccda9bd825ac174546f99a2 (Wrapped Vault Address)
- Request Timestamp: Sat, 04 Jan 2025 02:49:12 GMT

feat(market-map): Update market -- 98865_1_0xebedd3ec4b38c0488ccda9bd825ac174546f99a2

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x1912c9673292bb0f8309e53989511e5bc4d9aec0e27d616ac43032b80f730cd6.ts

feat(market-map): Update market -- 11155111_0_0x1912c9673292bb0f8309e53989511e5bc4d9aec0e27d616ac43032b80f730cd6 -- Recipe (0x1912...0cd6)
- Market ID: 0x1912c9673292bb0f8309e53989511e5bc4d9aec0e27d616ac43032b80f730cd6 (Market Hash)
- Request Timestamp: Sat, 04 Jan 2025 04:35:04 GMT

feat(market-map): Update market -- 11155111_0_0x1912c9673292bb0f8309e53989511e5bc4d9aec0e27d616ac43032b80f730cd6

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x2358c05d965774d2db56493dfa94ce3edb7e78a35ebcbff30c112db54a008ce4.ts

feat(market-map): Update market -- 11155111_0_0x2358c05d965774d2db56493dfa94ce3edb7e78a35ebcbff30c112db54a008ce4 -- Recipe (0x2358...8ce4)
- Market ID: 0x2358c05d965774d2db56493dfa94ce3edb7e78a35ebcbff30c112db54a008ce4 (Market Hash)
- Request Timestamp: Sun, 05 Jan 2025 04:17:33 GMT

feat(market-map): Update market -- 11155111_0_0x2358c05d965774d2db56493dfa94ce3edb7e78a35ebcbff30c112db54a008ce4

---

sdk/constants/market-map/98865/definitions/98865_0_0x183932d726ff41d6eb7bb998b5eda7b4a04b81eccddcbab9f04dfccca0206bcb.ts

feat(market-map): Update market -- 98865_0_0x183932d726ff41d6eb7bb998b5eda7b4a04b81eccddcbab9f04dfccca0206bcb -- Recipe (0x1839...6bcb)
- Market ID: 0x183932d726ff41d6eb7bb998b5eda7b4a04b81eccddcbab9f04dfccca0206bcb (Market Hash)
- Request Timestamp: Sun, 05 Jan 2025 17:00:41 GMT

feat(market-map): Update market -- 98865_0_0x183932d726ff41d6eb7bb998b5eda7b4a04b81eccddcbab9f04dfccca0206bcb

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xc168f10a234adae731ce0d7f593ed5fe389577811ef6b024efb57ce4629fb3e4.ts

feat(market-map): Update market -- 11155111_0_0xc168f10a234adae731ce0d7f593ed5fe389577811ef6b024efb57ce4629fb3e4 -- Recipe (0xc168...b3e4)
- Market ID: 0xc168f10a234adae731ce0d7f593ed5fe389577811ef6b024efb57ce4629fb3e4 (Market Hash)
- Request Timestamp: Mon, 06 Jan 2025 18:02:15 GMT

feat(market-map): Update market -- 11155111_0_0xc168f10a234adae731ce0d7f593ed5fe389577811ef6b024efb57ce4629fb3e4

---

sdk/constants/market-map/1/definitions/1_1_0x4864da63d2e00199c76b602674deea214d670fce.ts

feat(market-map): Update market -- 1_1_0x4864da63d2e00199c76b602674deea214d670fce -- Vault (0x4864...0fce)
- Chain ID: 1
- Market ID: 0x4864da63d2e00199c76b602674deea214d670fce (Wrapped Vault Address)
- Request Timestamp: Tue, 07 Jan 2025 00:59:06 GMT

feat(market-map): Update market -- 1_1_0x4864da63d2e00199c76b602674deea214d670fce

---

sdk/constants/market-map/98865/definitions/98865_1_0x3bffe0403260c1809694d59939a75804791d5185.ts

feat(market-map): Update market -- 98865_1_0x3bffe0403260c1809694d59939a75804791d5185 -- Vault (0x3bff...5185)
- Market ID: 0x3bffe0403260c1809694d59939a75804791d5185 (Wrapped Vault Address)
- Request Timestamp: Tue, 07 Jan 2025 01:20:11 GMT

feat(market-map): Update market -- 98865_1_0x3bffe0403260c1809694d59939a75804791d5185

---

sdk/constants/market-map/1/definitions/1_1_0xf76c7e001d5f743956821f9cb18c95a99cd94c72.ts

feat(market-map): Update market -- 1_1_0xf76c7e001d5f743956821f9cb18c95a99cd94c72 -- Vault (0xf76c...4c72)
- Chain ID: 1
- Market ID: 0xf76c7e001d5f743956821f9cb18c95a99cd94c72 (Wrapped Vault Address)
- Request Timestamp: Tue, 07 Jan 2025 01:57:40 GMT

feat(market-map): Update market -- 1_1_0xf76c7e001d5f743956821f9cb18c95a99cd94c72

---

sdk/constants/market-map/1/definitions/1_1_0xa628e21a09c8826bcbc12ebb8e9efde1f9f54b26.ts

feat(market-map): Update market -- 1_1_0xa628e21a09c8826bcbc12ebb8e9efde1f9f54b26 -- Vault (0xa628...4b26)
- Chain ID: 1
- Market ID: 0xa628e21a09c8826bcbc12ebb8e9efde1f9f54b26 (Wrapped Vault Address)
- Request Timestamp: Tue, 07 Jan 2025 02:01:24 GMT

feat(market-map): Update market -- 1_1_0xa628e21a09c8826bcbc12ebb8e9efde1f9f54b26

---

sdk/constants/market-map/98865/definitions/98865_0_0xa7ebb71cacae2db2c8db5e8be1e383e520f76fe89bd180c430007b7bb000eab9.ts

feat(market-map): Update market -- 98865_0_0xa7ebb71cacae2db2c8db5e8be1e383e520f76fe89bd180c430007b7bb000eab9 -- Recipe (0xa7eb...eab9)
- Market ID: 0xa7ebb71cacae2db2c8db5e8be1e383e520f76fe89bd180c430007b7bb000eab9 (Market Hash)
- Request Timestamp: Tue, 07 Jan 2025 02:30:19 GMT

feat(market-map): Update market -- 98865_0_0xa7ebb71cacae2db2c8db5e8be1e383e520f76fe89bd180c430007b7bb000eab9

---

sdk/constants/market-map/98865/definitions/98865_1_0xe86a17a5e498161b19f9aaa374240473b8e2e5e9.ts

feat(market-map): Update market -- 98865_1_0xe86a17a5e498161b19f9aaa374240473b8e2e5e9 -- Vault (0xe86a...e5e9)
- Market ID: 0xe86a17a5e498161b19f9aaa374240473b8e2e5e9 (Wrapped Vault Address)
- Request Timestamp: Tue, 07 Jan 2025 02:49:31 GMT

feat(market-map): Update market -- 98865_1_0xe86a17a5e498161b19f9aaa374240473b8e2e5e9

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x75091cb3ba55fe7af132865c9a9d97c57203c2b7c8aca6c293c4cf1a9f1c765f.ts

feat(market-map): Update market -- 11155111_0_0x75091cb3ba55fe7af132865c9a9d97c57203c2b7c8aca6c293c4cf1a9f1c765f -- Recipe (0x7509...765f)
- Market ID: 0x75091cb3ba55fe7af132865c9a9d97c57203c2b7c8aca6c293c4cf1a9f1c765f (Market Hash)
- Request Timestamp: Tue, 07 Jan 2025 04:55:55 GMT

feat(market-map): Update market -- 11155111_0_0x75091cb3ba55fe7af132865c9a9d97c57203c2b7c8aca6c293c4cf1a9f1c765f

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x3ec1c4ce239efccc95df32886b4eda6aad6813dd340e70efd0a262522781bd5e.ts

feat(market-map): Update market -- 11155111_0_0x3ec1c4ce239efccc95df32886b4eda6aad6813dd340e70efd0a262522781bd5e -- Recipe (0x3ec1...bd5e)
- Market ID: 0x3ec1c4ce239efccc95df32886b4eda6aad6813dd340e70efd0a262522781bd5e (Market Hash)
- Request Timestamp: Tue, 07 Jan 2025 04:57:53 GMT

feat(market-map): Update market -- 11155111_0_0x3ec1c4ce239efccc95df32886b4eda6aad6813dd340e70efd0a262522781bd5e

---

sdk/constants/market-map/42161/definitions/42161_1_0x6b0036ae0a76475b67f80c4ed849c72f0cc1a140.ts

feat(market-map): Update market -- 42161_1_0x6b0036ae0a76475b67f80c4ed849c72f0cc1a140 -- Vault (0x6b00...a140)
- Market ID: 0x6b0036ae0a76475b67f80c4ed849c72f0cc1a140 (Wrapped Vault Address)
- Request Timestamp: Tue, 07 Jan 2025 19:42:30 GMT

feat(market-map): Update market -- 42161_1_0x6b0036ae0a76475b67f80c4ed849c72f0cc1a140

---

sdk/constants/market-map/1/definitions/1_0_0xc1dc80b3da8a0daa59d8768eac41377b011016bdd3661a7b14917057235655d6.ts

feat(market-map): Update market -- 1_0_0xc1dc80b3da8a0daa59d8768eac41377b011016bdd3661a7b14917057235655d6 -- Recipe (0xc1dc...55d6)
- Chain ID: 1
- Market ID: 0xc1dc80b3da8a0daa59d8768eac41377b011016bdd3661a7b14917057235655d6 (Market Hash)
- Request Timestamp: Tue, 07 Jan 2025 21:26:05 GMT

feat(market-map): Update market -- 1_0_0xc1dc80b3da8a0daa59d8768eac41377b011016bdd3661a7b14917057235655d6

---

sdk/constants/market-map/1/definitions/1_0_0x98d9a1e56e8f60cb1843a7f0c1d27efc91f2f5eaef8fc4b07ae7299d3bc888a2.ts

feat(market-map): Update market -- 1_0_0x98d9a1e56e8f60cb1843a7f0c1d27efc91f2f5eaef8fc4b07ae7299d3bc888a2 -- Recipe (0x98d9...88a2)
- Chain ID: 1
- Market ID: 0x98d9a1e56e8f60cb1843a7f0c1d27efc91f2f5eaef8fc4b07ae7299d3bc888a2 (Market Hash)
- Request Timestamp: Tue, 07 Jan 2025 21:41:03 GMT

feat(market-map): Update market -- 1_0_0x98d9a1e56e8f60cb1843a7f0c1d27efc91f2f5eaef8fc4b07ae7299d3bc888a2

---

sdk/constants/market-map/1/definitions/1_0_0x137a23dce4c76528e79c3bc9c921808d0ab68ebc6973f3fef17454e14c6fe7d6.ts

feat(market-map): Update market -- 1_0_0x137a23dce4c76528e79c3bc9c921808d0ab68ebc6973f3fef17454e14c6fe7d6 -- Recipe (0x137a...e7d6)
- Chain ID: 1
- Market ID: 0x137a23dce4c76528e79c3bc9c921808d0ab68ebc6973f3fef17454e14c6fe7d6 (Market Hash)
- Request Timestamp: Tue, 07 Jan 2025 22:10:15 GMT

feat(market-map): Update market -- 1_0_0x137a23dce4c76528e79c3bc9c921808d0ab68ebc6973f3fef17454e14c6fe7d6

---

sdk/constants/market-map/98865/definitions/98865_0_0x1866ba487f09ab29612567f6a8f6ede1fbfed54e9e2305275fc3202f553c2f03.ts

feat(market-map): Update market -- 98865_0_0x1866ba487f09ab29612567f6a8f6ede1fbfed54e9e2305275fc3202f553c2f03 -- Recipe (0x1866...2f03)
- Market ID: 0x1866ba487f09ab29612567f6a8f6ede1fbfed54e9e2305275fc3202f553c2f03 (Market Hash)
- Request Timestamp: Tue, 07 Jan 2025 22:15:39 GMT

feat(market-map): Update market -- 98865_0_0x1866ba487f09ab29612567f6a8f6ede1fbfed54e9e2305275fc3202f553c2f03

---

sdk/constants/market-map/1/definitions/1_0_0xf98c40038e95042341a5e0f0d9fa4cc7a32a839f8645ebb91dd770f8578e2280.ts

feat(market-map): Update market -- 1_0_0xf98c40038e95042341a5e0f0d9fa4cc7a32a839f8645ebb91dd770f8578e2280 -- Recipe (0xf98c...2280)
- Chain ID: 1
- Market ID: 0xf98c40038e95042341a5e0f0d9fa4cc7a32a839f8645ebb91dd770f8578e2280 (Market Hash)
- Request Timestamp: Tue, 07 Jan 2025 22:39:06 GMT

feat(market-map): Update market -- 1_0_0xf98c40038e95042341a5e0f0d9fa4cc7a32a839f8645ebb91dd770f8578e2280

---

sdk/constants/market-map/98865/definitions/98865_0_0xab330f60b2a63cf05361a60019a06881f5dfb618e9c84dd9f8927e20d899430b.ts

feat(market-map): Update market -- 98865_0_0xab330f60b2a63cf05361a60019a06881f5dfb618e9c84dd9f8927e20d899430b -- Recipe (0xab33...430b)
- Market ID: 0xab330f60b2a63cf05361a60019a06881f5dfb618e9c84dd9f8927e20d899430b (Market Hash)
- Request Timestamp: Tue, 07 Jan 2025 23:20:28 GMT

feat(market-map): Update market -- 98865_0_0xab330f60b2a63cf05361a60019a06881f5dfb618e9c84dd9f8927e20d899430b

---

sdk/constants/market-map/1/definitions/1_0_0x0e999b4746b5f585c593209b687cee16f06314cc6d7db8630497f2587e71bed7.ts

feat(market-map): Update market -- 1_0_0x0e999b4746b5f585c593209b687cee16f06314cc6d7db8630497f2587e71bed7 -- Recipe (0x0e99...bed7)
- Chain ID: 1
- Market ID: 0x0e999b4746b5f585c593209b687cee16f06314cc6d7db8630497f2587e71bed7 (Market Hash)
- Request Timestamp: Wed, 08 Jan 2025 03:37:19 GMT

feat(market-map): Update market -- 1_0_0x0e999b4746b5f585c593209b687cee16f06314cc6d7db8630497f2587e71bed7

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x4adaf74d8888e44eac2ed539bc2d177bcc969f2155cb20b0c8087588802fbc20.ts

feat(market-map): Update market -- 11155111_0_0x4adaf74d8888e44eac2ed539bc2d177bcc969f2155cb20b0c8087588802fbc20 -- Recipe (0x4ada...bc20)
- Market ID: 0x4adaf74d8888e44eac2ed539bc2d177bcc969f2155cb20b0c8087588802fbc20 (Market Hash)
- Request Timestamp: Wed, 08 Jan 2025 06:50:57 GMT

feat(market-map): Update market -- 11155111_0_0x4adaf74d8888e44eac2ed539bc2d177bcc969f2155cb20b0c8087588802fbc20

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x53972e865d93fc59aac4bd1812d960da3de4a8f6c8fc8f220a233f6e6606223a.ts

feat(market-map): Update market -- 11155111_0_0x53972e865d93fc59aac4bd1812d960da3de4a8f6c8fc8f220a233f6e6606223a -- Recipe (0x5397...223a)
- Market ID: 0x53972e865d93fc59aac4bd1812d960da3de4a8f6c8fc8f220a233f6e6606223a (Market Hash)
- Request Timestamp: Wed, 08 Jan 2025 07:06:27 GMT

feat(market-map): Update market -- 11155111_0_0x53972e865d93fc59aac4bd1812d960da3de4a8f6c8fc8f220a233f6e6606223a

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xb87c3a5efa3e946edf20290836dfe0d1e55c1c762fdf3fdabfccdbb956c7c248.ts

feat(market-map): Update market -- 11155111_0_0xb87c3a5efa3e946edf20290836dfe0d1e55c1c762fdf3fdabfccdbb956c7c248 -- Recipe (0xb87c...c248)
- Market ID: 0xb87c3a5efa3e946edf20290836dfe0d1e55c1c762fdf3fdabfccdbb956c7c248 (Market Hash)
- Request Timestamp: Thu, 09 Jan 2025 05:00:54 GMT

feat(market-map): Update market -- 11155111_0_0xb87c3a5efa3e946edf20290836dfe0d1e55c1c762fdf3fdabfccdbb956c7c248

---

sdk/constants/market-map/8453/definitions/8453_0_0x01343749855527b9525f0a2c5e12daff5f3da81bfd8af3514334fdfb5a9ae931.ts

feat(market-map): Update market -- 8453_0_0x01343749855527b9525f0a2c5e12daff5f3da81bfd8af3514334fdfb5a9ae931 -- Recipe (0x0134...e931)
- Market ID: 0x01343749855527b9525f0a2c5e12daff5f3da81bfd8af3514334fdfb5a9ae931 (Market Hash)
- Request Timestamp: Thu, 09 Jan 2025 08:18:31 GMT

feat(market-map): Update market -- 8453_0_0x01343749855527b9525f0a2c5e12daff5f3da81bfd8af3514334fdfb5a9ae931

---

sdk/constants/market-map/1/definitions/1_1_0x8972fb213a02fb2296ea03ffad5af1e7f7e51161.ts

feat(market-map): Update market -- 1_1_0x8972fb213a02fb2296ea03ffad5af1e7f7e51161 -- Vault (0x8972...1161)
- Chain ID: 1
- Market ID: 0x8972fb213a02fb2296ea03ffad5af1e7f7e51161 (Wrapped Vault Address)
- Request Timestamp: Thu, 09 Jan 2025 11:52:57 GMT

feat(market-map): Update market -- 1_1_0x8972fb213a02fb2296ea03ffad5af1e7f7e51161

---

sdk/constants/market-map/42161/definitions/42161_1_0xb0aaa226fde54cf884760b12657074a56c5743ef.ts

feat(market-map): Update market -- 42161_1_0xb0aaa226fde54cf884760b12657074a56c5743ef -- Vault (0xb0aa...43ef)
- Market ID: 0xb0aaa226fde54cf884760b12657074a56c5743ef (Wrapped Vault Address)
- Request Timestamp: Thu, 09 Jan 2025 12:04:43 GMT

feat(market-map): Update market -- 42161_1_0xb0aaa226fde54cf884760b12657074a56c5743ef

---

sdk/constants/market-map/98865/definitions/98865_0_0xebb747b3c88deb9cde9fe5a89f8ec5b07441393e795bfb22973364c0e67bd123.ts

feat(market-map): Update market -- 98865_0_0xebb747b3c88deb9cde9fe5a89f8ec5b07441393e795bfb22973364c0e67bd123 -- Recipe (0xebb7...d123)
- Market ID: 0xebb747b3c88deb9cde9fe5a89f8ec5b07441393e795bfb22973364c0e67bd123 (Market Hash)
- Request Timestamp: Thu, 09 Jan 2025 18:22:21 GMT

feat(market-map): Update market -- 98865_0_0xebb747b3c88deb9cde9fe5a89f8ec5b07441393e795bfb22973364c0e67bd123

---

sdk/constants/market-map/1/definitions/1_1_0x2407ccfff27a6c40f8c8926959ae56ca8d1c3edc.ts

feat(market-map): Update market -- 1_1_0x2407ccfff27a6c40f8c8926959ae56ca8d1c3edc -- Vault (0x2407...3edc)
- Chain ID: 1
- Market ID: 0x2407ccfff27a6c40f8c8926959ae56ca8d1c3edc (Wrapped Vault Address)
- Request Timestamp: Thu, 09 Jan 2025 22:02:55 GMT

feat(market-map): Update market -- 1_1_0x2407ccfff27a6c40f8c8926959ae56ca8d1c3edc

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xee4357ad61ad86b0af97df82adb9e66a0911f82dfd19b98e1ad0ed76c63ceb72.ts

feat(market-map): Update market -- 11155111_0_0xee4357ad61ad86b0af97df82adb9e66a0911f82dfd19b98e1ad0ed76c63ceb72 -- Recipe (0xee43...eb72)
- Market ID: 0xee4357ad61ad86b0af97df82adb9e66a0911f82dfd19b98e1ad0ed76c63ceb72 (Market Hash)
- Request Timestamp: Thu, 09 Jan 2025 22:51:28 GMT

feat(market-map): Update market -- 11155111_0_0xee4357ad61ad86b0af97df82adb9e66a0911f82dfd19b98e1ad0ed76c63ceb72

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x59f9b753d4a23d2a0cad785c90bbda6fefb2a2da8e821ffab67e522b9308a2c4.ts

feat(market-map): Update market -- 11155111_0_0x59f9b753d4a23d2a0cad785c90bbda6fefb2a2da8e821ffab67e522b9308a2c4 -- Recipe (0x59f9...a2c4)
- Market ID: 0x59f9b753d4a23d2a0cad785c90bbda6fefb2a2da8e821ffab67e522b9308a2c4 (Market Hash)
- Request Timestamp: Fri, 10 Jan 2025 04:25:04 GMT

feat(market-map): Update market -- 11155111_0_0x59f9b753d4a23d2a0cad785c90bbda6fefb2a2da8e821ffab67e522b9308a2c4

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x031ac731c8c5981d183222752c371b45bf0c2e42610d2af9d0a01f3676308145.ts

feat(market-map): Update market -- 11155111_0_0x031ac731c8c5981d183222752c371b45bf0c2e42610d2af9d0a01f3676308145 -- Recipe (0x031a...8145)
- Market ID: 0x031ac731c8c5981d183222752c371b45bf0c2e42610d2af9d0a01f3676308145 (Market Hash)
- Request Timestamp: Fri, 10 Jan 2025 04:55:58 GMT

feat(market-map): Update market -- 11155111_0_0x031ac731c8c5981d183222752c371b45bf0c2e42610d2af9d0a01f3676308145

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x14a40bc60f69c582d9e664a2a03765b1dd6182296c42ef7eb2d71eefcd7825c4.ts

feat(market-map): Update market -- 11155111_0_0x14a40bc60f69c582d9e664a2a03765b1dd6182296c42ef7eb2d71eefcd7825c4 -- Recipe (0x14a4...25c4)
- Market ID: 0x14a40bc60f69c582d9e664a2a03765b1dd6182296c42ef7eb2d71eefcd7825c4 (Market Hash)
- Request Timestamp: Thu, 09 Jan 2025 06:50:28 GMT

feat(market-map): Update market -- 11155111_0_0x14a40bc60f69c582d9e664a2a03765b1dd6182296c42ef7eb2d71eefcd7825c4

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xfa8768959340503f01d11503080b1b5d77832bd20ad64785122c7e614f93518e.ts

feat(market-map): Update market -- 11155111_0_0xfa8768959340503f01d11503080b1b5d77832bd20ad64785122c7e614f93518e -- Recipe (0xfa87...518e)
- Market ID: 0xfa8768959340503f01d11503080b1b5d77832bd20ad64785122c7e614f93518e (Market Hash)
- Request Timestamp: Fri, 10 Jan 2025 13:23:41 GMT

feat(market-map): Update market -- 11155111_0_0xfa8768959340503f01d11503080b1b5d77832bd20ad64785122c7e614f93518e

---

sdk/constants/market-map/98865/definitions/98865_0_0x7070af46bf9981fd09a13b1feec3e8253a9fc4d3074ef073b1fe41afd7c0e51a.ts

feat(market-map): Update market -- 98865_0_0x7070af46bf9981fd09a13b1feec3e8253a9fc4d3074ef073b1fe41afd7c0e51a -- Recipe (0x7070...e51a)
- Market ID: 0x7070af46bf9981fd09a13b1feec3e8253a9fc4d3074ef073b1fe41afd7c0e51a (Market Hash)
- Request Timestamp: Fri, 10 Jan 2025 13:54:38 GMT

feat(market-map): Update market -- 98865_0_0x7070af46bf9981fd09a13b1feec3e8253a9fc4d3074ef073b1fe41afd7c0e51a

---

sdk/constants/market-map/8453/definitions/8453_0_0x1ca4129e09bfea50d71f1aaf8ef52be058b58301939a84406c51286454147591.ts

feat(market-map): Update market -- 8453_0_0x1ca4129e09bfea50d71f1aaf8ef52be058b58301939a84406c51286454147591 -- Recipe (0x1ca4...7591)
- Market ID: 0x1ca4129e09bfea50d71f1aaf8ef52be058b58301939a84406c51286454147591 (Market Hash)
- Request Timestamp: Fri, 10 Jan 2025 22:32:20 GMT

feat(market-map): Update market -- 8453_0_0x1ca4129e09bfea50d71f1aaf8ef52be058b58301939a84406c51286454147591

---

sdk/constants/market-map/8453/definitions/8453_0_0x1b467d65fde4ec8988e8df1706d0f9e028db8d41e14d10fbbd7b194e5744ac59.ts

feat(market-map): Update market -- 8453_0_0x1b467d65fde4ec8988e8df1706d0f9e028db8d41e14d10fbbd7b194e5744ac59 -- Recipe (0x1b46...ac59)
- Market ID: 0x1b467d65fde4ec8988e8df1706d0f9e028db8d41e14d10fbbd7b194e5744ac59 (Market Hash)
- Request Timestamp: Fri, 10 Jan 2025 22:58:59 GMT

feat(market-map): Update market -- 8453_0_0x1b467d65fde4ec8988e8df1706d0f9e028db8d41e14d10fbbd7b194e5744ac59

---

sdk/constants/market-map/1/definitions/1_1_0x28eb0e650153bc39dbf2f709feaee49362682458.ts

feat(market-map): Update market -- 1_1_0x28eb0e650153bc39dbf2f709feaee49362682458 -- Vault (0x28eb...2458)
- Chain ID: 1
- Market ID: 0x28eb0e650153bc39dbf2f709feaee49362682458 (Wrapped Vault Address)
- Request Timestamp: Sat, 11 Jan 2025 12:12:56 GMT

feat(market-map): Update market -- 1_1_0x28eb0e650153bc39dbf2f709feaee49362682458

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xb5144003925bfa37ce5ace2e76606955aa2a49c39dbaf90b95c58c46a586bb2d.ts

feat(market-map): Update market -- 11155111_0_0xb5144003925bfa37ce5ace2e76606955aa2a49c39dbaf90b95c58c46a586bb2d -- Recipe (0xb514...bb2d)
- Market ID: 0xb5144003925bfa37ce5ace2e76606955aa2a49c39dbaf90b95c58c46a586bb2d (Market Hash)
- Request Timestamp: Sun, 12 Jan 2025 21:06:02 GMT

feat(market-map): Update market -- 11155111_0_0xb5144003925bfa37ce5ace2e76606955aa2a49c39dbaf90b95c58c46a586bb2d

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x7df3eaefa1ddb60a290dca7bfd9f85b91ceec16f2998bbd17a06dfe9aefc0340.ts

feat(market-map): Update market -- 11155111_0_0x7df3eaefa1ddb60a290dca7bfd9f85b91ceec16f2998bbd17a06dfe9aefc0340 -- Recipe (0x7df3...0340)
- Market ID: 0x7df3eaefa1ddb60a290dca7bfd9f85b91ceec16f2998bbd17a06dfe9aefc0340 (Market Hash)
- Request Timestamp: Sun, 12 Jan 2025 21:26:17 GMT

feat(market-map): Update market -- 11155111_0_0x7df3eaefa1ddb60a290dca7bfd9f85b91ceec16f2998bbd17a06dfe9aefc0340

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xc152a589c25eba66e227bf5af150dbe50e1d18df2ff92dc6ee6d5e8a9bca325c.ts

feat(market-map): Update market -- 11155111_0_0xc152a589c25eba66e227bf5af150dbe50e1d18df2ff92dc6ee6d5e8a9bca325c -- Recipe (0xc152...325c)
- Market ID: 0xc152a589c25eba66e227bf5af150dbe50e1d18df2ff92dc6ee6d5e8a9bca325c (Market Hash)
- Request Timestamp: Sun, 12 Jan 2025 21:29:41 GMT

feat(market-map): Update market -- 11155111_0_0xc152a589c25eba66e227bf5af150dbe50e1d18df2ff92dc6ee6d5e8a9bca325c

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x32aab9f5498a018c4aeeb0bd1b85fa8be9e996f6a337b26b841db739ebabee75.ts

feat(market-map): Update market -- 11155111_0_0x32aab9f5498a018c4aeeb0bd1b85fa8be9e996f6a337b26b841db739ebabee75 -- Recipe (0x32aa...ee75)
- Market ID: 0x32aab9f5498a018c4aeeb0bd1b85fa8be9e996f6a337b26b841db739ebabee75 (Market Hash)
- Request Timestamp: Sun, 12 Jan 2025 21:32:18 GMT

feat(market-map): Update market -- 11155111_0_0x32aab9f5498a018c4aeeb0bd1b85fa8be9e996f6a337b26b841db739ebabee75

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x93480693dceada412617a905f6e0686214d94028f9548236ef5ff91f1e39a46d.ts

feat(market-map): Update market -- 11155111_0_0x93480693dceada412617a905f6e0686214d94028f9548236ef5ff91f1e39a46d -- Recipe (0x9348...a46d)
- Market ID: 0x93480693dceada412617a905f6e0686214d94028f9548236ef5ff91f1e39a46d (Market Hash)
- Request Timestamp: Sun, 12 Jan 2025 22:30:16 GMT

feat(market-map): Update market -- 11155111_0_0x93480693dceada412617a905f6e0686214d94028f9548236ef5ff91f1e39a46d

---

sdk/constants/market-map/98865/definitions/98865_0_0x8a0483a831367ad94d95b6ddc87d87c8214cb0b2ef520b00acc43b8e53383d3a.ts

feat(market-map): Update market -- 98865_0_0x8a0483a831367ad94d95b6ddc87d87c8214cb0b2ef520b00acc43b8e53383d3a -- Recipe (0x8a04...3d3a)
- Market ID: 0x8a0483a831367ad94d95b6ddc87d87c8214cb0b2ef520b00acc43b8e53383d3a (Market Hash)
- Request Timestamp: Sun, 12 Jan 2025 23:31:58 GMT

feat(market-map): Update market -- 98865_0_0x8a0483a831367ad94d95b6ddc87d87c8214cb0b2ef520b00acc43b8e53383d3a

---

sdk/constants/market-map/98865/definitions/98865_0_0xef42ef875aeb02e99eadda40ea60fd5d3a28afb914520fa5b2c2d19a7acd6cb4.ts

feat(market-map): Update market -- 98865_0_0xef42ef875aeb02e99eadda40ea60fd5d3a28afb914520fa5b2c2d19a7acd6cb4 -- Recipe (0xef42...6cb4)
- Market ID: 0xef42ef875aeb02e99eadda40ea60fd5d3a28afb914520fa5b2c2d19a7acd6cb4 (Market Hash)
- Request Timestamp: Sun, 12 Jan 2025 23:46:49 GMT

feat(market-map): Update market -- 98865_0_0xef42ef875aeb02e99eadda40ea60fd5d3a28afb914520fa5b2c2d19a7acd6cb4

---

sdk/constants/market-map/98865/definitions/98865_0_0x897854e0338bda707d52c57d234d3ad265e7337a9d64938be266d9f0074cbb3b.ts

feat(market-map): Update market -- 98865_0_0x897854e0338bda707d52c57d234d3ad265e7337a9d64938be266d9f0074cbb3b -- Recipe (0x8978...bb3b)
- Market ID: 0x897854e0338bda707d52c57d234d3ad265e7337a9d64938be266d9f0074cbb3b (Market Hash)
- Request Timestamp: Mon, 13 Jan 2025 12:50:59 GMT

feat(market-map): Update market -- 98865_0_0x897854e0338bda707d52c57d234d3ad265e7337a9d64938be266d9f0074cbb3b

---

sdk/constants/token-map/1/definitions/1-0xCfFE9112BfA141aE9170BE4d172d40a455662564.ts

On mainnet - required for boyco

Origami bKAMI points

---

sdk/constants/market-map/98865/definitions/98865_0_0x84504dd32c6c27dc7baf2f442df2a27f4ebec506d18526194836d1a752ce0c75.ts

feat(market-map): Update market -- 98865_0_0x84504dd32c6c27dc7baf2f442df2a27f4ebec506d18526194836d1a752ce0c75 -- Recipe (0x8450...0c75)
- Market ID: 0x84504dd32c6c27dc7baf2f442df2a27f4ebec506d18526194836d1a752ce0c75 (Market Hash)
- Request Timestamp: Tue, 14 Jan 2025 01:39:14 GMT

feat(market-map): Update market -- 98865_0_0x84504dd32c6c27dc7baf2f442df2a27f4ebec506d18526194836d1a752ce0c75

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x1f2b74e314a4520120aeef6a5f9dc9bb2f938adcdf59a838c8fe5971b301bf79.ts

feat(market-map): Update market -- 11155111_0_0x1f2b74e314a4520120aeef6a5f9dc9bb2f938adcdf59a838c8fe5971b301bf79 -- Recipe (0x1f2b...bf79)
- Market ID: 0x1f2b74e314a4520120aeef6a5f9dc9bb2f938adcdf59a838c8fe5971b301bf79 (Market Hash)
- Request Timestamp: Tue, 14 Jan 2025 06:00:26 GMT

feat(market-map): Update market -- 11155111_0_0x1f2b74e314a4520120aeef6a5f9dc9bb2f938adcdf59a838c8fe5971b301bf79

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x980e70b90e76ccb9b3a4fa5743e5e717f9342ec81860c9146169d4368df3ebf4.ts

feat(market-map): Update market -- 11155111_0_0x980e70b90e76ccb9b3a4fa5743e5e717f9342ec81860c9146169d4368df3ebf4 -- Recipe (0x980e...ebf4)
- Market ID: 0x980e70b90e76ccb9b3a4fa5743e5e717f9342ec81860c9146169d4368df3ebf4 (Market Hash)
- Request Timestamp: Tue, 14 Jan 2025 06:30:06 GMT

feat(market-map): Update market -- 11155111_0_0x980e70b90e76ccb9b3a4fa5743e5e717f9342ec81860c9146169d4368df3ebf4

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x5fb3243f9a7e617198d50a66db35dc437da15432602058f9225a5cf328347ad6.ts

feat(market-map): Update market -- 11155111_0_0x5fb3243f9a7e617198d50a66db35dc437da15432602058f9225a5cf328347ad6 -- Recipe (0x5fb3...7ad6)
- Market ID: 0x5fb3243f9a7e617198d50a66db35dc437da15432602058f9225a5cf328347ad6 (Market Hash)
- Request Timestamp: Tue, 14 Jan 2025 12:00:33 GMT

feat(market-map): Update market -- 11155111_0_0x5fb3243f9a7e617198d50a66db35dc437da15432602058f9225a5cf328347ad6

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x53108a3873b939aa859e82fb29db6137af4def04397395aeb977c83f41885d5c.ts

feat(market-map): Update market -- 11155111_0_0x53108a3873b939aa859e82fb29db6137af4def04397395aeb977c83f41885d5c -- Recipe (0x5310...5d5c)
- Market ID: 0x53108a3873b939aa859e82fb29db6137af4def04397395aeb977c83f41885d5c (Market Hash)
- Request Timestamp: Tue, 14 Jan 2025 12:16:18 GMT

feat(market-map): Update market -- 11155111_0_0x53108a3873b939aa859e82fb29db6137af4def04397395aeb977c83f41885d5c

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x1d0139cb434f4a5cc942ccb4f850ef0d2a4b84b55fcd15a498716993e8c243d3.ts

feat(market-map): Update market -- 11155111_0_0x1d0139cb434f4a5cc942ccb4f850ef0d2a4b84b55fcd15a498716993e8c243d3 -- Recipe (0x1d01...43d3)
- Market ID: 0x1d0139cb434f4a5cc942ccb4f850ef0d2a4b84b55fcd15a498716993e8c243d3 (Market Hash)
- Request Timestamp: Wed, 15 Jan 2025 17:23:22 GMT

feat(market-map): Update market -- 11155111_0_0x1d0139cb434f4a5cc942ccb4f850ef0d2a4b84b55fcd15a498716993e8c243d3

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x265e89a2056367a0b3233a6b7f3536fb9060a65c35480c6daad0d2eb66acc3a8.ts

feat(market-map): Update market -- 11155111_0_0x265e89a2056367a0b3233a6b7f3536fb9060a65c35480c6daad0d2eb66acc3a8 -- Recipe (0x265e...c3a8)
- Market ID: 0x265e89a2056367a0b3233a6b7f3536fb9060a65c35480c6daad0d2eb66acc3a8 (Market Hash)
- Request Timestamp: Wed, 15 Jan 2025 17:25:16 GMT

feat(market-map): Update market -- 11155111_0_0x265e89a2056367a0b3233a6b7f3536fb9060a65c35480c6daad0d2eb66acc3a8

---

sdk/constants/market-map/1/definitions/1_1_0xdd6e66853ef02d706c89c12d7cdf9dad6ab7e65e.ts

feat(market-map): Update market -- 1_1_0xdd6e66853ef02d706c89c12d7cdf9dad6ab7e65e -- Vault (0xdd6e...e65e)
- Chain ID: 1
- Market ID: 0xdd6e66853ef02d706c89c12d7cdf9dad6ab7e65e (Wrapped Vault Address)
- Request Timestamp: Wed, 15 Jan 2025 21:50:05 GMT

feat(market-map): Update market -- 1_1_0xdd6e66853ef02d706c89c12d7cdf9dad6ab7e65e

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x8ad1a401f1e96aa6778da9016b986364d6b541a6ac46e7c6b9c05442b9a65e9a.ts

feat(market-map): Update market -- 11155111_0_0x8ad1a401f1e96aa6778da9016b986364d6b541a6ac46e7c6b9c05442b9a65e9a -- Recipe (0x8ad1...5e9a)
- Market ID: 0x8ad1a401f1e96aa6778da9016b986364d6b541a6ac46e7c6b9c05442b9a65e9a (Market Hash)
- Request Timestamp: Thu, 16 Jan 2025 05:50:49 GMT

feat(market-map): Update market -- 11155111_0_0x8ad1a401f1e96aa6778da9016b986364d6b541a6ac46e7c6b9c05442b9a65e9a

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x15dce2565cef3fe3ed29dca20a94016d7cf6a7634f3ea8d3f49f18387dd3c976.ts

feat(market-map): Update market -- 11155111_0_0x15dce2565cef3fe3ed29dca20a94016d7cf6a7634f3ea8d3f49f18387dd3c976 -- Recipe (0x15dc...c976)
- Market ID: 0x15dce2565cef3fe3ed29dca20a94016d7cf6a7634f3ea8d3f49f18387dd3c976 (Market Hash)
- Request Timestamp: Thu, 16 Jan 2025 06:53:18 GMT

feat(market-map): Update market -- 11155111_0_0x15dce2565cef3fe3ed29dca20a94016d7cf6a7634f3ea8d3f49f18387dd3c976

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x3a911b4ea77a28c1ad9f5a75901a1354cf9108f5939090e9d4696f78df82deac.ts

feat(market-map): Update market -- 11155111_0_0x3a911b4ea77a28c1ad9f5a75901a1354cf9108f5939090e9d4696f78df82deac -- Recipe (0x3a91...deac)
- Market ID: 0x3a911b4ea77a28c1ad9f5a75901a1354cf9108f5939090e9d4696f78df82deac (Market Hash)
- Request Timestamp: Thu, 16 Jan 2025 07:20:08 GMT

feat(market-map): Update market -- 11155111_0_0x3a911b4ea77a28c1ad9f5a75901a1354cf9108f5939090e9d4696f78df82deac

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xf79998384ce10debc8d1b291ad2717a37f2db89da84f6556520f0c56c1b607dc.ts

feat(market-map): Update market -- 11155111_0_0xf79998384ce10debc8d1b291ad2717a37f2db89da84f6556520f0c56c1b607dc -- Recipe (0xf799...07dc)
- Market ID: 0xf79998384ce10debc8d1b291ad2717a37f2db89da84f6556520f0c56c1b607dc (Market Hash)
- Request Timestamp: Thu, 16 Jan 2025 09:32:29 GMT

feat(market-map): Update market -- 11155111_0_0xf79998384ce10debc8d1b291ad2717a37f2db89da84f6556520f0c56c1b607dc

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x1ff58bc3874d409c2bc542b34bf043774e2dd142887c1afa14868960c1e27127.ts

feat(market-map): Update market -- 11155111_0_0x1ff58bc3874d409c2bc542b34bf043774e2dd142887c1afa14868960c1e27127 -- Recipe (0x1ff5...7127)
- Market ID: 0x1ff58bc3874d409c2bc542b34bf043774e2dd142887c1afa14868960c1e27127 (Market Hash)
- Request Timestamp: Thu, 16 Jan 2025 14:30:29 GMT

feat(market-map): Update market -- 11155111_0_0x1ff58bc3874d409c2bc542b34bf043774e2dd142887c1afa14868960c1e27127

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x2ea20b925ef3c6a0840c7cecfb1f65a14364d2935a2559f8bf45f8007c369f3c.ts

feat(market-map): Update market -- 11155111_0_0x2ea20b925ef3c6a0840c7cecfb1f65a14364d2935a2559f8bf45f8007c369f3c -- Recipe (0x2ea2...9f3c)
- Market ID: 0x2ea20b925ef3c6a0840c7cecfb1f65a14364d2935a2559f8bf45f8007c369f3c (Market Hash)
- Request Timestamp: Thu, 16 Jan 2025 14:46:40 GMT

feat(market-map): Update market -- 11155111_0_0x2ea20b925ef3c6a0840c7cecfb1f65a14364d2935a2559f8bf45f8007c369f3c

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xaccc7132c8764a6ed514c7358b3d0bf2ba377b32cddf11b9d49df035b7a99b8c.ts

feat(market-map): Update market -- 11155111_0_0xaccc7132c8764a6ed514c7358b3d0bf2ba377b32cddf11b9d49df035b7a99b8c -- Recipe (0xaccc...9b8c)
- Market ID: 0xaccc7132c8764a6ed514c7358b3d0bf2ba377b32cddf11b9d49df035b7a99b8c (Market Hash)
- Request Timestamp: Thu, 16 Jan 2025 15:46:08 GMT

feat(market-map): Update market -- 11155111_0_0xaccc7132c8764a6ed514c7358b3d0bf2ba377b32cddf11b9d49df035b7a99b8c

---

sdk/constants/market-map/8453/definitions/8453_0_0x18493e771a4fd1cc17f01ec9f12cc3058bd4e30fda4affdd3e2c11ec6a557c8c.ts

feat(market-map): Update market -- 8453_0_0x18493e771a4fd1cc17f01ec9f12cc3058bd4e30fda4affdd3e2c11ec6a557c8c -- Recipe (0x1849...7c8c)
- Market ID: 0x18493e771a4fd1cc17f01ec9f12cc3058bd4e30fda4affdd3e2c11ec6a557c8c (Market Hash)
- Request Timestamp: Thu, 16 Jan 2025 20:41:30 GMT

feat(market-map): Update market -- 8453_0_0x18493e771a4fd1cc17f01ec9f12cc3058bd4e30fda4affdd3e2c11ec6a557c8c

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x3eb74ecafe8378df5eab8a32c94aff5db08be90d29354f77ffd938d76bbdad2b.ts

feat(market-map): Update market -- 11155111_0_0x3eb74ecafe8378df5eab8a32c94aff5db08be90d29354f77ffd938d76bbdad2b -- Recipe (0x3eb7...ad2b)
- Market ID: 0x3eb74ecafe8378df5eab8a32c94aff5db08be90d29354f77ffd938d76bbdad2b (Market Hash)
- Request Timestamp: Fri, 17 Jan 2025 15:16:29 GMT

feat(market-map): Update market -- 11155111_0_0x3eb74ecafe8378df5eab8a32c94aff5db08be90d29354f77ffd938d76bbdad2b

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x497fee5d36f4b2bdd15fa75857c887b65504d79443d412764b79df89ada73053.ts

feat(market-map): Update market -- 11155111_0_0x497fee5d36f4b2bdd15fa75857c887b65504d79443d412764b79df89ada73053 -- Recipe (0x497f...3053)
- Market ID: 0x497fee5d36f4b2bdd15fa75857c887b65504d79443d412764b79df89ada73053 (Market Hash)
- Request Timestamp: Fri, 17 Jan 2025 16:46:41 GMT

feat(market-map): Update market -- 11155111_0_0x497fee5d36f4b2bdd15fa75857c887b65504d79443d412764b79df89ada73053

---

sdk/constants/token-map/1/definitions/1-0xb193b1a5345c6b629af578ebdea89b2c24953184.ts

Added Bedrock Diamond points campaign for Royco

Added Bedrock Diamond points

---

sdk/constants/market-map/146/definitions/146_0_0xdfd26983257f927830585a7da408d598fe3260bc0afd2501bf7988ee1eedf142.ts

feat(market-map): Update market -- 146_0_0xdfd26983257f927830585a7da408d598fe3260bc0afd2501bf7988ee1eedf142 -- Recipe (0xdfd2...f142)
- Market ID: 0xdfd26983257f927830585a7da408d598fe3260bc0afd2501bf7988ee1eedf142 (Market Hash)
- Request Timestamp: Sat, 18 Jan 2025 22:12:54 GMT

feat(market-map): Update market -- 146_0_0xdfd26983257f927830585a7da408d598fe3260bc0afd2501bf7988ee1eedf142

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xd4d6596bdc7cb7f8b214961f895c2d79d884f9c3dfcac62996c3f94c1641af0d.ts

feat(market-map): Update market -- 11155111_0_0xd4d6596bdc7cb7f8b214961f895c2d79d884f9c3dfcac62996c3f94c1641af0d -- Recipe (0xd4d6...af0d)
- Market ID: 0xd4d6596bdc7cb7f8b214961f895c2d79d884f9c3dfcac62996c3f94c1641af0d (Market Hash)
- Request Timestamp: Sun, 19 Jan 2025 18:36:18 GMT

feat(market-map): Update market -- 11155111_0_0xd4d6596bdc7cb7f8b214961f895c2d79d884f9c3dfcac62996c3f94c1641af0d

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xde1e8297324284e8c0cc58fdb6c235777e852d113154715d130e98b351d55cfd.ts

feat(market-map): Update market -- 11155111_0_0xde1e8297324284e8c0cc58fdb6c235777e852d113154715d130e98b351d55cfd -- Recipe (0xde1e...5cfd)
- Market ID: 0xde1e8297324284e8c0cc58fdb6c235777e852d113154715d130e98b351d55cfd (Market Hash)
- Request Timestamp: Sun, 19 Jan 2025 20:10:26 GMT

feat(market-map): Update market -- 11155111_0_0xde1e8297324284e8c0cc58fdb6c235777e852d113154715d130e98b351d55cfd

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x7980d728b4646c36dcf6a89af683bc46adb21b0cfdce180d7513c14e6a6d832a.ts

feat(market-map): Update market -- 11155111_0_0x7980d728b4646c36dcf6a89af683bc46adb21b0cfdce180d7513c14e6a6d832a -- Recipe (0x7980...832a)
- Market ID: 0x7980d728b4646c36dcf6a89af683bc46adb21b0cfdce180d7513c14e6a6d832a (Market Hash)
- Request Timestamp: Sun, 19 Jan 2025 20:40:16 GMT

feat(market-map): Update market -- 11155111_0_0x7980d728b4646c36dcf6a89af683bc46adb21b0cfdce180d7513c14e6a6d832a

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x2226f288fb81a54c5f1ebd244313374c0d49ebea0953e0e7ac23d949d64ecbc1.ts

feat(market-map): Update market -- 11155111_0_0x2226f288fb81a54c5f1ebd244313374c0d49ebea0953e0e7ac23d949d64ecbc1 -- Recipe (0x2226...cbc1)
- Market ID: 0x2226f288fb81a54c5f1ebd244313374c0d49ebea0953e0e7ac23d949d64ecbc1 (Market Hash)
- Request Timestamp: Sun, 19 Jan 2025 20:54:41 GMT

feat(market-map): Update market -- 11155111_0_0x2226f288fb81a54c5f1ebd244313374c0d49ebea0953e0e7ac23d949d64ecbc1

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x2782ea83adf8787682b4aba8a51225c53d6e9adceed465171343def79f5a50fb.ts

feat(market-map): Update market -- 11155111_0_0x2782ea83adf8787682b4aba8a51225c53d6e9adceed465171343def79f5a50fb -- Recipe (0x2782...50fb)
- Market ID: 0x2782ea83adf8787682b4aba8a51225c53d6e9adceed465171343def79f5a50fb (Market Hash)
- Request Timestamp: Sun, 19 Jan 2025 21:30:36 GMT

feat(market-map): Update market -- 11155111_0_0x2782ea83adf8787682b4aba8a51225c53d6e9adceed465171343def79f5a50fb

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xe1d17082d6a272889f9917e005e2dcf03df30e27fc1691e1fb3a5234957a351f.ts

feat(market-map): Update market -- 11155111_0_0xe1d17082d6a272889f9917e005e2dcf03df30e27fc1691e1fb3a5234957a351f -- Recipe (0xe1d1...351f)
- Market ID: 0xe1d17082d6a272889f9917e005e2dcf03df30e27fc1691e1fb3a5234957a351f (Market Hash)
- Request Timestamp: Mon, 20 Jan 2025 07:40:08 GMT

feat(market-map): Update market -- 11155111_0_0xe1d17082d6a272889f9917e005e2dcf03df30e27fc1691e1fb3a5234957a351f

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x559bbb2111b177460c08dd5ff7a3e21c31ee457ec2ab39cf5238caff9a9d21de.ts

feat(market-map): Update market -- 11155111_0_0x559bbb2111b177460c08dd5ff7a3e21c31ee457ec2ab39cf5238caff9a9d21de -- Recipe (0x559b...21de)
- Market ID: 0x559bbb2111b177460c08dd5ff7a3e21c31ee457ec2ab39cf5238caff9a9d21de (Market Hash)
- Request Timestamp: Mon, 20 Jan 2025 13:35:52 GMT

feat(market-map): Update market -- 11155111_0_0x559bbb2111b177460c08dd5ff7a3e21c31ee457ec2ab39cf5238caff9a9d21de

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x7bfe8d801c9701b632722199a9d0e2749a4e3bd67ca460263d5098a01a279102.ts

feat(market-map): Update market -- 11155111_0_0x7bfe8d801c9701b632722199a9d0e2749a4e3bd67ca460263d5098a01a279102 -- Recipe (0x7bfe...9102)
- Market ID: 0x7bfe8d801c9701b632722199a9d0e2749a4e3bd67ca460263d5098a01a279102 (Market Hash)
- Request Timestamp: Mon, 20 Jan 2025 13:38:41 GMT

feat(market-map): Update market -- 11155111_0_0x7bfe8d801c9701b632722199a9d0e2749a4e3bd67ca460263d5098a01a279102

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x14cee3153f792f3c8abf22577325e6a436ce11b8078cba5785303b85a3d5e921.ts

feat(market-map): Update market -- 11155111_0_0x14cee3153f792f3c8abf22577325e6a436ce11b8078cba5785303b85a3d5e921 -- Recipe (0x14ce...e921)
- Market ID: 0x14cee3153f792f3c8abf22577325e6a436ce11b8078cba5785303b85a3d5e921 (Market Hash)
- Request Timestamp: Mon, 20 Jan 2025 14:20:28 GMT

feat(market-map): Update market -- 11155111_0_0x14cee3153f792f3c8abf22577325e6a436ce11b8078cba5785303b85a3d5e921

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x6ac4c45256f32dc452ae012e01a8c1ac980dbca6581af2b99296278c607b0221.ts

feat(market-map): Update market -- 11155111_0_0x6ac4c45256f32dc452ae012e01a8c1ac980dbca6581af2b99296278c607b0221 -- Recipe (0x6ac4...0221)
- Market ID: 0x6ac4c45256f32dc452ae012e01a8c1ac980dbca6581af2b99296278c607b0221 (Market Hash)
- Request Timestamp: Mon, 20 Jan 2025 15:19:56 GMT

feat(market-map): Update market -- 11155111_0_0x6ac4c45256f32dc452ae012e01a8c1ac980dbca6581af2b99296278c607b0221

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xea2c3ea7a58bce6eabb5ed1d48e30a13054aed7b25b745e7efd94ad5b8336918.ts

feat(market-map): Update market -- 11155111_0_0xea2c3ea7a58bce6eabb5ed1d48e30a13054aed7b25b745e7efd94ad5b8336918 -- Recipe (0xea2c...6918)
- Market ID: 0xea2c3ea7a58bce6eabb5ed1d48e30a13054aed7b25b745e7efd94ad5b8336918 (Market Hash)
- Request Timestamp: Mon, 20 Jan 2025 15:38:40 GMT

feat(market-map): Update market -- 11155111_0_0xea2c3ea7a58bce6eabb5ed1d48e30a13054aed7b25b745e7efd94ad5b8336918

---

sdk/constants/market-map/98865/definitions/98865_0_0x6929a2d8631e2788c062713f4e9dcea8b55478bdf924e8b5c49cc0186837908b.ts

feat(market-map): Update market -- 98865_0_0x6929a2d8631e2788c062713f4e9dcea8b55478bdf924e8b5c49cc0186837908b -- Recipe (0x6929...908b)
- Market ID: 0x6929a2d8631e2788c062713f4e9dcea8b55478bdf924e8b5c49cc0186837908b (Market Hash)
- Request Timestamp: Mon, 20 Jan 2025 17:36:42 GMT

feat(market-map): Update market -- 98865_0_0x6929a2d8631e2788c062713f4e9dcea8b55478bdf924e8b5c49cc0186837908b

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x0f4e051a617200f3fb5643ed22dd107213c4816a149e8094b5bc4768db3188d2.ts

feat(market-map): Update market -- 11155111_0_0x0f4e051a617200f3fb5643ed22dd107213c4816a149e8094b5bc4768db3188d2 -- Recipe (0x0f4e...88d2)
- Market ID: 0x0f4e051a617200f3fb5643ed22dd107213c4816a149e8094b5bc4768db3188d2 (Market Hash)
- Request Timestamp: Tue, 21 Jan 2025 20:09:17 GMT

feat(market-map): Update market -- 11155111_0_0x0f4e051a617200f3fb5643ed22dd107213c4816a149e8094b5bc4768db3188d2

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x7593f77f5b2882dcc69ea94926e402a20338fc345b4e66616f86725dda608a32.ts

feat(market-map): Update market -- 11155111_0_0x7593f77f5b2882dcc69ea94926e402a20338fc345b4e66616f86725dda608a32 -- Recipe (0x7593...8a32)
- Market ID: 0x7593f77f5b2882dcc69ea94926e402a20338fc345b4e66616f86725dda608a32 (Market Hash)
- Request Timestamp: Tue, 21 Jan 2025 23:58:26 GMT

feat(market-map): Update market -- 11155111_0_0x7593f77f5b2882dcc69ea94926e402a20338fc345b4e66616f86725dda608a32

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x2ea4064346c43df2dc316fbb9e6ad99baf878c45683d63b88cbd3db9a8e2abdd.ts

feat(market-map): Update market -- 11155111_0_0x2ea4064346c43df2dc316fbb9e6ad99baf878c45683d63b88cbd3db9a8e2abdd -- Recipe (0x2ea4...abdd)
- Market ID: 0x2ea4064346c43df2dc316fbb9e6ad99baf878c45683d63b88cbd3db9a8e2abdd (Market Hash)
- Request Timestamp: Wed, 22 Jan 2025 03:47:54 GMT

feat(market-map): Update market -- 11155111_0_0x2ea4064346c43df2dc316fbb9e6ad99baf878c45683d63b88cbd3db9a8e2abdd

---

sdk/constants/market-map/42161/definitions/42161_0_0x68cd2f902fc32eaf649d081513dcd4a53523d355e2e5b54ad5b0a4d5683e9982.ts

feat(market-map): Update market -- 42161_0_0x68cd2f902fc32eaf649d081513dcd4a53523d355e2e5b54ad5b0a4d5683e9982 -- Recipe (0x68cd...9982)
- Market ID: 0x68cd2f902fc32eaf649d081513dcd4a53523d355e2e5b54ad5b0a4d5683e9982 (Market Hash)
- Request Timestamp: Wed, 22 Jan 2025 09:46:58 GMT

feat(market-map): Update market -- 42161_0_0x68cd2f902fc32eaf649d081513dcd4a53523d355e2e5b54ad5b0a4d5683e9982

---

sdk/constants/market-map/42161/definitions/42161_0_0x8ad5d3b1e7da39ce148c0e1809d4e3814f97a285e88098e1973e9df19eedd009.ts

feat(market-map): Update market -- 42161_0_0x8ad5d3b1e7da39ce148c0e1809d4e3814f97a285e88098e1973e9df19eedd009 -- Recipe (0x8ad5...d009)
- Market ID: 0x8ad5d3b1e7da39ce148c0e1809d4e3814f97a285e88098e1973e9df19eedd009 (Market Hash)
- Request Timestamp: Thu, 23 Jan 2025 08:00:37 GMT

feat(market-map): Update market -- 42161_0_0x8ad5d3b1e7da39ce148c0e1809d4e3814f97a285e88098e1973e9df19eedd009

---

sdk/constants/market-map/1/definitions/1_0_0x083bccbec09356920752d469ec8ab7ac81c965f2bc6400046485c2a49f7babdb.ts

feat(market-map): Update market -- 1_0_0x083bccbec09356920752d469ec8ab7ac81c965f2bc6400046485c2a49f7babdb -- Recipe (0x083b...abdb)
- Chain ID: 1
- Market ID: 0x083bccbec09356920752d469ec8ab7ac81c965f2bc6400046485c2a49f7babdb (Market Hash)
- Request Timestamp: Fri, 24 Jan 2025 18:47:50 GMT

feat(market-map): Update market -- 1_0_0x083bccbec09356920752d469ec8ab7ac81c965f2bc6400046485c2a49f7babdb

---

sdk/constants/market-map/1/definitions/1_0_0xac820b8b0fc50cefd64f86e873bee57a6f68af3d6bc8235d01a54306155b92ac.ts

feat(market-map): Update market -- 1_0_0xac820b8b0fc50cefd64f86e873bee57a6f68af3d6bc8235d01a54306155b92ac -- Recipe (0xac82...92ac)
- Chain ID: 1
- Market ID: 0xac820b8b0fc50cefd64f86e873bee57a6f68af3d6bc8235d01a54306155b92ac (Market Hash)
- Request Timestamp: Fri, 24 Jan 2025 19:03:04 GMT

feat(market-map): Update market -- 1_0_0xac820b8b0fc50cefd64f86e873bee57a6f68af3d6bc8235d01a54306155b92ac

---

sdk/constants/market-map/1/definitions/1_0_0xb4fc4c03bf90525171dc61d6f20fe7c57ca61460bef6cfe40c85beff27658788.ts

feat(market-map): Update market -- 1_0_0xb4fc4c03bf90525171dc61d6f20fe7c57ca61460bef6cfe40c85beff27658788 -- Recipe (0xb4fc...8788)
- Chain ID: 1
- Market ID: 0xb4fc4c03bf90525171dc61d6f20fe7c57ca61460bef6cfe40c85beff27658788 (Market Hash)
- Request Timestamp: Fri, 24 Jan 2025 19:12:15 GMT

feat(market-map): Update market -- 1_0_0xb4fc4c03bf90525171dc61d6f20fe7c57ca61460bef6cfe40c85beff27658788

---

sdk/constants/market-map/1/definitions/1_0_0x8fcf9397e1671fdb7140f752dcdb9932c14722a3ba5170e4b48b170434998d68.ts

feat(market-map): Update market -- 1_0_0x8fcf9397e1671fdb7140f752dcdb9932c14722a3ba5170e4b48b170434998d68 -- Recipe (0x8fcf...8d68)
- Chain ID: 1
- Market ID: 0x8fcf9397e1671fdb7140f752dcdb9932c14722a3ba5170e4b48b170434998d68 (Market Hash)
- Request Timestamp: Fri, 24 Jan 2025 19:55:33 GMT

feat(market-map): Update market -- 1_0_0x8fcf9397e1671fdb7140f752dcdb9932c14722a3ba5170e4b48b170434998d68

---

sdk/constants/market-map/1/definitions/1_0_0xf46e7d9028c1a7e65e8e540885e831709a4301a0bb7eff9db33ddf878de68233.ts

feat(market-map): Update market -- 1_0_0xf46e7d9028c1a7e65e8e540885e831709a4301a0bb7eff9db33ddf878de68233 -- Recipe (0xf46e...8233)
- Chain ID: 1
- Market ID: 0xf46e7d9028c1a7e65e8e540885e831709a4301a0bb7eff9db33ddf878de68233 (Market Hash)
- Request Timestamp: Fri, 24 Jan 2025 20:07:27 GMT

feat(market-map): Update market -- 1_0_0xf46e7d9028c1a7e65e8e540885e831709a4301a0bb7eff9db33ddf878de68233

---

sdk/constants/market-map/1/definitions/1_0_0x4b2d79fdc0599cbf0faef7b6214a8080b58d75181cc1413834ea203e00641d79.ts

feat(market-map): Update market -- 1_0_0x4b2d79fdc0599cbf0faef7b6214a8080b58d75181cc1413834ea203e00641d79 -- Recipe (0x4b2d...1d79)
- Chain ID: 1
- Market ID: 0x4b2d79fdc0599cbf0faef7b6214a8080b58d75181cc1413834ea203e00641d79 (Market Hash)
- Request Timestamp: Fri, 24 Jan 2025 20:11:06 GMT

feat(market-map): Update market -- 1_0_0x4b2d79fdc0599cbf0faef7b6214a8080b58d75181cc1413834ea203e00641d79

---

sdk/constants/market-map/1/definitions/1_0_0x3f8ac93179309b994c1a2e88a35945569da56a846604ce05a10e2f2737b5d828.ts

feat(market-map): Update market -- 1_0_0x3f8ac93179309b994c1a2e88a35945569da56a846604ce05a10e2f2737b5d828 -- Recipe (0x3f8a...d828)
- Chain ID: 1
- Market ID: 0x3f8ac93179309b994c1a2e88a35945569da56a846604ce05a10e2f2737b5d828 (Market Hash)
- Request Timestamp: Fri, 24 Jan 2025 20:30:54 GMT

feat(market-map): Update market -- 1_0_0x3f8ac93179309b994c1a2e88a35945569da56a846604ce05a10e2f2737b5d828

---

sdk/constants/market-map/1/definitions/1_0_0x122ba6b2144f61703984c234c4f5a86c216de6b19173436b3f712fa40646b874.ts

feat(market-map): Update market -- 1_0_0x122ba6b2144f61703984c234c4f5a86c216de6b19173436b3f712fa40646b874 -- Recipe (0x122b...b874)
- Chain ID: 1
- Market ID: 0x122ba6b2144f61703984c234c4f5a86c216de6b19173436b3f712fa40646b874 (Market Hash)
- Request Timestamp: Fri, 24 Jan 2025 20:37:41 GMT

feat(market-map): Update market -- 1_0_0x122ba6b2144f61703984c234c4f5a86c216de6b19173436b3f712fa40646b874

---

sdk/constants/market-map/1/definitions/1_0_0x71dcce99f806b846f142143905664c59fcb763b2516327e09a89cdd48020227f.ts

feat(market-map): Update market -- 1_0_0x71dcce99f806b846f142143905664c59fcb763b2516327e09a89cdd48020227f -- Recipe (0x71dc...227f)
- Chain ID: 1
- Market ID: 0x71dcce99f806b846f142143905664c59fcb763b2516327e09a89cdd48020227f (Market Hash)
- Request Timestamp: Fri, 24 Jan 2025 21:02:43 GMT

feat(market-map): Update market -- 1_0_0x71dcce99f806b846f142143905664c59fcb763b2516327e09a89cdd48020227f

---

sdk/constants/market-map/1/definitions/1_0_0xcf68c89be125a4feb11f2de983073cf792fb99674d82a87cb0ceba676f73a284.ts

feat(market-map): Update market -- 1_0_0xcf68c89be125a4feb11f2de983073cf792fb99674d82a87cb0ceba676f73a284 -- Recipe (0xcf68...a284)
- Chain ID: 1
- Market ID: 0xcf68c89be125a4feb11f2de983073cf792fb99674d82a87cb0ceba676f73a284 (Market Hash)
- Request Timestamp: Fri, 24 Jan 2025 21:07:54 GMT

feat(market-map): Update market -- 1_0_0xcf68c89be125a4feb11f2de983073cf792fb99674d82a87cb0ceba676f73a284

---

sdk/constants/market-map/1/definitions/1_0_0x38c48a8354fde176cbe2b9a07d4b8321267d7d16aac5afafe209563f0b209e5c.ts

feat(market-map): Update market -- 1_0_0x38c48a8354fde176cbe2b9a07d4b8321267d7d16aac5afafe209563f0b209e5c -- Recipe (0x38c4...9e5c)
- Chain ID: 1
- Market ID: 0x38c48a8354fde176cbe2b9a07d4b8321267d7d16aac5afafe209563f0b209e5c (Market Hash)
- Request Timestamp: Fri, 24 Jan 2025 21:17:06 GMT

feat(market-map): Update market -- 1_0_0x38c48a8354fde176cbe2b9a07d4b8321267d7d16aac5afafe209563f0b209e5c

---

sdk/constants/market-map/1/definitions/1_0_0xf2c982b6705e631c291a98a1931d21d9c83cec79938e079f453a1331f1d26289.ts

feat(market-map): Update market -- 1_0_0xf2c982b6705e631c291a98a1931d21d9c83cec79938e079f453a1331f1d26289 -- Recipe (0xf2c9...6289)
- Chain ID: 1
- Market ID: 0xf2c982b6705e631c291a98a1931d21d9c83cec79938e079f453a1331f1d26289 (Market Hash)
- Request Timestamp: Fri, 24 Jan 2025 21:46:16 GMT

feat(market-map): Update market -- 1_0_0xf2c982b6705e631c291a98a1931d21d9c83cec79938e079f453a1331f1d26289

---

sdk/constants/market-map/1/definitions/1_0_0x85e1528b3bc4fc13933683ee82d53461133ccf96ac13742e8b00de896f1a57e3.ts

feat(market-map): Update market -- 1_0_0x85e1528b3bc4fc13933683ee82d53461133ccf96ac13742e8b00de896f1a57e3 -- Recipe (0x85e1...57e3)
- Chain ID: 1
- Market ID: 0x85e1528b3bc4fc13933683ee82d53461133ccf96ac13742e8b00de896f1a57e3 (Market Hash)
- Request Timestamp: Fri, 24 Jan 2025 21:55:00 GMT

feat(market-map): Update market -- 1_0_0x85e1528b3bc4fc13933683ee82d53461133ccf96ac13742e8b00de896f1a57e3

---

sdk/constants/market-map/1/definitions/1_0_0xa0c53b5a7f98c8b3222dc9671553c1a3fa18188d893e57cdd7971ec803074b33.ts

feat(market-map): Update market -- 1_0_0xa0c53b5a7f98c8b3222dc9671553c1a3fa18188d893e57cdd7971ec803074b33 -- Recipe (0xa0c5...4b33)
- Chain ID: 1
- Market ID: 0xa0c53b5a7f98c8b3222dc9671553c1a3fa18188d893e57cdd7971ec803074b33 (Market Hash)
- Request Timestamp: Fri, 24 Jan 2025 22:03:41 GMT

feat(market-map): Update market -- 1_0_0xa0c53b5a7f98c8b3222dc9671553c1a3fa18188d893e57cdd7971ec803074b33

---

sdk/constants/market-map/1/definitions/1_0_0x8db4fb50a4b9573ff18c0652147969403592f4214e94c219bcfa5304a6b81b30.ts

feat(market-map): Update market -- 1_0_0x8db4fb50a4b9573ff18c0652147969403592f4214e94c219bcfa5304a6b81b30 -- Recipe (0x8db4...1b30)
- Chain ID: 1
- Market ID: 0x8db4fb50a4b9573ff18c0652147969403592f4214e94c219bcfa5304a6b81b30 (Market Hash)
- Request Timestamp: Fri, 24 Jan 2025 22:08:53 GMT

feat(market-map): Update market -- 1_0_0x8db4fb50a4b9573ff18c0652147969403592f4214e94c219bcfa5304a6b81b30

---

sdk/constants/market-map/1/definitions/1_0_0xcc7ed5de6703bef0cb9fc2fe989bc824471a56f141b108eabe0ec7700ca4427a.ts

feat(market-map): Update market -- 1_0_0xcc7ed5de6703bef0cb9fc2fe989bc824471a56f141b108eabe0ec7700ca4427a -- Recipe (0xcc7e...427a)
- Chain ID: 1
- Market ID: 0xcc7ed5de6703bef0cb9fc2fe989bc824471a56f141b108eabe0ec7700ca4427a (Market Hash)
- Request Timestamp: Fri, 24 Jan 2025 23:01:41 GMT

feat(market-map): Update market -- 1_0_0xcc7ed5de6703bef0cb9fc2fe989bc824471a56f141b108eabe0ec7700ca4427a

---

sdk/constants/market-map/1/definitions/1_0_0x3d6842f28ce2b26e8c9566c49885f761153bf87ecd364881e2d4e6f60342fd87.ts

feat(market-map): Update market -- 1_0_0x3d6842f28ce2b26e8c9566c49885f761153bf87ecd364881e2d4e6f60342fd87 -- Recipe (0x3d68...fd87)
- Chain ID: 1
- Market ID: 0x3d6842f28ce2b26e8c9566c49885f761153bf87ecd364881e2d4e6f60342fd87 (Market Hash)
- Request Timestamp: Fri, 24 Jan 2025 23:06:02 GMT

feat(market-map): Update market -- 1_0_0x3d6842f28ce2b26e8c9566c49885f761153bf87ecd364881e2d4e6f60342fd87

---

sdk/constants/market-map/1/definitions/1_0_0x567d727e1596cdc3db970abe62ee3c43b05ecaa745e55dd3e818a3d7dd69e62b.ts

feat(market-map): Update market -- 1_0_0x567d727e1596cdc3db970abe62ee3c43b05ecaa745e55dd3e818a3d7dd69e62b -- Recipe (0x567d...e62b)
- Chain ID: 1
- Market ID: 0x567d727e1596cdc3db970abe62ee3c43b05ecaa745e55dd3e818a3d7dd69e62b (Market Hash)
- Request Timestamp: Sat, 25 Jan 2025 22:05:24 GMT

feat(market-map): Update market -- 1_0_0x567d727e1596cdc3db970abe62ee3c43b05ecaa745e55dd3e818a3d7dd69e62b

---

sdk/constants/market-map/1/definitions/1_0_0x96d19933bdae6454c01b08acc7b5cbc0a847743f65b6d5b80e1ca0b08a95f3a6.ts

feat(market-map): Update market -- 1_0_0x96d19933bdae6454c01b08acc7b5cbc0a847743f65b6d5b80e1ca0b08a95f3a6 -- Recipe (0x96d1...f3a6)
- Chain ID: 1
- Market ID: 0x96d19933bdae6454c01b08acc7b5cbc0a847743f65b6d5b80e1ca0b08a95f3a6 (Market Hash)
- Request Timestamp: Sat, 25 Jan 2025 22:06:14 GMT

feat(market-map): Update market -- 1_0_0x96d19933bdae6454c01b08acc7b5cbc0a847743f65b6d5b80e1ca0b08a95f3a6

---

sdk/constants/market-map/1/definitions/1_0_0x431f01f338ff3ec6348f14ffd5702ace4cb33c2106aca184a4cacc4ebd406b34.ts

feat(market-map): Update market -- 1_0_0x431f01f338ff3ec6348f14ffd5702ace4cb33c2106aca184a4cacc4ebd406b34 -- Recipe (0x431f...6b34)
- Chain ID: 1
- Market ID: 0x431f01f338ff3ec6348f14ffd5702ace4cb33c2106aca184a4cacc4ebd406b34 (Market Hash)
- Request Timestamp: Sat, 25 Jan 2025 22:09:15 GMT

feat(market-map): Update market -- 1_0_0x431f01f338ff3ec6348f14ffd5702ace4cb33c2106aca184a4cacc4ebd406b34

---

sdk/constants/market-map/1/definitions/1_0_0xbf379151853f6a5c1509ce6708861c0178ee3c17917dabf996fc47cdf87a6d4a.ts

feat(market-map): Update market -- 1_0_0xbf379151853f6a5c1509ce6708861c0178ee3c17917dabf996fc47cdf87a6d4a -- Recipe (0xbf37...6d4a)
- Chain ID: 1
- Market ID: 0xbf379151853f6a5c1509ce6708861c0178ee3c17917dabf996fc47cdf87a6d4a (Market Hash)
- Request Timestamp: Sat, 25 Jan 2025 22:11:07 GMT

feat(market-map): Update market -- 1_0_0xbf379151853f6a5c1509ce6708861c0178ee3c17917dabf996fc47cdf87a6d4a

---

sdk/constants/market-map/1/definitions/1_0_0x7e6902266a4a1904cff69db91904323c29cf50e5a1e4046954c43d7446f03da0.ts

feat(market-map): Update market -- 1_0_0x7e6902266a4a1904cff69db91904323c29cf50e5a1e4046954c43d7446f03da0 -- Recipe (0x7e69...3da0)
- Chain ID: 1
- Market ID: 0x7e6902266a4a1904cff69db91904323c29cf50e5a1e4046954c43d7446f03da0 (Market Hash)
- Request Timestamp: Sat, 25 Jan 2025 22:15:15 GMT

feat(market-map): Update market -- 1_0_0x7e6902266a4a1904cff69db91904323c29cf50e5a1e4046954c43d7446f03da0

---

sdk/constants/market-map/1/definitions/1_0_0x2242fddcee8fab6c3f73730c7221e324893c72d9e2cc1d811f6f07df15338a50.ts

feat(market-map): Update market -- 1_0_0x2242fddcee8fab6c3f73730c7221e324893c72d9e2cc1d811f6f07df15338a50 -- Recipe (0x2242...8a50)
- Chain ID: 1
- Market ID: 0x2242fddcee8fab6c3f73730c7221e324893c72d9e2cc1d811f6f07df15338a50 (Market Hash)
- Request Timestamp: Sat, 25 Jan 2025 22:19:06 GMT

feat(market-map): Update market -- 1_0_0x2242fddcee8fab6c3f73730c7221e324893c72d9e2cc1d811f6f07df15338a50

---

sdk/constants/market-map/1/definitions/1_0_0xae7886c751ec92e1b87e8361b2a4c6ce745cab3ddcaf2f539c612a2dc4ed4e62.ts

feat(market-map): Update market -- 1_0_0xae7886c751ec92e1b87e8361b2a4c6ce745cab3ddcaf2f539c612a2dc4ed4e62 -- Recipe (0xae78...4e62)
- Chain ID: 1
- Market ID: 0xae7886c751ec92e1b87e8361b2a4c6ce745cab3ddcaf2f539c612a2dc4ed4e62 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 01:59:29 GMT

feat(market-map): Update market -- 1_0_0xae7886c751ec92e1b87e8361b2a4c6ce745cab3ddcaf2f539c612a2dc4ed4e62

---

sdk/constants/market-map/1/definitions/1_0_0x14028b015a5ed1e4340c16a8b6f582b49656dd20f2fc8c5af465de6a319c2504.ts

feat(market-map): Update market -- 1_0_0x14028b015a5ed1e4340c16a8b6f582b49656dd20f2fc8c5af465de6a319c2504 -- Recipe (0x1402...2504)
- Chain ID: 1
- Market ID: 0x14028b015a5ed1e4340c16a8b6f582b49656dd20f2fc8c5af465de6a319c2504 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 04:38:50 GMT

feat(market-map): Update market -- 1_0_0x14028b015a5ed1e4340c16a8b6f582b49656dd20f2fc8c5af465de6a319c2504

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xe2836d7a7ad2b658c2657ae50a38d9e9bed9e1f329e6878c3d2b9572d6603861.ts

feat(market-map): Update market -- 11155111_0_0xe2836d7a7ad2b658c2657ae50a38d9e9bed9e1f329e6878c3d2b9572d6603861 -- Recipe (0xe283...3861)
- Market ID: 0xe2836d7a7ad2b658c2657ae50a38d9e9bed9e1f329e6878c3d2b9572d6603861 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 07:22:31 GMT

feat(market-map): Update market -- 11155111_0_0xe2836d7a7ad2b658c2657ae50a38d9e9bed9e1f329e6878c3d2b9572d6603861

---

sdk/constants/market-map/1/definitions/1_0_0xde012cef3d9ccd8da585ba3b98bf89ab339607984fc001f2480ea672928f6284.ts

feat(market-map): Update market -- 1_0_0xde012cef3d9ccd8da585ba3b98bf89ab339607984fc001f2480ea672928f6284 -- Recipe (0xde01...6284)
- Chain ID: 1
- Market ID: 0xde012cef3d9ccd8da585ba3b98bf89ab339607984fc001f2480ea672928f6284 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 07:46:40 GMT

feat(market-map): Update market -- 1_0_0xde012cef3d9ccd8da585ba3b98bf89ab339607984fc001f2480ea672928f6284

---

sdk/constants/market-map/1/definitions/1_0_0x606d48942091b72a09337280c32d473e0a4f82729974357124ceed9ddbf6969f.ts

feat(market-map): Update market -- 1_0_0x606d48942091b72a09337280c32d473e0a4f82729974357124ceed9ddbf6969f -- Recipe (0x606d...969f)
- Chain ID: 1
- Market ID: 0x606d48942091b72a09337280c32d473e0a4f82729974357124ceed9ddbf6969f (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 07:49:54 GMT

feat(market-map): Update market -- 1_0_0x606d48942091b72a09337280c32d473e0a4f82729974357124ceed9ddbf6969f

---

sdk/constants/market-map/1/definitions/1_0_0x0dd68edb796a49667f96c8d7aed3a7375e3a7fb5151341401f3aff3d489d43c2.ts

feat(market-map): Update market -- 1_0_0x0dd68edb796a49667f96c8d7aed3a7375e3a7fb5151341401f3aff3d489d43c2 -- Recipe (0x0dd6...43c2)
- Chain ID: 1
- Market ID: 0x0dd68edb796a49667f96c8d7aed3a7375e3a7fb5151341401f3aff3d489d43c2 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 12:27:16 GMT

feat(market-map): Update market -- 1_0_0x0dd68edb796a49667f96c8d7aed3a7375e3a7fb5151341401f3aff3d489d43c2

---

sdk/constants/market-map/1/definitions/1_0_0x87b88dacbd04f88fe9ddfd3fe8347f3793611d001016069d467d786e4896993c.ts

feat(market-map): Update market -- 1_0_0x87b88dacbd04f88fe9ddfd3fe8347f3793611d001016069d467d786e4896993c -- Recipe (0x87b8...993c)
- Chain ID: 1
- Market ID: 0x87b88dacbd04f88fe9ddfd3fe8347f3793611d001016069d467d786e4896993c (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 13:56:09 GMT

feat(market-map): Update market -- 1_0_0x87b88dacbd04f88fe9ddfd3fe8347f3793611d001016069d467d786e4896993c

---

sdk/constants/market-map/1/definitions/1_0_0x8f60f2fe646532e7b33154567c6f31eea9f96060da97d6d26bae538bd303bbed.ts

feat(market-map): Update market -- 1_0_0x8f60f2fe646532e7b33154567c6f31eea9f96060da97d6d26bae538bd303bbed -- Recipe (0x8f60...bbed)
- Chain ID: 1
- Market ID: 0x8f60f2fe646532e7b33154567c6f31eea9f96060da97d6d26bae538bd303bbed (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 14:13:40 GMT

feat(market-map): Update market -- 1_0_0x8f60f2fe646532e7b33154567c6f31eea9f96060da97d6d26bae538bd303bbed

---

sdk/constants/market-map/1/definitions/1_0_0xaa449e0679bd82798c7896c6a031f2da55299e64c0b4bddd57ad440921c04628.ts

feat(market-map): Update market -- 1_0_0xaa449e0679bd82798c7896c6a031f2da55299e64c0b4bddd57ad440921c04628 -- Recipe (0xaa44...4628)
- Chain ID: 1
- Market ID: 0xaa449e0679bd82798c7896c6a031f2da55299e64c0b4bddd57ad440921c04628 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 14:31:43 GMT

feat(market-map): Update market -- 1_0_0xaa449e0679bd82798c7896c6a031f2da55299e64c0b4bddd57ad440921c04628

---

sdk/constants/market-map/1/definitions/1_0_0x17ffd16948c053cc184c005477548e559566879a0e2847e87ebd1111c602535c.ts

feat(market-map): Update market -- 1_0_0x17ffd16948c053cc184c005477548e559566879a0e2847e87ebd1111c602535c -- Recipe (0x17ff...535c)
- Chain ID: 1
- Market ID: 0x17ffd16948c053cc184c005477548e559566879a0e2847e87ebd1111c602535c (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 15:16:07 GMT

feat(market-map): Update market -- 1_0_0x17ffd16948c053cc184c005477548e559566879a0e2847e87ebd1111c602535c

---

sdk/constants/market-map/1/definitions/1_0_0x60b1db95ec90325949de6ca83ed584a00e17f3967c66ee975ac53c5e45969485.ts

feat(market-map): Update market -- 1_0_0x60b1db95ec90325949de6ca83ed584a00e17f3967c66ee975ac53c5e45969485 -- Recipe (0x60b1...9485)
- Chain ID: 1
- Market ID: 0x60b1db95ec90325949de6ca83ed584a00e17f3967c66ee975ac53c5e45969485 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 15:23:02 GMT

feat(market-map): Update market -- 1_0_0x60b1db95ec90325949de6ca83ed584a00e17f3967c66ee975ac53c5e45969485

---

sdk/constants/market-map/1/definitions/1_0_0xab37ea8895eed81c4aa76d5dba64441756904b15e78f6ffa5183b0fc1563c1c5.ts

feat(market-map): Update market -- 1_0_0xab37ea8895eed81c4aa76d5dba64441756904b15e78f6ffa5183b0fc1563c1c5 -- Recipe (0xab37...c1c5)
- Chain ID: 1
- Market ID: 0xab37ea8895eed81c4aa76d5dba64441756904b15e78f6ffa5183b0fc1563c1c5 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 15:28:05 GMT

feat(market-map): Update market -- 1_0_0xab37ea8895eed81c4aa76d5dba64441756904b15e78f6ffa5183b0fc1563c1c5

---

sdk/constants/market-map/1/definitions/1_0_0x027987432679079fbbc990691d14dabe7f7780f51df6a1a53e7bd875b1f9581a.ts

feat(market-map): Update market -- 1_0_0x027987432679079fbbc990691d14dabe7f7780f51df6a1a53e7bd875b1f9581a -- Recipe (0x0279...581a)
- Chain ID: 1
- Market ID: 0x027987432679079fbbc990691d14dabe7f7780f51df6a1a53e7bd875b1f9581a (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 15:31:15 GMT

feat(market-map): Update market -- 1_0_0x027987432679079fbbc990691d14dabe7f7780f51df6a1a53e7bd875b1f9581a

---

sdk/constants/market-map/1/definitions/1_0_0x72bec627884d7bdf538f174bedd551e9eccf3995adc880f40972e2bab87df3b9.ts

feat(market-map): Update market -- 1_0_0x72bec627884d7bdf538f174bedd551e9eccf3995adc880f40972e2bab87df3b9 -- Recipe (0x72be...f3b9)
- Chain ID: 1
- Market ID: 0x72bec627884d7bdf538f174bedd551e9eccf3995adc880f40972e2bab87df3b9 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 15:32:42 GMT

feat(market-map): Update market -- 1_0_0x72bec627884d7bdf538f174bedd551e9eccf3995adc880f40972e2bab87df3b9

---

sdk/constants/market-map/1/definitions/1_0_0xf8f745f188ddb10c16724faee95583521191c3c69e15490fa53c1136b73c17d7.ts

feat(market-map): Update market -- 1_0_0xf8f745f188ddb10c16724faee95583521191c3c69e15490fa53c1136b73c17d7 -- Recipe (0xf8f7...17d7)
- Chain ID: 1
- Market ID: 0xf8f745f188ddb10c16724faee95583521191c3c69e15490fa53c1136b73c17d7 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 15:36:21 GMT

feat(market-map): Update market -- 1_0_0xf8f745f188ddb10c16724faee95583521191c3c69e15490fa53c1136b73c17d7

---

sdk/constants/market-map/1/definitions/1_0_0x0964848864e96952ee2454ce58fc93b867f9b2d9a6b44216eec8b08726813d1b.ts

feat(market-map): Update market -- 1_0_0x0964848864e96952ee2454ce58fc93b867f9b2d9a6b44216eec8b08726813d1b -- Recipe (0x0964...3d1b)
- Chain ID: 1
- Market ID: 0x0964848864e96952ee2454ce58fc93b867f9b2d9a6b44216eec8b08726813d1b (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 15:43:12 GMT

feat(market-map): Update market -- 1_0_0x0964848864e96952ee2454ce58fc93b867f9b2d9a6b44216eec8b08726813d1b

---

sdk/constants/market-map/1/definitions/1_0_0xdd3f0e11d59726f2e63fc1b180abc94034dd3e0f4018b51371b73348d82b3769.ts

feat(market-map): Update market -- 1_0_0xdd3f0e11d59726f2e63fc1b180abc94034dd3e0f4018b51371b73348d82b3769 -- Recipe (0xdd3f...3769)
- Chain ID: 1
- Market ID: 0xdd3f0e11d59726f2e63fc1b180abc94034dd3e0f4018b51371b73348d82b3769 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 15:43:48 GMT

feat(market-map): Update market -- 1_0_0xdd3f0e11d59726f2e63fc1b180abc94034dd3e0f4018b51371b73348d82b3769

---

sdk/constants/market-map/1/definitions/1_0_0x2dcd8ec59fe12b4cb802f5a26445f9684635c52139560f169a7c4d67da186c18.ts

feat(market-map): Update market -- 1_0_0x2dcd8ec59fe12b4cb802f5a26445f9684635c52139560f169a7c4d67da186c18 -- Recipe (0x2dcd...6c18)
- Chain ID: 1
- Market ID: 0x2dcd8ec59fe12b4cb802f5a26445f9684635c52139560f169a7c4d67da186c18 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 15:45:24 GMT

feat(market-map): Update market -- 1_0_0x2dcd8ec59fe12b4cb802f5a26445f9684635c52139560f169a7c4d67da186c18

---

sdk/constants/market-map/1/definitions/1_0_0xad9ee12ea8b3dccf85934c2918bd4ad38ccf7bc8b43d5fcb6f298858aa4c9ca4.ts

feat(market-map): Update market -- 1_0_0xad9ee12ea8b3dccf85934c2918bd4ad38ccf7bc8b43d5fcb6f298858aa4c9ca4 -- Recipe (0xad9e...9ca4)
- Chain ID: 1
- Market ID: 0xad9ee12ea8b3dccf85934c2918bd4ad38ccf7bc8b43d5fcb6f298858aa4c9ca4 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 15:46:20 GMT

feat(market-map): Update market -- 1_0_0xad9ee12ea8b3dccf85934c2918bd4ad38ccf7bc8b43d5fcb6f298858aa4c9ca4

---

sdk/constants/market-map/1/definitions/1_0_0x7dadff589e53d9813969d0be6de99c033d140ec1d304e57a754797736656dcd5.ts

feat(market-map): Update market -- 1_0_0x7dadff589e53d9813969d0be6de99c033d140ec1d304e57a754797736656dcd5 -- Recipe (0x7dad...dcd5)
- Chain ID: 1
- Market ID: 0x7dadff589e53d9813969d0be6de99c033d140ec1d304e57a754797736656dcd5 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 15:46:40 GMT

feat(market-map): Update market -- 1_0_0x7dadff589e53d9813969d0be6de99c033d140ec1d304e57a754797736656dcd5

---

sdk/constants/market-map/1/definitions/1_0_0xb7b78119806fcb9bbc499131da16b52ce52cf4a1ceabfc59e4f2f6e6ef7046c0.ts

feat(market-map): Update market -- 1_0_0xb7b78119806fcb9bbc499131da16b52ce52cf4a1ceabfc59e4f2f6e6ef7046c0 -- Recipe (0xb7b7...46c0)
- Chain ID: 1
- Market ID: 0xb7b78119806fcb9bbc499131da16b52ce52cf4a1ceabfc59e4f2f6e6ef7046c0 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 15:52:21 GMT

feat(market-map): Update market -- 1_0_0xb7b78119806fcb9bbc499131da16b52ce52cf4a1ceabfc59e4f2f6e6ef7046c0

---

sdk/constants/market-map/1/definitions/1_0_0xde894ab596c084e65d0123ab6fa66f95b0571091cd8ec7efbeabe4942e7c40cd.ts

feat(market-map): Update market -- 1_0_0xde894ab596c084e65d0123ab6fa66f95b0571091cd8ec7efbeabe4942e7c40cd -- Recipe (0xde89...40cd)
- Chain ID: 1
- Market ID: 0xde894ab596c084e65d0123ab6fa66f95b0571091cd8ec7efbeabe4942e7c40cd (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:03:56 GMT

feat(market-map): Update market -- 1_0_0xde894ab596c084e65d0123ab6fa66f95b0571091cd8ec7efbeabe4942e7c40cd

---

sdk/constants/market-map/1/definitions/1_0_0x7ccce28638cbb503d17e8d9290a97f18731199655ccde282da7b464f21361b79.ts

feat(market-map): Update market -- 1_0_0x7ccce28638cbb503d17e8d9290a97f18731199655ccde282da7b464f21361b79 -- Recipe (0x7ccc...1b79)
- Chain ID: 1
- Market ID: 0x7ccce28638cbb503d17e8d9290a97f18731199655ccde282da7b464f21361b79 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:05:28 GMT

feat(market-map): Update market -- 1_0_0x7ccce28638cbb503d17e8d9290a97f18731199655ccde282da7b464f21361b79

---

sdk/constants/market-map/1/definitions/1_0_0x036d9e250c6dafef1dd361199181548f9990a00452abf5231cebe7a15f9e19bd.ts

feat(market-map): Update market -- 1_0_0x036d9e250c6dafef1dd361199181548f9990a00452abf5231cebe7a15f9e19bd -- Recipe (0x036d...19bd)
- Chain ID: 1
- Market ID: 0x036d9e250c6dafef1dd361199181548f9990a00452abf5231cebe7a15f9e19bd (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:08:28 GMT

feat(market-map): Update market -- 1_0_0x036d9e250c6dafef1dd361199181548f9990a00452abf5231cebe7a15f9e19bd

---

sdk/constants/market-map/1/definitions/1_0_0x28b337bd45eda5e2fc596bfe22320bef0af9da85d4c770d0fd03ddf72428c00a.ts

feat(market-map): Update market -- 1_0_0x28b337bd45eda5e2fc596bfe22320bef0af9da85d4c770d0fd03ddf72428c00a -- Recipe (0x28b3...c00a)
- Chain ID: 1
- Market ID: 0x28b337bd45eda5e2fc596bfe22320bef0af9da85d4c770d0fd03ddf72428c00a (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:16:53 GMT

feat(market-map): Update market -- 1_0_0x28b337bd45eda5e2fc596bfe22320bef0af9da85d4c770d0fd03ddf72428c00a

---

sdk/constants/market-map/1/definitions/1_0_0x8f94886f456b6c517c0f53ef7a8d0a66b1b18cab60f42f5d591a42b912eab415.ts

feat(market-map): Update market -- 1_0_0x8f94886f456b6c517c0f53ef7a8d0a66b1b18cab60f42f5d591a42b912eab415 -- Recipe (0x8f94...b415)
- Chain ID: 1
- Market ID: 0x8f94886f456b6c517c0f53ef7a8d0a66b1b18cab60f42f5d591a42b912eab415 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:18:40 GMT

feat(market-map): Update market -- 1_0_0x8f94886f456b6c517c0f53ef7a8d0a66b1b18cab60f42f5d591a42b912eab415

---

sdk/constants/market-map/1/definitions/1_0_0xfcc0c3703168bf5d4a25d5213f2a79ea00b0f2e4e9f48a0bdcbeb4c254775179.ts

feat(market-map): Update market -- 1_0_0xfcc0c3703168bf5d4a25d5213f2a79ea00b0f2e4e9f48a0bdcbeb4c254775179 -- Recipe (0xfcc0...5179)
- Chain ID: 1
- Market ID: 0xfcc0c3703168bf5d4a25d5213f2a79ea00b0f2e4e9f48a0bdcbeb4c254775179 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:20:30 GMT

feat(market-map): Update market -- 1_0_0xfcc0c3703168bf5d4a25d5213f2a79ea00b0f2e4e9f48a0bdcbeb4c254775179

---

sdk/constants/market-map/1/definitions/1_0_0xfe95d44ab171140b66fb5180e9de765578d9d2bfbdbb66307abb86ba05a59e93.ts

feat(market-map): Update market -- 1_0_0xfe95d44ab171140b66fb5180e9de765578d9d2bfbdbb66307abb86ba05a59e93 -- Recipe (0xfe95...9e93)
- Chain ID: 1
- Market ID: 0xfe95d44ab171140b66fb5180e9de765578d9d2bfbdbb66307abb86ba05a59e93 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:21:30 GMT

feat(market-map): Update market -- 1_0_0xfe95d44ab171140b66fb5180e9de765578d9d2bfbdbb66307abb86ba05a59e93

---

sdk/constants/market-map/1/definitions/1_0_0x88ee202388086447b8dc8403c5aa2cfbcdb52e749fd16af5c6a3c7bb614b17c9.ts

feat(market-map): Update market -- 1_0_0x88ee202388086447b8dc8403c5aa2cfbcdb52e749fd16af5c6a3c7bb614b17c9 -- Recipe (0x88ee...17c9)
- Chain ID: 1
- Market ID: 0x88ee202388086447b8dc8403c5aa2cfbcdb52e749fd16af5c6a3c7bb614b17c9 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:24:20 GMT

feat(market-map): Update market -- 1_0_0x88ee202388086447b8dc8403c5aa2cfbcdb52e749fd16af5c6a3c7bb614b17c9

---

sdk/constants/market-map/1/definitions/1_0_0xe92ebafbee7aa7a636ff62e04aa2ab9353f60ef72dcdcfdfcf48b67a7ad8ffc7.ts

feat(market-map): Update market -- 1_0_0xe92ebafbee7aa7a636ff62e04aa2ab9353f60ef72dcdcfdfcf48b67a7ad8ffc7 -- Recipe (0xe92e...ffc7)
- Chain ID: 1
- Market ID: 0xe92ebafbee7aa7a636ff62e04aa2ab9353f60ef72dcdcfdfcf48b67a7ad8ffc7 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:25:32 GMT

feat(market-map): Update market -- 1_0_0xe92ebafbee7aa7a636ff62e04aa2ab9353f60ef72dcdcfdfcf48b67a7ad8ffc7

---

sdk/constants/market-map/1/definitions/1_0_0x62bb6fb784e059f338340a9724b35ef2ef8fde5e65613e9fcaacd097d81dc67e.ts

feat(market-map): Update market -- 1_0_0x62bb6fb784e059f338340a9724b35ef2ef8fde5e65613e9fcaacd097d81dc67e -- Recipe (0x62bb...c67e)
- Chain ID: 1
- Market ID: 0x62bb6fb784e059f338340a9724b35ef2ef8fde5e65613e9fcaacd097d81dc67e (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:26:16 GMT

feat(market-map): Update market -- 1_0_0x62bb6fb784e059f338340a9724b35ef2ef8fde5e65613e9fcaacd097d81dc67e

---

sdk/constants/market-map/1/definitions/1_0_0xb9f307d83c78d09a134aac7713821aab8e1da2404b895db66f0975135dd5006e.ts

feat(market-map): Update market -- 1_0_0xb9f307d83c78d09a134aac7713821aab8e1da2404b895db66f0975135dd5006e -- Recipe (0xb9f3...006e)
- Chain ID: 1
- Market ID: 0xb9f307d83c78d09a134aac7713821aab8e1da2404b895db66f0975135dd5006e (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:26:29 GMT

feat(market-map): Update market -- 1_0_0xb9f307d83c78d09a134aac7713821aab8e1da2404b895db66f0975135dd5006e

---

sdk/constants/market-map/1/definitions/1_0_0x9778047cb8f3740866882a97a186dff42743bebb3ad8010edbf637ab0e37751f.ts

feat(market-map): Update market -- 1_0_0x9778047cb8f3740866882a97a186dff42743bebb3ad8010edbf637ab0e37751f -- Recipe (0x9778...751f)
- Chain ID: 1
- Market ID: 0x9778047cb8f3740866882a97a186dff42743bebb3ad8010edbf637ab0e37751f (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:28:02 GMT

feat(market-map): Update market -- 1_0_0x9778047cb8f3740866882a97a186dff42743bebb3ad8010edbf637ab0e37751f

---

sdk/constants/market-map/1/definitions/1_0_0x1e0a98a276ba873cfa427e247c7d0e438f604a54fcb36481063e1220af021faf.ts

feat(market-map): Update market -- 1_0_0x1e0a98a276ba873cfa427e247c7d0e438f604a54fcb36481063e1220af021faf -- Recipe (0x1e0a...1faf)
- Chain ID: 1
- Market ID: 0x1e0a98a276ba873cfa427e247c7d0e438f604a54fcb36481063e1220af021faf (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:29:39 GMT

feat(market-map): Update market -- 1_0_0x1e0a98a276ba873cfa427e247c7d0e438f604a54fcb36481063e1220af021faf

---

sdk/constants/market-map/1/definitions/1_0_0x7be233caf60ad2ec5ee794aa0f1962c94c32378a597b8739e5c0cb3a4958b79e.ts

feat(market-map): Update market -- 1_0_0x7be233caf60ad2ec5ee794aa0f1962c94c32378a597b8739e5c0cb3a4958b79e -- Recipe (0x7be2...b79e)
- Chain ID: 1
- Market ID: 0x7be233caf60ad2ec5ee794aa0f1962c94c32378a597b8739e5c0cb3a4958b79e (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:29:46 GMT

feat(market-map): Update market -- 1_0_0x7be233caf60ad2ec5ee794aa0f1962c94c32378a597b8739e5c0cb3a4958b79e

---

sdk/constants/market-map/1/definitions/1_0_0xcdd60ed30d20f9edc3fac624bb623db32103658b6da678949ef53df16139b488.ts

feat(market-map): Update market -- 1_0_0xcdd60ed30d20f9edc3fac624bb623db32103658b6da678949ef53df16139b488 -- Recipe (0xcdd6...b488)
- Chain ID: 1
- Market ID: 0xcdd60ed30d20f9edc3fac624bb623db32103658b6da678949ef53df16139b488 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:29:53 GMT

feat(market-map): Update market -- 1_0_0xcdd60ed30d20f9edc3fac624bb623db32103658b6da678949ef53df16139b488

---

sdk/constants/market-map/1/definitions/1_0_0x9c7bd5b59ebcb9a9e6787b9b174a98a69e27fa5a4fe98270b461a1b9b1b1aa3e.ts

feat(market-map): Update market -- 1_0_0x9c7bd5b59ebcb9a9e6787b9b174a98a69e27fa5a4fe98270b461a1b9b1b1aa3e -- Recipe (0x9c7b...aa3e)
- Chain ID: 1
- Market ID: 0x9c7bd5b59ebcb9a9e6787b9b174a98a69e27fa5a4fe98270b461a1b9b1b1aa3e (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:30:51 GMT

feat(market-map): Update market -- 1_0_0x9c7bd5b59ebcb9a9e6787b9b174a98a69e27fa5a4fe98270b461a1b9b1b1aa3e

---

sdk/constants/market-map/1/definitions/1_0_0xf8663b3c0f78b4efae0422b163e86e79afa1ce90778885d93d53c9d4f6d5c3d8.ts

feat(market-map): Update market -- 1_0_0xf8663b3c0f78b4efae0422b163e86e79afa1ce90778885d93d53c9d4f6d5c3d8 -- Recipe (0xf866...c3d8)
- Chain ID: 1
- Market ID: 0xf8663b3c0f78b4efae0422b163e86e79afa1ce90778885d93d53c9d4f6d5c3d8 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:31:06 GMT

feat(market-map): Update market -- 1_0_0xf8663b3c0f78b4efae0422b163e86e79afa1ce90778885d93d53c9d4f6d5c3d8

---

sdk/constants/market-map/1/definitions/1_0_0x568d2509ec17c27426a9d55e58673160c937aeaedc0a3fcc7c63c5b7df495ec7.ts

feat(market-map): Update market -- 1_0_0x568d2509ec17c27426a9d55e58673160c937aeaedc0a3fcc7c63c5b7df495ec7 -- Recipe (0x568d...5ec7)
- Chain ID: 1
- Market ID: 0x568d2509ec17c27426a9d55e58673160c937aeaedc0a3fcc7c63c5b7df495ec7 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:32:19 GMT

feat(market-map): Update market -- 1_0_0x568d2509ec17c27426a9d55e58673160c937aeaedc0a3fcc7c63c5b7df495ec7

---

sdk/constants/market-map/1/definitions/1_0_0x0a7565b14941c6a3dde083fb7a857e27e12c55fa34f709c37586ec585dbe7f3f.ts

feat(market-map): Update market -- 1_0_0x0a7565b14941c6a3dde083fb7a857e27e12c55fa34f709c37586ec585dbe7f3f -- Recipe (0x0a75...7f3f)
- Chain ID: 1
- Market ID: 0x0a7565b14941c6a3dde083fb7a857e27e12c55fa34f709c37586ec585dbe7f3f (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:32:33 GMT

feat(market-map): Update market -- 1_0_0x0a7565b14941c6a3dde083fb7a857e27e12c55fa34f709c37586ec585dbe7f3f

---

sdk/constants/market-map/1/definitions/1_0_0x2240151f263be555a4ef61476a5c111373e0efe8cd539f179b4b5850977e9d4e.ts

feat(market-map): Update market -- 1_0_0x2240151f263be555a4ef61476a5c111373e0efe8cd539f179b4b5850977e9d4e -- Recipe (0x2240...9d4e)
- Chain ID: 1
- Market ID: 0x2240151f263be555a4ef61476a5c111373e0efe8cd539f179b4b5850977e9d4e (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:32:46 GMT

feat(market-map): Update market -- 1_0_0x2240151f263be555a4ef61476a5c111373e0efe8cd539f179b4b5850977e9d4e

---

sdk/constants/market-map/1/definitions/1_0_0xa6905c68ad66ea9ce966aa1662e1417df08be333ab8ec04507e0f0301d3a78e9.ts

feat(market-map): Update market -- 1_0_0xa6905c68ad66ea9ce966aa1662e1417df08be333ab8ec04507e0f0301d3a78e9 -- Recipe (0xa690...78e9)
- Chain ID: 1
- Market ID: 0xa6905c68ad66ea9ce966aa1662e1417df08be333ab8ec04507e0f0301d3a78e9 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:33:18 GMT

feat(market-map): Update market -- 1_0_0xa6905c68ad66ea9ce966aa1662e1417df08be333ab8ec04507e0f0301d3a78e9

---

sdk/constants/market-map/1/definitions/1_0_0xc182b0267a6ca015c2d2a144ca19e1f6b36479675754914002e0613320ed8d9a.ts

feat(market-map): Update market -- 1_0_0xc182b0267a6ca015c2d2a144ca19e1f6b36479675754914002e0613320ed8d9a -- Recipe (0xc182...8d9a)
- Chain ID: 1
- Market ID: 0xc182b0267a6ca015c2d2a144ca19e1f6b36479675754914002e0613320ed8d9a (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:33:19 GMT

feat(market-map): Update market -- 1_0_0xc182b0267a6ca015c2d2a144ca19e1f6b36479675754914002e0613320ed8d9a

---

sdk/constants/market-map/1/definitions/1_0_0x4fa4a76aa8b93ccdddba0c20c336056803b7410fb375c9c9541e9c54fbfb2f9a.ts

feat(market-map): Update market -- 1_0_0x4fa4a76aa8b93ccdddba0c20c336056803b7410fb375c9c9541e9c54fbfb2f9a -- Recipe (0x4fa4...2f9a)
- Chain ID: 1
- Market ID: 0x4fa4a76aa8b93ccdddba0c20c336056803b7410fb375c9c9541e9c54fbfb2f9a (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:34:29 GMT

feat(market-map): Update market -- 1_0_0x4fa4a76aa8b93ccdddba0c20c336056803b7410fb375c9c9541e9c54fbfb2f9a

---

sdk/constants/market-map/1/definitions/1_0_0x897eec875e51d6c8b5339d6a9984a00acb0aa86f9d4ab4eddbb4a791bb0a88e9.ts

feat(market-map): Update market -- 1_0_0x897eec875e51d6c8b5339d6a9984a00acb0aa86f9d4ab4eddbb4a791bb0a88e9 -- Recipe (0x897e...88e9)
- Chain ID: 1
- Market ID: 0x897eec875e51d6c8b5339d6a9984a00acb0aa86f9d4ab4eddbb4a791bb0a88e9 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:35:30 GMT

feat(market-map): Update market -- 1_0_0x897eec875e51d6c8b5339d6a9984a00acb0aa86f9d4ab4eddbb4a791bb0a88e9

---

sdk/constants/market-map/1/definitions/1_0_0x45a3a982031a8fe1b35f53c6db51bd1dbcb588c56abcaf1ca83ebc6fcf5cc4ef.ts

feat(market-map): Update market -- 1_0_0x45a3a982031a8fe1b35f53c6db51bd1dbcb588c56abcaf1ca83ebc6fcf5cc4ef -- Recipe (0x45a3...c4ef)
- Chain ID: 1
- Market ID: 0x45a3a982031a8fe1b35f53c6db51bd1dbcb588c56abcaf1ca83ebc6fcf5cc4ef (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:35:37 GMT

feat(market-map): Update market -- 1_0_0x45a3a982031a8fe1b35f53c6db51bd1dbcb588c56abcaf1ca83ebc6fcf5cc4ef

---

sdk/constants/market-map/1/definitions/1_0_0x84790e638ddd7a59e64b8c239e96e29c2c6c155a9882a0c834b9ced016b7c999.ts

feat(market-map): Update market -- 1_0_0x84790e638ddd7a59e64b8c239e96e29c2c6c155a9882a0c834b9ced016b7c999 -- Recipe (0x8479...c999)
- Chain ID: 1
- Market ID: 0x84790e638ddd7a59e64b8c239e96e29c2c6c155a9882a0c834b9ced016b7c999 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:39:05 GMT

feat(market-map): Update market -- 1_0_0x84790e638ddd7a59e64b8c239e96e29c2c6c155a9882a0c834b9ced016b7c999

---

sdk/constants/market-map/1/definitions/1_0_0xfef8ead03d79cf7cbe6f73c8d1136f8c84f6cf6ed9bc208719e7fcee807cb336.ts

feat(market-map): Update market -- 1_0_0xfef8ead03d79cf7cbe6f73c8d1136f8c84f6cf6ed9bc208719e7fcee807cb336 -- Recipe (0xfef8...b336)
- Chain ID: 1
- Market ID: 0xfef8ead03d79cf7cbe6f73c8d1136f8c84f6cf6ed9bc208719e7fcee807cb336 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:40:45 GMT

feat(market-map): Update market -- 1_0_0xfef8ead03d79cf7cbe6f73c8d1136f8c84f6cf6ed9bc208719e7fcee807cb336

---

sdk/constants/market-map/1/definitions/1_0_0xfa4917a871f9cf06d3d00be6678993888b3aac41c3da21edf32c3c9cf3978d70.ts

feat(market-map): Update market -- 1_0_0xfa4917a871f9cf06d3d00be6678993888b3aac41c3da21edf32c3c9cf3978d70 -- Recipe (0xfa49...8d70)
- Chain ID: 1
- Market ID: 0xfa4917a871f9cf06d3d00be6678993888b3aac41c3da21edf32c3c9cf3978d70 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:40:45 GMT

feat(market-map): Update market -- 1_0_0xfa4917a871f9cf06d3d00be6678993888b3aac41c3da21edf32c3c9cf3978d70

---

sdk/constants/market-map/1/definitions/1_0_0x6b3dfac03cea102e59d2d5711088f3001782e07239dcc90f274dd9762220c49a.ts

feat(market-map): Update market -- 1_0_0x6b3dfac03cea102e59d2d5711088f3001782e07239dcc90f274dd9762220c49a -- Recipe (0x6b3d...c49a)
- Chain ID: 1
- Market ID: 0x6b3dfac03cea102e59d2d5711088f3001782e07239dcc90f274dd9762220c49a (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:41:39 GMT

feat(market-map): Update market -- 1_0_0x6b3dfac03cea102e59d2d5711088f3001782e07239dcc90f274dd9762220c49a

---

sdk/constants/market-map/1/definitions/1_0_0xd77d3e3e075394a6c94a8c83dab114bb7266b96c5234e4a98476f41339029c30.ts

feat(market-map): Update market -- 1_0_0xd77d3e3e075394a6c94a8c83dab114bb7266b96c5234e4a98476f41339029c30 -- Recipe (0xd77d...9c30)
- Chain ID: 1
- Market ID: 0xd77d3e3e075394a6c94a8c83dab114bb7266b96c5234e4a98476f41339029c30 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:43:06 GMT

feat(market-map): Update market -- 1_0_0xd77d3e3e075394a6c94a8c83dab114bb7266b96c5234e4a98476f41339029c30

---

sdk/constants/market-map/1/definitions/1_0_0xd70673b98af7096f575717d70fbf2fa935dd719926b55c0e011480678cdac563.ts

feat(market-map): Update market -- 1_0_0xd70673b98af7096f575717d70fbf2fa935dd719926b55c0e011480678cdac563 -- Recipe (0xd706...c563)
- Chain ID: 1
- Market ID: 0xd70673b98af7096f575717d70fbf2fa935dd719926b55c0e011480678cdac563 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:48:40 GMT

feat(market-map): Update market -- 1_0_0xd70673b98af7096f575717d70fbf2fa935dd719926b55c0e011480678cdac563

---

sdk/constants/market-map/1/definitions/1_0_0xcdb30c06ea11f3f5408bce5eefdb392dfe0008ef81af3a486bcfed891f9cc112.ts

feat(market-map): Update market -- 1_0_0xcdb30c06ea11f3f5408bce5eefdb392dfe0008ef81af3a486bcfed891f9cc112 -- Recipe (0xcdb3...c112)
- Chain ID: 1
- Market ID: 0xcdb30c06ea11f3f5408bce5eefdb392dfe0008ef81af3a486bcfed891f9cc112 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:54:40 GMT

feat(market-map): Update market -- 1_0_0xcdb30c06ea11f3f5408bce5eefdb392dfe0008ef81af3a486bcfed891f9cc112

---

sdk/constants/market-map/1/definitions/1_0_0xa588ad19850cf2a111c3c727033da8e557abc94de70fce2d2b2f2f78140f15e5.ts

feat(market-map): Update market -- 1_0_0xa588ad19850cf2a111c3c727033da8e557abc94de70fce2d2b2f2f78140f15e5 -- Recipe (0xa588...15e5)
- Chain ID: 1
- Market ID: 0xa588ad19850cf2a111c3c727033da8e557abc94de70fce2d2b2f2f78140f15e5 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:57:05 GMT

feat(market-map): Update market -- 1_0_0xa588ad19850cf2a111c3c727033da8e557abc94de70fce2d2b2f2f78140f15e5

---

sdk/constants/market-map/1/definitions/1_0_0x870b2827e7965bce20f621888fb882f1d7e8803b45f556c41330c93612042582.ts

feat(market-map): Update market -- 1_0_0x870b2827e7965bce20f621888fb882f1d7e8803b45f556c41330c93612042582 -- Recipe (0x870b...2582)
- Chain ID: 1
- Market ID: 0x870b2827e7965bce20f621888fb882f1d7e8803b45f556c41330c93612042582 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:58:30 GMT

feat(market-map): Update market -- 1_0_0x870b2827e7965bce20f621888fb882f1d7e8803b45f556c41330c93612042582

---

sdk/constants/market-map/1/definitions/1_0_0xb32d047eb63b5c2af537c2e4df6a09c40a50b75aefd83a928600241a4666b087.ts

feat(market-map): Update market -- 1_0_0xb32d047eb63b5c2af537c2e4df6a09c40a50b75aefd83a928600241a4666b087 -- Recipe (0xb32d...b087)
- Chain ID: 1
- Market ID: 0xb32d047eb63b5c2af537c2e4df6a09c40a50b75aefd83a928600241a4666b087 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 16:58:54 GMT

feat(market-map): Update market -- 1_0_0xb32d047eb63b5c2af537c2e4df6a09c40a50b75aefd83a928600241a4666b087

---

sdk/constants/market-map/1/definitions/1_0_0x79e0436d7a8563f4beeb66ac9cfd3c40e43ed3b1fa07c57ac91e301da0469c4c.ts

feat(market-map): Update market -- 1_0_0x79e0436d7a8563f4beeb66ac9cfd3c40e43ed3b1fa07c57ac91e301da0469c4c -- Recipe (0x79e0...9c4c)
- Chain ID: 1
- Market ID: 0x79e0436d7a8563f4beeb66ac9cfd3c40e43ed3b1fa07c57ac91e301da0469c4c (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:02:32 GMT

feat(market-map): Update market -- 1_0_0x79e0436d7a8563f4beeb66ac9cfd3c40e43ed3b1fa07c57ac91e301da0469c4c

---

sdk/constants/market-map/1/definitions/1_0_0xab77a72ca3114da7dfd830033540da34e9045ed96415654893918931f7537bf0.ts

feat(market-map): Update market -- 1_0_0xab77a72ca3114da7dfd830033540da34e9045ed96415654893918931f7537bf0 -- Recipe (0xab77...7bf0)
- Chain ID: 1
- Market ID: 0xab77a72ca3114da7dfd830033540da34e9045ed96415654893918931f7537bf0 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:05:52 GMT

feat(market-map): Update market -- 1_0_0xab77a72ca3114da7dfd830033540da34e9045ed96415654893918931f7537bf0

---

sdk/constants/market-map/1/definitions/1_0_0x3ef317447bd10825f0a053565f8474a460cfb22cda414ea30b671e304f0691b6.ts

feat(market-map): Update market -- 1_0_0x3ef317447bd10825f0a053565f8474a460cfb22cda414ea30b671e304f0691b6 -- Recipe (0x3ef3...91b6)
- Chain ID: 1
- Market ID: 0x3ef317447bd10825f0a053565f8474a460cfb22cda414ea30b671e304f0691b6 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:11:30 GMT

feat(market-map): Update market -- 1_0_0x3ef317447bd10825f0a053565f8474a460cfb22cda414ea30b671e304f0691b6

---

sdk/constants/market-map/1/definitions/1_0_0x568f3bb6ba4c6afe37899fda35bc315ae8167274685ea295e03cf20d471afd8b.ts

feat(market-map): Update market -- 1_0_0x568f3bb6ba4c6afe37899fda35bc315ae8167274685ea295e03cf20d471afd8b -- Recipe (0x568f...fd8b)
- Chain ID: 1
- Market ID: 0x568f3bb6ba4c6afe37899fda35bc315ae8167274685ea295e03cf20d471afd8b (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:14:39 GMT

feat(market-map): Update market -- 1_0_0x568f3bb6ba4c6afe37899fda35bc315ae8167274685ea295e03cf20d471afd8b

---

sdk/constants/market-map/1/definitions/1_0_0x289dc2a22ebb4ef7404de9293b6718d9f81f0843e1af4cf9a9c51d2e757348d6.ts

feat(market-map): Update market -- 1_0_0x289dc2a22ebb4ef7404de9293b6718d9f81f0843e1af4cf9a9c51d2e757348d6 -- Recipe (0x289d...48d6)
- Chain ID: 1
- Market ID: 0x289dc2a22ebb4ef7404de9293b6718d9f81f0843e1af4cf9a9c51d2e757348d6 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:17:19 GMT

feat(market-map): Update market -- 1_0_0x289dc2a22ebb4ef7404de9293b6718d9f81f0843e1af4cf9a9c51d2e757348d6

---

sdk/constants/market-map/1/definitions/1_0_0x092c0c4d8d124fc29364e8cd8417198c4bbe335e3f6c4b1f79215a3457b4831a.ts

feat(market-map): Update market -- 1_0_0x092c0c4d8d124fc29364e8cd8417198c4bbe335e3f6c4b1f79215a3457b4831a -- Recipe (0x092c...831a)
- Chain ID: 1
- Market ID: 0x092c0c4d8d124fc29364e8cd8417198c4bbe335e3f6c4b1f79215a3457b4831a (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:20:26 GMT

feat(market-map): Update market -- 1_0_0x092c0c4d8d124fc29364e8cd8417198c4bbe335e3f6c4b1f79215a3457b4831a

---

sdk/constants/market-map/1/definitions/1_0_0x42a09eccabf1080c40a24522e9e8adbee5a0ad907188c9b6e50ba26ba332eac3.ts

feat(market-map): Update market -- 1_0_0x42a09eccabf1080c40a24522e9e8adbee5a0ad907188c9b6e50ba26ba332eac3 -- Recipe (0x42a0...eac3)
- Chain ID: 1
- Market ID: 0x42a09eccabf1080c40a24522e9e8adbee5a0ad907188c9b6e50ba26ba332eac3 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:21:05 GMT

feat(market-map): Update market -- 1_0_0x42a09eccabf1080c40a24522e9e8adbee5a0ad907188c9b6e50ba26ba332eac3

---

sdk/constants/market-map/1/definitions/1_0_0xd10bdc88272e0958baa62a4ae2bfce1d8feed639a93e03c0aa5cec7adfbdf2c3.ts

feat(market-map): Update market -- 1_0_0xd10bdc88272e0958baa62a4ae2bfce1d8feed639a93e03c0aa5cec7adfbdf2c3 -- Recipe (0xd10b...f2c3)
- Chain ID: 1
- Market ID: 0xd10bdc88272e0958baa62a4ae2bfce1d8feed639a93e03c0aa5cec7adfbdf2c3 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:22:21 GMT

feat(market-map): Update market -- 1_0_0xd10bdc88272e0958baa62a4ae2bfce1d8feed639a93e03c0aa5cec7adfbdf2c3

---

sdk/constants/market-map/1/definitions/1_0_0x55241e7b57b44ee68d875a1f0618c31f9ab82c46e6eaf2d5acb7605e23cd866b.ts

feat(market-map): Update market -- 1_0_0x55241e7b57b44ee68d875a1f0618c31f9ab82c46e6eaf2d5acb7605e23cd866b -- Recipe (0x5524...866b)
- Chain ID: 1
- Market ID: 0x55241e7b57b44ee68d875a1f0618c31f9ab82c46e6eaf2d5acb7605e23cd866b (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:24:26 GMT

feat(market-map): Update market -- 1_0_0x55241e7b57b44ee68d875a1f0618c31f9ab82c46e6eaf2d5acb7605e23cd866b

---

sdk/constants/market-map/1/definitions/1_0_0x9a117f13c7d5d2b4b18e444f72e6e77c010a1fd90cf21135be75669d66ad9428.ts

feat(market-map): Update market -- 1_0_0x9a117f13c7d5d2b4b18e444f72e6e77c010a1fd90cf21135be75669d66ad9428 -- Recipe (0x9a11...9428)
- Chain ID: 1
- Market ID: 0x9a117f13c7d5d2b4b18e444f72e6e77c010a1fd90cf21135be75669d66ad9428 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:28:05 GMT

feat(market-map): Update market -- 1_0_0x9a117f13c7d5d2b4b18e444f72e6e77c010a1fd90cf21135be75669d66ad9428

---

sdk/constants/market-map/1/definitions/1_0_0xb1d5ccc4388fe639f8d949061bc2de95ecb1efb11c5ceb93bdb71caab58c8aa3.ts

feat(market-map): Update market -- 1_0_0xb1d5ccc4388fe639f8d949061bc2de95ecb1efb11c5ceb93bdb71caab58c8aa3 -- Recipe (0xb1d5...8aa3)
- Chain ID: 1
- Market ID: 0xb1d5ccc4388fe639f8d949061bc2de95ecb1efb11c5ceb93bdb71caab58c8aa3 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:28:40 GMT

feat(market-map): Update market -- 1_0_0xb1d5ccc4388fe639f8d949061bc2de95ecb1efb11c5ceb93bdb71caab58c8aa3

---

sdk/constants/market-map/1/definitions/1_0_0x8e73cadb9f3eb2d3531a125dd2f0d746feb71d61aef585e130421eba58f00f4a.ts

feat(market-map): Update market -- 1_0_0x8e73cadb9f3eb2d3531a125dd2f0d746feb71d61aef585e130421eba58f00f4a -- Recipe (0x8e73...0f4a)
- Chain ID: 1
- Market ID: 0x8e73cadb9f3eb2d3531a125dd2f0d746feb71d61aef585e130421eba58f00f4a (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:29:53 GMT

feat(market-map): Update market -- 1_0_0x8e73cadb9f3eb2d3531a125dd2f0d746feb71d61aef585e130421eba58f00f4a

---

sdk/constants/market-map/1/definitions/1_0_0x2a3a73ba927ec6bbf0e2e12e21a32e274a295389ce9d6ae2b32435d12c597c2c.ts

feat(market-map): Update market -- 1_0_0x2a3a73ba927ec6bbf0e2e12e21a32e274a295389ce9d6ae2b32435d12c597c2c -- Recipe (0x2a3a...7c2c)
- Chain ID: 1
- Market ID: 0x2a3a73ba927ec6bbf0e2e12e21a32e274a295389ce9d6ae2b32435d12c597c2c (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:31:17 GMT

feat(market-map): Update market -- 1_0_0x2a3a73ba927ec6bbf0e2e12e21a32e274a295389ce9d6ae2b32435d12c597c2c

---

sdk/constants/market-map/1/definitions/1_0_0xff917303af9337534eece4b88948d609980b66ca0b41875da782aec4858cade5.ts

feat(market-map): Update market -- 1_0_0xff917303af9337534eece4b88948d609980b66ca0b41875da782aec4858cade5 -- Recipe (0xff91...ade5)
- Chain ID: 1
- Market ID: 0xff917303af9337534eece4b88948d609980b66ca0b41875da782aec4858cade5 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:33:56 GMT

feat(market-map): Update market -- 1_0_0xff917303af9337534eece4b88948d609980b66ca0b41875da782aec4858cade5

---

sdk/constants/market-map/1/definitions/1_0_0xb27f671bc0dd8773a25136253acd72150dd59e50e44dc8439e9dc5c84c2b19f6.ts

feat(market-map): Update market -- 1_0_0xb27f671bc0dd8773a25136253acd72150dd59e50e44dc8439e9dc5c84c2b19f6 -- Recipe (0xb27f...19f6)
- Chain ID: 1
- Market ID: 0xb27f671bc0dd8773a25136253acd72150dd59e50e44dc8439e9dc5c84c2b19f6 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:34:51 GMT

feat(market-map): Update market -- 1_0_0xb27f671bc0dd8773a25136253acd72150dd59e50e44dc8439e9dc5c84c2b19f6

---

sdk/constants/market-map/1/definitions/1_0_0x258ac521d801d5112a484ad1b82e6fd2efc24aba29e5cd3d56db83f4a173dc90.ts

feat(market-map): Update market -- 1_0_0x258ac521d801d5112a484ad1b82e6fd2efc24aba29e5cd3d56db83f4a173dc90 -- Recipe (0x258a...dc90)
- Chain ID: 1
- Market ID: 0x258ac521d801d5112a484ad1b82e6fd2efc24aba29e5cd3d56db83f4a173dc90 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:37:29 GMT

feat(market-map): Update market -- 1_0_0x258ac521d801d5112a484ad1b82e6fd2efc24aba29e5cd3d56db83f4a173dc90

---

sdk/constants/market-map/1/definitions/1_0_0x5bac1cacdd36b3d95a7f9880a264f8481ab56d3d1a53993de084c6fa5febcc15.ts

feat(market-map): Update market -- 1_0_0x5bac1cacdd36b3d95a7f9880a264f8481ab56d3d1a53993de084c6fa5febcc15 -- Recipe (0x5bac...cc15)
- Chain ID: 1
- Market ID: 0x5bac1cacdd36b3d95a7f9880a264f8481ab56d3d1a53993de084c6fa5febcc15 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:40:28 GMT

feat(market-map): Update market -- 1_0_0x5bac1cacdd36b3d95a7f9880a264f8481ab56d3d1a53993de084c6fa5febcc15

---

sdk/constants/market-map/1/definitions/1_0_0x0194c329e2b9712802c37d3f17502bcefce2e128933f24f4fe847dfc7e5e8965.ts

feat(market-map): Update market -- 1_0_0x0194c329e2b9712802c37d3f17502bcefce2e128933f24f4fe847dfc7e5e8965 -- Recipe (0x0194...8965)
- Chain ID: 1
- Market ID: 0x0194c329e2b9712802c37d3f17502bcefce2e128933f24f4fe847dfc7e5e8965 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:43:50 GMT

feat(market-map): Update market -- 1_0_0x0194c329e2b9712802c37d3f17502bcefce2e128933f24f4fe847dfc7e5e8965

---

sdk/constants/market-map/1/definitions/1_0_0x6306bfce6bff30ec4efcea193253c43e057f1474007d0d2a5a0c2938bd6a9b81.ts

feat(market-map): Update market -- 1_0_0x6306bfce6bff30ec4efcea193253c43e057f1474007d0d2a5a0c2938bd6a9b81 -- Recipe (0x6306...9b81)
- Chain ID: 1
- Market ID: 0x6306bfce6bff30ec4efcea193253c43e057f1474007d0d2a5a0c2938bd6a9b81 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:47:31 GMT

feat(market-map): Update market -- 1_0_0x6306bfce6bff30ec4efcea193253c43e057f1474007d0d2a5a0c2938bd6a9b81

---

sdk/constants/market-map/1/definitions/1_0_0xc6887dddd833a3d585c7941cd31b0f8ff3ec5903d49cd5e7ac450b46532d3e79.ts

feat(market-map): Update market -- 1_0_0xc6887dddd833a3d585c7941cd31b0f8ff3ec5903d49cd5e7ac450b46532d3e79 -- Recipe (0xc688...3e79)
- Chain ID: 1
- Market ID: 0xc6887dddd833a3d585c7941cd31b0f8ff3ec5903d49cd5e7ac450b46532d3e79 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:48:59 GMT

feat(market-map): Update market -- 1_0_0xc6887dddd833a3d585c7941cd31b0f8ff3ec5903d49cd5e7ac450b46532d3e79

---

sdk/constants/market-map/1/definitions/1_0_0x1997c604de34a71974228bca4a66f601427c48960b6e59ff7ebc8e34f43f3ecf.ts

feat(market-map): Update market -- 1_0_0x1997c604de34a71974228bca4a66f601427c48960b6e59ff7ebc8e34f43f3ecf -- Recipe (0x1997...3ecf)
- Chain ID: 1
- Market ID: 0x1997c604de34a71974228bca4a66f601427c48960b6e59ff7ebc8e34f43f3ecf (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:50:28 GMT

feat(market-map): Update market -- 1_0_0x1997c604de34a71974228bca4a66f601427c48960b6e59ff7ebc8e34f43f3ecf

---

sdk/constants/market-map/1/definitions/1_0_0x86a5077c6a9190cde78ec75b8888c46ed0a3d1289054127a955a2af544633cf3.ts

feat(market-map): Update market -- 1_0_0x86a5077c6a9190cde78ec75b8888c46ed0a3d1289054127a955a2af544633cf3 -- Recipe (0x86a5...3cf3)
- Chain ID: 1
- Market ID: 0x86a5077c6a9190cde78ec75b8888c46ed0a3d1289054127a955a2af544633cf3 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:50:35 GMT

feat(market-map): Update market -- 1_0_0x86a5077c6a9190cde78ec75b8888c46ed0a3d1289054127a955a2af544633cf3

---

sdk/constants/market-map/1/definitions/1_0_0x2dd74f8f8a8d7f27b2a82a6edce57b201f9b4a3c4780934caf99363115e48be6.ts

feat(market-map): Update market -- 1_0_0x2dd74f8f8a8d7f27b2a82a6edce57b201f9b4a3c4780934caf99363115e48be6 -- Recipe (0x2dd7...8be6)
- Chain ID: 1
- Market ID: 0x2dd74f8f8a8d7f27b2a82a6edce57b201f9b4a3c4780934caf99363115e48be6 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:51:43 GMT

feat(market-map): Update market -- 1_0_0x2dd74f8f8a8d7f27b2a82a6edce57b201f9b4a3c4780934caf99363115e48be6

---

sdk/constants/market-map/1/definitions/1_0_0x7ecf55915abe3c24dc5d8365a8edabc8833f4efb8e7c027429c9528aed91ecb7.ts

feat(market-map): Update market -- 1_0_0x7ecf55915abe3c24dc5d8365a8edabc8833f4efb8e7c027429c9528aed91ecb7 -- Recipe (0x7ecf...ecb7)
- Chain ID: 1
- Market ID: 0x7ecf55915abe3c24dc5d8365a8edabc8833f4efb8e7c027429c9528aed91ecb7 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:52:31 GMT

feat(market-map): Update market -- 1_0_0x7ecf55915abe3c24dc5d8365a8edabc8833f4efb8e7c027429c9528aed91ecb7

---

sdk/constants/market-map/1/definitions/1_0_0xc90525132d909f992363102ebd6298d95b1f312acdb9421fd1f7ac0c0dd78d3f.ts

feat(market-map): Update market -- 1_0_0xc90525132d909f992363102ebd6298d95b1f312acdb9421fd1f7ac0c0dd78d3f -- Recipe (0xc905...8d3f)
- Chain ID: 1
- Market ID: 0xc90525132d909f992363102ebd6298d95b1f312acdb9421fd1f7ac0c0dd78d3f (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:52:38 GMT

feat(market-map): Update market -- 1_0_0xc90525132d909f992363102ebd6298d95b1f312acdb9421fd1f7ac0c0dd78d3f

---

sdk/constants/market-map/1/definitions/1_0_0x415f935bbb9bf1bdc1f49f2ca763d5b2406efbf9cc949836880dd5bbd054db95.ts

feat(market-map): Update market -- 1_0_0x415f935bbb9bf1bdc1f49f2ca763d5b2406efbf9cc949836880dd5bbd054db95 -- Recipe (0x415f...db95)
- Chain ID: 1
- Market ID: 0x415f935bbb9bf1bdc1f49f2ca763d5b2406efbf9cc949836880dd5bbd054db95 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:53:38 GMT

feat(market-map): Update market -- 1_0_0x415f935bbb9bf1bdc1f49f2ca763d5b2406efbf9cc949836880dd5bbd054db95

---

sdk/constants/market-map/1/definitions/1_0_0x290aad1fabd8d2557d28a3854a2433ddc11a35f0d12936dd99102067ac515d07.ts

feat(market-map): Update market -- 1_0_0x290aad1fabd8d2557d28a3854a2433ddc11a35f0d12936dd99102067ac515d07 -- Recipe (0x290a...5d07)
- Chain ID: 1
- Market ID: 0x290aad1fabd8d2557d28a3854a2433ddc11a35f0d12936dd99102067ac515d07 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:55:41 GMT

feat(market-map): Update market -- 1_0_0x290aad1fabd8d2557d28a3854a2433ddc11a35f0d12936dd99102067ac515d07

---

sdk/constants/market-map/1/definitions/1_0_0x378d4d32d89450978d01cfdf1ff1907d4419aa186c48abb94e612b76d75f3fae.ts

feat(market-map): Update market -- 1_0_0x378d4d32d89450978d01cfdf1ff1907d4419aa186c48abb94e612b76d75f3fae -- Recipe (0x378d...3fae)
- Chain ID: 1
- Market ID: 0x378d4d32d89450978d01cfdf1ff1907d4419aa186c48abb94e612b76d75f3fae (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 17:58:53 GMT

feat(market-map): Update market -- 1_0_0x378d4d32d89450978d01cfdf1ff1907d4419aa186c48abb94e612b76d75f3fae

---

sdk/constants/market-map/1/definitions/1_0_0x4dd921e829db80e73c56d888eeaf46a7934a3c4a2f7f78231dd4502f8eaa2558.ts

feat(market-map): Update market -- 1_0_0x4dd921e829db80e73c56d888eeaf46a7934a3c4a2f7f78231dd4502f8eaa2558 -- Recipe (0x4dd9...2558)
- Chain ID: 1
- Market ID: 0x4dd921e829db80e73c56d888eeaf46a7934a3c4a2f7f78231dd4502f8eaa2558 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 18:06:58 GMT

feat(market-map): Update market -- 1_0_0x4dd921e829db80e73c56d888eeaf46a7934a3c4a2f7f78231dd4502f8eaa2558

---

sdk/constants/market-map/1/definitions/1_0_0x7e804adb4c426b81fbe1f005f92d8dee99f98b0502c3946ac5ad436b453c6435.ts

feat(market-map): Update market -- 1_0_0x7e804adb4c426b81fbe1f005f92d8dee99f98b0502c3946ac5ad436b453c6435 -- Recipe (0x7e80...6435)
- Chain ID: 1
- Market ID: 0x7e804adb4c426b81fbe1f005f92d8dee99f98b0502c3946ac5ad436b453c6435 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 18:08:19 GMT

feat(market-map): Update market -- 1_0_0x7e804adb4c426b81fbe1f005f92d8dee99f98b0502c3946ac5ad436b453c6435

---

sdk/constants/market-map/1/definitions/1_0_0xaa636d73f39ea0de0e04ed9270eac5d943707e7f8fb9c3480c0d80eb015ccfc8.ts

feat(market-map): Update market -- 1_0_0xaa636d73f39ea0de0e04ed9270eac5d943707e7f8fb9c3480c0d80eb015ccfc8 -- Recipe (0xaa63...cfc8)
- Chain ID: 1
- Market ID: 0xaa636d73f39ea0de0e04ed9270eac5d943707e7f8fb9c3480c0d80eb015ccfc8 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 18:08:41 GMT

feat(market-map): Update market -- 1_0_0xaa636d73f39ea0de0e04ed9270eac5d943707e7f8fb9c3480c0d80eb015ccfc8

---

sdk/constants/market-map/1/definitions/1_0_0x2fa37184f43783f5d6b23548c4a7a21bb86cd2f314bba9d5bb7d2415d61d11c8.ts

feat(market-map): Update market -- 1_0_0x2fa37184f43783f5d6b23548c4a7a21bb86cd2f314bba9d5bb7d2415d61d11c8 -- Recipe (0x2fa3...11c8)
- Chain ID: 1
- Market ID: 0x2fa37184f43783f5d6b23548c4a7a21bb86cd2f314bba9d5bb7d2415d61d11c8 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 18:12:10 GMT

feat(market-map): Update market -- 1_0_0x2fa37184f43783f5d6b23548c4a7a21bb86cd2f314bba9d5bb7d2415d61d11c8

---

sdk/constants/market-map/1/definitions/1_0_0xa74b61544834483b093531cff533d01788a5dea12d8a83902646111025303bfb.ts

feat(market-map): Update market -- 1_0_0xa74b61544834483b093531cff533d01788a5dea12d8a83902646111025303bfb -- Recipe (0xa74b...3bfb)
- Chain ID: 1
- Market ID: 0xa74b61544834483b093531cff533d01788a5dea12d8a83902646111025303bfb (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 18:18:32 GMT

feat(market-map): Update market -- 1_0_0xa74b61544834483b093531cff533d01788a5dea12d8a83902646111025303bfb

---

sdk/constants/market-map/1/definitions/1_0_0x49104b3cadbb31470e5b949c6892a33954ee9ce35041df4a04a88eb694b645c0.ts

feat(market-map): Update market -- 1_0_0x49104b3cadbb31470e5b949c6892a33954ee9ce35041df4a04a88eb694b645c0 -- Recipe (0x4910...45c0)
- Chain ID: 1
- Market ID: 0x49104b3cadbb31470e5b949c6892a33954ee9ce35041df4a04a88eb694b645c0 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 18:21:32 GMT

feat(market-map): Update market -- 1_0_0x49104b3cadbb31470e5b949c6892a33954ee9ce35041df4a04a88eb694b645c0

---

sdk/constants/market-map/1/definitions/1_0_0x9b60d30f266858fa671bf268796aa503700310e31a8f46ebaa8f8281fbad89aa.ts

feat(market-map): Update market -- 1_0_0x9b60d30f266858fa671bf268796aa503700310e31a8f46ebaa8f8281fbad89aa -- Recipe (0x9b60...89aa)
- Chain ID: 1
- Market ID: 0x9b60d30f266858fa671bf268796aa503700310e31a8f46ebaa8f8281fbad89aa (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 18:23:52 GMT

feat(market-map): Update market -- 1_0_0x9b60d30f266858fa671bf268796aa503700310e31a8f46ebaa8f8281fbad89aa

---

sdk/constants/market-map/1/definitions/1_0_0x21c6a0baa6f41b060937be5a4f1be096b63f426c50f763b4dabd1af46803fa2f.ts

feat(market-map): Update market -- 1_0_0x21c6a0baa6f41b060937be5a4f1be096b63f426c50f763b4dabd1af46803fa2f -- Recipe (0x21c6...fa2f)
- Chain ID: 1
- Market ID: 0x21c6a0baa6f41b060937be5a4f1be096b63f426c50f763b4dabd1af46803fa2f (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 18:26:35 GMT

feat(market-map): Update market -- 1_0_0x21c6a0baa6f41b060937be5a4f1be096b63f426c50f763b4dabd1af46803fa2f

---

sdk/constants/market-map/1/definitions/1_0_0xc5165360e2e8b195cb55e21cf259ce6a5ee996b055057d8705851d9b01fc8620.ts

feat(market-map): Update market -- 1_0_0xc5165360e2e8b195cb55e21cf259ce6a5ee996b055057d8705851d9b01fc8620 -- Recipe (0xc516...8620)
- Chain ID: 1
- Market ID: 0xc5165360e2e8b195cb55e21cf259ce6a5ee996b055057d8705851d9b01fc8620 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 18:28:53 GMT

feat(market-map): Update market -- 1_0_0xc5165360e2e8b195cb55e21cf259ce6a5ee996b055057d8705851d9b01fc8620

---

sdk/constants/market-map/1/definitions/1_0_0xab27dc8061f66791bb94a536546b08ba15e06344dabad2cc6267cf44f0070574.ts

feat(market-map): Update market -- 1_0_0xab27dc8061f66791bb94a536546b08ba15e06344dabad2cc6267cf44f0070574 -- Recipe (0xab27...0574)
- Chain ID: 1
- Market ID: 0xab27dc8061f66791bb94a536546b08ba15e06344dabad2cc6267cf44f0070574 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 18:31:32 GMT

feat(market-map): Update market -- 1_0_0xab27dc8061f66791bb94a536546b08ba15e06344dabad2cc6267cf44f0070574

---

sdk/constants/market-map/1/definitions/1_0_0xd6e9ff1fa0c9c6bb25cafcb76c61c0d398a479ba073509e10209271f40a01712.ts

feat(market-map): Update market -- 1_0_0xd6e9ff1fa0c9c6bb25cafcb76c61c0d398a479ba073509e10209271f40a01712 -- Recipe (0xd6e9...1712)
- Chain ID: 1
- Market ID: 0xd6e9ff1fa0c9c6bb25cafcb76c61c0d398a479ba073509e10209271f40a01712 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 18:36:03 GMT

feat(market-map): Update market -- 1_0_0xd6e9ff1fa0c9c6bb25cafcb76c61c0d398a479ba073509e10209271f40a01712

---

sdk/constants/market-map/1/definitions/1_0_0xa295c9d622bf2e562bcae859c46a9e95343982c3eab087b9ab098c256c1a32be.ts

feat(market-map): Update market -- 1_0_0xa295c9d622bf2e562bcae859c46a9e95343982c3eab087b9ab098c256c1a32be -- Recipe (0xa295...32be)
- Chain ID: 1
- Market ID: 0xa295c9d622bf2e562bcae859c46a9e95343982c3eab087b9ab098c256c1a32be (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 18:41:41 GMT

feat(market-map): Update market -- 1_0_0xa295c9d622bf2e562bcae859c46a9e95343982c3eab087b9ab098c256c1a32be

---

sdk/constants/market-map/1/definitions/1_0_0x460ec133419318efe4e05b4c3b6db421503fd6fcefbb20a43f50e3fc50f2ee39.ts

feat(market-map): Update market -- 1_0_0x460ec133419318efe4e05b4c3b6db421503fd6fcefbb20a43f50e3fc50f2ee39 -- Recipe (0x460e...ee39)
- Chain ID: 1
- Market ID: 0x460ec133419318efe4e05b4c3b6db421503fd6fcefbb20a43f50e3fc50f2ee39 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 18:48:08 GMT

feat(market-map): Update market -- 1_0_0x460ec133419318efe4e05b4c3b6db421503fd6fcefbb20a43f50e3fc50f2ee39

---

sdk/constants/market-map/1/definitions/1_0_0x25f7a422282a1f26d9d96b5d1c43fa5c6f8c355b0ed7a4755ac8d04a504817f5.ts

feat(market-map): Update market -- 1_0_0x25f7a422282a1f26d9d96b5d1c43fa5c6f8c355b0ed7a4755ac8d04a504817f5 -- Recipe (0x25f7...17f5)
- Chain ID: 1
- Market ID: 0x25f7a422282a1f26d9d96b5d1c43fa5c6f8c355b0ed7a4755ac8d04a504817f5 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 18:49:52 GMT

feat(market-map): Update market -- 1_0_0x25f7a422282a1f26d9d96b5d1c43fa5c6f8c355b0ed7a4755ac8d04a504817f5

---

sdk/constants/market-map/1/definitions/1_0_0x219169d9e78064768cddd0397c2202dc9e5c2bc0e1dbc13465363b0458d33c34.ts

feat(market-map): Update market -- 1_0_0x219169d9e78064768cddd0397c2202dc9e5c2bc0e1dbc13465363b0458d33c34 -- Recipe (0x2191...3c34)
- Chain ID: 1
- Market ID: 0x219169d9e78064768cddd0397c2202dc9e5c2bc0e1dbc13465363b0458d33c34 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 18:53:13 GMT

feat(market-map): Update market -- 1_0_0x219169d9e78064768cddd0397c2202dc9e5c2bc0e1dbc13465363b0458d33c34

---

sdk/constants/market-map/1/definitions/1_0_0x6262ac035c2284f5b5249a690a6fd81c35f1ecef501da089f25741a4492cf5f3.ts

feat(market-map): Update market -- 1_0_0x6262ac035c2284f5b5249a690a6fd81c35f1ecef501da089f25741a4492cf5f3 -- Recipe (0x6262...f5f3)
- Chain ID: 1
- Market ID: 0x6262ac035c2284f5b5249a690a6fd81c35f1ecef501da089f25741a4492cf5f3 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 19:20:55 GMT

feat(market-map): Update market -- 1_0_0x6262ac035c2284f5b5249a690a6fd81c35f1ecef501da089f25741a4492cf5f3

---

sdk/constants/market-map/1/definitions/1_0_0xa655556eb64a0fd18b9a3c80794ab370743bc431a4b2a6116fa97dcc7f741a2b.ts

feat(market-map): Update market -- 1_0_0xa655556eb64a0fd18b9a3c80794ab370743bc431a4b2a6116fa97dcc7f741a2b -- Recipe (0xa655...1a2b)
- Chain ID: 1
- Market ID: 0xa655556eb64a0fd18b9a3c80794ab370743bc431a4b2a6116fa97dcc7f741a2b (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 19:41:17 GMT

feat(market-map): Update market -- 1_0_0xa655556eb64a0fd18b9a3c80794ab370743bc431a4b2a6116fa97dcc7f741a2b

---

sdk/constants/market-map/1/definitions/1_0_0x5f3eb887e8c46508efa707774636dbfab09eaf109d2c8d699917b273da8bcc04.ts

feat(market-map): Update market -- 1_0_0x5f3eb887e8c46508efa707774636dbfab09eaf109d2c8d699917b273da8bcc04 -- Recipe (0x5f3e...cc04)
- Chain ID: 1
- Market ID: 0x5f3eb887e8c46508efa707774636dbfab09eaf109d2c8d699917b273da8bcc04 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 21:48:08 GMT

feat(market-map): Update market -- 1_0_0x5f3eb887e8c46508efa707774636dbfab09eaf109d2c8d699917b273da8bcc04

---

sdk/constants/market-map/1/definitions/1_0_0xe48262be7fd7d738763545e81a781fc62e58abf9e0a5f0be228fca5bc01ee1f8.ts

feat(market-map): Update market -- 1_0_0xe48262be7fd7d738763545e81a781fc62e58abf9e0a5f0be228fca5bc01ee1f8 -- Recipe (0xe482...e1f8)
- Chain ID: 1
- Market ID: 0xe48262be7fd7d738763545e81a781fc62e58abf9e0a5f0be228fca5bc01ee1f8 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 21:51:57 GMT

feat(market-map): Update market -- 1_0_0xe48262be7fd7d738763545e81a781fc62e58abf9e0a5f0be228fca5bc01ee1f8

---

sdk/constants/market-map/1/definitions/1_0_0xd830e95e4a9a5bddf1e9dea286445f4613ff316c07d5e9b11844e2e8e243ad95.ts

feat(market-map): Update market -- 1_0_0xd830e95e4a9a5bddf1e9dea286445f4613ff316c07d5e9b11844e2e8e243ad95 -- Recipe (0xd830...ad95)
- Chain ID: 1
- Market ID: 0xd830e95e4a9a5bddf1e9dea286445f4613ff316c07d5e9b11844e2e8e243ad95 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 21:52:51 GMT

feat(market-map): Update market -- 1_0_0xd830e95e4a9a5bddf1e9dea286445f4613ff316c07d5e9b11844e2e8e243ad95

---

sdk/constants/market-map/1/definitions/1_0_0x3a19f33c056aa1670d280caf9caa9f7125754f2ff5c25dfc6a186a2b7302006b.ts

feat(market-map): Update market -- 1_0_0x3a19f33c056aa1670d280caf9caa9f7125754f2ff5c25dfc6a186a2b7302006b -- Recipe (0x3a19...006b)
- Chain ID: 1
- Market ID: 0x3a19f33c056aa1670d280caf9caa9f7125754f2ff5c25dfc6a186a2b7302006b (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 21:53:58 GMT

feat(market-map): Update market -- 1_0_0x3a19f33c056aa1670d280caf9caa9f7125754f2ff5c25dfc6a186a2b7302006b

---

sdk/constants/market-map/1/definitions/1_0_0xc72fd1a3128f9898ab1bd589119bc9240add1af48d1c39ff23c4028163c8dca8.ts

feat(market-map): Update market -- 1_0_0xc72fd1a3128f9898ab1bd589119bc9240add1af48d1c39ff23c4028163c8dca8 -- Recipe (0xc72f...dca8)
- Chain ID: 1
- Market ID: 0xc72fd1a3128f9898ab1bd589119bc9240add1af48d1c39ff23c4028163c8dca8 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 21:57:08 GMT

feat(market-map): Update market -- 1_0_0xc72fd1a3128f9898ab1bd589119bc9240add1af48d1c39ff23c4028163c8dca8

---

sdk/constants/market-map/1/definitions/1_0_0xa31a8bb230f77a5d286985b92fe8d0c7504a1892568d70685659f781aec78209.ts

feat(market-map): Update market -- 1_0_0xa31a8bb230f77a5d286985b92fe8d0c7504a1892568d70685659f781aec78209 -- Recipe (0xa31a...8209)
- Chain ID: 1
- Market ID: 0xa31a8bb230f77a5d286985b92fe8d0c7504a1892568d70685659f781aec78209 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 22:05:53 GMT

feat(market-map): Update market -- 1_0_0xa31a8bb230f77a5d286985b92fe8d0c7504a1892568d70685659f781aec78209

---

sdk/constants/market-map/1/definitions/1_0_0xece925dbccbb21333dbe99679fef655ad2dc2cb185e0963711c944e302595b28.ts

feat(market-map): Update market -- 1_0_0xece925dbccbb21333dbe99679fef655ad2dc2cb185e0963711c944e302595b28 -- Recipe (0xece9...5b28)
- Chain ID: 1
- Market ID: 0xece925dbccbb21333dbe99679fef655ad2dc2cb185e0963711c944e302595b28 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 22:06:36 GMT

feat(market-map): Update market -- 1_0_0xece925dbccbb21333dbe99679fef655ad2dc2cb185e0963711c944e302595b28

---

sdk/constants/market-map/1/definitions/1_0_0x5043bfe3f6bab5fa4c8f19fb2f6856de2d2e717a541e0d7126b308926be04e2e.ts

feat(market-map): Update market -- 1_0_0x5043bfe3f6bab5fa4c8f19fb2f6856de2d2e717a541e0d7126b308926be04e2e -- Recipe (0x5043...4e2e)
- Chain ID: 1
- Market ID: 0x5043bfe3f6bab5fa4c8f19fb2f6856de2d2e717a541e0d7126b308926be04e2e (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 22:07:28 GMT

feat(market-map): Update market -- 1_0_0x5043bfe3f6bab5fa4c8f19fb2f6856de2d2e717a541e0d7126b308926be04e2e

---

sdk/constants/market-map/1/definitions/1_0_0x3d7cf2bd0a04fd3c66a5fa334a399b3926efe0fc0450b8da49a5da29f2c36d7f.ts

feat(market-map): Update market -- 1_0_0x3d7cf2bd0a04fd3c66a5fa334a399b3926efe0fc0450b8da49a5da29f2c36d7f -- Recipe (0x3d7c...6d7f)
- Chain ID: 1
- Market ID: 0x3d7cf2bd0a04fd3c66a5fa334a399b3926efe0fc0450b8da49a5da29f2c36d7f (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 22:08:01 GMT

feat(market-map): Update market -- 1_0_0x3d7cf2bd0a04fd3c66a5fa334a399b3926efe0fc0450b8da49a5da29f2c36d7f

---

sdk/constants/market-map/1/definitions/1_0_0xb36f14fd392b9a1d6c3fabedb9a62a63d2067ca0ebeb63bbc2c93b11cc8eb3a2.ts

feat(market-map): Update market -- 1_0_0xb36f14fd392b9a1d6c3fabedb9a62a63d2067ca0ebeb63bbc2c93b11cc8eb3a2 -- Recipe (0xb36f...b3a2)
- Chain ID: 1
- Market ID: 0xb36f14fd392b9a1d6c3fabedb9a62a63d2067ca0ebeb63bbc2c93b11cc8eb3a2 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 22:26:15 GMT

feat(market-map): Update market -- 1_0_0xb36f14fd392b9a1d6c3fabedb9a62a63d2067ca0ebeb63bbc2c93b11cc8eb3a2

---

sdk/constants/market-map/1/definitions/1_0_0xabf4b2f17bc32faf4c3295b1347f36d21ec5629128d465b5569e600bf8d46c4f.ts

feat(market-map): Update market -- 1_0_0xabf4b2f17bc32faf4c3295b1347f36d21ec5629128d465b5569e600bf8d46c4f -- Recipe (0xabf4...6c4f)
- Chain ID: 1
- Market ID: 0xabf4b2f17bc32faf4c3295b1347f36d21ec5629128d465b5569e600bf8d46c4f (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 22:29:06 GMT

feat(market-map): Update market -- 1_0_0xabf4b2f17bc32faf4c3295b1347f36d21ec5629128d465b5569e600bf8d46c4f

---

sdk/constants/market-map/1/definitions/1_0_0x5f7935e257b94aee6caf9bbe917d4cfad75e8bc3b231806769ca0935af8371e8.ts

feat(market-map): Update market -- 1_0_0x5f7935e257b94aee6caf9bbe917d4cfad75e8bc3b231806769ca0935af8371e8 -- Recipe (0x5f79...71e8)
- Chain ID: 1
- Market ID: 0x5f7935e257b94aee6caf9bbe917d4cfad75e8bc3b231806769ca0935af8371e8 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 15:40:21 GMT

feat(market-map): Update market -- 1_0_0x5f7935e257b94aee6caf9bbe917d4cfad75e8bc3b231806769ca0935af8371e8

---

sdk/constants/market-map/1/definitions/1_0_0x0484203315d701daff0d6dbdd55c49c3f220c3c7b917892bed1badb8fdc0182e.ts

feat(market-map): Update market -- 1_0_0x0484203315d701daff0d6dbdd55c49c3f220c3c7b917892bed1badb8fdc0182e -- Recipe (0x0484...182e)
- Chain ID: 1
- Market ID: 0x0484203315d701daff0d6dbdd55c49c3f220c3c7b917892bed1badb8fdc0182e (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 22:31:15 GMT

feat(market-map): Update market -- 1_0_0x0484203315d701daff0d6dbdd55c49c3f220c3c7b917892bed1badb8fdc0182e

---

sdk/constants/market-map/1/definitions/1_0_0xff0182973d5f1e9a64392c413caaa75f364f24632a7de0fdd1a31fe30517fdd2.ts

feat(market-map): Update market -- 1_0_0xff0182973d5f1e9a64392c413caaa75f364f24632a7de0fdd1a31fe30517fdd2 -- Recipe (0xff01...fdd2)
- Chain ID: 1
- Market ID: 0xff0182973d5f1e9a64392c413caaa75f364f24632a7de0fdd1a31fe30517fdd2 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 22:33:28 GMT

feat(market-map): Update market -- 1_0_0xff0182973d5f1e9a64392c413caaa75f364f24632a7de0fdd1a31fe30517fdd2

---

sdk/constants/market-map/1/definitions/1_0_0x72679855f582a6d908bf39d40cb5a299b6a98a82bf1bfd9055f1853fc5160f54.ts

feat(market-map): Update market -- 1_0_0x72679855f582a6d908bf39d40cb5a299b6a98a82bf1bfd9055f1853fc5160f54 -- Recipe (0x7267...0f54)
- Chain ID: 1
- Market ID: 0x72679855f582a6d908bf39d40cb5a299b6a98a82bf1bfd9055f1853fc5160f54 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 23:40:56 GMT

feat(market-map): Update market -- 1_0_0x72679855f582a6d908bf39d40cb5a299b6a98a82bf1bfd9055f1853fc5160f54

---

sdk/constants/market-map/1/definitions/1_0_0xbd3ef685577bdca03225bb2cd2158f0772cdfd694ba03b9eb4856b59a7288081.ts

feat(market-map): Update market -- 1_0_0xbd3ef685577bdca03225bb2cd2158f0772cdfd694ba03b9eb4856b59a7288081 -- Recipe (0xbd3e...8081)
- Chain ID: 1
- Market ID: 0xbd3ef685577bdca03225bb2cd2158f0772cdfd694ba03b9eb4856b59a7288081 (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 23:42:47 GMT

feat(market-map): Update market -- 1_0_0xbd3ef685577bdca03225bb2cd2158f0772cdfd694ba03b9eb4856b59a7288081

---

sdk/constants/market-map/1/definitions/1_0_0xab32e1695b84b148140cb78c044d247e307b26cb043dc5538657f3a5634dee6e.ts

feat(market-map): Update market -- 1_0_0xab32e1695b84b148140cb78c044d247e307b26cb043dc5538657f3a5634dee6e -- Recipe (0xab32...ee6e)
- Chain ID: 1
- Market ID: 0xab32e1695b84b148140cb78c044d247e307b26cb043dc5538657f3a5634dee6e (Market Hash)
- Request Timestamp: Sun, 26 Jan 2025 23:44:25 GMT

feat(market-map): Update market -- 1_0_0xab32e1695b84b148140cb78c044d247e307b26cb043dc5538657f3a5634dee6e

---

sdk/constants/market-map/1/definitions/1_0_0x54b4b37c355868591a91baed36a3c8083f6480ccb11145106d0dad912d7dffd2.ts

feat(market-map): Update market -- 1_0_0x54b4b37c355868591a91baed36a3c8083f6480ccb11145106d0dad912d7dffd2 -- Recipe (0x54b4...ffd2)
- Chain ID: 1
- Market ID: 0x54b4b37c355868591a91baed36a3c8083f6480ccb11145106d0dad912d7dffd2 (Market Hash)
- Request Timestamp: Mon, 27 Jan 2025 00:49:15 GMT

feat(market-map): Update market -- 1_0_0x54b4b37c355868591a91baed36a3c8083f6480ccb11145106d0dad912d7dffd2

---

sdk/constants/market-map/42161/definitions/42161_0_0xbf09f8cde91cff7f58e80dfaec5a960c319e962f21be0c5dae8e31fd27c6d156.ts

feat(market-map): Update market -- 42161_0_0xbf09f8cde91cff7f58e80dfaec5a960c319e962f21be0c5dae8e31fd27c6d156 -- Recipe (0xbf09...d156)
- Market ID: 0xbf09f8cde91cff7f58e80dfaec5a960c319e962f21be0c5dae8e31fd27c6d156 (Market Hash)
- Request Timestamp: Mon, 27 Jan 2025 05:25:57 GMT

feat(market-map): Update market -- 42161_0_0xbf09f8cde91cff7f58e80dfaec5a960c319e962f21be0c5dae8e31fd27c6d156

---

sdk/constants/market-map/1/definitions/1_0_0x71cee3cf3329e9a2803d578cdd6c823d7a16aa39adea3a7053395299bd258800.ts

feat(market-map): Update market -- 1_0_0x71cee3cf3329e9a2803d578cdd6c823d7a16aa39adea3a7053395299bd258800 -- Recipe (0x71ce...8800)
- Chain ID: 1
- Market ID: 0x71cee3cf3329e9a2803d578cdd6c823d7a16aa39adea3a7053395299bd258800 (Market Hash)
- Request Timestamp: Mon, 27 Jan 2025 15:53:58 GMT

feat(market-map): Update market -- 1_0_0x71cee3cf3329e9a2803d578cdd6c823d7a16aa39adea3a7053395299bd258800

---

sdk/constants/market-map/1/definitions/1_0_0x20ca89af1fd136d0ef9c4e3e74e8ab1943d28e6879206a3e180fd35e29fb2d7d.ts

feat(market-map): Update market -- 1_0_0x20ca89af1fd136d0ef9c4e3e74e8ab1943d28e6879206a3e180fd35e29fb2d7d -- Recipe (0x20ca...2d7d)
- Chain ID: 1
- Market ID: 0x20ca89af1fd136d0ef9c4e3e74e8ab1943d28e6879206a3e180fd35e29fb2d7d (Market Hash)
- Request Timestamp: Mon, 27 Jan 2025 21:54:42 GMT

feat(market-map): Update market -- 1_0_0x20ca89af1fd136d0ef9c4e3e74e8ab1943d28e6879206a3e180fd35e29fb2d7d

---

sdk/boyco/bera-yield/manage-multiplier.tsx

correct the multiplier for 2 markets

Update multipliers map 

---

sdk/constants/token-map/1/definitions/1-0x4C3b39EDc50D58C1C59A389A77AEf1e767F6bC3f.ts
sdk/constants/token-map/1/index.ts

Add Yieldnest points contract to token-map

feat(token-map): 1-0x4C3b39EDc50D58C1C59A389A77AEf1e767F6bC3f.ts

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xebea0c5c5ffc07244ea7416e336a71ba6d44c089657a20a5e6e33ca8fbd32a20.ts

feat(market-map): Update market -- 11155111_0_0xebea0c5c5ffc07244ea7416e336a71ba6d44c089657a20a5e6e33ca8fbd32a20 -- Recipe (0xebea...2a20)
- Market ID: 0xebea0c5c5ffc07244ea7416e336a71ba6d44c089657a20a5e6e33ca8fbd32a20 (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 17:45:17 GMT

feat(market-map): Update market -- 11155111_0_0xebea0c5c5ffc07244ea7416e336a71ba6d44c089657a20a5e6e33ca8fbd32a20

---

sdk/constants/market-map/1/definitions/1_0_0xcd4a25be0ea0055a91b9825dc81717e68da15bc50563bc23a306694680a025d5.ts

feat(market-map): Update market -- 1_0_0xcd4a25be0ea0055a91b9825dc81717e68da15bc50563bc23a306694680a025d5 -- Recipe (0xcd4a...25d5)
- Chain ID: 1
- Market ID: 0xcd4a25be0ea0055a91b9825dc81717e68da15bc50563bc23a306694680a025d5 (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:12:22 GMT

feat(market-map): Update market -- 1_0_0xcd4a25be0ea0055a91b9825dc81717e68da15bc50563bc23a306694680a025d5

---

sdk/constants/market-map/1/definitions/1_0_0xdfacd6b5e1e6603b613165c1dbefb21678ebdd457c51ea9e62347ea4aee05086.ts

feat(market-map): Update market -- 1_0_0xdfacd6b5e1e6603b613165c1dbefb21678ebdd457c51ea9e62347ea4aee05086 -- Recipe (0xdfac...5086)
- Chain ID: 1
- Market ID: 0xdfacd6b5e1e6603b613165c1dbefb21678ebdd457c51ea9e62347ea4aee05086 (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:13:45 GMT

feat(market-map): Update market -- 1_0_0xdfacd6b5e1e6603b613165c1dbefb21678ebdd457c51ea9e62347ea4aee05086

---

sdk/constants/market-map/1/definitions/1_0_0x9fe71de2cbc7a18db40d01d9e83a09015236ba62a8e8fcd78839fcd53e3c7b70.ts

feat(market-map): Update market -- 1_0_0x9fe71de2cbc7a18db40d01d9e83a09015236ba62a8e8fcd78839fcd53e3c7b70 -- Recipe (0x9fe7...7b70)
- Chain ID: 1
- Market ID: 0x9fe71de2cbc7a18db40d01d9e83a09015236ba62a8e8fcd78839fcd53e3c7b70 (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:15:14 GMT

feat(market-map): Update market -- 1_0_0x9fe71de2cbc7a18db40d01d9e83a09015236ba62a8e8fcd78839fcd53e3c7b70

---

sdk/constants/market-map/1/definitions/1_0_0x1e50d9b764caec170614b8f808c1af3ce621d6d2c1ca135b1210d2127f3cc856.ts

feat(market-map): Update market -- 1_0_0x1e50d9b764caec170614b8f808c1af3ce621d6d2c1ca135b1210d2127f3cc856 -- Recipe (0x1e50...c856)
- Chain ID: 1
- Market ID: 0x1e50d9b764caec170614b8f808c1af3ce621d6d2c1ca135b1210d2127f3cc856 (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:17:13 GMT

feat(market-map): Update market -- 1_0_0x1e50d9b764caec170614b8f808c1af3ce621d6d2c1ca135b1210d2127f3cc856

---

sdk/constants/market-map/1/definitions/1_0_0x6037a22aada94cec515c8f7286ef865cb7643c5139116df4b6de7bc105042f96.ts

feat(market-map): Update market -- 1_0_0x6037a22aada94cec515c8f7286ef865cb7643c5139116df4b6de7bc105042f96 -- Recipe (0x6037...2f96)
- Chain ID: 1
- Market ID: 0x6037a22aada94cec515c8f7286ef865cb7643c5139116df4b6de7bc105042f96 (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:18:51 GMT

feat(market-map): Update market -- 1_0_0x6037a22aada94cec515c8f7286ef865cb7643c5139116df4b6de7bc105042f96

---

sdk/constants/market-map/1/definitions/1_0_0xa540d11898d919445efa9275cb529df239fa09f9bb8b27d60c1bc2266f35da63.ts

feat(market-map): Update market -- 1_0_0xa540d11898d919445efa9275cb529df239fa09f9bb8b27d60c1bc2266f35da63 -- Recipe (0xa540...da63)
- Chain ID: 1
- Market ID: 0xa540d11898d919445efa9275cb529df239fa09f9bb8b27d60c1bc2266f35da63 (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:25:24 GMT

feat(market-map): Update market -- 1_0_0xa540d11898d919445efa9275cb529df239fa09f9bb8b27d60c1bc2266f35da63

---

sdk/constants/market-map/1/definitions/1_0_0x0cfc1fb9254ded3240b02bd9d4148da130e2c8ebfd2d0014d1b7e40f73d58515.ts

feat(market-map): Update market -- 1_0_0x0cfc1fb9254ded3240b02bd9d4148da130e2c8ebfd2d0014d1b7e40f73d58515 -- Recipe (0x0cfc...8515)
- Chain ID: 1
- Market ID: 0x0cfc1fb9254ded3240b02bd9d4148da130e2c8ebfd2d0014d1b7e40f73d58515 (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:29:13 GMT

feat(market-map): Update market -- 1_0_0x0cfc1fb9254ded3240b02bd9d4148da130e2c8ebfd2d0014d1b7e40f73d58515

---

sdk/constants/market-map/1/definitions/1_0_0xfc65dca6efb0142eddac182d5ddcc9d3bd2a24d4f73b154b13c8bf0ea826ca55.ts

feat(market-map): Update market -- 1_0_0xfc65dca6efb0142eddac182d5ddcc9d3bd2a24d4f73b154b13c8bf0ea826ca55 -- Recipe (0xfc65...ca55)
- Chain ID: 1
- Market ID: 0xfc65dca6efb0142eddac182d5ddcc9d3bd2a24d4f73b154b13c8bf0ea826ca55 (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:30:15 GMT

feat(market-map): Update market -- 1_0_0xfc65dca6efb0142eddac182d5ddcc9d3bd2a24d4f73b154b13c8bf0ea826ca55

---

sdk/constants/market-map/1/definitions/1_0_0x63f6a0d8f675965824f75bfdd9519873d7b0f8568ebc9ffb1d91afeb2d64af39.ts

feat(market-map): Update market -- 1_0_0x63f6a0d8f675965824f75bfdd9519873d7b0f8568ebc9ffb1d91afeb2d64af39 -- Recipe (0x63f6...af39)
- Chain ID: 1
- Market ID: 0x63f6a0d8f675965824f75bfdd9519873d7b0f8568ebc9ffb1d91afeb2d64af39 (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:31:01 GMT

feat(market-map): Update market -- 1_0_0x63f6a0d8f675965824f75bfdd9519873d7b0f8568ebc9ffb1d91afeb2d64af39

---

sdk/constants/market-map/1/definitions/1_0_0xa894207d442cd64d8449fd55d9ea74322c3fee2095e8ad954ad7989dd85a2b01.ts

feat(market-map): Update market -- 1_0_0xa894207d442cd64d8449fd55d9ea74322c3fee2095e8ad954ad7989dd85a2b01 -- Recipe (0xa894...2b01)
- Chain ID: 1
- Market ID: 0xa894207d442cd64d8449fd55d9ea74322c3fee2095e8ad954ad7989dd85a2b01 (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:33:50 GMT

feat(market-map): Update market -- 1_0_0xa894207d442cd64d8449fd55d9ea74322c3fee2095e8ad954ad7989dd85a2b01

---

sdk/constants/market-map/1/definitions/1_0_0x38402a156ad8f9436fbd8ce96dea2973839fb024591aead6cfaa8a752be6ba8d.ts

feat(market-map): Update market -- 1_0_0x38402a156ad8f9436fbd8ce96dea2973839fb024591aead6cfaa8a752be6ba8d -- Recipe (0x3840...ba8d)
- Chain ID: 1
- Market ID: 0x38402a156ad8f9436fbd8ce96dea2973839fb024591aead6cfaa8a752be6ba8d (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:34:52 GMT

feat(market-map): Update market -- 1_0_0x38402a156ad8f9436fbd8ce96dea2973839fb024591aead6cfaa8a752be6ba8d

---

sdk/constants/market-map/1/definitions/1_0_0xb5ad81d0cdb02b05a01ac9d29d7ec808d53def8bc41925cbe97b7d809a924475.ts

feat(market-map): Update market -- 1_0_0xb5ad81d0cdb02b05a01ac9d29d7ec808d53def8bc41925cbe97b7d809a924475 -- Recipe (0xb5ad...4475)
- Chain ID: 1
- Market ID: 0xb5ad81d0cdb02b05a01ac9d29d7ec808d53def8bc41925cbe97b7d809a924475 (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:38:14 GMT

feat(market-map): Update market -- 1_0_0xb5ad81d0cdb02b05a01ac9d29d7ec808d53def8bc41925cbe97b7d809a924475

---

sdk/constants/market-map/1/definitions/1_0_0x712d0016ef0feab1881594731c673c060a78d787bb09e9429c90df3e8f8e2b74.ts

feat(market-map): Update market -- 1_0_0x712d0016ef0feab1881594731c673c060a78d787bb09e9429c90df3e8f8e2b74 -- Recipe (0x712d...2b74)
- Chain ID: 1
- Market ID: 0x712d0016ef0feab1881594731c673c060a78d787bb09e9429c90df3e8f8e2b74 (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:39:15 GMT

feat(market-map): Update market -- 1_0_0x712d0016ef0feab1881594731c673c060a78d787bb09e9429c90df3e8f8e2b74

---

sdk/constants/market-map/1/definitions/1_0_0x06f6fe9b9bf0af42765fadd1ec1a38cce2f007a3688b8f2cb0b588d82bc2a799.ts

feat(market-map): Update market -- 1_0_0x06f6fe9b9bf0af42765fadd1ec1a38cce2f007a3688b8f2cb0b588d82bc2a799 -- Recipe (0x06f6...a799)
- Chain ID: 1
- Market ID: 0x06f6fe9b9bf0af42765fadd1ec1a38cce2f007a3688b8f2cb0b588d82bc2a799 (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:40:12 GMT

feat(market-map): Update market -- 1_0_0x06f6fe9b9bf0af42765fadd1ec1a38cce2f007a3688b8f2cb0b588d82bc2a799

---

sdk/constants/market-map/1/definitions/1_0_0x1638a5c50413b2b873d156f58a355498d28fee902e289178381c5a986f93d4c0.ts

feat(market-map): Update market -- 1_0_0x1638a5c50413b2b873d156f58a355498d28fee902e289178381c5a986f93d4c0 -- Recipe (0x1638...d4c0)
- Chain ID: 1
- Market ID: 0x1638a5c50413b2b873d156f58a355498d28fee902e289178381c5a986f93d4c0 (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:41:51 GMT

feat(market-map): Update market -- 1_0_0x1638a5c50413b2b873d156f58a355498d28fee902e289178381c5a986f93d4c0

---

sdk/constants/market-map/1/definitions/1_0_0x90aa8052cc08c77a23959e75ad3936dba56b7126130511d2e7f3b682bc269814.ts

feat(market-map): Update market -- 1_0_0x90aa8052cc08c77a23959e75ad3936dba56b7126130511d2e7f3b682bc269814 -- Recipe (0x90aa...9814)
- Chain ID: 1
- Market ID: 0x90aa8052cc08c77a23959e75ad3936dba56b7126130511d2e7f3b682bc269814 (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:45:41 GMT

feat(market-map): Update market -- 1_0_0x90aa8052cc08c77a23959e75ad3936dba56b7126130511d2e7f3b682bc269814

---

sdk/constants/market-map/1/definitions/1_0_0x2aefe67c5240817a753c462985064337dcd704b9f23251dcce0e37ad0bd64c5c.ts

feat(market-map): Update market -- 1_0_0x2aefe67c5240817a753c462985064337dcd704b9f23251dcce0e37ad0bd64c5c -- Recipe (0x2aef...4c5c)
- Chain ID: 1
- Market ID: 0x2aefe67c5240817a753c462985064337dcd704b9f23251dcce0e37ad0bd64c5c (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:47:28 GMT

feat(market-map): Update market -- 1_0_0x2aefe67c5240817a753c462985064337dcd704b9f23251dcce0e37ad0bd64c5c

---

sdk/constants/market-map/1/definitions/1_0_0x792bea5c2d1c00325254a0b1aeacfadf6ed010c1b00af5c3e4ef3da5d1d5665f.ts

feat(market-map): Update market -- 1_0_0x792bea5c2d1c00325254a0b1aeacfadf6ed010c1b00af5c3e4ef3da5d1d5665f -- Recipe (0x792b...665f)
- Chain ID: 1
- Market ID: 0x792bea5c2d1c00325254a0b1aeacfadf6ed010c1b00af5c3e4ef3da5d1d5665f (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:48:12 GMT

feat(market-map): Update market -- 1_0_0x792bea5c2d1c00325254a0b1aeacfadf6ed010c1b00af5c3e4ef3da5d1d5665f

---

sdk/constants/market-map/1/definitions/1_0_0x354bee23352682f2193be6e62baffc36e8a443ab496542305a538d9c9de03c8c.ts

feat(market-map): Update market -- 1_0_0x354bee23352682f2193be6e62baffc36e8a443ab496542305a538d9c9de03c8c -- Recipe (0x354b...3c8c)
- Chain ID: 1
- Market ID: 0x354bee23352682f2193be6e62baffc36e8a443ab496542305a538d9c9de03c8c (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:54:53 GMT

feat(market-map): Update market -- 1_0_0x354bee23352682f2193be6e62baffc36e8a443ab496542305a538d9c9de03c8c

---

sdk/constants/market-map/1/definitions/1_0_0x1f3c50f0c85c0ec006d5e453b18020b5e5347c1cfb6f1632741bd6e8b86fb24f.ts

feat(market-map): Update market -- 1_0_0x1f3c50f0c85c0ec006d5e453b18020b5e5347c1cfb6f1632741bd6e8b86fb24f -- Recipe (0x1f3c...b24f)
- Chain ID: 1
- Market ID: 0x1f3c50f0c85c0ec006d5e453b18020b5e5347c1cfb6f1632741bd6e8b86fb24f (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:55:16 GMT

feat(market-map): Update market -- 1_0_0x1f3c50f0c85c0ec006d5e453b18020b5e5347c1cfb6f1632741bd6e8b86fb24f

---

sdk/constants/market-map/1/definitions/1_0_0x64f2a679a5eb24fc6bf975870626faf75ff1bcf831a670c144d8b78035dc54e9.ts

feat(market-map): Update market -- 1_0_0x64f2a679a5eb24fc6bf975870626faf75ff1bcf831a670c144d8b78035dc54e9 -- Recipe (0x64f2...54e9)
- Chain ID: 1
- Market ID: 0x64f2a679a5eb24fc6bf975870626faf75ff1bcf831a670c144d8b78035dc54e9 (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:55:52 GMT

feat(market-map): Update market -- 1_0_0x64f2a679a5eb24fc6bf975870626faf75ff1bcf831a670c144d8b78035dc54e9

---

sdk/constants/market-map/1/definitions/1_0_0xa6cde8ca73aa5309011dc3e399a59a13fd12a504329f76917646c65f6b1e0213.ts

feat(market-map): Update market -- 1_0_0xa6cde8ca73aa5309011dc3e399a59a13fd12a504329f76917646c65f6b1e0213 -- Recipe (0xa6cd...0213)
- Chain ID: 1
- Market ID: 0xa6cde8ca73aa5309011dc3e399a59a13fd12a504329f76917646c65f6b1e0213 (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:56:30 GMT

feat(market-map): Update market -- 1_0_0xa6cde8ca73aa5309011dc3e399a59a13fd12a504329f76917646c65f6b1e0213

---

sdk/constants/market-map/1/definitions/1_0_0x6ceac970b31fab7c609d67303491e47ca718277b5a0f99f16d0062cdbe0aa53a.ts

feat(market-map): Update market -- 1_0_0x6ceac970b31fab7c609d67303491e47ca718277b5a0f99f16d0062cdbe0aa53a -- Recipe (0x6cea...a53a)
- Chain ID: 1
- Market ID: 0x6ceac970b31fab7c609d67303491e47ca718277b5a0f99f16d0062cdbe0aa53a (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:57:38 GMT

feat(market-map): Update market -- 1_0_0x6ceac970b31fab7c609d67303491e47ca718277b5a0f99f16d0062cdbe0aa53a

---

sdk/constants/market-map/1/definitions/1_0_0x9566e7e23919d15cf4df9f7076aea4d50d6b943d36c9d78dd203793eb94e3a88.ts

feat(market-map): Update market -- 1_0_0x9566e7e23919d15cf4df9f7076aea4d50d6b943d36c9d78dd203793eb94e3a88 -- Recipe (0x9566...3a88)
- Chain ID: 1
- Market ID: 0x9566e7e23919d15cf4df9f7076aea4d50d6b943d36c9d78dd203793eb94e3a88 (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 19:58:54 GMT

feat(market-map): Update market -- 1_0_0x9566e7e23919d15cf4df9f7076aea4d50d6b943d36c9d78dd203793eb94e3a88

---

sdk/constants/market-map/1/definitions/1_0_0x6e1ba4f621a800c5866cb99d8d2cb2dcb65180c9c60bc8a569a3350e138b62a8.ts

feat(market-map): Update market -- 1_0_0x6e1ba4f621a800c5866cb99d8d2cb2dcb65180c9c60bc8a569a3350e138b62a8 -- Recipe (0x6e1b...62a8)
- Chain ID: 1
- Market ID: 0x6e1ba4f621a800c5866cb99d8d2cb2dcb65180c9c60bc8a569a3350e138b62a8 (Market Hash)
- Request Timestamp: Thu, 30 Jan 2025 20:38:13 GMT

feat(market-map): Update market -- 1_0_0x6e1ba4f621a800c5866cb99d8d2cb2dcb65180c9c60bc8a569a3350e138b62a8

---

sdk/constants/market-map/1/definitions/1_0_0x0a7565b14941c6a3dde083fb7a857e27e12c55fa34f709c37586ec585dbe7f3f.ts
sdk/constants/market-map/1/definitions/1_0_0x17ffd16948c053cc184c005477548e559566879a0e2847e87ebd1111c602535c.ts
sdk/constants/market-map/1/definitions/1_0_0x62bb6fb784e059f338340a9724b35ef2ef8fde5e65613e9fcaacd097d81dc67e.ts
sdk/constants/market-map/1/definitions/1_0_0x71cee3cf3329e9a2803d578cdd6c823d7a16aa39adea3a7053395299bd258800.ts
sdk/constants/market-map/1/definitions/1_0_0x72bec627884d7bdf538f174bedd551e9eccf3995adc880f40972e2bab87df3b9.ts
sdk/constants/market-map/1/definitions/1_0_0x9778047cb8f3740866882a97a186dff42743bebb3ad8010edbf637ab0e37751f.ts
sdk/constants/market-map/1/definitions/1_0_0xaf2a845c9d6007128b7aec375a4fcdee2b12bbaeb78caf928d3bd08e104417d6.ts
sdk/constants/market-map/1/definitions/1_0_0xb9f307d83c78d09a134aac7713821aab8e1da2404b895db66f0975135dd5006e.ts

Adding Stargate Incentives to:
WETH on Dolomite
HONEY on Dolomite
USDC/HONEY on Kodiak
NECT/HONEY on Kodiak
beraETH/ETH on Kodiak
WETH/HONEY on Kodiak
WETH on Beraborrow
USDC on Burrbear

Stargate incentives

---

sdk/constants/market-map/146/definitions/146_1_0x7f24390ef4f8c1a372524ff1fa3a1d79d66d86ca.ts

feat(market-map): Update market -- 146_1_0x7f24390ef4f8c1a372524ff1fa3a1d79d66d86ca -- Vault (0x7f24...86ca)
- Market ID: 0x7f24390ef4f8c1a372524ff1fa3a1d79d66d86ca (Wrapped Vault Address)
- Request Timestamp: Wed, 05 Feb 2025 21:23:23 GMT

feat(market-map): Update market -- 146_1_0x7f24390ef4f8c1a372524ff1fa3a1d79d66d86ca

---

sdk/constants/market-map/1/definitions/1_1_0x470fa30720ab37a46119c81f6e0c3cdf4c476faa.ts

feat(market-map): Update market -- 1_1_0x470fa30720ab37a46119c81f6e0c3cdf4c476faa -- Vault (0x470f...6faa)
- Chain ID: 1
- Market ID: 0x470fa30720ab37a46119c81f6e0c3cdf4c476faa (Wrapped Vault Address)
- Request Timestamp: Wed, 05 Feb 2025 21:30:22 GMT

feat(market-map): Update market -- 1_1_0x470fa30720ab37a46119c81f6e0c3cdf4c476faa

---

sdk/constants/market-map/8453/definitions/8453_1_0x28b5f996e5aaf9e44d9a80743486573661317b1a.ts

feat(market-map): Update market -- 8453_1_0x28b5f996e5aaf9e44d9a80743486573661317b1a -- Vault (0x28b5...7b1a)
- Market ID: 0x28b5f996e5aaf9e44d9a80743486573661317b1a (Wrapped Vault Address)
- Request Timestamp: Wed, 05 Feb 2025 21:33:17 GMT

feat(market-map): Update market -- 8453_1_0x28b5f996e5aaf9e44d9a80743486573661317b1a

---

sdk/boyco/bera-yield/manage-bera-apy.tsx

Fixes bucket multipliers for majors + third party

fix: update bucket multipliers

---

sdk/constants/market-map/1/definitions/1_1_0x373ad427eb579133da3061d50b007f04f4cd1d59.ts

feat(market-map): Update market -- 1_1_0x373ad427eb579133da3061d50b007f04f4cd1d59 -- Vault (0x373a...1d59)
- Chain ID: 1
- Market ID: 0x373ad427eb579133da3061d50b007f04f4cd1d59 (Wrapped Vault Address)
- Request Timestamp: Thu, 13 Feb 2025 18:47:42 GMT

feat(market-map): Update market -- 1_1_0x373ad427eb579133da3061d50b007f04f4cd1d59

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x46d19eb8ef2abf31a609931354efd5b29d29f8223e608d700bfd680807161a4e.ts

feat(market-map): Update market -- 11155111_0_0x46d19eb8ef2abf31a609931354efd5b29d29f8223e608d700bfd680807161a4e -- Recipe (0x46d1...1a4e)
- Market ID: 0x46d19eb8ef2abf31a609931354efd5b29d29f8223e608d700bfd680807161a4e (Market Hash)
- Request Timestamp: Tue, 18 Feb 2025 17:20:02 GMT

feat(market-map): Update market -- 11155111_0_0x46d19eb8ef2abf31a609931354efd5b29d29f8223e608d700bfd680807161a4e

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xe2c26e9779e1cb3da128a4d310caff5c2c5202dca590a578fd90c5cb4e34cc53.ts

feat(market-map): Update market -- 11155111_0_0xe2c26e9779e1cb3da128a4d310caff5c2c5202dca590a578fd90c5cb4e34cc53 -- Recipe (0xe2c2...cc53)
- Market ID: 0xe2c26e9779e1cb3da128a4d310caff5c2c5202dca590a578fd90c5cb4e34cc53 (Market Hash)
- Request Timestamp: Tue, 18 Feb 2025 17:24:41 GMT

feat(market-map): Update market -- 11155111_0_0xe2c26e9779e1cb3da128a4d310caff5c2c5202dca590a578fd90c5cb4e34cc53

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x4cd04879c1c60a81c419d23fb77ceef697dde8d87f26f8dfd89de5e32d632a56.ts

feat(market-map): Update market -- 11155111_0_0x4cd04879c1c60a81c419d23fb77ceef697dde8d87f26f8dfd89de5e32d632a56 -- Recipe (0x4cd0...2a56)
- Market ID: 0x4cd04879c1c60a81c419d23fb77ceef697dde8d87f26f8dfd89de5e32d632a56 (Market Hash)
- Request Timestamp: Tue, 18 Feb 2025 19:03:07 GMT

feat(market-map): Update market -- 11155111_0_0x4cd04879c1c60a81c419d23fb77ceef697dde8d87f26f8dfd89de5e32d632a56

---

sdk/constants/market-map/146/definitions/146_1_0x7f24390ef4f8c1a372524ff1fa3a1d79d66d86ca.ts

On the test site it shows double yield. This should fix that.

fix misunderstood implementation of Origin Sonic (OS) yield

---

sdk/constants/market-map/146/definitions/146_0_0x6adba8ef01b34eee49d9f5545a9bf760c69626309a5f74bfedad5d366b3a8ab6.ts

feat(market-map): Update market -- 146_0_0x6adba8ef01b34eee49d9f5545a9bf760c69626309a5f74bfedad5d366b3a8ab6 -- Recipe (0x6adb...8ab6)
- Market ID: 0x6adba8ef01b34eee49d9f5545a9bf760c69626309a5f74bfedad5d366b3a8ab6 (Market Hash)
- Request Timestamp: Thu, 20 Feb 2025 11:18:08 GMT

feat(market-map): Update market -- 146_0_0x6adba8ef01b34eee49d9f5545a9bf760c69626309a5f74bfedad5d366b3a8ab6

---

sdk/constants/market-map/146/definitions/146_0_0x60ef118e2ce3f925a01d2ce6131cf97956e16d5296ec99da21d2ebdad9f5c35d.ts

feat(market-map): Update market -- 146_0_0x60ef118e2ce3f925a01d2ce6131cf97956e16d5296ec99da21d2ebdad9f5c35d -- Recipe (0x60ef...c35d)
- Market ID: 0x60ef118e2ce3f925a01d2ce6131cf97956e16d5296ec99da21d2ebdad9f5c35d (Market Hash)
- Request Timestamp: Thu, 20 Feb 2025 12:42:03 GMT

feat(market-map): Update market -- 146_0_0x60ef118e2ce3f925a01d2ce6131cf97956e16d5296ec99da21d2ebdad9f5c35d

---

sdk/constants/market-map/146/definitions/146_0_0x7720dcecb2918f4ad0554d883f552800609d3443dd79d73dadf4219c2cd1168d.ts

feat(market-map): Update market -- 146_0_0x7720dcecb2918f4ad0554d883f552800609d3443dd79d73dadf4219c2cd1168d -- Recipe (0x7720...168d)
- Market ID: 0x7720dcecb2918f4ad0554d883f552800609d3443dd79d73dadf4219c2cd1168d (Market Hash)
- Request Timestamp: Sun, 23 Feb 2025 08:00:27 GMT

feat(market-map): Update market -- 146_0_0x7720dcecb2918f4ad0554d883f552800609d3443dd79d73dadf4219c2cd1168d

---

sdk/constants/market-map/146/definitions/146_0_0x99edd3f2f47d6097d77699cf4e1ec0a32efb7965c8b1c08bc867608f2b6fd3e5.ts

feat(market-map): Update market -- 146_0_0x99edd3f2f47d6097d77699cf4e1ec0a32efb7965c8b1c08bc867608f2b6fd3e5 -- Recipe (0x99ed...d3e5)
- Market ID: 0x99edd3f2f47d6097d77699cf4e1ec0a32efb7965c8b1c08bc867608f2b6fd3e5 (Market Hash)
- Request Timestamp: Sun, 23 Feb 2025 08:04:54 GMT

feat(market-map): Update market -- 146_0_0x99edd3f2f47d6097d77699cf4e1ec0a32efb7965c8b1c08bc867608f2b6fd3e5

---

sdk/constants/market-map/146/definitions/146_0_0xfcf80cdd03f18c665bbb19f547b63200dcf15a60267b096c4ec43548b9aada09.ts

feat(market-map): Update market -- 146_0_0xfcf80cdd03f18c665bbb19f547b63200dcf15a60267b096c4ec43548b9aada09 -- Recipe (0xfcf8...da09)
- Market ID: 0xfcf80cdd03f18c665bbb19f547b63200dcf15a60267b096c4ec43548b9aada09 (Market Hash)
- Request Timestamp: Sun, 23 Feb 2025 08:06:15 GMT

feat(market-map): Update market -- 146_0_0xfcf80cdd03f18c665bbb19f547b63200dcf15a60267b096c4ec43548b9aada09

---

sdk/constants/market-map/146/definitions/146_0_0xabe64886c51ae566fe648b132f0f53f31aff6fb531c464eb3630931e139aed98.ts

feat(market-map): Update market -- 146_0_0xabe64886c51ae566fe648b132f0f53f31aff6fb531c464eb3630931e139aed98 -- Recipe (0xabe6...ed98)
- Market ID: 0xabe64886c51ae566fe648b132f0f53f31aff6fb531c464eb3630931e139aed98 (Market Hash)
- Request Timestamp: Sun, 23 Feb 2025 08:07:54 GMT

feat(market-map): Update market -- 146_0_0xabe64886c51ae566fe648b132f0f53f31aff6fb531c464eb3630931e139aed98

---

sdk/constants/market-map/146/definitions/146_0_0x2f9dabe1388e41ce534c649dfa6bb7fc4293219b422ec3a654663d0f2f181604.ts

feat(market-map): Update market -- 146_0_0x2f9dabe1388e41ce534c649dfa6bb7fc4293219b422ec3a654663d0f2f181604 -- Recipe (0x2f9d...1604)
- Market ID: 0x2f9dabe1388e41ce534c649dfa6bb7fc4293219b422ec3a654663d0f2f181604 (Market Hash)
- Request Timestamp: Sun, 23 Feb 2025 21:22:32 GMT

feat(market-map): Update market -- 146_0_0x2f9dabe1388e41ce534c649dfa6bb7fc4293219b422ec3a654663d0f2f181604

---

sdk/constants/market-map/146/definitions/146_0_0x2e8fb605f1e044b8a6bc9f0db673b92b6815b5333508e62b85de7e2ff44199a8.ts

feat(market-map): Update market -- 146_0_0x2e8fb605f1e044b8a6bc9f0db673b92b6815b5333508e62b85de7e2ff44199a8 -- Recipe (0x2e8f...99a8)
- Market ID: 0x2e8fb605f1e044b8a6bc9f0db673b92b6815b5333508e62b85de7e2ff44199a8 (Market Hash)
- Request Timestamp: Sun, 23 Feb 2025 21:25:41 GMT

feat(market-map): Update market -- 146_0_0x2e8fb605f1e044b8a6bc9f0db673b92b6815b5333508e62b85de7e2ff44199a8

---

sdk/constants/market-map/146/definitions/146_0_0x74634bc836c8c44e39b87ae656db006d36a6d4e3d618eabb2fabf668960168cf.ts

feat(market-map): Update market -- 146_0_0x74634bc836c8c44e39b87ae656db006d36a6d4e3d618eabb2fabf668960168cf -- Recipe (0x7463...68cf)
- Market ID: 0x74634bc836c8c44e39b87ae656db006d36a6d4e3d618eabb2fabf668960168cf (Market Hash)
- Request Timestamp: Sun, 23 Feb 2025 21:27:35 GMT

feat(market-map): Update market -- 146_0_0x74634bc836c8c44e39b87ae656db006d36a6d4e3d618eabb2fabf668960168cf

---

sdk/constants/market-map/146/definitions/146_0_0x38e23d90004295763e6ca3c02aa15de17dd7c2b3cbb16e6ce1e52f3b68dea552.ts

feat(market-map): Update market -- 146_0_0x38e23d90004295763e6ca3c02aa15de17dd7c2b3cbb16e6ce1e52f3b68dea552 -- Recipe (0x38e2...a552)
- Market ID: 0x38e23d90004295763e6ca3c02aa15de17dd7c2b3cbb16e6ce1e52f3b68dea552 (Market Hash)
- Request Timestamp: Sun, 23 Feb 2025 21:29:23 GMT

feat(market-map): Update market -- 146_0_0x38e23d90004295763e6ca3c02aa15de17dd7c2b3cbb16e6ce1e52f3b68dea552

---

sdk/constants/market-map/146/definitions/146_0_0x2e8fb605f1e044b8a6bc9f0db673b92b6815b5333508e62b85de7e2ff44199a8.ts
sdk/constants/market-map/146/definitions/146_0_0x2f9dabe1388e41ce534c649dfa6bb7fc4293219b422ec3a654663d0f2f181604.ts
sdk/constants/market-map/146/definitions/146_0_0x38e23d90004295763e6ca3c02aa15de17dd7c2b3cbb16e6ce1e52f3b68dea552.ts
sdk/constants/market-map/146/definitions/146_0_0x74634bc836c8c44e39b87ae656db006d36a6d4e3d618eabb2fabf668960168cf.ts
sdk/constants/token-map/146/definitions/146-0x0fa31f0d5a574F083E0be272a6CF807270352b3f.ts
sdk/constants/token-map/146/definitions/146-0xe16bb6061b3567ee86285ab7780187cb39acc55e.ts

Notes: Please check PT-wOS and PT-stS, since the incentives there are points, not tokens, i did not add the token_id

feat: stable jack incentives

---

sdk/constants/market-map/1/definitions/1_0_0x051d7d77b432ddce4e30bf12450132b44850ccbbc930b5b03c32579c6ab7dc3e.ts

feat(market-map): Update market -- 1_0_0x051d7d77b432ddce4e30bf12450132b44850ccbbc930b5b03c32579c6ab7dc3e -- Recipe (0x051d...dc3e)
- Chain ID: 1
- Market ID: 0x051d7d77b432ddce4e30bf12450132b44850ccbbc930b5b03c32579c6ab7dc3e (Market Hash)
- Request Timestamp: Mon, 24 Feb 2025 18:42:44 GMT

feat(market-map): Update market -- 1_0_0x051d7d77b432ddce4e30bf12450132b44850ccbbc930b5b03c32579c6ab7dc3e

---

sdk/constants/market-map/146/definitions/146_0_0x7fd0cedaa22a0cc3ef500acd2e3f1f4d4bfa6e13cee075ee53ac6129a290519a.ts

feat(market-map): Update market -- 146_0_0x7fd0cedaa22a0cc3ef500acd2e3f1f4d4bfa6e13cee075ee53ac6129a290519a -- Recipe (0x7fd0...519a)
- Market ID: 0x7fd0cedaa22a0cc3ef500acd2e3f1f4d4bfa6e13cee075ee53ac6129a290519a (Market Hash)
- Request Timestamp: Tue, 25 Feb 2025 08:08:47 GMT

feat(market-map): Update market -- 146_0_0x7fd0cedaa22a0cc3ef500acd2e3f1f4d4bfa6e13cee075ee53ac6129a290519a

---

sdk/constants/market-map/146/definitions/146_0_0x3886db0b10927d63ff2b8132879adf2c2b20ece04c77bcb06087eed08980c059.ts

feat(market-map): Update market -- 146_0_0x3886db0b10927d63ff2b8132879adf2c2b20ece04c77bcb06087eed08980c059 -- Recipe (0x3886...c059)
- Market ID: 0x3886db0b10927d63ff2b8132879adf2c2b20ece04c77bcb06087eed08980c059 (Market Hash)
- Request Timestamp: Tue, 25 Feb 2025 08:21:45 GMT

feat(market-map): Update market -- 146_0_0x3886db0b10927d63ff2b8132879adf2c2b20ece04c77bcb06087eed08980c059

---

sdk/constants/market-map/146/definitions/146_0_0x4ff251baadb17e754b09b625eddd4f3f79b689933c1c699d53aa4f7c89f2524c.ts

feat(market-map): Update market -- 146_0_0x4ff251baadb17e754b09b625eddd4f3f79b689933c1c699d53aa4f7c89f2524c -- Recipe (0x4ff2...524c)
- Market ID: 0x4ff251baadb17e754b09b625eddd4f3f79b689933c1c699d53aa4f7c89f2524c (Market Hash)
- Request Timestamp: Tue, 25 Feb 2025 14:46:03 GMT

feat(market-map): Update market -- 146_0_0x4ff251baadb17e754b09b625eddd4f3f79b689933c1c699d53aa4f7c89f2524c

---

sdk/constants/market-map/146/definitions/146_0_0xcef231a25fb93120b9f666d4b929bc1eea4efe4483ba10986ae1c2b11e39f152.ts

feat(market-map): Update market -- 146_0_0xcef231a25fb93120b9f666d4b929bc1eea4efe4483ba10986ae1c2b11e39f152 -- Recipe (0xcef2...f152)
- Market ID: 0xcef231a25fb93120b9f666d4b929bc1eea4efe4483ba10986ae1c2b11e39f152 (Market Hash)
- Request Timestamp: Tue, 25 Feb 2025 16:30:23 GMT

feat(market-map): Update market -- 146_0_0xcef231a25fb93120b9f666d4b929bc1eea4efe4483ba10986ae1c2b11e39f152

---

sdk/constants/market-map/146/definitions/146_0_0xf7ba3090764666145e0ccfe50e5c41b9c3d453d6c31edb0a1e28dfe504bd4ca8.ts

feat(market-map): Update market -- 146_0_0xf7ba3090764666145e0ccfe50e5c41b9c3d453d6c31edb0a1e28dfe504bd4ca8 -- Recipe (0xf7ba...4ca8)
- Market ID: 0xf7ba3090764666145e0ccfe50e5c41b9c3d453d6c31edb0a1e28dfe504bd4ca8 (Market Hash)
- Request Timestamp: Tue, 25 Feb 2025 17:56:33 GMT

feat(market-map): Update market -- 146_0_0xf7ba3090764666145e0ccfe50e5c41b9c3d453d6c31edb0a1e28dfe504bd4ca8

---

sdk/constants/market-map/146/definitions/146_0_0xa72eaff7b5b5e5a0b36fc628984241433baf863d3f1d19deddfcddab053e95bd.ts

feat(market-map): Update market -- 146_0_0xa72eaff7b5b5e5a0b36fc628984241433baf863d3f1d19deddfcddab053e95bd -- Recipe (0xa72e...95bd)
- Market ID: 0xa72eaff7b5b5e5a0b36fc628984241433baf863d3f1d19deddfcddab053e95bd (Market Hash)
- Request Timestamp: Tue, 25 Feb 2025 20:42:16 GMT

feat(market-map): Update market -- 146_0_0xa72eaff7b5b5e5a0b36fc628984241433baf863d3f1d19deddfcddab053e95bd

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x9597896a7208d4b6ae9d7ce3fcdba522213762becd1c0ae95f3ff9bf500fdab2.ts

feat(market-map): Update market -- 11155111_0_0x9597896a7208d4b6ae9d7ce3fcdba522213762becd1c0ae95f3ff9bf500fdab2 -- Recipe (0x9597...dab2)
- Market ID: 0x9597896a7208d4b6ae9d7ce3fcdba522213762becd1c0ae95f3ff9bf500fdab2 (Market Hash)
- Request Timestamp: Tue, 25 Feb 2025 22:47:17 GMT

feat(market-map): Update market -- 11155111_0_0x9597896a7208d4b6ae9d7ce3fcdba522213762becd1c0ae95f3ff9bf500fdab2

---

sdk/constants/market-map/146/definitions/146_0_0x0a019f1b709d5b3afc96fded1850545f40f1d4431ea6cc041983833904788c78.ts

feat(market-map): Update market -- 146_0_0x0a019f1b709d5b3afc96fded1850545f40f1d4431ea6cc041983833904788c78 -- Recipe (0x0a01...8c78)
- Market ID: 0x0a019f1b709d5b3afc96fded1850545f40f1d4431ea6cc041983833904788c78 (Market Hash)
- Request Timestamp: Tue, 25 Feb 2025 22:48:22 GMT

feat(market-map): Update market -- 146_0_0x0a019f1b709d5b3afc96fded1850545f40f1d4431ea6cc041983833904788c78

---

sdk/constants/market-map/146/definitions/146_0_0xb595ee1ce1ed0cb227c4dff793621845baf4d907bc60264349d5e975188ba5c2.ts

feat(market-map): Update market -- 146_0_0xb595ee1ce1ed0cb227c4dff793621845baf4d907bc60264349d5e975188ba5c2 -- Recipe (0xb595...a5c2)
- Market ID: 0xb595ee1ce1ed0cb227c4dff793621845baf4d907bc60264349d5e975188ba5c2 (Market Hash)
- Request Timestamp: Thu, 27 Feb 2025 21:24:51 GMT

feat(market-map): Update market -- 146_0_0xb595ee1ce1ed0cb227c4dff793621845baf4d907bc60264349d5e975188ba5c2

---

sdk/constants/market-map/146/definitions/146_0_0x30f002e2f62bc4155d273b9745b5b40863b7ce80ec9f861ba08ca3e33f9e549c.ts

feat(market-map): Update market -- 146_0_0x30f002e2f62bc4155d273b9745b5b40863b7ce80ec9f861ba08ca3e33f9e549c -- Recipe (0x30f0...549c)
- Market ID: 0x30f002e2f62bc4155d273b9745b5b40863b7ce80ec9f861ba08ca3e33f9e549c (Market Hash)
- Request Timestamp: Thu, 27 Feb 2025 21:30:35 GMT

feat(market-map): Update market -- 146_0_0x30f002e2f62bc4155d273b9745b5b40863b7ce80ec9f861ba08ca3e33f9e549c

---

sdk/constants/market-map/146/definitions/146_0_0x4c3c6946186992f776e9ddff186e0cedcbadbfb95fbe3d31f6f2b0f2d287253a.ts

feat(market-map): Update market -- 146_0_0x4c3c6946186992f776e9ddff186e0cedcbadbfb95fbe3d31f6f2b0f2d287253a -- Recipe (0x4c3c...253a)
- Market ID: 0x4c3c6946186992f776e9ddff186e0cedcbadbfb95fbe3d31f6f2b0f2d287253a (Market Hash)
- Request Timestamp: Thu, 27 Feb 2025 21:33:51 GMT

feat(market-map): Update market -- 146_0_0x4c3c6946186992f776e9ddff186e0cedcbadbfb95fbe3d31f6f2b0f2d287253a

---

sdk/constants/market-map/146/definitions/146_0_0x0d7700e96d3bea53eb4d4271d02ff798e505b808afd646ea677ba1bb3843d8f5.ts

feat(market-map): Update market -- 146_0_0x0d7700e96d3bea53eb4d4271d02ff798e505b808afd646ea677ba1bb3843d8f5 -- Recipe (0x0d77...d8f5)
- Market ID: 0x0d7700e96d3bea53eb4d4271d02ff798e505b808afd646ea677ba1bb3843d8f5 (Market Hash)
- Request Timestamp: Thu, 27 Feb 2025 21:36:29 GMT

feat(market-map): Update market -- 146_0_0x0d7700e96d3bea53eb4d4271d02ff798e505b808afd646ea677ba1bb3843d8f5

---

sdk/constants/market-map/146/definitions/146_0_0xa617b6fa04e006f79053160f4c6d531a2285a1c7f685eea02d4b9545b4ea58a1.ts

feat(market-map): Update market -- 146_0_0xa617b6fa04e006f79053160f4c6d531a2285a1c7f685eea02d4b9545b4ea58a1 -- Recipe (0xa617...58a1)
- Market ID: 0xa617b6fa04e006f79053160f4c6d531a2285a1c7f685eea02d4b9545b4ea58a1 (Market Hash)
- Request Timestamp: Fri, 28 Feb 2025 05:50:19 GMT

feat(market-map): Update market -- 146_0_0xa617b6fa04e006f79053160f4c6d531a2285a1c7f685eea02d4b9545b4ea58a1

---

sdk/constants/market-map/146/definitions/146_0_0xe896bc4f98e677d6c4e0c146e3cce74c3f152db7023f85b1131c0ee91a89fff1.ts

feat(market-map): Update market -- 146_0_0xe896bc4f98e677d6c4e0c146e3cce74c3f152db7023f85b1131c0ee91a89fff1 -- Recipe (0xe896...fff1)
- Market ID: 0xe896bc4f98e677d6c4e0c146e3cce74c3f152db7023f85b1131c0ee91a89fff1 (Market Hash)
- Request Timestamp: Fri, 28 Feb 2025 05:53:48 GMT

feat(market-map): Update market -- 146_0_0xe896bc4f98e677d6c4e0c146e3cce74c3f152db7023f85b1131c0ee91a89fff1

---

sdk/constants/market-map/146/definitions/146_0_0xae9d3aea56a5214f8f2488359eeaf6c9b9e518138a070e8dc635a4e4031f144b.ts

feat(market-map): Update market -- 146_0_0xae9d3aea56a5214f8f2488359eeaf6c9b9e518138a070e8dc635a4e4031f144b -- Recipe (0xae9d...144b)
- Market ID: 0xae9d3aea56a5214f8f2488359eeaf6c9b9e518138a070e8dc635a4e4031f144b (Market Hash)
- Request Timestamp: Fri, 28 Feb 2025 08:02:15 GMT

feat(market-map): Update market -- 146_0_0xae9d3aea56a5214f8f2488359eeaf6c9b9e518138a070e8dc635a4e4031f144b

---

sdk/constants/market-map/146/definitions/146_0_0x19f6cd41b19e30ff21883905b0aa4a65f09d83aa0877b03e2d9ad7521c005bc3.ts

feat(market-map): Update market -- 146_0_0x19f6cd41b19e30ff21883905b0aa4a65f09d83aa0877b03e2d9ad7521c005bc3 -- Recipe (0x19f6...5bc3)
- Market ID: 0x19f6cd41b19e30ff21883905b0aa4a65f09d83aa0877b03e2d9ad7521c005bc3 (Market Hash)
- Request Timestamp: Fri, 28 Feb 2025 08:03:07 GMT

feat(market-map): Update market -- 146_0_0x19f6cd41b19e30ff21883905b0aa4a65f09d83aa0877b03e2d9ad7521c005bc3

---

sdk/constants/market-map/146/definitions/146_0_0x95e6b9cb4070855d188efc4799c75e37b7615112269d1ab7db98e234c61ed04d.ts

feat(market-map): Update market -- 146_0_0x95e6b9cb4070855d188efc4799c75e37b7615112269d1ab7db98e234c61ed04d -- Recipe (0x95e6...d04d)
- Market ID: 0x95e6b9cb4070855d188efc4799c75e37b7615112269d1ab7db98e234c61ed04d (Market Hash)
- Request Timestamp: Fri, 28 Feb 2025 08:27:48 GMT

feat(market-map): Update market -- 146_0_0x95e6b9cb4070855d188efc4799c75e37b7615112269d1ab7db98e234c61ed04d

---

sdk/constants/market-map/146/definitions/146_0_0x76f6ee6e67eb13e428390f88f0df57326c15a1344e751548af67b743d41643c1.ts

feat(market-map): Update market -- 146_0_0x76f6ee6e67eb13e428390f88f0df57326c15a1344e751548af67b743d41643c1 -- Recipe (0x76f6...43c1)
- Market ID: 0x76f6ee6e67eb13e428390f88f0df57326c15a1344e751548af67b743d41643c1 (Market Hash)
- Request Timestamp: Fri, 28 Feb 2025 08:28:50 GMT

feat(market-map): Update market -- 146_0_0x76f6ee6e67eb13e428390f88f0df57326c15a1344e751548af67b743d41643c1

---

sdk/constants/market-map/146/definitions/146_0_0xd4fa0b3746229598ed47afb12ab9900c8ab295f50ea94a9e1f5461c697210054.ts

feat(market-map): Update market -- 146_0_0xd4fa0b3746229598ed47afb12ab9900c8ab295f50ea94a9e1f5461c697210054 -- Recipe (0xd4fa...0054)
- Market ID: 0xd4fa0b3746229598ed47afb12ab9900c8ab295f50ea94a9e1f5461c697210054 (Market Hash)
- Request Timestamp: Fri, 28 Feb 2025 08:49:06 GMT

feat(market-map): Update market -- 146_0_0xd4fa0b3746229598ed47afb12ab9900c8ab295f50ea94a9e1f5461c697210054

---

sdk/constants/market-map/146/definitions/146_0_0x0d7700e96d3bea53eb4d4271d02ff798e505b808afd646ea677ba1bb3843d8f5.ts
sdk/constants/market-map/146/definitions/146_0_0x30f002e2f62bc4155d273b9745b5b40863b7ce80ec9f861ba08ca3e33f9e549c.ts
sdk/constants/market-map/146/definitions/146_0_0x4c3c6946186992f776e9ddff186e0cedcbadbfb95fbe3d31f6f2b0f2d287253a.ts
sdk/constants/market-map/146/definitions/146_0_0xa617b6fa04e006f79053160f4c6d531a2285a1c7f685eea02d4b9545b4ea58a1.ts
sdk/constants/market-map/146/definitions/146_0_0xb595ee1ce1ed0cb227c4dff793621845baf4d907bc60264349d5e975188ba5c2.ts
sdk/constants/market-map/146/definitions/146_0_0xe896bc4f98e677d6c4e0c146e3cce74c3f152db7023f85b1131c0ee91a89fff1.ts
sdk/constants/token-map/146/definitions/146-0xab8898b840b681cd406aa53ad5d1c167178441c7.ts
sdk/constants/token-map/146/definitions/146-0xbb9beb82ebf43d02d3a3f4fd431906d1e39a117d.ts
sdk/constants/token-map/146/definitions/146-0xd2901d474b351bc6ee7b119f9c920863b0f781b2.ts

added markets:
- stS
- wOS
- scUSD

feat: stablejack

---

sdk/constants/market-map/146/definitions/146_0_0x87b970690fd03360f97e6aaba20e0b6e2a42148a20b7c7406115aec18ab8747a.ts

feat(market-map): Update market -- 146_0_0x87b970690fd03360f97e6aaba20e0b6e2a42148a20b7c7406115aec18ab8747a -- Recipe (0x87b9...747a)
- Market ID: 0x87b970690fd03360f97e6aaba20e0b6e2a42148a20b7c7406115aec18ab8747a (Market Hash)
- Request Timestamp: Sat, 01 Mar 2025 15:10:15 GMT

feat(market-map): Update market -- 146_0_0x87b970690fd03360f97e6aaba20e0b6e2a42148a20b7c7406115aec18ab8747a

---

sdk/constants/market-map/146/definitions/146_0_0x5d17756540f85c4a9c5fb1bf0a3451b497ac767b1188b5be39227d2cdf430f70.ts

feat(market-map): Update market -- 146_0_0x5d17756540f85c4a9c5fb1bf0a3451b497ac767b1188b5be39227d2cdf430f70 -- Recipe (0x5d17...0f70)
- Market ID: 0x5d17756540f85c4a9c5fb1bf0a3451b497ac767b1188b5be39227d2cdf430f70 (Market Hash)
- Request Timestamp: Sat, 01 Mar 2025 15:11:36 GMT

feat(market-map): Update market -- 146_0_0x5d17756540f85c4a9c5fb1bf0a3451b497ac767b1188b5be39227d2cdf430f70

---

sdk/constants/market-map/146/definitions/146_0_0x14ad21876c8f9807422fb549f11c65856543ec96a7b67d8302aeb72facc2bca6.ts

feat(market-map): Update market -- 146_0_0x14ad21876c8f9807422fb549f11c65856543ec96a7b67d8302aeb72facc2bca6 -- Recipe (0x14ad...bca6)
- Market ID: 0x14ad21876c8f9807422fb549f11c65856543ec96a7b67d8302aeb72facc2bca6 (Market Hash)
- Request Timestamp: Sat, 01 Mar 2025 15:12:51 GMT

feat(market-map): Update market -- 146_0_0x14ad21876c8f9807422fb549f11c65856543ec96a7b67d8302aeb72facc2bca6

---

sdk/constants/market-map/146/definitions/146_0_0x7d1f2a66eabf9142dd30d1355efcbfd4cfbefd2872d24ca9855641434816a525.ts

feat(market-map): Update market -- 146_0_0x7d1f2a66eabf9142dd30d1355efcbfd4cfbefd2872d24ca9855641434816a525 -- Recipe (0x7d1f...a525)
- Market ID: 0x7d1f2a66eabf9142dd30d1355efcbfd4cfbefd2872d24ca9855641434816a525 (Market Hash)
- Request Timestamp: Sun, 02 Mar 2025 20:06:59 GMT

feat(market-map): Update market -- 146_0_0x7d1f2a66eabf9142dd30d1355efcbfd4cfbefd2872d24ca9855641434816a525

---

sdk/constants/market-map/146/definitions/146_0_0x4db7f85fc602e994e4043b98abecfeda8acab06bcc186ab266a07a508c8fc92f.ts

feat(market-map): Update market -- 146_0_0x4db7f85fc602e994e4043b98abecfeda8acab06bcc186ab266a07a508c8fc92f -- Recipe (0x4db7...c92f)
- Market ID: 0x4db7f85fc602e994e4043b98abecfeda8acab06bcc186ab266a07a508c8fc92f (Market Hash)
- Request Timestamp: Sun, 02 Mar 2025 21:39:43 GMT

feat(market-map): Update market -- 146_0_0x4db7f85fc602e994e4043b98abecfeda8acab06bcc186ab266a07a508c8fc92f

---

sdk/constants/market-map/146/definitions/146_0_0xb5f162c88950f16ff2870e8d035ad6f808eb88b0fe367edf3a76a209776f9852.ts

feat(market-map): Update market -- 146_0_0xb5f162c88950f16ff2870e8d035ad6f808eb88b0fe367edf3a76a209776f9852 -- Recipe (0xb5f1...9852)
- Market ID: 0xb5f162c88950f16ff2870e8d035ad6f808eb88b0fe367edf3a76a209776f9852 (Market Hash)
- Request Timestamp: Sun, 02 Mar 2025 21:43:38 GMT

feat(market-map): Update market -- 146_0_0xb5f162c88950f16ff2870e8d035ad6f808eb88b0fe367edf3a76a209776f9852

---

sdk/constants/market-map/146/definitions/146_0_0x1fb4fbd6970656419f697476644aa82cfea979be4620da2bf09dd204456722b8.ts

feat(market-map): Update market -- 146_0_0x1fb4fbd6970656419f697476644aa82cfea979be4620da2bf09dd204456722b8 -- Recipe (0x1fb4...22b8)
- Market ID: 0x1fb4fbd6970656419f697476644aa82cfea979be4620da2bf09dd204456722b8 (Market Hash)
- Request Timestamp: Mon, 03 Mar 2025 14:17:24 GMT

feat(market-map): Update market -- 146_0_0x1fb4fbd6970656419f697476644aa82cfea979be4620da2bf09dd204456722b8

---

package.json
sdk/provider/RoycoProvider.tsx
sdk/sonic/sonic-market-map.tsx
sdk/sonic/sonic-points-map.tsx

Reverts roycoprotocol/royco-sdk#635

Revert "fix: update sonic market map"

---

sdk/constants/market-map/146/definitions/146_0_0xd355d633abacb9617e31c71fd21c68b224357850522defab3dfb8d6932d5cc11.ts

feat(market-map): Update market -- 146_0_0xd355d633abacb9617e31c71fd21c68b224357850522defab3dfb8d6932d5cc11 -- Recipe (0xd355...cc11)
- Market ID: 0xd355d633abacb9617e31c71fd21c68b224357850522defab3dfb8d6932d5cc11 (Market Hash)
- Request Timestamp: Wed, 05 Mar 2025 09:33:53 GMT

feat(market-map): Update market -- 146_0_0xd355d633abacb9617e31c71fd21c68b224357850522defab3dfb8d6932d5cc11

---

sdk/constants/market-map/146/definitions/146_0_0x66166f2eab76626cb9763d9616b055c6e0efdbef52744dc146b79a600789dbb4.ts

feat(market-map): Update market -- 146_0_0x66166f2eab76626cb9763d9616b055c6e0efdbef52744dc146b79a600789dbb4 -- Recipe (0x6616...dbb4)
- Market ID: 0x66166f2eab76626cb9763d9616b055c6e0efdbef52744dc146b79a600789dbb4 (Market Hash)
- Request Timestamp: Wed, 05 Mar 2025 23:01:17 GMT

feat(market-map): Update market -- 146_0_0x66166f2eab76626cb9763d9616b055c6e0efdbef52744dc146b79a600789dbb4

---

sdk/constants/market-map/146/definitions/146_0_0xe589ebb349720b6166b68d92fd01447ae8efa5b83c478ec466c929142e465b51.ts

feat(market-map): Update market -- 146_0_0xe589ebb349720b6166b68d92fd01447ae8efa5b83c478ec466c929142e465b51 -- Recipe (0xe589...5b51)
- Market ID: 0xe589ebb349720b6166b68d92fd01447ae8efa5b83c478ec466c929142e465b51 (Market Hash)
- Request Timestamp: Thu, 06 Mar 2025 10:54:48 GMT

feat(market-map): Update market -- 146_0_0xe589ebb349720b6166b68d92fd01447ae8efa5b83c478ec466c929142e465b51

---

sdk/constants/market-map/146/definitions/146_0_0xf88e5c4dc5a93102e0a2b8cd3d0ff1eb2c6e488d6edef7c72a5636843540b4f4.ts

feat(market-map): Update market -- 146_0_0xf88e5c4dc5a93102e0a2b8cd3d0ff1eb2c6e488d6edef7c72a5636843540b4f4 -- Recipe (0xf88e...b4f4)
- Market ID: 0xf88e5c4dc5a93102e0a2b8cd3d0ff1eb2c6e488d6edef7c72a5636843540b4f4 (Market Hash)
- Request Timestamp: Thu, 06 Mar 2025 18:14:06 GMT

feat(market-map): Update market -- 146_0_0xf88e5c4dc5a93102e0a2b8cd3d0ff1eb2c6e488d6edef7c72a5636843540b4f4

---

sdk/constants/market-map/8453/definitions/8453_1_0x38b2abdfb2fe79ad5e240fbd934a87b63038df5b.ts

feat(market-map): Update market -- 8453_1_0x38b2abdfb2fe79ad5e240fbd934a87b63038df5b -- Vault (0x38b2...df5b)
- Market ID: 0x38b2abdfb2fe79ad5e240fbd934a87b63038df5b (Wrapped Vault Address)
- Request Timestamp: Thu, 06 Mar 2025 18:23:07 GMT

feat(market-map): Update market -- 8453_1_0x38b2abdfb2fe79ad5e240fbd934a87b63038df5b

---

sdk/constants/market-map/146/definitions/146_0_0xfc54f53282763606c7cbf28db3490b9781c9bbb3ae228bd586b97926816e0244.ts

feat(market-map): Update market -- 146_0_0xfc54f53282763606c7cbf28db3490b9781c9bbb3ae228bd586b97926816e0244 -- Recipe (0xfc54...0244)
- Market ID: 0xfc54f53282763606c7cbf28db3490b9781c9bbb3ae228bd586b97926816e0244 (Market Hash)
- Request Timestamp: Thu, 06 Mar 2025 19:22:04 GMT

feat(market-map): Update market -- 146_0_0xfc54f53282763606c7cbf28db3490b9781c9bbb3ae228bd586b97926816e0244

---

sdk/constants/market-map/146/definitions/146_0_0x298704e61b0720d95aa73960722c07ab2387d4618b1a769124c157a1420699e1.ts

feat(market-map): Update market -- 146_0_0x298704e61b0720d95aa73960722c07ab2387d4618b1a769124c157a1420699e1 -- Recipe (0x2987...99e1)
- Market ID: 0x298704e61b0720d95aa73960722c07ab2387d4618b1a769124c157a1420699e1 (Market Hash)
- Request Timestamp: Fri, 07 Mar 2025 19:58:44 GMT

feat(market-map): Update market -- 146_0_0x298704e61b0720d95aa73960722c07ab2387d4618b1a769124c157a1420699e1

---

sdk/constants/market-map/146/definitions/146_0_0x43089e4f71ca768555542d3229de5a06b9f3ed25f5ba829ba105c0dadc1ea22f.ts

feat(market-map): Update market -- 146_0_0x43089e4f71ca768555542d3229de5a06b9f3ed25f5ba829ba105c0dadc1ea22f -- Recipe (0x4308...a22f)
- Market ID: 0x43089e4f71ca768555542d3229de5a06b9f3ed25f5ba829ba105c0dadc1ea22f (Market Hash)
- Request Timestamp: Fri, 07 Mar 2025 20:05:34 GMT

feat(market-map): Update market -- 146_0_0x43089e4f71ca768555542d3229de5a06b9f3ed25f5ba829ba105c0dadc1ea22f

---

sdk/constants/market-map/11155111/definitions/11155111_1_0xc64877aae6437c11c72880d0d61e9e81c2310a22.ts

feat(market-map): Update market -- 11155111_1_0xc64877aae6437c11c72880d0d61e9e81c2310a22 -- Vault (0xc648...0a22)
- Market ID: 0xc64877aae6437c11c72880d0d61e9e81c2310a22 (Wrapped Vault Address)
- Request Timestamp: Mon, 10 Mar 2025 09:21:18 GMT

feat(market-map): Update market -- 11155111_1_0xc64877aae6437c11c72880d0d61e9e81c2310a22

---

sdk/constants/market-map/146/definitions/146_0_0x1909c54081dda4ba39d7c18f53f1cdb34cb4f436557a5e82cb057d1355a0cd86.ts

feat(market-map): Update market -- 146_0_0x1909c54081dda4ba39d7c18f53f1cdb34cb4f436557a5e82cb057d1355a0cd86 -- Recipe (0x1909...cd86)
- Market ID: 0x1909c54081dda4ba39d7c18f53f1cdb34cb4f436557a5e82cb057d1355a0cd86 (Market Hash)
- Request Timestamp: Mon, 10 Mar 2025 23:29:02 GMT

feat(market-map): Update market -- 146_0_0x1909c54081dda4ba39d7c18f53f1cdb34cb4f436557a5e82cb057d1355a0cd86

---

sdk/constants/market-map/146/definitions/146_0_0xe3a13caa79517a6d37b4023c653f221f83b66c268741f78a97ccdbf10bd92703.ts

feat(market-map): Update market -- 146_0_0xe3a13caa79517a6d37b4023c653f221f83b66c268741f78a97ccdbf10bd92703 -- Recipe (0xe3a1...2703)
- Market ID: 0xe3a13caa79517a6d37b4023c653f221f83b66c268741f78a97ccdbf10bd92703 (Market Hash)
- Request Timestamp: Thu, 13 Mar 2025 20:02:21 GMT

feat(market-map): Update market -- 146_0_0xe3a13caa79517a6d37b4023c653f221f83b66c268741f78a97ccdbf10bd92703

---

sdk/constants/market-map/146/definitions/146_0_0xd994e3b26cf3b837c7029008d2b340462d58c9fc23669b39b009e4f903cd5248.ts

feat(market-map): Update market -- 146_0_0xd994e3b26cf3b837c7029008d2b340462d58c9fc23669b39b009e4f903cd5248 -- Recipe (0xd994...5248)
- Market ID: 0xd994e3b26cf3b837c7029008d2b340462d58c9fc23669b39b009e4f903cd5248 (Market Hash)
- Request Timestamp: Thu, 13 Mar 2025 20:26:15 GMT

feat(market-map): Update market -- 146_0_0xd994e3b26cf3b837c7029008d2b340462d58c9fc23669b39b009e4f903cd5248

---

sdk/constants/market-map/146/definitions/146_0_0x4bbb7d09032eec243b9a114b254c98160f8123795ee7f98a447c876d250cb89a.ts

feat(market-map): Update market -- 146_0_0x4bbb7d09032eec243b9a114b254c98160f8123795ee7f98a447c876d250cb89a -- Recipe (0x4bbb...b89a)
- Market ID: 0x4bbb7d09032eec243b9a114b254c98160f8123795ee7f98a447c876d250cb89a (Market Hash)
- Request Timestamp: Fri, 14 Mar 2025 01:24:48 GMT

feat(market-map): Update market -- 146_0_0x4bbb7d09032eec243b9a114b254c98160f8123795ee7f98a447c876d250cb89a

---

sdk/constants/market-map/146/definitions/146_0_0x4e20121fb62791362565365080088dbfa17680ec368f5fc49e801dac00f73f30.ts

feat(market-map): Update market -- 146_0_0x4e20121fb62791362565365080088dbfa17680ec368f5fc49e801dac00f73f30 -- Recipe (0x4e20...3f30)
- Market ID: 0x4e20121fb62791362565365080088dbfa17680ec368f5fc49e801dac00f73f30 (Market Hash)
- Request Timestamp: Fri, 14 Mar 2025 01:26:59 GMT

feat(market-map): Update market -- 146_0_0x4e20121fb62791362565365080088dbfa17680ec368f5fc49e801dac00f73f30

---

sdk/constants/market-map/146/definitions/146_0_0x6288f069f1626e2c49d3b92ddaf1911bf4576fe670e0798648f1d25beb5cb383.ts

feat(market-map): Update market -- 146_0_0x6288f069f1626e2c49d3b92ddaf1911bf4576fe670e0798648f1d25beb5cb383 -- Recipe (0x6288...b383)
- Market ID: 0x6288f069f1626e2c49d3b92ddaf1911bf4576fe670e0798648f1d25beb5cb383 (Market Hash)
- Request Timestamp: Fri, 14 Mar 2025 19:22:35 GMT

feat(market-map): Update market -- 146_0_0x6288f069f1626e2c49d3b92ddaf1911bf4576fe670e0798648f1d25beb5cb383

---

sdk/constants/market-map/42161/definitions/42161_0_0x425bf45476f7964e9c3df9d4ad1709c758ec5838c0edec2d3e34a34fce8294e0.ts

feat(market-map): Update market -- 42161_0_0x425bf45476f7964e9c3df9d4ad1709c758ec5838c0edec2d3e34a34fce8294e0 -- Recipe (0x425b...94e0)
- Market ID: 0x425bf45476f7964e9c3df9d4ad1709c758ec5838c0edec2d3e34a34fce8294e0 (Market Hash)
- Request Timestamp: Sat, 15 Mar 2025 00:56:44 GMT

feat(market-map): Update market -- 42161_0_0x425bf45476f7964e9c3df9d4ad1709c758ec5838c0edec2d3e34a34fce8294e0

---

sdk/constants/market-map/42161/definitions/42161_0_0xf7be9ccbe83741bc736f32233d48f395428d08ca9e1bef9921b09c1dfbd7c1ec.ts

feat(market-map): Update market -- 42161_0_0xf7be9ccbe83741bc736f32233d48f395428d08ca9e1bef9921b09c1dfbd7c1ec -- Recipe (0xf7be...c1ec)
- Market ID: 0xf7be9ccbe83741bc736f32233d48f395428d08ca9e1bef9921b09c1dfbd7c1ec (Market Hash)
- Request Timestamp: Sat, 15 Mar 2025 01:09:31 GMT

feat(market-map): Update market -- 42161_0_0xf7be9ccbe83741bc736f32233d48f395428d08ca9e1bef9921b09c1dfbd7c1ec

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xa8e8724b3d547e3710dd3b842e1c89b2b5f522a28565cf115715d4d5317aeaf8.ts

feat(market-map): Update market -- 11155111_0_0xa8e8724b3d547e3710dd3b842e1c89b2b5f522a28565cf115715d4d5317aeaf8 -- Recipe (0xa8e8...eaf8)
- Market ID: 0xa8e8724b3d547e3710dd3b842e1c89b2b5f522a28565cf115715d4d5317aeaf8 (Market Hash)
- Request Timestamp: Mon, 17 Mar 2025 04:35:05 GMT

feat(market-map): Update market -- 11155111_0_0xa8e8724b3d547e3710dd3b842e1c89b2b5f522a28565cf115715d4d5317aeaf8

---

sdk/constants/market-map/146/definitions/146_0_0xfe47f86e5193d910ab9f19486978c5ddceab4d457b6cd65acb44e604da05fd87.ts

feat(market-map): Update market -- 146_0_0xfe47f86e5193d910ab9f19486978c5ddceab4d457b6cd65acb44e604da05fd87 -- Recipe (0xfe47...fd87)
- Market ID: 0xfe47f86e5193d910ab9f19486978c5ddceab4d457b6cd65acb44e604da05fd87 (Market Hash)
- Request Timestamp: Wed, 19 Mar 2025 03:59:22 GMT

feat(market-map): Update market -- 146_0_0xfe47f86e5193d910ab9f19486978c5ddceab4d457b6cd65acb44e604da05fd87

---

sdk/constants/market-map/146/definitions/146_0_0xfcd798abefe4f9784e8f7ce3019c5e567e85687235ce0ce61c27271ba97d26cd.ts

feat(market-map): Update market -- 146_0_0xfcd798abefe4f9784e8f7ce3019c5e567e85687235ce0ce61c27271ba97d26cd -- Recipe (0xfcd7...26cd)
- Market ID: 0xfcd798abefe4f9784e8f7ce3019c5e567e85687235ce0ce61c27271ba97d26cd (Market Hash)
- Request Timestamp: Wed, 19 Mar 2025 21:38:22 GMT

feat(market-map): Update market -- 146_0_0xfcd798abefe4f9784e8f7ce3019c5e567e85687235ce0ce61c27271ba97d26cd

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x417188a6d62630edd2597ae4447721e89034bf42c15403029a74533993dd6604.ts

feat(market-map): Update market -- 11155111_0_0x417188a6d62630edd2597ae4447721e89034bf42c15403029a74533993dd6604 -- Recipe (0x4171...6604)
- Market ID: 0x417188a6d62630edd2597ae4447721e89034bf42c15403029a74533993dd6604 (Market Hash)
- Request Timestamp: Thu, 20 Mar 2025 18:18:17 GMT

feat(market-map): Update market -- 11155111_0_0x417188a6d62630edd2597ae4447721e89034bf42c15403029a74533993dd6604

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xe143142ecc85c74e399ca5bd4225f392e1b43f49b87d7ca6748a2f68cdbf683c.ts

feat(market-map): Update market -- 11155111_0_0xe143142ecc85c74e399ca5bd4225f392e1b43f49b87d7ca6748a2f68cdbf683c -- Recipe (0xe143...683c)
- Market ID: 0xe143142ecc85c74e399ca5bd4225f392e1b43f49b87d7ca6748a2f68cdbf683c (Market Hash)
- Request Timestamp: Thu, 20 Mar 2025 18:39:36 GMT

feat(market-map): Update market -- 11155111_0_0xe143142ecc85c74e399ca5bd4225f392e1b43f49b87d7ca6748a2f68cdbf683c

---

sdk/constants/market-map/1/definitions/1_0_0x4e77e290afd1bf6e7b440219634c39756210b421959e9e51b1a1d36ce7568744.ts

feat(market-map): Update market -- 1_0_0x4e77e290afd1bf6e7b440219634c39756210b421959e9e51b1a1d36ce7568744 -- Recipe (0x4e77...8744)
- Chain ID: 1
- Market ID: 0x4e77e290afd1bf6e7b440219634c39756210b421959e9e51b1a1d36ce7568744 (Market Hash)
- Request Timestamp: Thu, 20 Mar 2025 19:03:32 GMT

feat(market-map): Update market -- 1_0_0x4e77e290afd1bf6e7b440219634c39756210b421959e9e51b1a1d36ce7568744

---

sdk/constants/market-map/8453/definitions/8453_0_0x7633e2623cfa8c51e5e29734f03462781b15b22b15e5da540ce800204778c39f.ts

feat(market-map): Update market -- 8453_0_0x7633e2623cfa8c51e5e29734f03462781b15b22b15e5da540ce800204778c39f -- Recipe (0x7633...c39f)
- Market ID: 0x7633e2623cfa8c51e5e29734f03462781b15b22b15e5da540ce800204778c39f (Market Hash)
- Request Timestamp: Thu, 20 Mar 2025 19:31:04 GMT

feat(market-map): Update market -- 8453_0_0x7633e2623cfa8c51e5e29734f03462781b15b22b15e5da540ce800204778c39f

---

sdk/constants/market-map/98866/definitions/98866_0_0x709bcc976fd6be016b2904b9331ce5f70f64ebb5b66ee65be9569b9885a4a430.ts

feat(market-map): Update market -- 98866_0_0x709bcc976fd6be016b2904b9331ce5f70f64ebb5b66ee65be9569b9885a4a430 -- Recipe (0x709b...a430)
- Market ID: 0x709bcc976fd6be016b2904b9331ce5f70f64ebb5b66ee65be9569b9885a4a430 (Market Hash)
- Request Timestamp: Thu, 20 Mar 2025 22:26:54 GMT

feat(market-map): Update market -- 98866_0_0x709bcc976fd6be016b2904b9331ce5f70f64ebb5b66ee65be9569b9885a4a430

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x63b20b01d7fddf1772444b424b46e89f9912cefe4d74379626c67412a2348dd6.ts

feat(market-map): Update market -- 11155111_0_0x63b20b01d7fddf1772444b424b46e89f9912cefe4d74379626c67412a2348dd6 -- Recipe (0x63b2...8dd6)
- Market ID: 0x63b20b01d7fddf1772444b424b46e89f9912cefe4d74379626c67412a2348dd6 (Market Hash)
- Request Timestamp: Fri, 21 Mar 2025 02:45:06 GMT

feat(market-map): Update market -- 11155111_0_0x63b20b01d7fddf1772444b424b46e89f9912cefe4d74379626c67412a2348dd6

---

sdk/constants/market-map/8453/definitions/8453_0_0xcb1d4d5c02139b57ea1d42d8d6053ee8fad7009fdf0abb2bd09fa44d448e3ee9.ts

feat(market-map): Update market -- 8453_0_0xcb1d4d5c02139b57ea1d42d8d6053ee8fad7009fdf0abb2bd09fa44d448e3ee9 -- Recipe (0xcb1d...3ee9)
- Market ID: 0xcb1d4d5c02139b57ea1d42d8d6053ee8fad7009fdf0abb2bd09fa44d448e3ee9 (Market Hash)
- Request Timestamp: Fri, 21 Mar 2025 13:11:38 GMT

feat(market-map): Update market -- 8453_0_0xcb1d4d5c02139b57ea1d42d8d6053ee8fad7009fdf0abb2bd09fa44d448e3ee9

---

sdk/constants/market-map/8453/definitions/8453_0_0xe54f8149c237f621f1e7361e266b9e52750c2fc2c4dc9bf82cd72b1cbf985ffc.ts

feat(market-map): Update market -- 8453_0_0xe54f8149c237f621f1e7361e266b9e52750c2fc2c4dc9bf82cd72b1cbf985ffc -- Recipe (0xe54f...5ffc)
- Market ID: 0xe54f8149c237f621f1e7361e266b9e52750c2fc2c4dc9bf82cd72b1cbf985ffc (Market Hash)
- Request Timestamp: Fri, 21 Mar 2025 13:30:19 GMT

feat(market-map): Update market -- 8453_0_0xe54f8149c237f621f1e7361e266b9e52750c2fc2c4dc9bf82cd72b1cbf985ffc

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xeed50c17ec0ea0f243be3e62341fd0801acc349aa6911afb75bd87384011de88.ts

feat(market-map): Update market -- 11155111_0_0xeed50c17ec0ea0f243be3e62341fd0801acc349aa6911afb75bd87384011de88 -- Recipe (0xeed5...de88)
- Market ID: 0xeed50c17ec0ea0f243be3e62341fd0801acc349aa6911afb75bd87384011de88 (Market Hash)
- Request Timestamp: Fri, 21 Mar 2025 19:53:53 GMT

feat(market-map): Update market -- 11155111_0_0xeed50c17ec0ea0f243be3e62341fd0801acc349aa6911afb75bd87384011de88

---

sdk/constants/market-map/8453/definitions/8453_0_0x359b1ab31ad97399621323854d77e18ba9189b2e0795733f372d26aa98718a94.ts

feat(market-map): Update market -- 8453_0_0x359b1ab31ad97399621323854d77e18ba9189b2e0795733f372d26aa98718a94 -- Recipe (0x359b...8a94)
- Market ID: 0x359b1ab31ad97399621323854d77e18ba9189b2e0795733f372d26aa98718a94 (Market Hash)
- Request Timestamp: Sun, 23 Mar 2025 16:07:26 GMT

feat(market-map): Update market -- 8453_0_0x359b1ab31ad97399621323854d77e18ba9189b2e0795733f372d26aa98718a94

---

sdk/constants/market-map/1/definitions/1_0_0xbf37244d56e3673977eb4c5cbf6627fc32452735bdc7339594d4bd10d00a573e.ts

feat(market-map): Update market -- 1_0_0xbf37244d56e3673977eb4c5cbf6627fc32452735bdc7339594d4bd10d00a573e -- Recipe (0xbf37...573e)
- Chain ID: 1
- Market ID: 0xbf37244d56e3673977eb4c5cbf6627fc32452735bdc7339594d4bd10d00a573e (Market Hash)
- Request Timestamp: Sun, 23 Mar 2025 16:31:55 GMT

feat(market-map): Update market -- 1_0_0xbf37244d56e3673977eb4c5cbf6627fc32452735bdc7339594d4bd10d00a573e

---

sdk/constants/market-map/8453/definitions/8453_0_0x05a04628ebdf1c729360515e337309d2b6c0f69e425e831b3a1fcc156f3e4acb.ts

feat(market-map): Update market -- 8453_0_0x05a04628ebdf1c729360515e337309d2b6c0f69e425e831b3a1fcc156f3e4acb -- Recipe (0x05a0...4acb)
- Market ID: 0x05a04628ebdf1c729360515e337309d2b6c0f69e425e831b3a1fcc156f3e4acb (Market Hash)
- Request Timestamp: Sun, 23 Mar 2025 16:55:56 GMT

feat(market-map): Update market -- 8453_0_0x05a04628ebdf1c729360515e337309d2b6c0f69e425e831b3a1fcc156f3e4acb

---

sdk/constants/market-map/8453/definitions/8453_0_0x31d83b312d85452d6dfd66004642fb2456d4882c994f8d66e1d8ab731ef2c8db.ts

feat(market-map): Update market -- 8453_0_0x31d83b312d85452d6dfd66004642fb2456d4882c994f8d66e1d8ab731ef2c8db -- Recipe (0x31d8...c8db)
- Market ID: 0x31d83b312d85452d6dfd66004642fb2456d4882c994f8d66e1d8ab731ef2c8db (Market Hash)
- Request Timestamp: Sun, 23 Mar 2025 17:47:13 GMT

feat(market-map): Update market -- 8453_0_0x31d83b312d85452d6dfd66004642fb2456d4882c994f8d66e1d8ab731ef2c8db

---

sdk/constants/market-map/8453/definitions/8453_0_0x8395b7174fde125dcd576857a7aed6b92df32e32c1577565c0da6b7aa0d4da12.ts

feat(market-map): Update market -- 8453_0_0x8395b7174fde125dcd576857a7aed6b92df32e32c1577565c0da6b7aa0d4da12 -- Recipe (0x8395...da12)
- Market ID: 0x8395b7174fde125dcd576857a7aed6b92df32e32c1577565c0da6b7aa0d4da12 (Market Hash)
- Request Timestamp: Sun, 23 Mar 2025 19:42:56 GMT

feat(market-map): Update market -- 8453_0_0x8395b7174fde125dcd576857a7aed6b92df32e32c1577565c0da6b7aa0d4da12

---

sdk/constants/market-map/1/definitions/1_0_0x3091b1eb5e3467ababee3810687db4e72202d3e18df43c236fbcbd1697f3d32a.ts

feat(market-map): Update market -- 1_0_0x3091b1eb5e3467ababee3810687db4e72202d3e18df43c236fbcbd1697f3d32a -- Recipe (0x3091...d32a)
- Chain ID: 1
- Market ID: 0x3091b1eb5e3467ababee3810687db4e72202d3e18df43c236fbcbd1697f3d32a (Market Hash)
- Request Timestamp: Mon, 24 Mar 2025 10:38:54 GMT

feat(market-map): Update market -- 1_0_0x3091b1eb5e3467ababee3810687db4e72202d3e18df43c236fbcbd1697f3d32a

---

sdk/constants/market-map/146/definitions/146_0_0x22f1c99a829fd11f3a6ffdc874eb55cf881391c3035f22e47b92c18a03e32c71.ts

feat(market-map): Update market -- 146_0_0x22f1c99a829fd11f3a6ffdc874eb55cf881391c3035f22e47b92c18a03e32c71 -- Recipe (0x22f1...2c71)
- Market ID: 0x22f1c99a829fd11f3a6ffdc874eb55cf881391c3035f22e47b92c18a03e32c71 (Market Hash)
- Request Timestamp: Mon, 24 Mar 2025 12:51:16 GMT

feat(market-map): Update market -- 146_0_0x22f1c99a829fd11f3a6ffdc874eb55cf881391c3035f22e47b92c18a03e32c71

---

sdk/constants/market-map/1/definitions/1_0_0xbbe14504d929dc41591982a474ff8a68b0f35fad9a70c78bdd03f9f403caa1df.ts

feat(market-map): Update market -- 1_0_0xbbe14504d929dc41591982a474ff8a68b0f35fad9a70c78bdd03f9f403caa1df -- Recipe (0xbbe1...a1df)
- Chain ID: 1
- Market ID: 0xbbe14504d929dc41591982a474ff8a68b0f35fad9a70c78bdd03f9f403caa1df (Market Hash)
- Request Timestamp: Mon, 24 Mar 2025 12:57:29 GMT

feat(market-map): Update market -- 1_0_0xbbe14504d929dc41591982a474ff8a68b0f35fad9a70c78bdd03f9f403caa1df

---

sdk/constants/market-map/146/definitions/146_0_0x3eb3a00ff84f953977e9370e42e8246f900a0294d95de770a8a3f6e060201cd6.ts

feat(market-map): Update market -- 146_0_0x3eb3a00ff84f953977e9370e42e8246f900a0294d95de770a8a3f6e060201cd6 -- Recipe (0x3eb3...1cd6)
- Market ID: 0x3eb3a00ff84f953977e9370e42e8246f900a0294d95de770a8a3f6e060201cd6 (Market Hash)
- Request Timestamp: Mon, 24 Mar 2025 13:19:04 GMT

feat(market-map): Update market -- 146_0_0x3eb3a00ff84f953977e9370e42e8246f900a0294d95de770a8a3f6e060201cd6

---

sdk/constants/market-map/146/definitions/146_0_0x27baf3e08eb34664c2ea393bb7a2ab2c3683ffe0d91b2817e6993b4e0c751626.ts

feat(market-map): Update market -- 146_0_0x27baf3e08eb34664c2ea393bb7a2ab2c3683ffe0d91b2817e6993b4e0c751626 -- Recipe (0x27ba...1626)
- Market ID: 0x27baf3e08eb34664c2ea393bb7a2ab2c3683ffe0d91b2817e6993b4e0c751626 (Market Hash)
- Request Timestamp: Mon, 24 Mar 2025 13:20:30 GMT

feat(market-map): Update market -- 146_0_0x27baf3e08eb34664c2ea393bb7a2ab2c3683ffe0d91b2817e6993b4e0c751626

---

sdk/constants/market-map/146/definitions/146_0_0x88d8647e8c15fca7e32edfad1d72c93111ed06981d4833a2b77a2ccad895da53.ts

feat(market-map): Update market -- 146_0_0x88d8647e8c15fca7e32edfad1d72c93111ed06981d4833a2b77a2ccad895da53 -- Recipe (0x88d8...da53)
- Market ID: 0x88d8647e8c15fca7e32edfad1d72c93111ed06981d4833a2b77a2ccad895da53 (Market Hash)
- Request Timestamp: Mon, 24 Mar 2025 13:21:15 GMT

feat(market-map): Update market -- 146_0_0x88d8647e8c15fca7e32edfad1d72c93111ed06981d4833a2b77a2ccad895da53

---

sdk/constants/market-map/146/definitions/146_0_0x012e7054c10ad6820e6f2ee5fd7411343ebda527d5e2822c51f3a61a13ce9bdf.ts

feat(market-map): Update market -- 146_0_0x012e7054c10ad6820e6f2ee5fd7411343ebda527d5e2822c51f3a61a13ce9bdf -- Recipe (0x012e...9bdf)
- Market ID: 0x012e7054c10ad6820e6f2ee5fd7411343ebda527d5e2822c51f3a61a13ce9bdf (Market Hash)
- Request Timestamp: Mon, 24 Mar 2025 13:22:10 GMT

feat(market-map): Update market -- 146_0_0x012e7054c10ad6820e6f2ee5fd7411343ebda527d5e2822c51f3a61a13ce9bdf

---

sdk/constants/market-map/146/definitions/146_0_0xb732d0079accffca18174c533ef4065a0bc4d06fe5d835166ff88189ac08ec6d.ts

feat(market-map): Update market -- 146_0_0xb732d0079accffca18174c533ef4065a0bc4d06fe5d835166ff88189ac08ec6d -- Recipe (0xb732...ec6d)
- Market ID: 0xb732d0079accffca18174c533ef4065a0bc4d06fe5d835166ff88189ac08ec6d (Market Hash)
- Request Timestamp: Mon, 24 Mar 2025 13:46:08 GMT

feat(market-map): Update market -- 146_0_0xb732d0079accffca18174c533ef4065a0bc4d06fe5d835166ff88189ac08ec6d

---

sdk/constants/market-map/146/definitions/146_0_0x4e66b3b7e23e265e18d428a3acfe79eb782081ffb677e0fae4e1d431868d2f09.ts

feat(market-map): Update market -- 146_0_0x4e66b3b7e23e265e18d428a3acfe79eb782081ffb677e0fae4e1d431868d2f09 -- Recipe (0x4e66...2f09)
- Market ID: 0x4e66b3b7e23e265e18d428a3acfe79eb782081ffb677e0fae4e1d431868d2f09 (Market Hash)
- Request Timestamp: Mon, 24 Mar 2025 14:03:08 GMT

feat(market-map): Update market -- 146_0_0x4e66b3b7e23e265e18d428a3acfe79eb782081ffb677e0fae4e1d431868d2f09

---

sdk/constants/market-map/8453/definitions/8453_0_0x950acfbc9e53c7e0d1d1300577fe45b2b9a76d157921808a1cd4520e1e6dea72.ts

feat(market-map): Update market -- 8453_0_0x950acfbc9e53c7e0d1d1300577fe45b2b9a76d157921808a1cd4520e1e6dea72 -- Recipe (0x950a...ea72)
- Market ID: 0x950acfbc9e53c7e0d1d1300577fe45b2b9a76d157921808a1cd4520e1e6dea72 (Market Hash)
- Request Timestamp: Mon, 24 Mar 2025 14:41:26 GMT

feat(market-map): Update market -- 8453_0_0x950acfbc9e53c7e0d1d1300577fe45b2b9a76d157921808a1cd4520e1e6dea72

---

sdk/constants/market-map/8453/definitions/8453_0_0xa8c77e0b4883c901f01d352ecdc1a5404b7ec83bcfb2a2fa3d1960a682c9d3dd.ts

feat(market-map): Update market -- 8453_0_0xa8c77e0b4883c901f01d352ecdc1a5404b7ec83bcfb2a2fa3d1960a682c9d3dd -- Recipe (0xa8c7...d3dd)
- Market ID: 0xa8c77e0b4883c901f01d352ecdc1a5404b7ec83bcfb2a2fa3d1960a682c9d3dd (Market Hash)
- Request Timestamp: Mon, 24 Mar 2025 14:50:57 GMT

feat(market-map): Update market -- 8453_0_0xa8c77e0b4883c901f01d352ecdc1a5404b7ec83bcfb2a2fa3d1960a682c9d3dd

---

sdk/constants/market-map/8453/definitions/8453_0_0xe4f4bdbc4a5b04cffc4cfd2a37063fc73dbc25932fe6f8b3bd3820d8092e9bf5.ts

feat(market-map): Update market -- 8453_0_0xe4f4bdbc4a5b04cffc4cfd2a37063fc73dbc25932fe6f8b3bd3820d8092e9bf5 -- Recipe (0xe4f4...9bf5)
- Market ID: 0xe4f4bdbc4a5b04cffc4cfd2a37063fc73dbc25932fe6f8b3bd3820d8092e9bf5 (Market Hash)
- Request Timestamp: Mon, 24 Mar 2025 15:00:08 GMT

feat(market-map): Update market -- 8453_0_0xe4f4bdbc4a5b04cffc4cfd2a37063fc73dbc25932fe6f8b3bd3820d8092e9bf5

---

sdk/constants/market-map/8453/definitions/8453_0_0x21d50922f380bec451006781989cefac5fc627447b5a0f6f580d9d4c8162e512.ts

feat(market-map): Update market -- 8453_0_0x21d50922f380bec451006781989cefac5fc627447b5a0f6f580d9d4c8162e512 -- Recipe (0x21d5...e512)
- Market ID: 0x21d50922f380bec451006781989cefac5fc627447b5a0f6f580d9d4c8162e512 (Market Hash)
- Request Timestamp: Mon, 24 Mar 2025 15:03:28 GMT

feat(market-map): Update market -- 8453_0_0x21d50922f380bec451006781989cefac5fc627447b5a0f6f580d9d4c8162e512

---

sdk/constants/market-map/8453/definitions/8453_0_0x94582ea5b2fa66674772f5f1b60ed990926dcc0b14d21e6d0931080833026884.ts

feat(market-map): Update market -- 8453_0_0x94582ea5b2fa66674772f5f1b60ed990926dcc0b14d21e6d0931080833026884 -- Recipe (0x9458...6884)
- Market ID: 0x94582ea5b2fa66674772f5f1b60ed990926dcc0b14d21e6d0931080833026884 (Market Hash)
- Request Timestamp: Mon, 24 Mar 2025 15:07:18 GMT

feat(market-map): Update market -- 8453_0_0x94582ea5b2fa66674772f5f1b60ed990926dcc0b14d21e6d0931080833026884

---

sdk/constants/market-map/8453/definitions/8453_0_0xab2d51cdd994702ddc1397eb7a1400da6949781ef0894f35161c3248b27bcc1b.ts

feat(market-map): Update market -- 8453_0_0xab2d51cdd994702ddc1397eb7a1400da6949781ef0894f35161c3248b27bcc1b -- Recipe (0xab2d...cc1b)
- Market ID: 0xab2d51cdd994702ddc1397eb7a1400da6949781ef0894f35161c3248b27bcc1b (Market Hash)
- Request Timestamp: Mon, 24 Mar 2025 15:16:18 GMT

feat(market-map): Update market -- 8453_0_0xab2d51cdd994702ddc1397eb7a1400da6949781ef0894f35161c3248b27bcc1b

---

sdk/constants/market-map/8453/definitions/8453_0_0x746eda4c70e4e594327c3097b16a647710485728ebff5bf0429b8087b870b4ee.ts

feat(market-map): Update market -- 8453_0_0x746eda4c70e4e594327c3097b16a647710485728ebff5bf0429b8087b870b4ee -- Recipe (0x746e...b4ee)
- Market ID: 0x746eda4c70e4e594327c3097b16a647710485728ebff5bf0429b8087b870b4ee (Market Hash)
- Request Timestamp: Mon, 24 Mar 2025 18:09:16 GMT

feat(market-map): Update market -- 8453_0_0x746eda4c70e4e594327c3097b16a647710485728ebff5bf0429b8087b870b4ee

---

sdk/constants/market-map/8453/definitions/8453_0_0x4cecf03efd03e280943fc410c01a2e351a136a443b5eaa07ef008ae53a0d8871.ts

feat(market-map): Update market -- 8453_0_0x4cecf03efd03e280943fc410c01a2e351a136a443b5eaa07ef008ae53a0d8871 -- Recipe (0x4cec...8871)
- Market ID: 0x4cecf03efd03e280943fc410c01a2e351a136a443b5eaa07ef008ae53a0d8871 (Market Hash)
- Request Timestamp: Mon, 24 Mar 2025 21:32:23 GMT

feat(market-map): Update market -- 8453_0_0x4cecf03efd03e280943fc410c01a2e351a136a443b5eaa07ef008ae53a0d8871

---

sdk/constants/market-map/8453/definitions/8453_0_0x6aa1012d375773f215cbb97b320c4d702af289c709e6c377da23cfff316f872e.ts

feat(market-map): Update market -- 8453_0_0x6aa1012d375773f215cbb97b320c4d702af289c709e6c377da23cfff316f872e -- Recipe (0x6aa1...872e)
- Market ID: 0x6aa1012d375773f215cbb97b320c4d702af289c709e6c377da23cfff316f872e (Market Hash)
- Request Timestamp: Mon, 24 Mar 2025 21:41:26 GMT

feat(market-map): Update market -- 8453_0_0x6aa1012d375773f215cbb97b320c4d702af289c709e6c377da23cfff316f872e

---

sdk/constants/market-map/8453/definitions/8453_0_0x5f6b065e7dac8c53e30be5c7f27fbd00201cab01e07cd389404b3135905e8a97.ts

feat(market-map): Update market -- 8453_0_0x5f6b065e7dac8c53e30be5c7f27fbd00201cab01e07cd389404b3135905e8a97 -- Recipe (0x5f6b...8a97)
- Market ID: 0x5f6b065e7dac8c53e30be5c7f27fbd00201cab01e07cd389404b3135905e8a97 (Market Hash)
- Request Timestamp: Mon, 24 Mar 2025 21:52:47 GMT

feat(market-map): Update market -- 8453_0_0x5f6b065e7dac8c53e30be5c7f27fbd00201cab01e07cd389404b3135905e8a97

---

sdk/constants/market-map/8453/definitions/8453_0_0x99eff7dbf67cff955e375bb0540dfa5b53000637e7304fbfab59b0f5e262214f.ts

feat(market-map): Update market -- 8453_0_0x99eff7dbf67cff955e375bb0540dfa5b53000637e7304fbfab59b0f5e262214f -- Recipe (0x99ef...214f)
- Market ID: 0x99eff7dbf67cff955e375bb0540dfa5b53000637e7304fbfab59b0f5e262214f (Market Hash)
- Request Timestamp: Mon, 24 Mar 2025 23:53:34 GMT

feat(market-map): Update market -- 8453_0_0x99eff7dbf67cff955e375bb0540dfa5b53000637e7304fbfab59b0f5e262214f

---

sdk/constants/market-map/8453/definitions/8453_0_0xfc24cc4a94543caa9e24f48c5d2f09f2156e6c449ed510dac327970cb472c5a7.ts

feat(market-map): Update market -- 8453_0_0xfc24cc4a94543caa9e24f48c5d2f09f2156e6c449ed510dac327970cb472c5a7 -- Recipe (0xfc24...c5a7)
- Market ID: 0xfc24cc4a94543caa9e24f48c5d2f09f2156e6c449ed510dac327970cb472c5a7 (Market Hash)
- Request Timestamp: Tue, 25 Mar 2025 00:09:55 GMT

feat(market-map): Update market -- 8453_0_0xfc24cc4a94543caa9e24f48c5d2f09f2156e6c449ed510dac327970cb472c5a7

---

sdk/constants/market-map/8453/definitions/8453_0_0x43314ce58840f0c26bf2fbb2135ea86051b391afe186d42186cccef55e318e10.ts

feat(market-map): Update market -- 8453_0_0x43314ce58840f0c26bf2fbb2135ea86051b391afe186d42186cccef55e318e10 -- Recipe (0x4331...8e10)
- Market ID: 0x43314ce58840f0c26bf2fbb2135ea86051b391afe186d42186cccef55e318e10 (Market Hash)
- Request Timestamp: Tue, 25 Mar 2025 10:28:02 GMT

feat(market-map): Update market -- 8453_0_0x43314ce58840f0c26bf2fbb2135ea86051b391afe186d42186cccef55e318e10

---

sdk/constants/market-map/8453/definitions/8453_0_0x714c108cc91ab9419cca2cc761252e949a5f3a0a398557c49742eedf9639f721.ts

feat(market-map): Update market -- 8453_0_0x714c108cc91ab9419cca2cc761252e949a5f3a0a398557c49742eedf9639f721 -- Recipe (0x714c...f721)
- Market ID: 0x714c108cc91ab9419cca2cc761252e949a5f3a0a398557c49742eedf9639f721 (Market Hash)
- Request Timestamp: Tue, 25 Mar 2025 10:32:42 GMT

feat(market-map): Update market -- 8453_0_0x714c108cc91ab9419cca2cc761252e949a5f3a0a398557c49742eedf9639f721

---

sdk/constants/market-map/8453/definitions/8453_0_0x57f1a13d5dc3d192954c7aded801d6ab4ca403b6526defd2f6f2f328995bcdbd.ts

feat(market-map): Update market -- 8453_0_0x57f1a13d5dc3d192954c7aded801d6ab4ca403b6526defd2f6f2f328995bcdbd -- Recipe (0x57f1...cdbd)
- Market ID: 0x57f1a13d5dc3d192954c7aded801d6ab4ca403b6526defd2f6f2f328995bcdbd (Market Hash)
- Request Timestamp: Tue, 25 Mar 2025 10:37:01 GMT

feat(market-map): Update market -- 8453_0_0x57f1a13d5dc3d192954c7aded801d6ab4ca403b6526defd2f6f2f328995bcdbd

---

sdk/constants/market-map/8453/definitions/8453_0_0xa2beb8098171d1c5556a837c16a7d9d4eea75c9a353fc01241a33ae6bf095dab.ts

feat(market-map): Update market -- 8453_0_0xa2beb8098171d1c5556a837c16a7d9d4eea75c9a353fc01241a33ae6bf095dab -- Recipe (0xa2be...5dab)
- Market ID: 0xa2beb8098171d1c5556a837c16a7d9d4eea75c9a353fc01241a33ae6bf095dab (Market Hash)
- Request Timestamp: Tue, 25 Mar 2025 10:41:12 GMT

feat(market-map): Update market -- 8453_0_0xa2beb8098171d1c5556a837c16a7d9d4eea75c9a353fc01241a33ae6bf095dab

---

sdk/constants/market-map/8453/definitions/8453_0_0x9953a1d25df1ece15b0ef05546c2c22ac61d4551d1e8d2e8af6ec938a84418e0.ts

feat(market-map): Update market -- 8453_0_0x9953a1d25df1ece15b0ef05546c2c22ac61d4551d1e8d2e8af6ec938a84418e0 -- Recipe (0x9953...18e0)
- Market ID: 0x9953a1d25df1ece15b0ef05546c2c22ac61d4551d1e8d2e8af6ec938a84418e0 (Market Hash)
- Request Timestamp: Tue, 25 Mar 2025 10:45:51 GMT

feat(market-map): Update market -- 8453_0_0x9953a1d25df1ece15b0ef05546c2c22ac61d4551d1e8d2e8af6ec938a84418e0

---

sdk/constants/market-map/8453/definitions/8453_0_0x6af06ea828ab63ab930887404342b6da79568869b01d8268b87ffa5dad75cdab.ts

feat(market-map): Update market -- 8453_0_0x6af06ea828ab63ab930887404342b6da79568869b01d8268b87ffa5dad75cdab -- Recipe (0x6af0...cdab)
- Market ID: 0x6af06ea828ab63ab930887404342b6da79568869b01d8268b87ffa5dad75cdab (Market Hash)
- Request Timestamp: Tue, 25 Mar 2025 10:50:11 GMT

feat(market-map): Update market -- 8453_0_0x6af06ea828ab63ab930887404342b6da79568869b01d8268b87ffa5dad75cdab

---

sdk/constants/market-map/8453/definitions/8453_0_0xe1d6683013d3e41b40a978071805ef52cd2bdb73dcb2a38dd19aa28ed87771c0.ts

feat(market-map): Update market -- 8453_0_0xe1d6683013d3e41b40a978071805ef52cd2bdb73dcb2a38dd19aa28ed87771c0 -- Recipe (0xe1d6...71c0)
- Market ID: 0xe1d6683013d3e41b40a978071805ef52cd2bdb73dcb2a38dd19aa28ed87771c0 (Market Hash)
- Request Timestamp: Tue, 25 Mar 2025 10:54:33 GMT

feat(market-map): Update market -- 8453_0_0xe1d6683013d3e41b40a978071805ef52cd2bdb73dcb2a38dd19aa28ed87771c0

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xf9c7d9d6e53941475b1ec03b479bb057aa6c4c5afeef1258fb22afb94b6b159c.ts

feat(market-map): Update market -- 11155111_0_0xf9c7d9d6e53941475b1ec03b479bb057aa6c4c5afeef1258fb22afb94b6b159c -- Recipe (0xf9c7...159c)
- Market ID: 0xf9c7d9d6e53941475b1ec03b479bb057aa6c4c5afeef1258fb22afb94b6b159c (Market Hash)
- Request Timestamp: Tue, 25 Mar 2025 12:18:08 GMT

feat(market-map): Update market -- 11155111_0_0xf9c7d9d6e53941475b1ec03b479bb057aa6c4c5afeef1258fb22afb94b6b159c

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x24832faa1c4ec5fa6193642be41f91265c383dc74574a7ca855d70716d3c6ffd.ts

feat(market-map): Update market -- 11155111_0_0x24832faa1c4ec5fa6193642be41f91265c383dc74574a7ca855d70716d3c6ffd -- Recipe (0x2483...6ffd)
- Market ID: 0x24832faa1c4ec5fa6193642be41f91265c383dc74574a7ca855d70716d3c6ffd (Market Hash)
- Request Timestamp: Wed, 26 Mar 2025 09:37:29 GMT

feat(market-map): Update market -- 11155111_0_0x24832faa1c4ec5fa6193642be41f91265c383dc74574a7ca855d70716d3c6ffd

---

sdk/constants/market-map/98866/definitions/98866_0_0x4d1dfab8800e535f8a1343c6c1af902d37b78f948287ff02c5dfa30baa4687b2.ts

feat(market-map): Update market -- 98866_0_0x4d1dfab8800e535f8a1343c6c1af902d37b78f948287ff02c5dfa30baa4687b2 -- Recipe (0x4d1d...87b2)
- Market ID: 0x4d1dfab8800e535f8a1343c6c1af902d37b78f948287ff02c5dfa30baa4687b2 (Market Hash)
- Request Timestamp: Wed, 26 Mar 2025 22:00:44 GMT

feat(market-map): Update market -- 98866_0_0x4d1dfab8800e535f8a1343c6c1af902d37b78f948287ff02c5dfa30baa4687b2

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x0f29c974d0d2610ccdc777b2c84e1b69ae859dccd55708e272f594bb67ed4e57.ts

feat(market-map): Update market -- 11155111_0_0x0f29c974d0d2610ccdc777b2c84e1b69ae859dccd55708e272f594bb67ed4e57 -- Recipe (0x0f29...4e57)
- Market ID: 0x0f29c974d0d2610ccdc777b2c84e1b69ae859dccd55708e272f594bb67ed4e57 (Market Hash)
- Request Timestamp: Thu, 27 Mar 2025 20:51:45 GMT

feat(market-map): Update market -- 11155111_0_0x0f29c974d0d2610ccdc777b2c84e1b69ae859dccd55708e272f594bb67ed4e57

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xe3dbf381e909dea1aebf7b527d9484e1f5ba543d47fe5e2c9d00c3cb8d3109de.ts

feat(market-map): Update market -- 11155111_0_0xe3dbf381e909dea1aebf7b527d9484e1f5ba543d47fe5e2c9d00c3cb8d3109de -- Recipe (0xe3db...09de)
- Market ID: 0xe3dbf381e909dea1aebf7b527d9484e1f5ba543d47fe5e2c9d00c3cb8d3109de (Market Hash)
- Request Timestamp: Thu, 27 Mar 2025 20:56:28 GMT

feat(market-map): Update market -- 11155111_0_0xe3dbf381e909dea1aebf7b527d9484e1f5ba543d47fe5e2c9d00c3cb8d3109de

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xc3fce3f86eae7d0e66f9a38f05aa6135a737d20b1a6d997f06ff44cb45cce724.ts

feat(market-map): Update market -- 11155111_0_0xc3fce3f86eae7d0e66f9a38f05aa6135a737d20b1a6d997f06ff44cb45cce724 -- Recipe (0xc3fc...e724)
- Market ID: 0xc3fce3f86eae7d0e66f9a38f05aa6135a737d20b1a6d997f06ff44cb45cce724 (Market Hash)
- Request Timestamp: Fri, 28 Mar 2025 03:55:19 GMT

feat(market-map): Update market -- 11155111_0_0xc3fce3f86eae7d0e66f9a38f05aa6135a737d20b1a6d997f06ff44cb45cce724

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x9cad5ebc42dde1c600968892697ccef7eac91ae242cfd7d421b993eabee95023.ts

feat(market-map): Update market -- 11155111_0_0x9cad5ebc42dde1c600968892697ccef7eac91ae242cfd7d421b993eabee95023 -- Recipe (0x9cad...5023)
- Market ID: 0x9cad5ebc42dde1c600968892697ccef7eac91ae242cfd7d421b993eabee95023 (Market Hash)
- Request Timestamp: Fri, 28 Mar 2025 13:53:45 GMT

feat(market-map): Update market -- 11155111_0_0x9cad5ebc42dde1c600968892697ccef7eac91ae242cfd7d421b993eabee95023

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x79a6d67b7aa65ddb20a6a189bc242276a84e459767cd10362916d27ef4efa468.ts

feat(market-map): Update market -- 11155111_0_0x79a6d67b7aa65ddb20a6a189bc242276a84e459767cd10362916d27ef4efa468 -- Recipe (0x79a6...a468)
- Market ID: 0x79a6d67b7aa65ddb20a6a189bc242276a84e459767cd10362916d27ef4efa468 (Market Hash)
- Request Timestamp: Fri, 28 Mar 2025 14:47:56 GMT

feat(market-map): Update market -- 11155111_0_0x79a6d67b7aa65ddb20a6a189bc242276a84e459767cd10362916d27ef4efa468

---

sdk/constants/market-map/146/definitions/146_0_0x8cea54997edee928963d41475e459c41ffd0489f1f9515c4a80787514fea82de.ts

feat(market-map): Update market -- 146_0_0x8cea54997edee928963d41475e459c41ffd0489f1f9515c4a80787514fea82de -- Recipe (0x8cea...82de)
- Market ID: 0x8cea54997edee928963d41475e459c41ffd0489f1f9515c4a80787514fea82de (Market Hash)
- Request Timestamp: Fri, 28 Mar 2025 17:32:17 GMT

feat(market-map): Update market -- 146_0_0x8cea54997edee928963d41475e459c41ffd0489f1f9515c4a80787514fea82de

---

sdk/constants/market-map/146/definitions/146_0_0xb7213bb1cdb02537098e9d092e5cee938d1f19ae47494915e7b255b9114dabe5.ts

feat(market-map): Update market -- 146_0_0xb7213bb1cdb02537098e9d092e5cee938d1f19ae47494915e7b255b9114dabe5 -- Recipe (0xb721...abe5)
- Market ID: 0xb7213bb1cdb02537098e9d092e5cee938d1f19ae47494915e7b255b9114dabe5 (Market Hash)
- Request Timestamp: Fri, 28 Mar 2025 18:43:07 GMT

feat(market-map): Update market -- 146_0_0xb7213bb1cdb02537098e9d092e5cee938d1f19ae47494915e7b255b9114dabe5

---

sdk/constants/market-map/146/definitions/146_0_0xa56e8c04fe6ab60995acee98902371663cbd68600814765253a994be2f80ab70.ts

feat(market-map): Update market -- 146_0_0xa56e8c04fe6ab60995acee98902371663cbd68600814765253a994be2f80ab70 -- Recipe (0xa56e...ab70)
- Market ID: 0xa56e8c04fe6ab60995acee98902371663cbd68600814765253a994be2f80ab70 (Market Hash)
- Request Timestamp: Fri, 28 Mar 2025 18:52:35 GMT

feat(market-map): Update market -- 146_0_0xa56e8c04fe6ab60995acee98902371663cbd68600814765253a994be2f80ab70

---

sdk/constants/market-map/146/definitions/146_0_0x3bc81c4d5a9f3130904d23f45a9eaff9bfa645e26a6540790ebf6fb1ad108c37.ts

feat(market-map): Update market -- 146_0_0x3bc81c4d5a9f3130904d23f45a9eaff9bfa645e26a6540790ebf6fb1ad108c37 -- Recipe (0x3bc8...8c37)
- Market ID: 0x3bc81c4d5a9f3130904d23f45a9eaff9bfa645e26a6540790ebf6fb1ad108c37 (Market Hash)
- Request Timestamp: Fri, 28 Mar 2025 18:53:42 GMT

feat(market-map): Update market -- 146_0_0x3bc81c4d5a9f3130904d23f45a9eaff9bfa645e26a6540790ebf6fb1ad108c37

---

sdk/constants/market-map/146/definitions/146_0_0x79d0c5d93ff7f33f707cdb7b9bc707a5c2fd175a02940ec6204d274c1b148bc4.ts

feat(market-map): Update market -- 146_0_0x79d0c5d93ff7f33f707cdb7b9bc707a5c2fd175a02940ec6204d274c1b148bc4 -- Recipe (0x79d0...8bc4)
- Market ID: 0x79d0c5d93ff7f33f707cdb7b9bc707a5c2fd175a02940ec6204d274c1b148bc4 (Market Hash)
- Request Timestamp: Fri, 28 Mar 2025 18:54:51 GMT

feat(market-map): Update market -- 146_0_0x79d0c5d93ff7f33f707cdb7b9bc707a5c2fd175a02940ec6204d274c1b148bc4

---

sdk/constants/market-map/98866/definitions/98866_0_0x2f78c78d19cb5de966299880ff0a93c8e68f31423c67f1c0ddf4140de19018f8.ts

feat(market-map): Update market -- 98866_0_0x2f78c78d19cb5de966299880ff0a93c8e68f31423c67f1c0ddf4140de19018f8 -- Recipe (0x2f78...18f8)
- Market ID: 0x2f78c78d19cb5de966299880ff0a93c8e68f31423c67f1c0ddf4140de19018f8 (Market Hash)
- Request Timestamp: Mon, 31 Mar 2025 10:28:26 GMT

feat(market-map): Update market -- 98866_0_0x2f78c78d19cb5de966299880ff0a93c8e68f31423c67f1c0ddf4140de19018f8

---

sdk/constants/market-map/146/definitions/146_0_0x31bdffd0bbab9391f6c2903be86b89a7d5107e26e091ccb6c0c9239107ab02e7.ts

feat(market-map): Update market -- 146_0_0x31bdffd0bbab9391f6c2903be86b89a7d5107e26e091ccb6c0c9239107ab02e7 -- Recipe (0x31bd...02e7)
- Market ID: 0x31bdffd0bbab9391f6c2903be86b89a7d5107e26e091ccb6c0c9239107ab02e7 (Market Hash)
- Request Timestamp: Mon, 31 Mar 2025 15:32:37 GMT

feat(market-map): Update market -- 146_0_0x31bdffd0bbab9391f6c2903be86b89a7d5107e26e091ccb6c0c9239107ab02e7

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xb5cea6a53cba3d45d899956667483e5e593a195744880c4dcec6e048c019974e.ts

feat(market-map): Update market -- 11155111_0_0xb5cea6a53cba3d45d899956667483e5e593a195744880c4dcec6e048c019974e -- Recipe (0xb5ce...974e)
- Market ID: 0xb5cea6a53cba3d45d899956667483e5e593a195744880c4dcec6e048c019974e (Market Hash)
- Request Timestamp: Mon, 31 Mar 2025 17:38:35 GMT

feat(market-map): Update market -- 11155111_0_0xb5cea6a53cba3d45d899956667483e5e593a195744880c4dcec6e048c019974e

---

sdk/constants/market-map/146/definitions/146_0_0xf8b51673d19ac7c2b804113d68f3c07310e2aaee5d6873bc55d9dc4e0b71484a.ts

feat(market-map): Update market -- 146_0_0xf8b51673d19ac7c2b804113d68f3c07310e2aaee5d6873bc55d9dc4e0b71484a -- Recipe (0xf8b5...484a)
- Market ID: 0xf8b51673d19ac7c2b804113d68f3c07310e2aaee5d6873bc55d9dc4e0b71484a (Market Hash)
- Request Timestamp: Mon, 31 Mar 2025 18:09:09 GMT

feat(market-map): Update market -- 146_0_0xf8b51673d19ac7c2b804113d68f3c07310e2aaee5d6873bc55d9dc4e0b71484a

---

sdk/constants/market-map/146/definitions/146_0_0xc11c90babd60a148eba7540569f05a707fcb16eb6ae10bc08d8607f2525c73a5.ts

feat(market-map): Update market -- 146_0_0xc11c90babd60a148eba7540569f05a707fcb16eb6ae10bc08d8607f2525c73a5 -- Recipe (0xc11c...73a5)
- Market ID: 0xc11c90babd60a148eba7540569f05a707fcb16eb6ae10bc08d8607f2525c73a5 (Market Hash)
- Request Timestamp: Mon, 31 Mar 2025 19:27:34 GMT

feat(market-map): Update market -- 146_0_0xc11c90babd60a148eba7540569f05a707fcb16eb6ae10bc08d8607f2525c73a5

---

sdk/constants/market-map/98866/definitions/98866_0_0xbe31d9ad295ecb4eccb4dd4f98720488706cd036ed2b7098a7c342cc109a5d32.ts

feat(market-map): Update market -- 98866_0_0xbe31d9ad295ecb4eccb4dd4f98720488706cd036ed2b7098a7c342cc109a5d32 -- Recipe (0xbe31...5d32)
- Market ID: 0xbe31d9ad295ecb4eccb4dd4f98720488706cd036ed2b7098a7c342cc109a5d32 (Market Hash)
- Request Timestamp: Wed, 02 Apr 2025 08:43:58 GMT

feat(market-map): Update market -- 98866_0_0xbe31d9ad295ecb4eccb4dd4f98720488706cd036ed2b7098a7c342cc109a5d32

---

sdk/constants/market-map/98866/definitions/98866_0_0xbb9b61b9c4ff250d210b295b80db9e7e5e3e0d562b063cb61a36d79ca0eb0554.ts

feat(market-map): Update market -- 98866_0_0xbb9b61b9c4ff250d210b295b80db9e7e5e3e0d562b063cb61a36d79ca0eb0554 -- Recipe (0xbb9b...0554)
- Market ID: 0xbb9b61b9c4ff250d210b295b80db9e7e5e3e0d562b063cb61a36d79ca0eb0554 (Market Hash)
- Request Timestamp: Wed, 02 Apr 2025 09:24:30 GMT

feat(market-map): Update market -- 98866_0_0xbb9b61b9c4ff250d210b295b80db9e7e5e3e0d562b063cb61a36d79ca0eb0554

---

sdk/constants/market-map/98866/definitions/98866_0_0xb6cce16cb8444aae43f2fd3877f67de7762974d28c4b20bdb628b9fde61569bc.ts

feat(market-map): Update market -- 98866_0_0xb6cce16cb8444aae43f2fd3877f67de7762974d28c4b20bdb628b9fde61569bc -- Recipe (0xb6cc...69bc)
- Market ID: 0xb6cce16cb8444aae43f2fd3877f67de7762974d28c4b20bdb628b9fde61569bc (Market Hash)
- Request Timestamp: Wed, 02 Apr 2025 09:50:04 GMT

feat(market-map): Update market -- 98866_0_0xb6cce16cb8444aae43f2fd3877f67de7762974d28c4b20bdb628b9fde61569bc

---

sdk/constants/market-map/146/definitions/146_0_0x1b60d926bc5417a4bf6d7aebdee4b5307e5e6828a22b56507e570fb678eae9d8.ts

feat(market-map): Update market -- 146_0_0x1b60d926bc5417a4bf6d7aebdee4b5307e5e6828a22b56507e570fb678eae9d8 -- Recipe (0x1b60...e9d8)
- Market ID: 0x1b60d926bc5417a4bf6d7aebdee4b5307e5e6828a22b56507e570fb678eae9d8 (Market Hash)
- Request Timestamp: Wed, 02 Apr 2025 22:44:16 GMT

feat(market-map): Update market -- 146_0_0x1b60d926bc5417a4bf6d7aebdee4b5307e5e6828a22b56507e570fb678eae9d8

---

sdk/constants/market-map/1/definitions/1_0_0x219d17616b475b0c2c423dbdcdbf02c50b1129800e7869a5a7892abc54324935.ts

feat(market-map): Update market -- 1_0_0x219d17616b475b0c2c423dbdcdbf02c50b1129800e7869a5a7892abc54324935 -- Recipe (0x219d...4935)
- Chain ID: 1
- Market ID: 0x219d17616b475b0c2c423dbdcdbf02c50b1129800e7869a5a7892abc54324935 (Market Hash)
- Request Timestamp: Thu, 03 Apr 2025 12:18:53 GMT

feat(market-map): Update market -- 1_0_0x219d17616b475b0c2c423dbdcdbf02c50b1129800e7869a5a7892abc54324935

---

sdk/constants/market-map/98866/definitions/98866_0_0xef6573033aed82d3de3280e5e0fb2e8e49e9ace6d4a6d1f054be8797dea1a25b.ts

feat(market-map): Update market -- 98866_0_0xef6573033aed82d3de3280e5e0fb2e8e49e9ace6d4a6d1f054be8797dea1a25b -- Recipe (0xef65...a25b)
- Market ID: 0xef6573033aed82d3de3280e5e0fb2e8e49e9ace6d4a6d1f054be8797dea1a25b (Market Hash)
- Request Timestamp: Thu, 03 Apr 2025 12:46:33 GMT

feat(market-map): Update market -- 98866_0_0xef6573033aed82d3de3280e5e0fb2e8e49e9ace6d4a6d1f054be8797dea1a25b

---

sdk/constants/market-map/98866/definitions/98866_0_0x6e1fcdd01bec1ac68a1a510408c844702c5793ffaf6f3117f7c42a9c555bc13d.ts

feat(market-map): Update market -- 98866_0_0x6e1fcdd01bec1ac68a1a510408c844702c5793ffaf6f3117f7c42a9c555bc13d -- Recipe (0x6e1f...c13d)
- Market ID: 0x6e1fcdd01bec1ac68a1a510408c844702c5793ffaf6f3117f7c42a9c555bc13d (Market Hash)
- Request Timestamp: Thu, 03 Apr 2025 17:20:48 GMT

feat(market-map): Update market -- 98866_0_0x6e1fcdd01bec1ac68a1a510408c844702c5793ffaf6f3117f7c42a9c555bc13d

---

sdk/constants/market-map/146/definitions/146_0_0xe090a9ee9d9e88c3a70e06f84fc0eea1a540f9ddd0de4f5f1d0ae2d3ff5c908a.ts

feat(market-map): Update market -- 146_0_0xe090a9ee9d9e88c3a70e06f84fc0eea1a540f9ddd0de4f5f1d0ae2d3ff5c908a -- Recipe (0xe090...908a)
- Market ID: 0xe090a9ee9d9e88c3a70e06f84fc0eea1a540f9ddd0de4f5f1d0ae2d3ff5c908a (Market Hash)
- Request Timestamp: Thu, 03 Apr 2025 20:48:05 GMT

feat(market-map): Update market -- 146_0_0xe090a9ee9d9e88c3a70e06f84fc0eea1a540f9ddd0de4f5f1d0ae2d3ff5c908a

---

sdk/constants/market-map/146/definitions/146_0_0xccad00da8a4a30b3d6b9eaf437671b49b3e55aa265015b5f63f7d15ae8d5034b.ts

feat(market-map): Update market -- 146_0_0xccad00da8a4a30b3d6b9eaf437671b49b3e55aa265015b5f63f7d15ae8d5034b -- Recipe (0xccad...034b)
- Market ID: 0xccad00da8a4a30b3d6b9eaf437671b49b3e55aa265015b5f63f7d15ae8d5034b (Market Hash)
- Request Timestamp: Thu, 03 Apr 2025 21:23:39 GMT

feat(market-map): Update market -- 146_0_0xccad00da8a4a30b3d6b9eaf437671b49b3e55aa265015b5f63f7d15ae8d5034b

---

sdk/constants/market-map/98866/definitions/98866_0_0x1d72d7d02de6f19f7cc5f83de5b6c1c29101196d1aabd0082148e8091a35c4bc.ts

feat(market-map): Update market -- 98866_0_0x1d72d7d02de6f19f7cc5f83de5b6c1c29101196d1aabd0082148e8091a35c4bc -- Recipe (0x1d72...c4bc)
- Market ID: 0x1d72d7d02de6f19f7cc5f83de5b6c1c29101196d1aabd0082148e8091a35c4bc (Market Hash)
- Request Timestamp: Thu, 03 Apr 2025 21:50:24 GMT

feat(market-map): Update market -- 98866_0_0x1d72d7d02de6f19f7cc5f83de5b6c1c29101196d1aabd0082148e8091a35c4bc

---

sdk/constants/market-map/98866/definitions/98866_0_0xafb853582fe7f410f2c4688c818087a2c4c70c03a2de281dec94b96e55a840e0.ts

feat(market-map): Update market -- 98866_0_0xafb853582fe7f410f2c4688c818087a2c4c70c03a2de281dec94b96e55a840e0 -- Recipe (0xafb8...40e0)
- Market ID: 0xafb853582fe7f410f2c4688c818087a2c4c70c03a2de281dec94b96e55a840e0 (Market Hash)
- Request Timestamp: Thu, 03 Apr 2025 22:03:10 GMT

feat(market-map): Update market -- 98866_0_0xafb853582fe7f410f2c4688c818087a2c4c70c03a2de281dec94b96e55a840e0

---

sdk/constants/market-map/98866/definitions/98866_0_0xb9824138a4a1b58ba9b27942df266f3361fe60c856b1bca84de427caf4472752.ts

feat(market-map): Update market -- 98866_0_0xb9824138a4a1b58ba9b27942df266f3361fe60c856b1bca84de427caf4472752 -- Recipe (0xb982...2752)
- Market ID: 0xb9824138a4a1b58ba9b27942df266f3361fe60c856b1bca84de427caf4472752 (Market Hash)
- Request Timestamp: Thu, 03 Apr 2025 22:11:09 GMT

feat(market-map): Update market -- 98866_0_0xb9824138a4a1b58ba9b27942df266f3361fe60c856b1bca84de427caf4472752

---

sdk/constants/market-map/98866/definitions/98866_0_0xb26196c9e8a5a3da90fb034b7398d0f1c0cda132e5d1a6b7f66f98392245e2e5.ts

feat(market-map): Update market -- 98866_0_0xb26196c9e8a5a3da90fb034b7398d0f1c0cda132e5d1a6b7f66f98392245e2e5 -- Recipe (0xb261...e2e5)
- Market ID: 0xb26196c9e8a5a3da90fb034b7398d0f1c0cda132e5d1a6b7f66f98392245e2e5 (Market Hash)
- Request Timestamp: Thu, 03 Apr 2025 22:17:29 GMT

feat(market-map): Update market -- 98866_0_0xb26196c9e8a5a3da90fb034b7398d0f1c0cda132e5d1a6b7f66f98392245e2e5

---

sdk/constants/market-map/98866/definitions/98866_0_0x65734bff78f3adcf98f5dddfe4eb8d86782a4434f3e675131b3c7af0a918bfa4.ts

feat(market-map): Update market -- 98866_0_0x65734bff78f3adcf98f5dddfe4eb8d86782a4434f3e675131b3c7af0a918bfa4 -- Recipe (0x6573...bfa4)
- Market ID: 0x65734bff78f3adcf98f5dddfe4eb8d86782a4434f3e675131b3c7af0a918bfa4 (Market Hash)
- Request Timestamp: Thu, 03 Apr 2025 22:22:00 GMT

feat(market-map): Update market -- 98866_0_0x65734bff78f3adcf98f5dddfe4eb8d86782a4434f3e675131b3c7af0a918bfa4

---

sdk/constants/market-map/98866/definitions/98866_0_0x4f74b6985433522beafdf8744d386905ff9b1f466f92f00be185c4b1ea0c2cdb.ts

feat(market-map): Update market -- 98866_0_0x4f74b6985433522beafdf8744d386905ff9b1f466f92f00be185c4b1ea0c2cdb -- Recipe (0x4f74...2cdb)
- Market ID: 0x4f74b6985433522beafdf8744d386905ff9b1f466f92f00be185c4b1ea0c2cdb (Market Hash)
- Request Timestamp: Thu, 03 Apr 2025 22:27:19 GMT

feat(market-map): Update market -- 98866_0_0x4f74b6985433522beafdf8744d386905ff9b1f466f92f00be185c4b1ea0c2cdb

---

sdk/constants/market-map/98866/definitions/98866_0_0x8a0989ac3d7df5ec7259e5a0b0bfee646dc8a34b4c9de80790fa9625545bd579.ts

feat(market-map): Update market -- 98866_0_0x8a0989ac3d7df5ec7259e5a0b0bfee646dc8a34b4c9de80790fa9625545bd579 -- Recipe (0x8a09...d579)
- Market ID: 0x8a0989ac3d7df5ec7259e5a0b0bfee646dc8a34b4c9de80790fa9625545bd579 (Market Hash)
- Request Timestamp: Thu, 03 Apr 2025 22:31:45 GMT

feat(market-map): Update market -- 98866_0_0x8a0989ac3d7df5ec7259e5a0b0bfee646dc8a34b4c9de80790fa9625545bd579

---

sdk/constants/market-map/98866/definitions/98866_0_0x6d1bfdffda95b0885251bb684a0aa3c005b5503c2ab3ed51c33268cd7549ea28.ts

feat(market-map): Update market -- 98866_0_0x6d1bfdffda95b0885251bb684a0aa3c005b5503c2ab3ed51c33268cd7549ea28 -- Recipe (0x6d1b...ea28)
- Market ID: 0x6d1bfdffda95b0885251bb684a0aa3c005b5503c2ab3ed51c33268cd7549ea28 (Market Hash)
- Request Timestamp: Fri, 04 Apr 2025 19:15:50 GMT

feat(market-map): Update market -- 98866_0_0x6d1bfdffda95b0885251bb684a0aa3c005b5503c2ab3ed51c33268cd7549ea28

---

sdk/constants/market-map/98866/definitions/98866_0_0x213e01d3919905428ff8fd846e89111d80c81d646556a24e9d96838932532f01.ts

feat(market-map): Update market -- 98866_0_0x213e01d3919905428ff8fd846e89111d80c81d646556a24e9d96838932532f01 -- Recipe (0x213e...2f01)
- Market ID: 0x213e01d3919905428ff8fd846e89111d80c81d646556a24e9d96838932532f01 (Market Hash)
- Request Timestamp: Fri, 04 Apr 2025 21:01:12 GMT

feat(market-map): Update market -- 98866_0_0x213e01d3919905428ff8fd846e89111d80c81d646556a24e9d96838932532f01

---

sdk/constants/market-map/98866/definitions/98866_0_0xdc5e7169392a4c0c6955a4db02e90c4e197167cc6b17c5df2da9accbcaa9fa59.ts

feat(market-map): Update market -- 98866_0_0xdc5e7169392a4c0c6955a4db02e90c4e197167cc6b17c5df2da9accbcaa9fa59 -- Recipe (0xdc5e...fa59)
- Market ID: 0xdc5e7169392a4c0c6955a4db02e90c4e197167cc6b17c5df2da9accbcaa9fa59 (Market Hash)
- Request Timestamp: Fri, 04 Apr 2025 21:48:10 GMT

feat(market-map): Update market -- 98866_0_0xdc5e7169392a4c0c6955a4db02e90c4e197167cc6b17c5df2da9accbcaa9fa59

---

sdk/constants/market-map/98866/definitions/98866_0_0xe8cfa9dd3a0f06c880e10b85d7405027331e0c98dc75574769b06dcb60a8b2ad.ts

feat(market-map): Update market -- 98866_0_0xe8cfa9dd3a0f06c880e10b85d7405027331e0c98dc75574769b06dcb60a8b2ad -- Recipe (0xe8cf...b2ad)
- Market ID: 0xe8cfa9dd3a0f06c880e10b85d7405027331e0c98dc75574769b06dcb60a8b2ad (Market Hash)
- Request Timestamp: Mon, 07 Apr 2025 17:36:38 GMT

feat(market-map): Update market -- 98866_0_0xe8cfa9dd3a0f06c880e10b85d7405027331e0c98dc75574769b06dcb60a8b2ad

---

sdk/constants/market-map/98866/definitions/98866_0_0x0bec22d7c0b653e8ef25232c2b42cd59542192c1f40e851d81aaeda82fa14170.ts

feat(market-map): Update market -- 98866_0_0x0bec22d7c0b653e8ef25232c2b42cd59542192c1f40e851d81aaeda82fa14170 -- Recipe (0x0bec...4170)
- Market ID: 0x0bec22d7c0b653e8ef25232c2b42cd59542192c1f40e851d81aaeda82fa14170 (Market Hash)
- Request Timestamp: Mon, 07 Apr 2025 18:50:59 GMT

feat(market-map): Update market -- 98866_0_0x0bec22d7c0b653e8ef25232c2b42cd59542192c1f40e851d81aaeda82fa14170

---

sdk/constants/market-map/98866/definitions/98866_0_0x60c354e05857beb09354abf6adce46ca8e04b35fc261ffacfb62d66312fa71c6.ts

feat(market-map): Update market -- 98866_0_0x60c354e05857beb09354abf6adce46ca8e04b35fc261ffacfb62d66312fa71c6 -- Recipe (0x60c3...71c6)
- Market ID: 0x60c354e05857beb09354abf6adce46ca8e04b35fc261ffacfb62d66312fa71c6 (Market Hash)
- Request Timestamp: Mon, 07 Apr 2025 19:02:06 GMT

feat(market-map): Update market -- 98866_0_0x60c354e05857beb09354abf6adce46ca8e04b35fc261ffacfb62d66312fa71c6

---

sdk/constants/market-map/98866/definitions/98866_0_0xc1ffc7d872da2d80b97435451893660f7174c70800996263023c6e77291b1ccf.ts

feat(market-map): Update market -- 98866_0_0xc1ffc7d872da2d80b97435451893660f7174c70800996263023c6e77291b1ccf -- Recipe (0xc1ff...1ccf)
- Market ID: 0xc1ffc7d872da2d80b97435451893660f7174c70800996263023c6e77291b1ccf (Market Hash)
- Request Timestamp: Tue, 08 Apr 2025 21:26:25 GMT

feat(market-map): Update market -- 98866_0_0xc1ffc7d872da2d80b97435451893660f7174c70800996263023c6e77291b1ccf

---

sdk/constants/market-map/98866/definitions/98866_0_0x023edcffbcdaa45f3c11f7375733ca592361af4ca51945c26cc572b2f86b6ce7.ts

feat(market-map): Update market -- 98866_0_0x023edcffbcdaa45f3c11f7375733ca592361af4ca51945c26cc572b2f86b6ce7 -- Recipe (0x023e...6ce7)
- Market ID: 0x023edcffbcdaa45f3c11f7375733ca592361af4ca51945c26cc572b2f86b6ce7 (Market Hash)
- Request Timestamp: Wed, 09 Apr 2025 17:28:37 GMT

feat(market-map): Update market -- 98866_0_0x023edcffbcdaa45f3c11f7375733ca592361af4ca51945c26cc572b2f86b6ce7

---

sdk/constants/market-map/98866/definitions/98866_0_0x670c560fd97462c086e64e1b3749ee17dea43f508164ee8c77daf863bee634f3.ts

feat(market-map): Update market -- 98866_0_0x670c560fd97462c086e64e1b3749ee17dea43f508164ee8c77daf863bee634f3 -- Recipe (0x670c...34f3)
- Market ID: 0x670c560fd97462c086e64e1b3749ee17dea43f508164ee8c77daf863bee634f3 (Market Hash)
- Request Timestamp: Thu, 10 Apr 2025 22:11:32 GMT

feat(market-map): Update market -- 98866_0_0x670c560fd97462c086e64e1b3749ee17dea43f508164ee8c77daf863bee634f3

---

sdk/constants/market-map/11155111/definitions/11155111_1_0x671dfd188e96278a2cfa7c4245b0d366d2628503.ts

feat(market-map): Update market -- 11155111_1_0x671dfd188e96278a2cfa7c4245b0d366d2628503 -- Vault (0x671d...8503)
- Market ID: 0x671dfd188e96278a2cfa7c4245b0d366d2628503 (Wrapped Vault Address)
- Request Timestamp: Sat, 12 Apr 2025 07:31:20 GMT

feat(market-map): Update market -- 11155111_1_0x671dfd188e96278a2cfa7c4245b0d366d2628503

---

sdk/constants/market-map/11155111/definitions/11155111_1_0x95e45879b574114db41d90cca3700486dc22a977.ts

feat(market-map): Update market -- 11155111_1_0x95e45879b574114db41d90cca3700486dc22a977 -- Vault (0x95e4...a977)
- Market ID: 0x95e45879b574114db41d90cca3700486dc22a977 (Wrapped Vault Address)
- Request Timestamp: Sat, 12 Apr 2025 08:04:43 GMT

feat(market-map): Update market -- 11155111_1_0x95e45879b574114db41d90cca3700486dc22a977

---

sdk/constants/market-map/11155111/definitions/11155111_1_0x95a65b8cf93d6e443976753a50e2550c194e93d6.ts

feat(market-map): Update market -- 11155111_1_0x95a65b8cf93d6e443976753a50e2550c194e93d6 -- Vault (0x95a6...93d6)
- Market ID: 0x95a65b8cf93d6e443976753a50e2550c194e93d6 (Wrapped Vault Address)
- Request Timestamp: Sat, 12 Apr 2025 08:12:41 GMT

feat(market-map): Update market -- 11155111_1_0x95a65b8cf93d6e443976753a50e2550c194e93d6

---

sdk/constants/market-map/98866/definitions/98866_0_0x9dc945e013647ee9dcd9e297b11b1f3185fc9206e88ff92023db5ccd04bdda2c.ts

feat(market-map): Update market -- 98866_0_0x9dc945e013647ee9dcd9e297b11b1f3185fc9206e88ff92023db5ccd04bdda2c -- Recipe (0x9dc9...da2c)
- Market ID: 0x9dc945e013647ee9dcd9e297b11b1f3185fc9206e88ff92023db5ccd04bdda2c (Market Hash)
- Request Timestamp: Mon, 14 Apr 2025 18:50:43 GMT

feat(market-map): Update market -- 98866_0_0x9dc945e013647ee9dcd9e297b11b1f3185fc9206e88ff92023db5ccd04bdda2c

---

sdk/constants/market-map/98866/definitions/98866_0_0x2bdfa3bcf5b6f1a1dff54b846371bf221ee4a33ddc74452101914818a54a5b6e.ts

feat(market-map): Update market -- 98866_0_0x2bdfa3bcf5b6f1a1dff54b846371bf221ee4a33ddc74452101914818a54a5b6e -- Recipe (0x2bdf...5b6e)
- Market ID: 0x2bdfa3bcf5b6f1a1dff54b846371bf221ee4a33ddc74452101914818a54a5b6e (Market Hash)
- Request Timestamp: Mon, 14 Apr 2025 18:55:22 GMT

feat(market-map): Update market -- 98866_0_0x2bdfa3bcf5b6f1a1dff54b846371bf221ee4a33ddc74452101914818a54a5b6e

---

sdk/constants/market-map/98866/definitions/98866_0_0xbba4b98b19f6f8230c46413c7f0d128ce438dcbe24ae2f40d124b6e7b4f91eb5.ts

feat(market-map): Update market -- 98866_0_0xbba4b98b19f6f8230c46413c7f0d128ce438dcbe24ae2f40d124b6e7b4f91eb5 -- Recipe (0xbba4...1eb5)
- Market ID: 0xbba4b98b19f6f8230c46413c7f0d128ce438dcbe24ae2f40d124b6e7b4f91eb5 (Market Hash)
- Request Timestamp: Tue, 15 Apr 2025 00:02:08 GMT

feat(market-map): Update market -- 98866_0_0xbba4b98b19f6f8230c46413c7f0d128ce438dcbe24ae2f40d124b6e7b4f91eb5

---

sdk/constants/market-map/98866/definitions/98866_0_0xf69d122de4072ea3cdc89ad920c6253149d7d874b139c4ffde8bba6f0d177f50.ts

feat(market-map): Update market -- 98866_0_0xf69d122de4072ea3cdc89ad920c6253149d7d874b139c4ffde8bba6f0d177f50 -- Recipe (0xf69d...7f50)
- Market ID: 0xf69d122de4072ea3cdc89ad920c6253149d7d874b139c4ffde8bba6f0d177f50 (Market Hash)
- Request Timestamp: Tue, 15 Apr 2025 00:54:49 GMT

feat(market-map): Update market -- 98866_0_0xf69d122de4072ea3cdc89ad920c6253149d7d874b139c4ffde8bba6f0d177f50

---

sdk/constants/market-map/98866/definitions/98866_0_0x11c0d2e939d550da04ff69f76b699885b9d62d942dbf9465c6eb2d64fcac0939.ts

feat(market-map): Update market -- 98866_0_0x11c0d2e939d550da04ff69f76b699885b9d62d942dbf9465c6eb2d64fcac0939 -- Recipe (0x11c0...0939)
- Market ID: 0x11c0d2e939d550da04ff69f76b699885b9d62d942dbf9465c6eb2d64fcac0939 (Market Hash)
- Request Timestamp: Tue, 15 Apr 2025 00:57:15 GMT

feat(market-map): Update market -- 98866_0_0x11c0d2e939d550da04ff69f76b699885b9d62d942dbf9465c6eb2d64fcac0939

---

sdk/constants/market-map/1/definitions/1_0_0xc55f7e179abed67f34cdf01a0d313336ab5bc2dd84c834325c91c311ec079c6b.ts

feat(market-map): Update market -- 1_0_0xc55f7e179abed67f34cdf01a0d313336ab5bc2dd84c834325c91c311ec079c6b -- Recipe (0xc55f...9c6b)
- Chain ID: 1
- Market ID: 0xc55f7e179abed67f34cdf01a0d313336ab5bc2dd84c834325c91c311ec079c6b (Market Hash)
- Request Timestamp: Tue, 15 Apr 2025 09:14:06 GMT

feat(market-map): Update market -- 1_0_0xc55f7e179abed67f34cdf01a0d313336ab5bc2dd84c834325c91c311ec079c6b

---

sdk/constants/market-map/98866/definitions/98866_0_0xbf398306282c870f89f4e604594355434f4518da6aaf5fa883d459fd69588b48.ts

feat(market-map): Update market -- 98866_0_0xbf398306282c870f89f4e604594355434f4518da6aaf5fa883d459fd69588b48 -- Recipe (0xbf39...8b48)
- Market ID: 0xbf398306282c870f89f4e604594355434f4518da6aaf5fa883d459fd69588b48 (Market Hash)
- Request Timestamp: Tue, 15 Apr 2025 19:18:22 GMT

feat(market-map): Update market -- 98866_0_0xbf398306282c870f89f4e604594355434f4518da6aaf5fa883d459fd69588b48

---

sdk/constants/market-map/999/definitions/999_0_0x135a8b25c07db741421b1201f7d68b9169b9b58a18f333f9b22212dbe343de1d.ts

feat(market-map): Update market -- 999_0_0x135a8b25c07db741421b1201f7d68b9169b9b58a18f333f9b22212dbe343de1d -- Recipe (0x135a...de1d)
- Chain ID: 999
- Market ID: 0x135a8b25c07db741421b1201f7d68b9169b9b58a18f333f9b22212dbe343de1d (Market Hash)
- Request Timestamp: Tue, 15 Apr 2025 22:27:30 GMT

feat(market-map): Update market -- 999_0_0x135a8b25c07db741421b1201f7d68b9169b9b58a18f333f9b22212dbe343de1d

---

sdk/constants/market-map/98866/definitions/98866_0_0x8a323730895f90120bc4593b1656a1e47b1d55188b1655a3e2666e89485f1d63.ts

feat(market-map): Update market -- 98866_0_0x8a323730895f90120bc4593b1656a1e47b1d55188b1655a3e2666e89485f1d63 -- Recipe (0x8a32...1d63)
- Market ID: 0x8a323730895f90120bc4593b1656a1e47b1d55188b1655a3e2666e89485f1d63 (Market Hash)
- Request Timestamp: Thu, 17 Apr 2025 04:22:04 GMT

feat(market-map): Update market -- 98866_0_0x8a323730895f90120bc4593b1656a1e47b1d55188b1655a3e2666e89485f1d63

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x5601a1f7c51d55dedae99ccea424fe728b05e48d9f45b417e9655ce22aaafff4.ts

feat(market-map): Update market -- 11155111_0_0x5601a1f7c51d55dedae99ccea424fe728b05e48d9f45b417e9655ce22aaafff4 -- Recipe (0x5601...fff4)
- Market ID: 0x5601a1f7c51d55dedae99ccea424fe728b05e48d9f45b417e9655ce22aaafff4 (Market Hash)
- Request Timestamp: Fri, 18 Apr 2025 01:28:29 GMT

feat(market-map): Update market -- 11155111_0_0x5601a1f7c51d55dedae99ccea424fe728b05e48d9f45b417e9655ce22aaafff4

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x9c4d5bd1f4c56b3a7b03537144ea9f4ef85c0da9b860ed88187f0c14d3c2f258.ts

feat(market-map): Update market -- 11155111_0_0x9c4d5bd1f4c56b3a7b03537144ea9f4ef85c0da9b860ed88187f0c14d3c2f258 -- Recipe (0x9c4d...f258)
- Market ID: 0x9c4d5bd1f4c56b3a7b03537144ea9f4ef85c0da9b860ed88187f0c14d3c2f258 (Market Hash)
- Request Timestamp: Fri, 18 Apr 2025 02:45:05 GMT

feat(market-map): Update market -- 11155111_0_0x9c4d5bd1f4c56b3a7b03537144ea9f4ef85c0da9b860ed88187f0c14d3c2f258

---

sdk/constants/market-map/1/definitions/1_1_0xd845f6d6748f74360cd977f7fb6b9a3b73439021.ts

feat(market-map): Update market -- 1_1_0xd845f6d6748f74360cd977f7fb6b9a3b73439021 -- Vault (0xd845...9021)
- Chain ID: 1
- Market ID: 0xd845f6d6748f74360cd977f7fb6b9a3b73439021 (Wrapped Vault Address)
- Request Timestamp: Fri, 18 Apr 2025 06:16:33 GMT

feat(market-map): Update market -- 1_1_0xd845f6d6748f74360cd977f7fb6b9a3b73439021

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x3c84bbc3a0680564b69aceb6894939344dcf65d424991df77cf25870ab06a423.ts

feat(market-map): Update market -- 11155111_0_0x3c84bbc3a0680564b69aceb6894939344dcf65d424991df77cf25870ab06a423 -- Recipe (0x3c84...a423)
- Market ID: 0x3c84bbc3a0680564b69aceb6894939344dcf65d424991df77cf25870ab06a423 (Market Hash)
- Request Timestamp: Fri, 18 Apr 2025 09:33:33 GMT

feat(market-map): Update market -- 11155111_0_0x3c84bbc3a0680564b69aceb6894939344dcf65d424991df77cf25870ab06a423

---

sdk/constants/market-map/98866/definitions/98866_0_0x2807a6b682560c9b110d66ed1598accc1c0e043fad91d55a6790a00c942f08e9.ts

feat(market-map): Update market -- 98866_0_0x2807a6b682560c9b110d66ed1598accc1c0e043fad91d55a6790a00c942f08e9 -- Recipe (0x2807...08e9)
- Market ID: 0x2807a6b682560c9b110d66ed1598accc1c0e043fad91d55a6790a00c942f08e9 (Market Hash)
- Request Timestamp: Fri, 18 Apr 2025 10:30:50 GMT

feat(market-map): Update market -- 98866_0_0x2807a6b682560c9b110d66ed1598accc1c0e043fad91d55a6790a00c942f08e9

---

sdk/constants/market-map/146/definitions/146_0_0x5ba168d51627169be3942d735346d35101e4cdc02092bceee8882722bc407b04.ts

feat(market-map): Update market -- 146_0_0x5ba168d51627169be3942d735346d35101e4cdc02092bceee8882722bc407b04 -- Recipe (0x5ba1...7b04)
- Market ID: 0x5ba168d51627169be3942d735346d35101e4cdc02092bceee8882722bc407b04 (Market Hash)
- Request Timestamp: Fri, 18 Apr 2025 11:46:46 GMT

feat(market-map): Update market -- 146_0_0x5ba168d51627169be3942d735346d35101e4cdc02092bceee8882722bc407b04

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x03759fb81907d61b9659c35d67d8eb215976179bdd59d73878c1c12898ae90a3.ts

feat(market-map): Update market -- 11155111_0_0x03759fb81907d61b9659c35d67d8eb215976179bdd59d73878c1c12898ae90a3 -- Recipe (0x0375...90a3)
- Market ID: 0x03759fb81907d61b9659c35d67d8eb215976179bdd59d73878c1c12898ae90a3 (Market Hash)
- Request Timestamp: Fri, 18 Apr 2025 13:44:04 GMT

feat(market-map): Update market -- 11155111_0_0x03759fb81907d61b9659c35d67d8eb215976179bdd59d73878c1c12898ae90a3

---

sdk/constants/market-map/98866/definitions/98866_0_0x72ca67a025655b3985a22fa50112bdfcb3736e7ebf42e34570122d76cff52b30.ts

feat(market-map): Update market -- 98866_0_0x72ca67a025655b3985a22fa50112bdfcb3736e7ebf42e34570122d76cff52b30 -- Recipe (0x72ca...2b30)
- Market ID: 0x72ca67a025655b3985a22fa50112bdfcb3736e7ebf42e34570122d76cff52b30 (Market Hash)
- Request Timestamp: Sat, 19 Apr 2025 20:58:58 GMT

feat(market-map): Update market -- 98866_0_0x72ca67a025655b3985a22fa50112bdfcb3736e7ebf42e34570122d76cff52b30

---

sdk/constants/market-map/98866/definitions/98866_0_0xf7f9dadab7c91a3761c6e3bca7b5a2ad3411ef6d249a30fa0109d52306569048.ts

feat(market-map): Update market -- 98866_0_0xf7f9dadab7c91a3761c6e3bca7b5a2ad3411ef6d249a30fa0109d52306569048 -- Recipe (0xf7f9...9048)
- Market ID: 0xf7f9dadab7c91a3761c6e3bca7b5a2ad3411ef6d249a30fa0109d52306569048 (Market Hash)
- Request Timestamp: Sat, 19 Apr 2025 22:21:03 GMT

feat(market-map): Update market -- 98866_0_0xf7f9dadab7c91a3761c6e3bca7b5a2ad3411ef6d249a30fa0109d52306569048

---

sdk/constants/token-map/146/definitions/146-0xe600c9c2129A78D3845Bd9E2DefeF296af3Ec5B8.ts
sdk/constants/token-map/146/index.ts

feat(token-map): 146-0xe600c9c2129A78D3845Bd9E2DefeF296af3Ec5B8.ts

---

sdk/constants/token-map/146/definitions/146-0x29618C821B5c4027e9D50D5051Ed116d808b87d5.ts
sdk/constants/token-map/146/index.ts

Updated Points Program Address for RFX Particle Points

Token Map Address Update 146-0x29618C821B5c4027e9D50D5051Ed116d808b87d5

---

sdk/constants/market-map/98866/definitions/98866_0_0x60b09ad85cacf66b99d8e8341715035d60517785bca4da8f69b8950ba2351a22.ts

feat(market-map): Update market -- 98866_0_0x60b09ad85cacf66b99d8e8341715035d60517785bca4da8f69b8950ba2351a22 -- Recipe (0x60b0...1a22)
- Market ID: 0x60b09ad85cacf66b99d8e8341715035d60517785bca4da8f69b8950ba2351a22 (Market Hash)
- Request Timestamp: Tue, 22 Apr 2025 17:21:10 GMT

feat(market-map): Update market -- 98866_0_0x60b09ad85cacf66b99d8e8341715035d60517785bca4da8f69b8950ba2351a22

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x8def383f01e44c44b76df46c5d5a716b5999e17dabc5c0a3258ce89f5b2b8801.ts

feat(market-map): Update market -- 11155111_0_0x8def383f01e44c44b76df46c5d5a716b5999e17dabc5c0a3258ce89f5b2b8801 -- Recipe (0x8def...8801)
- Market ID: 0x8def383f01e44c44b76df46c5d5a716b5999e17dabc5c0a3258ce89f5b2b8801 (Market Hash)
- Request Timestamp: Tue, 22 Apr 2025 17:35:46 GMT

feat(market-map): Update market -- 11155111_0_0x8def383f01e44c44b76df46c5d5a716b5999e17dabc5c0a3258ce89f5b2b8801

---

sdk/constants/market-map/146/definitions/146_0_0xec783a68452e3fc44de0f5c9769c312be9ed17fbb4594f635eea88230ec68c28.ts

feat(market-map): Update market -- 146_0_0xec783a68452e3fc44de0f5c9769c312be9ed17fbb4594f635eea88230ec68c28 -- Recipe (0xec78...8c28)
- Market ID: 0xec783a68452e3fc44de0f5c9769c312be9ed17fbb4594f635eea88230ec68c28 (Market Hash)
- Request Timestamp: Wed, 23 Apr 2025 11:06:44 GMT

feat(market-map): Update market -- 146_0_0xec783a68452e3fc44de0f5c9769c312be9ed17fbb4594f635eea88230ec68c28

---

sdk/constants/market-map/98866/definitions/98866_0_0x7f45154e5bef3a8a39f0170c93b7da4a0fa97141909114d5aa8986d2486ddc77.ts

feat(market-map): Update market -- 98866_0_0x7f45154e5bef3a8a39f0170c93b7da4a0fa97141909114d5aa8986d2486ddc77 -- Recipe (0x7f45...dc77)
- Market ID: 0x7f45154e5bef3a8a39f0170c93b7da4a0fa97141909114d5aa8986d2486ddc77 (Market Hash)
- Request Timestamp: Wed, 23 Apr 2025 11:44:43 GMT

feat(market-map): Update market -- 98866_0_0x7f45154e5bef3a8a39f0170c93b7da4a0fa97141909114d5aa8986d2486ddc77

---

sdk/constants/market-map/98866/definitions/98866_0_0x0ab8aa50a791bed9e6aea64db916afa82d6d5ca5a284e76575fe09bfd9bb9e6a.ts

feat(market-map): Update market -- 98866_0_0x0ab8aa50a791bed9e6aea64db916afa82d6d5ca5a284e76575fe09bfd9bb9e6a -- Recipe (0x0ab8...9e6a)
- Market ID: 0x0ab8aa50a791bed9e6aea64db916afa82d6d5ca5a284e76575fe09bfd9bb9e6a (Market Hash)
- Request Timestamp: Wed, 23 Apr 2025 11:57:54 GMT

feat(market-map): Update market -- 98866_0_0x0ab8aa50a791bed9e6aea64db916afa82d6d5ca5a284e76575fe09bfd9bb9e6a

---

sdk/constants/market-map/98866/definitions/98866_0_0x66a4f7333d14307e5559b0ceb3c9f122459b7efaa77b2e4428c1ebd355a20cb2.ts

feat(market-map): Update market -- 98866_0_0x66a4f7333d14307e5559b0ceb3c9f122459b7efaa77b2e4428c1ebd355a20cb2 -- Recipe (0x66a4...0cb2)
- Market ID: 0x66a4f7333d14307e5559b0ceb3c9f122459b7efaa77b2e4428c1ebd355a20cb2 (Market Hash)
- Request Timestamp: Wed, 23 Apr 2025 12:53:47 GMT

feat(market-map): Update market -- 98866_0_0x66a4f7333d14307e5559b0ceb3c9f122459b7efaa77b2e4428c1ebd355a20cb2

---

sdk/constants/market-map/98866/definitions/98866_0_0xd02a8393b18fbba3cd4d89ddb29708c1b31f0fe4c6124610512486b70db023ab.ts

feat(market-map): Update market -- 98866_0_0xd02a8393b18fbba3cd4d89ddb29708c1b31f0fe4c6124610512486b70db023ab -- Recipe (0xd02a...23ab)
- Market ID: 0xd02a8393b18fbba3cd4d89ddb29708c1b31f0fe4c6124610512486b70db023ab (Market Hash)
- Request Timestamp: Wed, 23 Apr 2025 16:00:32 GMT

feat(market-map): Update market -- 98866_0_0xd02a8393b18fbba3cd4d89ddb29708c1b31f0fe4c6124610512486b70db023ab

---

sdk/constants/market-map/98866/definitions/98866_0_0xa9fa7ce37cfa352c661701ed1c2583465a7753d4d94b792e0cc49a60e6004ed3.ts

feat(market-map): Update market -- 98866_0_0xa9fa7ce37cfa352c661701ed1c2583465a7753d4d94b792e0cc49a60e6004ed3 -- Recipe (0xa9fa...4ed3)
- Market ID: 0xa9fa7ce37cfa352c661701ed1c2583465a7753d4d94b792e0cc49a60e6004ed3 (Market Hash)
- Request Timestamp: Wed, 23 Apr 2025 16:35:57 GMT

feat(market-map): Update market -- 98866_0_0xa9fa7ce37cfa352c661701ed1c2583465a7753d4d94b792e0cc49a60e6004ed3

---

sdk/constants/market-map/98866/definitions/98866_0_0x40bb8b77686fdea111f3e5b369dacd049abb8224550b453b6308b1038638e355.ts

feat(market-map): Update market -- 98866_0_0x40bb8b77686fdea111f3e5b369dacd049abb8224550b453b6308b1038638e355 -- Recipe (0x40bb...e355)
- Market ID: 0x40bb8b77686fdea111f3e5b369dacd049abb8224550b453b6308b1038638e355 (Market Hash)
- Request Timestamp: Wed, 23 Apr 2025 16:47:20 GMT

feat(market-map): Update market -- 98866_0_0x40bb8b77686fdea111f3e5b369dacd049abb8224550b453b6308b1038638e355

---

sdk/constants/market-map/98866/definitions/98866_0_0xf06a072a23e0550634bfdc93dc0174b0eeb502731de51b63ee05c80d8dd448b2.ts

feat(market-map): Update market -- 98866_0_0xf06a072a23e0550634bfdc93dc0174b0eeb502731de51b63ee05c80d8dd448b2 -- Recipe (0xf06a...48b2)
- Market ID: 0xf06a072a23e0550634bfdc93dc0174b0eeb502731de51b63ee05c80d8dd448b2 (Market Hash)
- Request Timestamp: Wed, 23 Apr 2025 17:01:32 GMT

feat(market-map): Update market -- 98866_0_0xf06a072a23e0550634bfdc93dc0174b0eeb502731de51b63ee05c80d8dd448b2

---

sdk/constants/market-map/98866/definitions/98866_0_0x3d971045e3d8bd67d8b8e1c9ec1e1e7cd08463f502d79e6c0875d626415fcfaf.ts

feat(market-map): Update market -- 98866_0_0x3d971045e3d8bd67d8b8e1c9ec1e1e7cd08463f502d79e6c0875d626415fcfaf -- Recipe (0x3d97...cfaf)
- Market ID: 0x3d971045e3d8bd67d8b8e1c9ec1e1e7cd08463f502d79e6c0875d626415fcfaf (Market Hash)
- Request Timestamp: Wed, 23 Apr 2025 17:11:34 GMT

feat(market-map): Update market -- 98866_0_0x3d971045e3d8bd67d8b8e1c9ec1e1e7cd08463f502d79e6c0875d626415fcfaf

---

sdk/constants/market-map/98866/definitions/98866_0_0x2350ad77868ea5ed3cb6b3068a5891529c20ad62b1bdde0904a464163f8813f8.ts

feat(market-map): Update market -- 98866_0_0x2350ad77868ea5ed3cb6b3068a5891529c20ad62b1bdde0904a464163f8813f8 -- Recipe (0x2350...13f8)
- Market ID: 0x2350ad77868ea5ed3cb6b3068a5891529c20ad62b1bdde0904a464163f8813f8 (Market Hash)
- Request Timestamp: Wed, 23 Apr 2025 17:29:35 GMT

feat(market-map): Update market -- 98866_0_0x2350ad77868ea5ed3cb6b3068a5891529c20ad62b1bdde0904a464163f8813f8

---

sdk/constants/market-map/98866/definitions/98866_0_0x366a10211a18cb5804df637aca00cae8fd6680474bb184f920c7343d46d3c876.ts

feat(market-map): Update market -- 98866_0_0x366a10211a18cb5804df637aca00cae8fd6680474bb184f920c7343d46d3c876 -- Recipe (0x366a...c876)
- Market ID: 0x366a10211a18cb5804df637aca00cae8fd6680474bb184f920c7343d46d3c876 (Market Hash)
- Request Timestamp: Wed, 23 Apr 2025 17:38:19 GMT

feat(market-map): Update market -- 98866_0_0x366a10211a18cb5804df637aca00cae8fd6680474bb184f920c7343d46d3c876

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xd219313b6c627adf628525e24e5369797ecd1f1841bd3f02b60b2c6435ee9f20.ts

feat(market-map): Update market -- 11155111_0_0xd219313b6c627adf628525e24e5369797ecd1f1841bd3f02b60b2c6435ee9f20 -- Recipe (0xd219...9f20)
- Market ID: 0xd219313b6c627adf628525e24e5369797ecd1f1841bd3f02b60b2c6435ee9f20 (Market Hash)
- Request Timestamp: Wed, 23 Apr 2025 17:58:42 GMT

feat(market-map): Update market -- 11155111_0_0xd219313b6c627adf628525e24e5369797ecd1f1841bd3f02b60b2c6435ee9f20

---

sdk/constants/market-map/98866/definitions/98866_0_0x71da305e14044d38fb95d6b25f1ce9fa5702085611e0c387931764ad4ec072f9.ts

feat(market-map): Update market -- 98866_0_0x71da305e14044d38fb95d6b25f1ce9fa5702085611e0c387931764ad4ec072f9 -- Recipe (0x71da...72f9)
- Market ID: 0x71da305e14044d38fb95d6b25f1ce9fa5702085611e0c387931764ad4ec072f9 (Market Hash)
- Request Timestamp: Wed, 23 Apr 2025 18:16:12 GMT

feat(market-map): Update market -- 98866_0_0x71da305e14044d38fb95d6b25f1ce9fa5702085611e0c387931764ad4ec072f9

---

sdk/constants/market-map/98866/definitions/98866_0_0x3e62aafbbf762e50e559cd618d81e8451306932a2ce9114391d606cea8e254c7.ts

feat(market-map): Update market -- 98866_0_0x3e62aafbbf762e50e559cd618d81e8451306932a2ce9114391d606cea8e254c7 -- Recipe (0x3e62...54c7)
- Market ID: 0x3e62aafbbf762e50e559cd618d81e8451306932a2ce9114391d606cea8e254c7 (Market Hash)
- Request Timestamp: Wed, 23 Apr 2025 18:22:54 GMT

feat(market-map): Update market -- 98866_0_0x3e62aafbbf762e50e559cd618d81e8451306932a2ce9114391d606cea8e254c7

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xb7be8b6efee4c2d1fead07d98c3a4b3d3c85dff0d1800294c27782b550099fc4.ts

feat(market-map): Update market -- 11155111_0_0xb7be8b6efee4c2d1fead07d98c3a4b3d3c85dff0d1800294c27782b550099fc4 -- Recipe (0xb7be...9fc4)
- Market ID: 0xb7be8b6efee4c2d1fead07d98c3a4b3d3c85dff0d1800294c27782b550099fc4 (Market Hash)
- Request Timestamp: Wed, 23 Apr 2025 18:23:54 GMT

feat(market-map): Update market -- 11155111_0_0xb7be8b6efee4c2d1fead07d98c3a4b3d3c85dff0d1800294c27782b550099fc4

---

sdk/constants/market-map/98866/definitions/98866_0_0x35fa8e161c16fd373af9694440d3997169bbcfd173351b150af627289cedfb58.ts

feat(market-map): Update market -- 98866_0_0x35fa8e161c16fd373af9694440d3997169bbcfd173351b150af627289cedfb58 -- Recipe (0x35fa...fb58)
- Market ID: 0x35fa8e161c16fd373af9694440d3997169bbcfd173351b150af627289cedfb58 (Market Hash)
- Request Timestamp: Wed, 23 Apr 2025 18:48:19 GMT

feat(market-map): Update market -- 98866_0_0x35fa8e161c16fd373af9694440d3997169bbcfd173351b150af627289cedfb58

---

sdk/constants/market-map/98866/definitions/98866_0_0x579faf40ca0f509b535552cf032c6b24030fa2c4b3e69f269f6c9520a7fffb1b.ts

feat(market-map): Update market -- 98866_0_0x579faf40ca0f509b535552cf032c6b24030fa2c4b3e69f269f6c9520a7fffb1b -- Recipe (0x579f...fb1b)
- Market ID: 0x579faf40ca0f509b535552cf032c6b24030fa2c4b3e69f269f6c9520a7fffb1b (Market Hash)
- Request Timestamp: Wed, 23 Apr 2025 22:55:23 GMT

feat(market-map): Update market -- 98866_0_0x579faf40ca0f509b535552cf032c6b24030fa2c4b3e69f269f6c9520a7fffb1b

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x98e2e674a5dbf76b25a89b9f2e38f1d918ae77612be6743f430d38765437f942.ts

feat(market-map): Update market -- 11155111_0_0x98e2e674a5dbf76b25a89b9f2e38f1d918ae77612be6743f430d38765437f942 -- Recipe (0x98e2...f942)
- Market ID: 0x98e2e674a5dbf76b25a89b9f2e38f1d918ae77612be6743f430d38765437f942 (Market Hash)
- Request Timestamp: Thu, 24 Apr 2025 17:03:16 GMT

feat(market-map): Update market -- 11155111_0_0x98e2e674a5dbf76b25a89b9f2e38f1d918ae77612be6743f430d38765437f942

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x2a6887b796cd9b7fe5520f1ac0efb019fc44323ddd847f5f71e312d6fbab4ac9.ts

feat(market-map): Update market -- 11155111_0_0x2a6887b796cd9b7fe5520f1ac0efb019fc44323ddd847f5f71e312d6fbab4ac9 -- Recipe (0x2a68...4ac9)
- Market ID: 0x2a6887b796cd9b7fe5520f1ac0efb019fc44323ddd847f5f71e312d6fbab4ac9 (Market Hash)
- Request Timestamp: Thu, 24 Apr 2025 17:46:54 GMT

feat(market-map): Update market -- 11155111_0_0x2a6887b796cd9b7fe5520f1ac0efb019fc44323ddd847f5f71e312d6fbab4ac9

---

sdk/constants/market-map/98866/definitions/98866_0_0x3b8a0521b465839cdfe5370ffe0d67259adc91424339ccee8db144dae3f742f1.ts

feat(market-map): Update market -- 98866_0_0x3b8a0521b465839cdfe5370ffe0d67259adc91424339ccee8db144dae3f742f1 -- Recipe (0x3b8a...42f1)
- Market ID: 0x3b8a0521b465839cdfe5370ffe0d67259adc91424339ccee8db144dae3f742f1 (Market Hash)
- Request Timestamp: Thu, 24 Apr 2025 22:47:20 GMT

feat(market-map): Update market -- 98866_0_0x3b8a0521b465839cdfe5370ffe0d67259adc91424339ccee8db144dae3f742f1

---

sdk/constants/market-map/98866/definitions/98866_0_0xb52a7b315f1f0a83c6cdec526a72198c9c09c9e25d7a145a3a4086f114fbb91c.ts

feat(market-map): Update market -- 98866_0_0xb52a7b315f1f0a83c6cdec526a72198c9c09c9e25d7a145a3a4086f114fbb91c -- Recipe (0xb52a...b91c)
- Market ID: 0xb52a7b315f1f0a83c6cdec526a72198c9c09c9e25d7a145a3a4086f114fbb91c (Market Hash)
- Request Timestamp: Thu, 24 Apr 2025 23:54:59 GMT

feat(market-map): Update market -- 98866_0_0xb52a7b315f1f0a83c6cdec526a72198c9c09c9e25d7a145a3a4086f114fbb91c

---

sdk/constants/market-map/98866/definitions/98866_0_0x6ff6282aec81d863959225895e93aa02f7e9fee8a7d41f24281db8956d64f6a2.ts

feat(market-map): Update market -- 98866_0_0x6ff6282aec81d863959225895e93aa02f7e9fee8a7d41f24281db8956d64f6a2 -- Recipe (0x6ff6...f6a2)
- Market ID: 0x6ff6282aec81d863959225895e93aa02f7e9fee8a7d41f24281db8956d64f6a2 (Market Hash)
- Request Timestamp: Fri, 25 Apr 2025 00:36:16 GMT

feat(market-map): Update market -- 98866_0_0x6ff6282aec81d863959225895e93aa02f7e9fee8a7d41f24281db8956d64f6a2

---

sdk/constants/market-map/8453/definitions/8453_1_0x10a1bca416313725daeaf4eb0478c0c00d34eb52.ts

feat(market-map): Update market -- 8453_1_0x10a1bca416313725daeaf4eb0478c0c00d34eb52 -- Vault (0x10a1...eb52)
- Market ID: 0x10a1bca416313725daeaf4eb0478c0c00d34eb52 (Wrapped Vault Address)
- Request Timestamp: Mon, 28 Apr 2025 08:05:00 GMT

feat(market-map): Update market -- 8453_1_0x10a1bca416313725daeaf4eb0478c0c00d34eb52

---

sdk/constants/market-map/98866/definitions/98866_0_0xcd4c52c859c5e96e3d2c787def900658e942a0bac7c615f19ede6d207a0538cc.ts

feat(market-map): Update market -- 98866_0_0xcd4c52c859c5e96e3d2c787def900658e942a0bac7c615f19ede6d207a0538cc -- Recipe (0xcd4c...38cc)
- Market ID: 0xcd4c52c859c5e96e3d2c787def900658e942a0bac7c615f19ede6d207a0538cc (Market Hash)
- Request Timestamp: Mon, 28 Apr 2025 14:00:06 GMT

feat(market-map): Update market -- 98866_0_0xcd4c52c859c5e96e3d2c787def900658e942a0bac7c615f19ede6d207a0538cc

---

sdk/constants/market-map/98866/definitions/98866_0_0x0e8ed2a7fc70f142f3fb6edcbc6b6087efd89937e04b9555016b60fc3ab732af.ts

feat(market-map): Update market -- 98866_0_0x0e8ed2a7fc70f142f3fb6edcbc6b6087efd89937e04b9555016b60fc3ab732af -- Recipe (0x0e8e...32af)
- Market ID: 0x0e8ed2a7fc70f142f3fb6edcbc6b6087efd89937e04b9555016b60fc3ab732af (Market Hash)
- Request Timestamp: Mon, 28 Apr 2025 18:42:00 GMT

feat(market-map): Update market -- 98866_0_0x0e8ed2a7fc70f142f3fb6edcbc6b6087efd89937e04b9555016b60fc3ab732af

---

sdk/constants/market-map/98866/definitions/98866_0_0x23a84a85084361ee8aebd958e918c4e336510af0bf5092f6b649195fb26aea22.ts

feat(market-map): Update market -- 98866_0_0x23a84a85084361ee8aebd958e918c4e336510af0bf5092f6b649195fb26aea22 -- Recipe (0x23a8...ea22)
- Market ID: 0x23a84a85084361ee8aebd958e918c4e336510af0bf5092f6b649195fb26aea22 (Market Hash)
- Request Timestamp: Mon, 28 Apr 2025 18:44:06 GMT

feat(market-map): Update market -- 98866_0_0x23a84a85084361ee8aebd958e918c4e336510af0bf5092f6b649195fb26aea22

---

sdk/constants/market-map/98866/definitions/98866_0_0x508897cc8d87f260a5d2ca64c4d87a17903e0c4cb10684d284e934dbb9604886.ts

feat(market-map): Update market -- 98866_0_0x508897cc8d87f260a5d2ca64c4d87a17903e0c4cb10684d284e934dbb9604886 -- Recipe (0x5088...4886)
- Market ID: 0x508897cc8d87f260a5d2ca64c4d87a17903e0c4cb10684d284e934dbb9604886 (Market Hash)
- Request Timestamp: Mon, 28 Apr 2025 19:07:18 GMT

feat(market-map): Update market -- 98866_0_0x508897cc8d87f260a5d2ca64c4d87a17903e0c4cb10684d284e934dbb9604886

---

sdk/constants/market-map/1/definitions/1_1_0xe951eb523ce216ce777fda067675a9ba7d8ee63c.ts

feat(market-map): Update market -- 1_1_0xe951eb523ce216ce777fda067675a9ba7d8ee63c -- Vault (0xe951...e63c)
- Chain ID: 1
- Market ID: 0xe951eb523ce216ce777fda067675a9ba7d8ee63c (Wrapped Vault Address)
- Request Timestamp: Thu, 01 May 2025 09:58:41 GMT

feat(market-map): Update market -- 1_1_0xe951eb523ce216ce777fda067675a9ba7d8ee63c

---

sdk/constants/market-map/146/definitions/146_0_0x6cbe082176bca0ccd12323e537af91cd3a1bba77920cbfad6b20aa6287c299f1.ts

feat(market-map): Update market -- 146_0_0x6cbe082176bca0ccd12323e537af91cd3a1bba77920cbfad6b20aa6287c299f1 -- Recipe (0x6cbe...99f1)
- Market ID: 0x6cbe082176bca0ccd12323e537af91cd3a1bba77920cbfad6b20aa6287c299f1 (Market Hash)
- Request Timestamp: Fri, 02 May 2025 11:36:02 GMT

feat(market-map): Update market -- 146_0_0x6cbe082176bca0ccd12323e537af91cd3a1bba77920cbfad6b20aa6287c299f1

---

sdk/constants/market-map/146/definitions/146_0_0xd521138f8028d18faa22b48577216c1bfd46b2a1ac7bd0d253dea84b24cd1938.ts

feat(market-map): Update market -- 146_0_0xd521138f8028d18faa22b48577216c1bfd46b2a1ac7bd0d253dea84b24cd1938 -- Recipe (0xd521...1938)
- Market ID: 0xd521138f8028d18faa22b48577216c1bfd46b2a1ac7bd0d253dea84b24cd1938 (Market Hash)
- Request Timestamp: Fri, 02 May 2025 11:44:40 GMT

feat(market-map): Update market -- 146_0_0xd521138f8028d18faa22b48577216c1bfd46b2a1ac7bd0d253dea84b24cd1938

---

sdk/constants/market-map/1/definitions/1_0_0x6c3c178d5f252162c1607c6aaaf6de8a950287093469e62629df9544076c5c64.ts

feat(market-map): Update market -- 1_0_0x6c3c178d5f252162c1607c6aaaf6de8a950287093469e62629df9544076c5c64 -- Recipe (0x6c3c...5c64)
- Chain ID: 1
- Market ID: 0x6c3c178d5f252162c1607c6aaaf6de8a950287093469e62629df9544076c5c64 (Market Hash)
- Request Timestamp: Mon, 05 May 2025 00:21:57 GMT

feat(market-map): Update market -- 1_0_0x6c3c178d5f252162c1607c6aaaf6de8a950287093469e62629df9544076c5c64

---

sdk/constants/market-map/1/definitions/1_0_0xad0638b8e54fe13974731cbe9ecbeeb3bd67b0c66163d5995427ee3a7367880a.ts

feat(market-map): Update market -- 1_0_0xad0638b8e54fe13974731cbe9ecbeeb3bd67b0c66163d5995427ee3a7367880a -- Recipe (0xad06...880a)
- Chain ID: 1
- Market ID: 0xad0638b8e54fe13974731cbe9ecbeeb3bd67b0c66163d5995427ee3a7367880a (Market Hash)
- Request Timestamp: Wed, 07 May 2025 05:54:59 GMT

feat(market-map): Update market -- 1_0_0xad0638b8e54fe13974731cbe9ecbeeb3bd67b0c66163d5995427ee3a7367880a

---

sdk/constants/market-map/98866/definitions/98866_0_0x7c53c4b8b0c83bbf2e5a5217d1f175f9658e93f091c7f0e9b561af20b182fd8d.ts

feat(market-map): Update market -- 98866_0_0x7c53c4b8b0c83bbf2e5a5217d1f175f9658e93f091c7f0e9b561af20b182fd8d -- Recipe (0x7c53...fd8d)
- Market ID: 0x7c53c4b8b0c83bbf2e5a5217d1f175f9658e93f091c7f0e9b561af20b182fd8d (Market Hash)
- Request Timestamp: Fri, 09 May 2025 01:14:23 GMT

feat(market-map): Update market -- 98866_0_0x7c53c4b8b0c83bbf2e5a5217d1f175f9658e93f091c7f0e9b561af20b182fd8d

---

sdk/constants/market-map/98866/definitions/98866_0_0xc23dac9e52a2ec9b35198d97c368f5b5fe41704684a3c9d75d6998f51126a573.ts

feat(market-map): Update market -- 98866_0_0xc23dac9e52a2ec9b35198d97c368f5b5fe41704684a3c9d75d6998f51126a573 -- Recipe (0xc23d...a573)
- Market ID: 0xc23dac9e52a2ec9b35198d97c368f5b5fe41704684a3c9d75d6998f51126a573 (Market Hash)
- Request Timestamp: Fri, 09 May 2025 01:46:41 GMT

feat(market-map): Update market -- 98866_0_0xc23dac9e52a2ec9b35198d97c368f5b5fe41704684a3c9d75d6998f51126a573

---

sdk/constants/market-map/98866/definitions/98866_0_0x474447878a359b07c3f762cd355d199ff71c7de0939a6768706d730e714a6218.ts

feat(market-map): Update market -- 98866_0_0x474447878a359b07c3f762cd355d199ff71c7de0939a6768706d730e714a6218 -- Recipe (0x4744...6218)
- Market ID: 0x474447878a359b07c3f762cd355d199ff71c7de0939a6768706d730e714a6218 (Market Hash)
- Request Timestamp: Fri, 09 May 2025 02:02:08 GMT

feat(market-map): Update market -- 98866_0_0x474447878a359b07c3f762cd355d199ff71c7de0939a6768706d730e714a6218

---

sdk/constants/market-map/98866/definitions/98866_0_0x24eac8fce50e743fe531e1a8169972ae05f6bf61de7b8395ddaf372b1be1ddac.ts

feat(market-map): Update market -- 98866_0_0x24eac8fce50e743fe531e1a8169972ae05f6bf61de7b8395ddaf372b1be1ddac -- Recipe (0x24ea...ddac)
- Market ID: 0x24eac8fce50e743fe531e1a8169972ae05f6bf61de7b8395ddaf372b1be1ddac (Market Hash)
- Request Timestamp: Fri, 09 May 2025 02:48:46 GMT

feat(market-map): Update market -- 98866_0_0x24eac8fce50e743fe531e1a8169972ae05f6bf61de7b8395ddaf372b1be1ddac

---

sdk/constants/market-map/98866/definitions/98866_0_0x85c3ab928fdf01f9f53d4a776a9cdd9ab34d6e48a4ac2a111471f4425d5ce04c.ts

feat(market-map): Update market -- 98866_0_0x85c3ab928fdf01f9f53d4a776a9cdd9ab34d6e48a4ac2a111471f4425d5ce04c -- Recipe (0x85c3...e04c)
- Market ID: 0x85c3ab928fdf01f9f53d4a776a9cdd9ab34d6e48a4ac2a111471f4425d5ce04c (Market Hash)
- Request Timestamp: Fri, 09 May 2025 03:21:14 GMT

feat(market-map): Update market -- 98866_0_0x85c3ab928fdf01f9f53d4a776a9cdd9ab34d6e48a4ac2a111471f4425d5ce04c

---

sdk/constants/market-map/98866/definitions/98866_0_0xd7b4af5225fb14fc0f0f7e068faaa03c3d1530f695b60187f74ed7a0e259fa10.ts

feat(market-map): Update market -- 98866_0_0xd7b4af5225fb14fc0f0f7e068faaa03c3d1530f695b60187f74ed7a0e259fa10 -- Recipe (0xd7b4...fa10)
- Market ID: 0xd7b4af5225fb14fc0f0f7e068faaa03c3d1530f695b60187f74ed7a0e259fa10 (Market Hash)
- Request Timestamp: Fri, 09 May 2025 03:24:30 GMT

feat(market-map): Update market -- 98866_0_0xd7b4af5225fb14fc0f0f7e068faaa03c3d1530f695b60187f74ed7a0e259fa10

---

sdk/constants/market-map/999/definitions/999_1_0x2dfbcadf22c84320f45a445df5685b30427f4cbf.ts

feat(market-map): Update market -- 999_1_0x2dfbcadf22c84320f45a445df5685b30427f4cbf -- Vault (0x2dfb...4cbf)
- Chain ID: 999
- Market ID: 0x2dfbcadf22c84320f45a445df5685b30427f4cbf (Wrapped Vault Address)
- Request Timestamp: Fri, 09 May 2025 17:34:20 GMT

feat(market-map): Update market -- 999_1_0x2dfbcadf22c84320f45a445df5685b30427f4cbf

---

sdk/constants/market-map/11155111/definitions/11155111_0_0x26e32facbc8412fa142130265ab35aae92ff3366d6887b7b15f216b8ff294f45.ts

feat(market-map): Update market -- 11155111_0_0x26e32facbc8412fa142130265ab35aae92ff3366d6887b7b15f216b8ff294f45 -- Recipe (0x26e3...4f45)
- Market ID: 0x26e32facbc8412fa142130265ab35aae92ff3366d6887b7b15f216b8ff294f45 (Market Hash)
- Request Timestamp: Fri, 09 May 2025 19:07:41 GMT

feat(market-map): Update market -- 11155111_0_0x26e32facbc8412fa142130265ab35aae92ff3366d6887b7b15f216b8ff294f45

---

sdk/constants/market-map/999/definitions/999_0_0x154e93f452af808d81857578e283e6349d0251760112810880fd964ef303f4ae.ts

feat(market-map): Update market -- 999_0_0x154e93f452af808d81857578e283e6349d0251760112810880fd964ef303f4ae -- Recipe (0x154e...f4ae)
- Chain ID: 999
- Market ID: 0x154e93f452af808d81857578e283e6349d0251760112810880fd964ef303f4ae (Market Hash)
- Request Timestamp: Fri, 09 May 2025 19:32:51 GMT

feat(market-map): Update market -- 999_0_0x154e93f452af808d81857578e283e6349d0251760112810880fd964ef303f4ae

---

sdk/constants/market-map/98866/definitions/98866_0_0xa1d68accf80e16047bf8c609e9da79a7ad75576d7fec71f490d73ff1f7d1eee7.ts

feat(market-map): Update market -- 98866_0_0xa1d68accf80e16047bf8c609e9da79a7ad75576d7fec71f490d73ff1f7d1eee7 -- Recipe (0xa1d6...eee7)
- Market ID: 0xa1d68accf80e16047bf8c609e9da79a7ad75576d7fec71f490d73ff1f7d1eee7 (Market Hash)
- Request Timestamp: Fri, 09 May 2025 20:48:27 GMT

feat(market-map): Update market -- 98866_0_0xa1d68accf80e16047bf8c609e9da79a7ad75576d7fec71f490d73ff1f7d1eee7

---

sdk/constants/market-map/98866/definitions/98866_0_0xc220ec824047d1438c76e06e81d38856d451f96ce1c16d97969f28e7520f4d7b.ts

feat(market-map): Update market -- 98866_0_0xc220ec824047d1438c76e06e81d38856d451f96ce1c16d97969f28e7520f4d7b -- Recipe (0xc220...4d7b)
- Market ID: 0xc220ec824047d1438c76e06e81d38856d451f96ce1c16d97969f28e7520f4d7b (Market Hash)
- Request Timestamp: Fri, 09 May 2025 20:51:00 GMT

feat(market-map): Update market -- 98866_0_0xc220ec824047d1438c76e06e81d38856d451f96ce1c16d97969f28e7520f4d7b

---

sdk/constants/market-map/98866/definitions/98866_0_0x2e2750c091f0dff7feefc0252a0420ea19c69abbccf3a8fbf2982ea2c34af5a0.ts

feat(market-map): Update market -- 98866_0_0x2e2750c091f0dff7feefc0252a0420ea19c69abbccf3a8fbf2982ea2c34af5a0 -- Recipe (0x2e27...f5a0)
- Market ID: 0x2e2750c091f0dff7feefc0252a0420ea19c69abbccf3a8fbf2982ea2c34af5a0 (Market Hash)
- Request Timestamp: Fri, 09 May 2025 20:52:53 GMT

feat(market-map): Update market -- 98866_0_0x2e2750c091f0dff7feefc0252a0420ea19c69abbccf3a8fbf2982ea2c34af5a0

---

sdk/constants/market-map/98866/definitions/98866_0_0xa319c980c19e1843d5e5a03c955bf6fb40e8cd1355f75841cef2f0285029a136.ts

feat(market-map): Update market -- 98866_0_0xa319c980c19e1843d5e5a03c955bf6fb40e8cd1355f75841cef2f0285029a136 -- Recipe (0xa319...a136)
- Market ID: 0xa319c980c19e1843d5e5a03c955bf6fb40e8cd1355f75841cef2f0285029a136 (Market Hash)
- Request Timestamp: Fri, 09 May 2025 20:55:51 GMT

feat(market-map): Update market -- 98866_0_0xa319c980c19e1843d5e5a03c955bf6fb40e8cd1355f75841cef2f0285029a136

---

sdk/constants/market-map/98866/definitions/98866_0_0xc942455121a6ede593f9895b113bd23ec68633c9232e7bc727871e078adf8011.ts

feat(market-map): Update market -- 98866_0_0xc942455121a6ede593f9895b113bd23ec68633c9232e7bc727871e078adf8011 -- Recipe (0xc942...8011)
- Market ID: 0xc942455121a6ede593f9895b113bd23ec68633c9232e7bc727871e078adf8011 (Market Hash)
- Request Timestamp: Fri, 09 May 2025 21:00:03 GMT

feat(market-map): Update market -- 98866_0_0xc942455121a6ede593f9895b113bd23ec68633c9232e7bc727871e078adf8011

---

sdk/constants/market-map/98866/definitions/98866_0_0x8a2f78e8cad2569a18faa3dcc4cdbd2092effb7186c7f4d4e81e472458c45a44.ts

feat(market-map): Update market -- 98866_0_0x8a2f78e8cad2569a18faa3dcc4cdbd2092effb7186c7f4d4e81e472458c45a44 -- Recipe (0x8a2f...5a44)
- Market ID: 0x8a2f78e8cad2569a18faa3dcc4cdbd2092effb7186c7f4d4e81e472458c45a44 (Market Hash)
- Request Timestamp: Sat, 10 May 2025 01:31:22 GMT

feat(market-map): Update market -- 98866_0_0x8a2f78e8cad2569a18faa3dcc4cdbd2092effb7186c7f4d4e81e472458c45a44

---

sdk/constants/market-map/98866/definitions/98866_0_0xde1264075f8b9ab937cd2e26278395257dfca0984803effe4d93ffb7f01bae26.ts

feat(market-map): Update market -- 98866_0_0xde1264075f8b9ab937cd2e26278395257dfca0984803effe4d93ffb7f01bae26 -- Recipe (0xde12...ae26)
- Market ID: 0xde1264075f8b9ab937cd2e26278395257dfca0984803effe4d93ffb7f01bae26 (Market Hash)
- Request Timestamp: Sat, 10 May 2025 01:33:09 GMT

feat(market-map): Update market -- 98866_0_0xde1264075f8b9ab937cd2e26278395257dfca0984803effe4d93ffb7f01bae26

---

sdk/constants/market-map/999/definitions/999_0_0x5994273024bcdd07f91cd745f157335b5f166d87e6c28d62601a7a3346879cfc.ts

feat(market-map): Update market -- 999_0_0x5994273024bcdd07f91cd745f157335b5f166d87e6c28d62601a7a3346879cfc -- Recipe (0x5994...9cfc)
- Chain ID: 999
- Market ID: 0x5994273024bcdd07f91cd745f157335b5f166d87e6c28d62601a7a3346879cfc (Market Hash)
- Request Timestamp: Sat, 10 May 2025 03:58:07 GMT

feat(market-map): Update market -- 999_0_0x5994273024bcdd07f91cd745f157335b5f166d87e6c28d62601a7a3346879cfc

---

sdk/constants/market-map/98866/definitions/98866_0_0x8e86bb8fa7870b7a13f30852e935b3438ebc199653678760290936bbcdfc685b.ts

feat(market-map): Update market -- 98866_0_0x8e86bb8fa7870b7a13f30852e935b3438ebc199653678760290936bbcdfc685b -- Recipe (0x8e86...685b)
- Market ID: 0x8e86bb8fa7870b7a13f30852e935b3438ebc199653678760290936bbcdfc685b (Market Hash)
- Request Timestamp: Sun, 11 May 2025 20:09:09 GMT

feat(market-map): Update market -- 98866_0_0x8e86bb8fa7870b7a13f30852e935b3438ebc199653678760290936bbcdfc685b

---

sdk/constants/market-map/98866/definitions/98866_0_0xf89bda68469012ebe5eecbdb60f3b0be88348cb4aa275af40c22f62c1326a773.ts

feat(market-map): Update market -- 98866_0_0xf89bda68469012ebe5eecbdb60f3b0be88348cb4aa275af40c22f62c1326a773 -- Recipe (0xf89b...a773)
- Market ID: 0xf89bda68469012ebe5eecbdb60f3b0be88348cb4aa275af40c22f62c1326a773 (Market Hash)
- Request Timestamp: Mon, 12 May 2025 02:34:56 GMT

feat(market-map): Update market -- 98866_0_0xf89bda68469012ebe5eecbdb60f3b0be88348cb4aa275af40c22f62c1326a773

---

sdk/constants/market-map/98866/definitions/98866_0_0x5e6c3e1e3cd66d238c8004c1555fceb657140c0c374fb5cfbd47d3dbf06828f9.ts

feat(market-map): Update market -- 98866_0_0x5e6c3e1e3cd66d238c8004c1555fceb657140c0c374fb5cfbd47d3dbf06828f9 -- Recipe (0x5e6c...28f9)
- Market ID: 0x5e6c3e1e3cd66d238c8004c1555fceb657140c0c374fb5cfbd47d3dbf06828f9 (Market Hash)
- Request Timestamp: Mon, 12 May 2025 08:59:10 GMT

feat(market-map): Update market -- 98866_0_0x5e6c3e1e3cd66d238c8004c1555fceb657140c0c374fb5cfbd47d3dbf06828f9

---

package-lock.json
sdk/api/Api.ts
sdk/api/data-contracts.ts
sdk/api/openapi.json
sdk/api/openapi.yaml

- adds activityControllerGetActivities

add sdk types

---

sdk/constants/market-map/98866/definitions/98866_0_0x499e360069408b0958f44195cd344a8b54b865529e34581a4a9ac95fc5d00805.ts

feat(market-map): Update market -- 98866_0_0x499e360069408b0958f44195cd344a8b54b865529e34581a4a9ac95fc5d00805 -- Recipe (0x499e...0805)
- Market ID: 0x499e360069408b0958f44195cd344a8b54b865529e34581a4a9ac95fc5d00805 (Market Hash)
- Request Timestamp: Tue, 13 May 2025 00:29:06 GMT

feat(market-map): Update market -- 98866_0_0x499e360069408b0958f44195cd344a8b54b865529e34581a4a9ac95fc5d00805

---

sdk/constants/market-map/98866/definitions/98866_0_0x514676cdaa99b7739d2ef8cb4f218d48f86e6923db427fc12aa3373019a3d785.ts

feat(market-map): Update market -- 98866_0_0x514676cdaa99b7739d2ef8cb4f218d48f86e6923db427fc12aa3373019a3d785 -- Recipe (0x5146...d785)
- Market ID: 0x514676cdaa99b7739d2ef8cb4f218d48f86e6923db427fc12aa3373019a3d785 (Market Hash)
- Request Timestamp: Tue, 13 May 2025 01:28:55 GMT

feat(market-map): Update market -- 98866_0_0x514676cdaa99b7739d2ef8cb4f218d48f86e6923db427fc12aa3373019a3d785

---

sdk/api/Api.ts
sdk/api/openapi.json
sdk/api/openapi.yaml

updates sdk to remove account address

update sdk to work without account address

---

sdk/constants/market-map/98866/definitions/98866_0_0xa91203b928f21b4e1193a3bc4bfbf2d01dbf9acc3992fc75bc2d3eac45a94ddb.ts

feat(market-map): Update market -- 98866_0_0xa91203b928f21b4e1193a3bc4bfbf2d01dbf9acc3992fc75bc2d3eac45a94ddb -- Recipe (0xa912...4ddb)
- Market ID: 0xa91203b928f21b4e1193a3bc4bfbf2d01dbf9acc3992fc75bc2d3eac45a94ddb (Market Hash)
- Request Timestamp: Tue, 13 May 2025 04:35:59 GMT

feat(market-map): Update market -- 98866_0_0xa91203b928f21b4e1193a3bc4bfbf2d01dbf9acc3992fc75bc2d3eac45a94ddb

---

sdk/constants/market-map/98866/definitions/98866_0_0x563219a6169f55e91988cbe9aa25a7f1d748f7a814e89e2df38f0cf399ad6a88.ts

feat(market-map): Update market -- 98866_0_0x563219a6169f55e91988cbe9aa25a7f1d748f7a814e89e2df38f0cf399ad6a88 -- Recipe (0x5632...6a88)
- Market ID: 0x563219a6169f55e91988cbe9aa25a7f1d748f7a814e89e2df38f0cf399ad6a88 (Market Hash)
- Request Timestamp: Tue, 13 May 2025 18:26:22 GMT

feat(market-map): Update market -- 98866_0_0x563219a6169f55e91988cbe9aa25a7f1d748f7a814e89e2df38f0cf399ad6a88

---

sdk/constants/market-map/8453/definitions/8453_0_0x29194a6a5a191a3c21f8361d42bbb7630020924516228e79fd437de1e7c1eac4.ts

feat(market-map): Update market -- 8453_0_0x29194a6a5a191a3c21f8361d42bbb7630020924516228e79fd437de1e7c1eac4 -- Recipe (0x2919...eac4)
- Market ID: 0x29194a6a5a191a3c21f8361d42bbb7630020924516228e79fd437de1e7c1eac4 (Market Hash)
- Request Timestamp: Wed, 14 May 2025 07:36:48 GMT

feat(market-map): Update market -- 8453_0_0x29194a6a5a191a3c21f8361d42bbb7630020924516228e79fd437de1e7c1eac4

---

sdk/constants/market-map/98866/definitions/98866_0_0x6db65a4821684d2db2f18026eb55c1e7c84232def8eae15527a3928affa8b175.ts

feat(market-map): Update market -- 98866_0_0x6db65a4821684d2db2f18026eb55c1e7c84232def8eae15527a3928affa8b175 -- Recipe (0x6db6...b175)
- Market ID: 0x6db65a4821684d2db2f18026eb55c1e7c84232def8eae15527a3928affa8b175 (Market Hash)
- Request Timestamp: Wed, 14 May 2025 16:19:41 GMT

feat(market-map): Update market -- 98866_0_0x6db65a4821684d2db2f18026eb55c1e7c84232def8eae15527a3928affa8b175

---

sdk/constants/market-map/98866/definitions/98866_0_0x502ecda130c353d2f59cedf7c8638cb2c72b1fd33a1c12132c991e74134f696c.ts

feat(market-map): Update market -- 98866_0_0x502ecda130c353d2f59cedf7c8638cb2c72b1fd33a1c12132c991e74134f696c -- Recipe (0x502e...696c)
- Market ID: 0x502ecda130c353d2f59cedf7c8638cb2c72b1fd33a1c12132c991e74134f696c (Market Hash)
- Request Timestamp: Wed, 14 May 2025 18:32:30 GMT

feat(market-map): Update market -- 98866_0_0x502ecda130c353d2f59cedf7c8638cb2c72b1fd33a1c12132c991e74134f696c

---

sdk/constants/market-map/98866/definitions/98866_0_0x7626d64b7f60786b715a68bc6a0c78fddb989a883d26747112a88a70453eacba.ts

feat(market-map): Update market -- 98866_0_0x7626d64b7f60786b715a68bc6a0c78fddb989a883d26747112a88a70453eacba -- Recipe (0x7626...acba)
- Market ID: 0x7626d64b7f60786b715a68bc6a0c78fddb989a883d26747112a88a70453eacba (Market Hash)
- Request Timestamp: Thu, 15 May 2025 12:50:51 GMT

feat(market-map): Update market -- 98866_0_0x7626d64b7f60786b715a68bc6a0c78fddb989a883d26747112a88a70453eacba

---

sdk/constants/market-map/98866/definitions/98866_0_0xd7ad4b024bd61cd9639c4e608440730287c8ace6a58228ac3791e46903085ca5.ts

feat(market-map): Update market -- 98866_0_0xd7ad4b024bd61cd9639c4e608440730287c8ace6a58228ac3791e46903085ca5 -- Recipe (0xd7ad...5ca5)
- Market ID: 0xd7ad4b024bd61cd9639c4e608440730287c8ace6a58228ac3791e46903085ca5 (Market Hash)
- Request Timestamp: Fri, 16 May 2025 01:59:43 GMT

feat(market-map): Update market -- 98866_0_0xd7ad4b024bd61cd9639c4e608440730287c8ace6a58228ac3791e46903085ca5

---

sdk/constants/market-map/11155111/definitions/11155111_0_0xe7ce19eb3e3990861bc5187a8f26b29e54d3bf3f96924bad198c87f08d61168f.ts

feat(market-map): Update market -- 11155111_0_0xe7ce19eb3e3990861bc5187a8f26b29e54d3bf3f96924bad198c87f08d61168f -- Recipe (0xe7ce...168f)
- Market ID: 0xe7ce19eb3e3990861bc5187a8f26b29e54d3bf3f96924bad198c87f08d61168f (Market Hash)
- Request Timestamp: Fri, 16 May 2025 07:22:30 GMT

feat(market-map): Update market -- 11155111_0_0xe7ce19eb3e3990861bc5187a8f26b29e54d3bf3f96924bad198c87f08d61168f

---

sdk/constants/token-map/98866/definitions/98866-0x2836d2047462fc8678c9b0c69166545c3b3007eb.ts
sdk/constants/token-map/98866/definitions/98866-0x2fb465b77a033e62c441f1b46751c55e3ab55de3.ts
sdk/constants/token-map/98866/definitions/98866-0x3c6ec7d1f4733a8e8f848d7e86e31b63616e27d8.ts
sdk/constants/token-map/98866/definitions/98866-0x5649009d65ebc80efee715c95768607b8fbacd55.ts
sdk/constants/token-map/98866/definitions/98866-0x66786085f7ff00397488a577aefc28aafd57ac74.ts
sdk/constants/token-map/98866/definitions/98866-0x7702b07cac789ad00b8c6cec4f24e88152b2a2ed.ts
sdk/constants/token-map/98866/definitions/98866-0xa516a21df0f89b539aad0da7bd06ca45e3dce5e7.ts
sdk/constants/token-map/98866/definitions/98866-0xc1a0b90e0661a4ed0280b1c4a633960312b82dae.ts
sdk/constants/token-map/98866/definitions/98866-0xd5c02efe86ebbc03126281e07b4d43f0b1021065.ts
sdk/constants/token-map/98866/definitions/98866-0xfc3bd0e01b4e755aedd2a4087ccdb90c4d28f038.ts

renames rooster tokens to search_id = token and source = rooster

rename external to rooster

---

sdk/constants/market-map/98866/definitions/98866_0_0x5fecfec9b424e2811552701fee5abf16f0db642a5a1f9428f9702c24b0423b57.ts

feat(market-map): Update market -- 98866_0_0x5fecfec9b424e2811552701fee5abf16f0db642a5a1f9428f9702c24b0423b57 -- Recipe (0x5fec...3b57)
- Market ID: 0x5fecfec9b424e2811552701fee5abf16f0db642a5a1f9428f9702c24b0423b57 (Market Hash)
- Request Timestamp: Mon, 19 May 2025 02:28:22 GMT

feat(market-map): Update market -- 98866_0_0x5fecfec9b424e2811552701fee5abf16f0db642a5a1f9428f9702c24b0423b57

---

sdk/constants/market-map/98866/definitions/98866_0_0x3bb753b8840d9eda1f1c34ff3286d853cc833aedd7c10dddb412bf8f37ecd5d1.ts

feat(market-map): Update market -- 98866_0_0x3bb753b8840d9eda1f1c34ff3286d853cc833aedd7c10dddb412bf8f37ecd5d1 -- Recipe (0x3bb7...d5d1)
- Market ID: 0x3bb753b8840d9eda1f1c34ff3286d853cc833aedd7c10dddb412bf8f37ecd5d1 (Market Hash)
- Request Timestamp: Mon, 19 May 2025 20:16:01 GMT

feat(market-map): Update market -- 98866_0_0x3bb753b8840d9eda1f1c34ff3286d853cc833aedd7c10dddb412bf8f37ecd5d1

---

sdk/constants/market-map/98866/definitions/98866_0_0x0fd353a37624c571c7643d8363edbbbdead48bf6662a99c28fd9cdede220c8b3.ts

feat(market-map): Update market -- 98866_0_0x0fd353a37624c571c7643d8363edbbbdead48bf6662a99c28fd9cdede220c8b3 -- Recipe (0x0fd3...c8b3)
- Market ID: 0x0fd353a37624c571c7643d8363edbbbdead48bf6662a99c28fd9cdede220c8b3 (Market Hash)
- Request Timestamp: Mon, 19 May 2025 20:18:51 GMT

feat(market-map): Update market -- 98866_0_0x0fd353a37624c571c7643d8363edbbbdead48bf6662a99c28fd9cdede220c8b3

---

sdk/constants/market-map/98866/definitions/98866_0_0x4d2ae1e85a4f4c2314e23833445c0a4cb6c434a1aa382bf5939fb18140bcb709.ts

feat(market-map): Update market -- 98866_0_0x4d2ae1e85a4f4c2314e23833445c0a4cb6c434a1aa382bf5939fb18140bcb709 -- Recipe (0x4d2a...b709)
- Market ID: 0x4d2ae1e85a4f4c2314e23833445c0a4cb6c434a1aa382bf5939fb18140bcb709 (Market Hash)
- Request Timestamp: Mon, 19 May 2025 20:20:58 GMT

feat(market-map): Update market -- 98866_0_0x4d2ae1e85a4f4c2314e23833445c0a4cb6c434a1aa382bf5939fb18140bcb709

---

sdk/constants/market-map/98866/definitions/98866_0_0x2878fdf2ab99986904ba571be7ba7af88cb881f4ca8d2f41d78f06566a3c0154.ts

feat(market-map): Update market -- 98866_0_0x2878fdf2ab99986904ba571be7ba7af88cb881f4ca8d2f41d78f06566a3c0154 -- Recipe (0x2878...0154)
- Market ID: 0x2878fdf2ab99986904ba571be7ba7af88cb881f4ca8d2f41d78f06566a3c0154 (Market Hash)
- Request Timestamp: Tue, 20 May 2025 01:05:15 GMT

feat(market-map): Update market -- 98866_0_0x2878fdf2ab99986904ba571be7ba7af88cb881f4ca8d2f41d78f06566a3c0154

---

sdk/constants/market-map/98866/definitions/98866_0_0x222639e2ad17292c98361836399fdd37cb0f0b1f58e6aa019ddf0ccf41540899.ts

feat(market-map): Update market -- 98866_0_0x222639e2ad17292c98361836399fdd37cb0f0b1f58e6aa019ddf0ccf41540899 -- Recipe (0x2226...0899)
- Market ID: 0x222639e2ad17292c98361836399fdd37cb0f0b1f58e6aa019ddf0ccf41540899 (Market Hash)
- Request Timestamp: Tue, 20 May 2025 01:28:01 GMT

feat(market-map): Update market -- 98866_0_0x222639e2ad17292c98361836399fdd37cb0f0b1f58e6aa019ddf0ccf41540899

---

sdk/constants/market-map/98866/definitions/98866_0_0x5190b7c94b572a00eeb5cf766239eb72a1af49f69c106a23a7ca97c4ca67110b.ts

feat(market-map): Update market -- 98866_0_0x5190b7c94b572a00eeb5cf766239eb72a1af49f69c106a23a7ca97c4ca67110b -- Recipe (0x5190...110b)
- Market ID: 0x5190b7c94b572a00eeb5cf766239eb72a1af49f69c106a23a7ca97c4ca67110b (Market Hash)
- Request Timestamp: Thu, 22 May 2025 03:33:24 GMT

feat(market-map): Update market -- 98866_0_0x5190b7c94b572a00eeb5cf766239eb72a1af49f69c106a23a7ca97c4ca67110b

---

sdk/constants/market-map/98866/definitions/98866_0_0x3c711b4305c02ed5a355039962172e0101e51ce33c6cd761276e682d82aaa6b3.ts

feat(market-map): Update market -- 98866_0_0x3c711b4305c02ed5a355039962172e0101e51ce33c6cd761276e682d82aaa6b3 -- Recipe (0x3c71...a6b3)
- Market ID: 0x3c711b4305c02ed5a355039962172e0101e51ce33c6cd761276e682d82aaa6b3 (Market Hash)
- Request Timestamp: Thu, 22 May 2025 03:35:18 GMT

feat(market-map): Update market -- 98866_0_0x3c711b4305c02ed5a355039962172e0101e51ce33c6cd761276e682d82aaa6b3

---

sdk/constants/market-map/98866/definitions/98866_0_0x2f0cc7b9660aec4fdb980fcde5990f271b5d5f3ce9ace5c1a6cfbf9b381c1682.ts

feat(market-map): Update market -- 98866_0_0x2f0cc7b9660aec4fdb980fcde5990f271b5d5f3ce9ace5c1a6cfbf9b381c1682 -- Recipe (0x2f0c...1682)
- Market ID: 0x2f0cc7b9660aec4fdb980fcde5990f271b5d5f3ce9ace5c1a6cfbf9b381c1682 (Market Hash)
- Request Timestamp: Mon, 26 May 2025 09:33:54 GMT

feat(market-map): Update market -- 98866_0_0x2f0cc7b9660aec4fdb980fcde5990f271b5d5f3ce9ace5c1a6cfbf9b381c1682

---

sdk/constants/market-map/98866/definitions/98866_0_0xb3f456fbb6061788958ea052b811f2c778bb2ba683af45db9e22f764a928748d.ts

feat(market-map): Update market -- 98866_0_0xb3f456fbb6061788958ea052b811f2c778bb2ba683af45db9e22f764a928748d -- Recipe (0xb3f4...748d)
- Market ID: 0xb3f456fbb6061788958ea052b811f2c778bb2ba683af45db9e22f764a928748d (Market Hash)
- Request Timestamp: Mon, 26 May 2025 09:42:34 GMT

feat(market-map): Update market -- 98866_0_0xb3f456fbb6061788958ea052b811f2c778bb2ba683af45db9e22f764a928748d

---

sdk/constants/market-map/98866/definitions/98866_0_0xe5b59682f60ecf752f3c0e908d9e30721fa6d2f8ac5f33b876358bef9365b99c.ts

feat(market-map): Update market -- 98866_0_0xe5b59682f60ecf752f3c0e908d9e30721fa6d2f8ac5f33b876358bef9365b99c -- Recipe (0xe5b5...b99c)
- Market ID: 0xe5b59682f60ecf752f3c0e908d9e30721fa6d2f8ac5f33b876358bef9365b99c (Market Hash)
- Request Timestamp: Tue, 27 May 2025 11:48:09 GMT

feat(market-map): Update market -- 98866_0_0xe5b59682f60ecf752f3c0e908d9e30721fa6d2f8ac5f33b876358bef9365b99c

---

sdk/constants/market-map/98866/definitions/98866_0_0xa20cec2756e7f2867790af5245088f127297c81ed5b84c07edca243ef3c44afc.ts

feat(market-map): Update market -- 98866_0_0xa20cec2756e7f2867790af5245088f127297c81ed5b84c07edca243ef3c44afc -- Recipe (0xa20c...4afc)
- Market ID: 0xa20cec2756e7f2867790af5245088f127297c81ed5b84c07edca243ef3c44afc (Market Hash)
- Request Timestamp: Tue, 27 May 2025 14:24:57 GMT

feat(market-map): Update market -- 98866_0_0xa20cec2756e7f2867790af5245088f127297c81ed5b84c07edca243ef3c44afc

---

sdk/constants/market-map/98866/definitions/98866_0_0x99437c449bc5e81a78fa8cf7aa82b9cc5c72aeb20c59d1e4d9d487f9c0a5530b.ts

feat(market-map): Update market -- 98866_0_0x99437c449bc5e81a78fa8cf7aa82b9cc5c72aeb20c59d1e4d9d487f9c0a5530b -- Recipe (0x9943...530b)
- Market ID: 0x99437c449bc5e81a78fa8cf7aa82b9cc5c72aeb20c59d1e4d9d487f9c0a5530b (Market Hash)
- Request Timestamp: Tue, 27 May 2025 14:55:31 GMT

feat(market-map): Update market -- 98866_0_0x99437c449bc5e81a78fa8cf7aa82b9cc5c72aeb20c59d1e4d9d487f9c0a5530b

---

sdk/constants/market-map/98866/definitions/98866_0_0xea3dcf2cd381b888ba6b0aadfc31ce5946402661c287dd4909ada41b9b250ac5.ts

feat(market-map): Update market -- 98866_0_0xea3dcf2cd381b888ba6b0aadfc31ce5946402661c287dd4909ada41b9b250ac5 -- Recipe (0xea3d...0ac5)
- Market ID: 0xea3dcf2cd381b888ba6b0aadfc31ce5946402661c287dd4909ada41b9b250ac5 (Market Hash)
- Request Timestamp: Tue, 27 May 2025 18:56:36 GMT

feat(market-map): Update market -- 98866_0_0xea3dcf2cd381b888ba6b0aadfc31ce5946402661c287dd4909ada41b9b250ac5

---

sdk/constants/market-map/98866/definitions/98866_0_0x34ca31e607f46f70e2f675b72e58c5a466c1697ca9bbe01f6f2237a1dba195d5.ts

feat(market-map): Update market -- 98866_0_0x34ca31e607f46f70e2f675b72e58c5a466c1697ca9bbe01f6f2237a1dba195d5 -- Recipe (0x34ca...95d5)
- Market ID: 0x34ca31e607f46f70e2f675b72e58c5a466c1697ca9bbe01f6f2237a1dba195d5 (Market Hash)
- Request Timestamp: Tue, 27 May 2025 19:06:07 GMT

feat(market-map): Update market -- 98866_0_0x34ca31e607f46f70e2f675b72e58c5a466c1697ca9bbe01f6f2237a1dba195d5

---

sdk/constants/market-map/98866/definitions/98866_0_0xb2d208a69576438d75a879b1b2f8101f303b41c0a1308cd373c509836dc0ae14.ts

feat(market-map): Update market -- 98866_0_0xb2d208a69576438d75a879b1b2f8101f303b41c0a1308cd373c509836dc0ae14 -- Recipe (0xb2d2...ae14)
- Market ID: 0xb2d208a69576438d75a879b1b2f8101f303b41c0a1308cd373c509836dc0ae14 (Market Hash)
- Request Timestamp: Tue, 27 May 2025 19:22:40 GMT

feat(market-map): Update market -- 98866_0_0xb2d208a69576438d75a879b1b2f8101f303b41c0a1308cd373c509836dc0ae14

---

sdk/constants/market-map/98866/definitions/98866_0_0x2f6cad82d875fea7c1167dbd0a0c8f31f46e23812e3074f9c42dd41261b416e6.ts

feat(market-map): Update market -- 98866_0_0x2f6cad82d875fea7c1167dbd0a0c8f31f46e23812e3074f9c42dd41261b416e6 -- Recipe (0x2f6c...16e6)
- Market ID: 0x2f6cad82d875fea7c1167dbd0a0c8f31f46e23812e3074f9c42dd41261b416e6 (Market Hash)
- Request Timestamp: Tue, 27 May 2025 19:55:29 GMT

feat(market-map): Update market -- 98866_0_0x2f6cad82d875fea7c1167dbd0a0c8f31f46e23812e3074f9c42dd41261b416e6

---

sdk/constants/market-map/98866/definitions/98866_0_0x2766988e24e12180017e4f683ca41aaf26ecfe1c631154f5a09610532a35303f.ts

feat(market-map): Update market -- 98866_0_0x2766988e24e12180017e4f683ca41aaf26ecfe1c631154f5a09610532a35303f -- Recipe (0x2766...303f)
- Market ID: 0x2766988e24e12180017e4f683ca41aaf26ecfe1c631154f5a09610532a35303f (Market Hash)
- Request Timestamp: Wed, 28 May 2025 17:05:24 GMT

feat(market-map): Update market -- 98866_0_0x2766988e24e12180017e4f683ca41aaf26ecfe1c631154f5a09610532a35303f
